### ISSUE TITLE
When "go to definition" of contact table, I get this error ...

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#1021]
[Error - 11:57:28] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/previewDocument' failed with error: 'Sequence contains no elements'
StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertTextConst(TypeSymbol type) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 363
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.GetDataTypeSyntax(TypeSymbol type) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 352
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertTypeReference(TypeSymbol type) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 329
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertVariables(IEnumerable`1 variables) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 90
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertMembers(ImmutableArray`1 members) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 65
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntaxTable.ConvertTable(TableTypeSymbol table) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax_Table.cs:line 47
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.Convert(ISymbol symbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 39
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPreviewDocumentRequestHandler.SymbolToPreviewText(ISymbol symbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPreviewDocumentRequestHandler.cs:line 64
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPreviewDocumentRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPreviewDocumentRequestHandler.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by qutreson** [comment]
We also found out about this bug, it has been fixed and should be available in the next update
