### ISSUE TITLE
NAV 2018 onPremise - VS Code - AL Language Extensions - Debugging not working

### ISSUE THREAD

**Issue by Wookiezuecheter** [Microsoft/AL#1038]
Hi.
I've installed NAV 2018 and Visual Studio Code and the AL Language Extensions that has been shipped with NAV 2018. I can run the Hello World project without debugging. But with debugging i get the message "Sorry, that didn't work". The eventviewer tells me the following.
Any ideas?
Thank for help.
Kind regards,
Mike

Config:
application
<img width="753" alt="nav2018" src="https://user-images.githubusercontent.com/34243547/33560265-95778820-d90f-11e7-9b3d-44b9d7d42465.PNG">

extension:
<img width="753" alt="vscode" src="https://user-images.githubusercontent.com/34243547/33560338-c41324f0-d90f-11e7-8d4d-dd286b0c6100.PNG">

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "DynamicsNAV110",
            "server": "http://localhost",
            "serverInstance": "DynamicsNAV110",
            "authentication": "Windows",
            "startupObjectId": 22
        }
    ]
}
```

app.json
```
{
  "id": "22c40094-6b30-42dd-91a5-41792317ed1e",
  "name": "helloworld",
  "publisher": "CSS",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": "11.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}
```

```
Server instance: DynamicsNAV110
Tenant ID: 
<ii>User: CSS\michael.muehlhauser
Type: System.NullReferenceException
Message: <ii>Object reference not set to an instance of an object.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntime.EnsureDetachedFromConnection(NavSession session)
     at Microsoft.Dynamics.Nav.Runtime.NavSession.ShutdownDebuggingEnvironment(NavBaseException& firstCaughtException)
     at Microsoft.Dynamics.Nav.Runtime.NavSession.InnerDispose()
     at Microsoft.Dynamics.Nav.Runtime.NavSession.<DisposeAsync>d__127.MoveNext()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147467261
</ii>
```

```
Server instance: DynamicsNAV110
Tenant ID: 
<ii>User: CSS\michael.muehlhauser
Type: System.NullReferenceException
Message: <ii>Object reference not set to an instance of an object.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntime.EnsureDetachedFromConnection(NavSession session)
     at Microsoft.Dynamics.Nav.Runtime.NavSession.ShutdownDebuggingEnvironment(NavBaseException& firstCaughtException)
     at Microsoft.Dynamics.Nav.Runtime.NavSession.InnerDispose()
     at Microsoft.Dynamics.Nav.Runtime.NavSession.<DisposeAsync>d__127.MoveNext()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147467261
</ii>

```

```
Server instance: DynamicsNAV110
Tenant ID: 
<ii>User: CSS\michael.muehlhauser
Type: System.InvalidOperationException
Message: <ii>Dynamic operations can only be performed in homogenous AppDomain.</ii>
StackTrace:
     at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
     at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
     at Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.DebuggerHub.OnDebuggeeConnected(Object sender, DebugSessionStartEventArgs eventArgs)
     at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManager.OnDebuggingSessionStarted(DebugSessionStartEventArgs e)
     at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManager.CreateRuntime(String debuggingContext, NavSession session, Boolean waitForDebugAdapterConfiguration)
     at Microsoft.Dynamics.Nav.Runtime.NavSession.StartDebuggingSession(String debuggingContext, Boolean waitForDebugAdapterConfiguration)
     at Microsoft.Dynamics.Nav.Service.NSService.OpenConnection(ConnectionRequest connectionRequest)
     at SyncInvokeOpenConnection(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: System.Core
HResult: -2146233079
</ii>
```

```
Error accessing Website 
Raw Url: 
Url: 
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException
Message: Die Anforderung konnte nicht vom Server „DynamicsNAV110“ verarbeitet werden. Die Anwendung wird beendet.
StackTrace:
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectFailedEventArgs connectFailedArgs, ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, SpnSetting spnSettingToTry, Boolean allowSpnSettingsSwap, UserSettings& userSettings) in S:\Depot\NAV110\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 377
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, UserSettings& userSettings) in S:\Depot\NAV110\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 216
   at Microsoft.Dynamics.Nav.Client.ServiceConnection.OpenConnection() in S:\Depot\NAV110\Platform\Client\Shared\Prod.Client.ServiceConnection\ServiceConnection.cs:line 911
   at Microsoft.Dynamics.Nav.Client.ServiceConnection.Initialize() in S:\Depot\NAV110\Platform\Client\Shared\Prod.Client.ServiceConnection\ServiceConnection.cs:line 561
   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSessionInitializer.OpenConnectionToServer() in S:\Depot\NAV110\Platform\Client\Shared\Prod.Client.Builder\BuilderSession\BuilderSessionInitializer.cs:line 195
   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSessionInitializer.InitializeCore() in S:\Depot\NAV110\Platform\Client\Shared\Prod.Client.Builder\BuilderSession\BuilderSessionInitializer.cs:line 92
   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSessionInitializer.Initialize() in S:\Depot\NAV110\Platform\Client\Shared\Prod.Client.Builder\BuilderSession\BuilderSessionInitializer.cs:line 76
   at Microsoft.Dynamics.Framework.UI.UISession.Initialize() in S:\Depot\NAV110\Platform\Client\Shared\Prod.ClientFwk\Session\UiSession.cs:line 1073
   at Microsoft.Dynamics.Nav.Client.Web.NavWebUISessionInitializer.InitializeCore(UISession session) in S:\Depot\NAV110\Platform\Client\Web\Prod.Client.WebCommon\Session\NavWebUISessionInitializer.cs:line 104
   at Microsoft.Dynamics.Nav.WebClient.NavWebClientUISessionInitializer.InitializeCore(UISession session) in S:\Depot\NAV110\Platform\Client\Web\Prod.Client.WebClient\Session\NavWebClientUISessionInitializer.cs:line 54
   at Microsoft.Dynamics.Nav.Client.Web.NavWebUISessionInitializer.Initialize(UISession session) in S:\Depot\NAV110\Platform\Client\Web\Prod.Client.WebCommon\Session\NavWebUISessionInitializer.cs:line 77
   at Microsoft.Dynamics.Framework.UI.Client.OpenFormExecutionStrategy.TryInitializeUiSession(UISession session) in S:\Depot\NAV110\Platform\Client\Shared\Prod.ClientFwk\Client\Interactions\ExecutionStrategies\OpenFormExecutionStrategy.cs:line 67
   at Microsoft.Dynamics.Framework.UI.Web.WebOpenFormExecutionStrategy.TryInitializeUiSession(UISession session) in S:\Depot\NAV110\Platform\Client\Web\Prod.Client.Web\Interactions\ExecutionStrategies\WebOpenFormExecutionStrategy.cs:line 61
   at Microsoft.Dynamics.Framework.UI.Client.OpenFormExecutionStrategy.Execute() in S:\Depot\NAV110\Platform\Client\Shared\Prod.ClientFwk\Client\Interactions\ExecutionStrategies\OpenFormExecutionStrategy.cs:line 41
   at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_0.<InvokeInteractions>b__3() in S:\Depot\NAV110\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 125
Source: Microsoft.Dynamics.Nav.Client.ServiceConnection----------------------------------
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException
Message: Die Anforderung konnte nicht vom Server „DynamicsNAV110“ verarbeitet werden. Die Anwendung wird beendet.
StackTrace:

Source: ----------------------------------
Type: System.InvalidOperationException
Message: Dynamic operations can only be performed in homogenous AppDomain.
StackTrace:
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.DebuggerHub.OnDebuggeeConnected(Object sender, DebugSessionStartEventArgs eventArgs)
   at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManager.OnDebuggingSessionStarted(DebugSessionStartEventArgs e)
   at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManager.CreateRuntime(String debuggingContext, NavSession session, Boolean waitForDebugAdapterConfiguration)
   at Microsoft.Dynamics.Nav.Runtime.NavSession.StartDebuggingSession(String debuggingContext, Boolean waitForDebugAdapterConfiguration)
   at Microsoft.Dynamics.Nav.Service.NSService.OpenConnection(ConnectionRequest connectionRequest)
   at SyncInvokeOpenConnection(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: System.Core
```

**Comment by Wookiezuecheter** [comment]
THANK YOU A LOT.
that did the trick!
