### ISSUE TITLE
AddAfter unhandled exception

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#109]
When I add some new action after some existing, all is ok. When I try to add another action after the added action, compiler ends with:
<code>
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emitter.Utility.ActionAddMetadataBuilder.ContainerGetter(ActionSymbol anchor) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Utility\ActionAddMetadataBuilder.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emitter.Utility.ContentDestinationMetadataBuilder2.SetContentMetadata(ContentDestinationMetadata& metadata, ChangeKind changeKind, TV anchor) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Utility\ContentDestinationMetadataBuilder.cs:line 70
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emitter.Utility.ContentAddMetadataBuilder3.SetContentMetadata(ContentAddMetadata& metadata) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Utility\ContentAddMetadataBuilder.cs:line 101
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.PageExtensionMetadataEmitter.WriteContentAdd(XmlWriter xmlWriter, SourceChangeAddSymbol addContentSymbol) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PageExtensionMetadataEmitter.cs:line 170
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.PageExtensionMetadataEmitter.HandleChangeSymbols(XmlWriter xmlWriter, Symbol sym) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PageExtensionMetadataEmitter.cs:line 104
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.PageExtensionMetadataEmitter.<EmitMetadata>b__2_0(XmlWriter xmlWriter) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PageExtensionMetadataEmitter.cs:line 52
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectMetadataEmitter.EmitMetadata(Action1 content) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ApplicationObjectMetadataEmitter.cs:line 134
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileApplicationObject(ApplicationObjectTypeSymbol containingType) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 237
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass14_0.<CompileApplicationObjectAsTask>b__0() in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 200
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 150
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 160
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 747
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 724
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 423
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 300
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<InternalHandleAsynch>d__1.MoveNext() in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase1.<HandleAsynch>d__1.MoveNext() in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\GenericRequestHandlerBase.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__4.MoveNext() in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestDispatcher.<ListenForMessages>d__18.MoveNext() in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestDispatcher.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.AsyncContext.Start(Func1 asyncMainFunc) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\AsyncContext.cs:line 29
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\2\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 100
[Info  - 10:19:23] Connection to server got closed. Server will restart.</code>

<b>You can try with adding this code at the end of HelloWorld.al demo created by the Go! function:</b>
<code>
pageextension 70770078 RoleCenterExt extends "Order Processor Role Center"
{
    actions 
    {
        addafter("Transfer Orders") 
        {
            action(ExtensionAction1)
            {
                trigger OnAction();
                begin
                    Message('Ext1');
                end;
            }
        }
    }
}

pageextension 70770079 RoleCenterExt2 extends "Order Processor Role Center"
{
    layout
    {
        // Add changes to page layout here
    }

    actions
    {
        addafter(ExtensionAction1) 
        {
            action(ExtensionAction2) {
                trigger OnAction();
                begin
                    Message('Ext2');
                end;
            }
        }
    }
}
</code>

Sorry for the styling, seems that it is somehow broken with the text and code....

**Comment by StanislawStempin** [comment]
This is a bug, we will look into it.
A slightly unrelated question prompted by your repro steps - do you foresee scenarios which require page extension objects for the same target within the same package? We are considering blocking that possibility and keep things simple - 1 extension object for a given target per 1 package.

**Comment by kine** [comment]
All is question of code separation to specific files. If I have app having e.g. 3 areas, I expect to have extension in 3 separate files/folder to structure the code. And I want to have the entries in specific order. Limit this is just temporal workaround. Target must be to be able to structure the app into e.g. 3 separate modules, which are linked.

Sent from my Windows 10 phone

**Comment by kaspermoerch** [comment]
> A slightly unrelated question prompted by your repro steps - do you foresee scenarios which require page extension objects for the same target within the same package? We are considering blocking that possibility and keep things simple - 1 extension object for a given target per 1 package.

As @kine stated the ability to have multiple extensions for one object would be very nice when considering separation of functionality. If I had an extension that would use the same object but for completely different reasons/result I would extend the object twice to make it clear that the two things have nothing in common.
