### ISSUE TITLE
Problems building app

### ISSUE THREAD

**Issue by niku-live** [Microsoft/AL#1091]
I am having issues building AL code that was converted from our add-on code. Sample applications compiles successfully, I can also compile some simple applications I have written, but when I try to compile out add-on code I get this scary output:
Microsoft (R) AL Compiler version 0.12.15355
Copyright (C) Microsoft Corporation. All rights reserved

[Error - 02:32:04] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteAttributeProperties(XmlWriter xmlWriter, IEnumerable`1 properties, Action`2 writePropertyMetadata) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 71
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteProperties(XmlWriter xmlWriter, Symbol declaringSymbol, IEnumerable`1 properties, Action`2 writePropertyMetadata, Boolean shouldOutputDefaultProperties) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 35
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.RequestPageMetadataEmitter.<>c__DisplayClass22_0.<WritePageProperties>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\RequestPageMetadataEmitter.cs:line 284
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.RequestPageMetadataEmitter.EmitMetadata() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\RequestPageMetadataEmitter.cs:line 70
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportMetadataEmitter.<EmitMetadata>b__1_0(XmlWriter xmlWriter) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportMetadataEmitter.cs:line 35
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter`1.EmitMetadata(Action`1 content) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\GenericObjectMetadataEmitter.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 239
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 216
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 150
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 810
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 787
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 531
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 312
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

To give you a context, what I am compiling:
1. I tried to take a full code of our add-on and convert it to AL. The main reason - take as a starting point whole add-on, compile and see what errors do I get and later split into smaller extensions. At first I got about 200 errors and 80 warnings, then I fixed all of them and then I got this error.
2. Everything was compiled using default NAV 2018 installation (RTM, demo database).
3. Our add-on modifies only 2 objects from standard NAV and that modification is only new fields (3 new fields in Vendor table and 2 new fields in Fixed Asset table) without any code.
4. Our add-on consists totally of  1248 new objects and 2 control add-ins.
5. Add-on fully compiles and works correctly on NAV 2018 when using old C/AL code.
6. In both service-tier and app.json config target is set to "Internal" (we still have lots of file functions in our code, so for now we are compiling like this).

I think that there is a problem with code in our add-on, but I have now way to debug compilation process. My main question is - is there a way to get more debug messages from compiler to see where it fails, because now it is almost impossible to find out which of 1248 objects is the reason.

**Comment by DominikDitoIvosevic** [comment]
The issue seems to happen at package build time and related to some property which is invalid. It would really help us a lot if you could try and get a sample repro.

The issue seems to be with a property on a request page of a report.
Could you please try and isolate the code which is causing issues?

**Comment by niku-live** [comment]
If problem is really with a request page property in a report, then I think it is possible to remove reports one by one (since they are less dependent on other objects) and see which fails. I will try to do this and write what I found.

**Comment by niku-live** [comment]
Hello again,

Finally it builds :). Your information that report request page properties was responsible saved a lot of time. So I removed reports one by one and found the one which was responsible. It seems that property that breaks this build is called "RefreshOnActivate":
    requestpage
    {
        RefreshOnActivate = true;  //When I comment this line, then everything compiles
        SaveValues = true;
        layout
        {
            area(content)
            {
                group(Options)

When I removed all instances of this property in all request pages then whole project compiles without any problems.
But I think that AL compiler should be modified to detect such properties and inform with correct error message, because now it took a lot time to identify real problem.

**Comment by DominikDitoIvosevic** [comment]
thank you for a great repro. I'll fix it

**Comment by DominikDitoIvosevic** [comment]
Hi @niku-live .
Has this request page had the property RefreshOnActivate before?
I'm just checking in CSIDE and I can see that request pages do not have this property. This explains why it's not accepted. It's probably our mistake that we accept it at all in the new compiler.
![image](https://user-images.githubusercontent.com/6378638/33989109-a1115f1c-e0c6-11e7-8819-c470854e3c09.png)

As you can see, the property is not allowed in cside so I'm wondering how it got there

**Comment by niku-live** [comment]
Well. To tell you the truth I am not sure myself, as it is from our add-on which is older than 10 years and it overcome many conversions :). If I were to guess RequestForm allowed "UpdateOnActivate" property, FormTransformation tool happily converted is to RequestPage "RefreshOnActivate" property, as there was no compilation problems that property went from NAV 2009 up until NAV 2018 until it finally met C/AL to AL converter.

**Comment by DominikDitoIvosevic** [comment]
I will do some more investigating whether this property actually does something for request pages on the platform even if it's not allowed in cside in which case we might consider allowing it again. Otherwise it makes no sense for us to support a property which doesn't do anything so I will probably add in the txt2al conversion that the property is commented out.

**Comment by niku-live** [comment]
Just my 2 cents - I tested it with and without property, there doesn't seem to be any difference (or it is not an obvious one). There are more properties that are "hidden" in C/SIDE, but still seen in text format, (of course RefreshOnActivate is the only one that breaks build, all others give proper error).

In fact now I use C/AL to AL converter for quite a silly reason - to tidy up our add-on and remove "hidden" properties. For example - XmlPort has property TextEncoding, but it is visible only when type is Variable or Fixed text. However if you set property and only then change type, funny thing happens - property is still here, but not visible. As our add-on is old, there are many instances of similar cases, and C/AL to AL converter helps finding them quite well :).

**Comment by DominikDitoIvosevic** [comment]
So I have fixed the issue where we were allowing properties from pages which shouldn't be available on request pages. As for txt2al, we wont be commenting these out as in reality this specific property doesn't differ from any other invalid property. They should be removed after conversion.
