### ISSUE TITLE
Issue with UsageCategory

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/AL#1166]
Hi All!

I tested UsageCategory on December Update.
When I build and publish full my app. Get the crash error:
     ![image](https://user-images.githubusercontent.com/24407031/33876981-9dc21252-df59-11e7-8818-697a4e50ea22.png)
     ![image](https://user-images.githubusercontent.com/24407031/33877047-c76c8ed4-df59-11e7-95fc-363911bd39d7.png)

If I restart the server and open NAV again, I don't see any new page and report on Menu Suite.

------------------------------------------------------------------------------------------------

**After that**, I test as bellow:
1. If I only add this property for 1 -> 19 Objects (10 Pages, 1..9 Reports) then They are added to MenuSuite as picture:
![image](https://user-images.githubusercontent.com/24407031/33877314-8ee04d66-df5a-11e7-815c-97bd7b78cb3f.png)

2. If I add this property for 20 or 20+ then I get above crash error.

**_Note:_**
I also tested on NAV 2018. I got the same result.
If you need the full package for debugging, Please provide me a email. I will send you full package.

**Comment by kalberes** [comment]
For the first picture, have you pressed F5 or Ctrl F5. Is it Nav 2018? 
If it is Nav 2018, have and you have pressed F5, have you disabled the NetFx40_LegacySecurityPolicy on the *server.exe.config 
The UsageCategory will just make it possible that your page or report appears in the search on the web client.

**Comment by hougaard** [comment]
If the Service crashed, there might be some useful exception stuff in the event log, please check.

**Comment by hgnamvn** [comment]
Hi kalberes,

My Purpose is that I want to add all my new pages and reports to Search on December Update.
I always use F5 (on Visual Studio Code) to build and publish my App.
But after publishing done, both win client and web client can't access, so I can't see result. 
I check eventviewer then log is recorded as bellow:

//////////////////////
_Type: Microsoft.Dynamics.Nav.Client.NavClientClosingException
Fatal: False
ShowError: True
Message: <ii>The server "NAV" was unable to process the request. The application will close.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.DoExecute(Func`1 execute)
     at Microsoft.Dynamics.Nav.Client.WinClient.StartWinFormsClient.RunCore()
Source: Microsoft.Dynamics.Nav.Client.WinClient
HResult: -2146233088_

_Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException
Message: <ii>The server "NAV" was unable to process the request. The application will close.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod, ServerCallOptions options)
     at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod)
     at Microsoft.Dynamics.Nav.Client.MetadataHandler.GetNavigationFrame(Boolean applyPersonalization, Boolean getNavigationFrameFromServer)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.RefreshNavigationForm()
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.get_NavigationForm()
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(String name)
     at Microsoft.Dynamics.Framework.UI.UISession.CreateLogicalForm(String name, Boolean reuseActiveForm)
     at Microsoft.Dynamics.Framework.UI.Windows.ClientSessionBase.ShowLogicalForm(String formName)
     at Microsoft.Dynamics.Framework.UI.Windows.ClientSessionBase.RunCore()
     at Microsoft.Dynamics.Nav.Client.WinClient.NavWinFormsClientSession.RunCore()
     at Microsoft.Dynamics.Nav.Client.WinClient.NavClientErrorHandler.ExecuteAndCatchExceptions(Func`1 execute)
Source: Microsoft.Dynamics.Nav.Client.ServiceConnection
HResult: -2146233088_

_Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException
Message: <ii>The server "NAV" was unable to process the request. The application will close.</ii>
HResult: -2146233088_

_Type: System.InvalidOperationException
Message: <ii>There is an error in XML document (27, 24).</ii>
StackTrace:
     at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
     at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.CreateNavigationData(String content)
     at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.CreateNavigationData(PackageId id)
     at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.UpdateNavigationDataCache(NavAppGroup appGroup)
     at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.GetNavigationData(NavAppGroup appGroup)
     at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.AppendExtensionNavigationData(NavigationDefinition existingDefinitions, NavAppGroup appGroup)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetNavigationDepartments(NavAppGroup appGroup)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetNavigationFrame(Int32 homepageId, Boolean applyPersonalization)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetNavigationFrame(Boolean applyPersonalization)
     at SyncInvokeGetNavigationFrame(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass25_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass25_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: System.Xml
HResult: -2146233079_

_Type: System.Xml.XmlException
LineNumber: 27
LinePosition: 24
Message: <ii>'.', hexadecimal value 0x00, is an invalid character. Line 27, position 24.</ii>
StackTrace:
     at System.Xml.XmlTextReaderImpl.Throw(Exception e)
     at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
     at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
     at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
     at System.Xml.XmlReader.ReadEndElement()
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderNavigationDefinition.Read97_NavigationDefinition(Boolean isNullable, Boolean checkType)
     at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderNavigationDefinition.Read98_NavigationDefinition()
Source: System.Xml
HResult: -2146232000_
///////////////////

I must restart NAV Service again so that i can open NAV again. However, Don't have any new objects are added.

-----------------------------

As you suggest, I tested on NAV 2018. I disabled the NetFx40_LegacySecurityPolicy on the *server.exe.config and test again. But the result is same, event logs is recorded the same.

**Comment by kalberes** [comment]
Let me try to understand your issue. You have  added Usage category to 19 pages/reports in your extension package. If you try adding the 20th usage category and publish (FYI: Ctrl F5 is what publishes, F5 starts a debugging session) you get a crash on the web client?

**Comment by hgnamvn** [comment]
Yes kalberes, 

If I add Usage category to 19 pages/reports in my extension, and press F5 to build and publish App, It work well.
But, If I try adding the 20th object, and press F5 to rebuild and publish app again. I get above error.

**Comment by kalberes** [comment]
Ok,  we will investigate it.

Thanks
Kalman

**Comment by strophanthus** [comment]
We have encountered this as well. The number of pages we wish to make searchable is at 20 at this time. This caused the same type of crash with the same event log. Please let me know if more detail is needed.

**Comment by kalberes** [comment]
I have tried reproducing this by creating 22 simple pages assigning various usage categories, then the same usage category I have no repro either way. So any data @strophanthus , @hgnamvn  that would repro it would be helpful.

**Comment by strophanthus** [comment]
I took a look and I would guess it is because we still have CaptionML set on all UI.

**Comment by hgnamvn** [comment]
Hi kalberes,

Please give me your email. I will send you my Package, You can test and debug on it.

**Comment by hgnamvn** [comment]
Hi kalberes,

I send you the package, please check for me. Thank you so much.

**Comment by kalberes** [comment]
Hi. 
I have logged a bug and have attached your repro. I did not have time to look at it. Someone in the team will pick it up and have a look at it.

**Comment by hgnamvn** [comment]
Thank Kalberes so much.

**Comment by jcooper01** [comment]
We are having the same issue.

**Comment by qutreson** [comment]
This will also be backported to NAV 2018 CU 2
