### ISSUE TITLE
In-client designer fails to add fields

### ISSUE THREAD

**Issue by tfenster** [Microsoft/AL#122]
I get an error if I try to add fields through the in-client designer. I try to follow the example from https://blogs.msdn.microsoft.com/nav/2017/03/28/nav-development-tools-preview-march-update/ and add line discount % to the lines in a sales order. For that I do the following:

- Open Web Client
- Open the sales orders through the role center cue
- Open the first sales order
- Start edit mode
- More > + Field
- Select lines > the border appears
- Search for discount
- Drag and drop Line Discount %

Then I get the following error in the browser

Sorry, that didn't work
A server error has occurred, and the content cannot be displayed. Refresh the page or open a new browser window.

In the event log I see
`Error accessing Website Microsoft Dynamics NAV TENERIFE Web Client
Raw Url: /Navision_main/WebClient/cbs?aid=NAV
Url: http://localhost:8080/Navision_main/WebClient/cbs?aid=NAV
Type: Microsoft.Dynamics.Framework.UI.FormNotFoundException
Message: The logical form as specified in parameter with name 'LogicalControlReference' could not be found in the current session.
StackTrace:
   at Microsoft.Dynamics.Framework.UI.InteractionParameterHelper.GetLogicalControl(UISession uiSession, ClientLogicalControlReference clientLogicalControlReference)
   at Microsoft.Dynamics.Framework.UI.Client.DropItemInteractionExecutionStrategy.Initialize(IInteractionContext context, IDictionary``2 namedParameters)
   at Microsoft.Dynamics.Framework.UI.InteractionManager.<InvokeInteractions>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Framework.UI.WebBase.WebBaseInteractionManager.<InvokeInteractions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Framework.UI.CultureAwaiter``1.GetResult()
   at Microsoft.Dynamics.Framework.UI.Web.WebInteractionManager.<InvokeInteractions>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Framework.UI.CultureAwaiter``1.GetResult()
   at Microsoft.Dynamics.Framework.UI.Web.CallbackHandler.<HandleRequestCore>d__4.MoveNext()
Source: Microsoft.Dynamics.Framework.UI`

Any ideas what might cause this? Is this not the flow I am supposed to follow? I would love to show the new Designer to some colleagues but can't get any way how to add a field to work

**Comment by tfenster** [comment]
After deploying an Extension through VS Code / F5, now the In-client designer works as well. If I uninstall the Extension from VS Code, the error appears again.

**Comment by StanislawStempin** [comment]
We could not reproduce this on the current builds so it looks like this issue has been already fixed. FormNotFoundException is a generic issue that happens when the server session has timed out. We would ask you to try this out on the April Update that will go out later this month and see if it still reproduces there.

**Comment by tfenster** [comment]
OK, will test this. Any approximate idea when the update might be released?

**Comment by StanislawStempin** [comment]
We expect to release in the second half of April, I cannot promise a more precise date at this point.

**Comment by StanislawStempin** [comment]
The April Update is available. If you could please check if you can still reproduced this issue that would be great.

**Comment by tfenster** [comment]
Can't repro with April Update, working as expected now
