### ISSUE TITLE
Error when trying to build HelloWorld: Could not load type 'System.ValueTuple`2

### ISSUE THREAD

**Issue by reiniroosh** [Microsoft/AL#1439]
When I try to build the application it gives me this strange error.
Microsoft_Application_11.0.20048.0
Microsoft_System_11.0.12927.0

`[Error - 9:14:02 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.IsolatedDotNetTypeLoader..ctor(IAssemblyLocator locator)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.DotNetResolverFactory..ctor(IEnumerable`1 assemblyProbingPaths, Boolean cachePathsToAssembliesInCurrentAppDomain) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\DotNet\DotNetResolverFactory.cs:line 27
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.<>c__DisplayClass6_0.<TryGetService>b__0(Type svctype) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 62
   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue](ImmutableDictionary`2& location, TKey key, Func`2 valueFactory)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.TryGetService(Type serviceType, ILanguageService& service) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 58
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.GetService[TLanguageService]() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 43
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Project.get_SupportsCompilation() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Project.cs:line 101
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Solution.GetCompilationAsync(Project project, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Solution.cs:line 1977
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59`

**Comment by anzwdev** [comment]
Do you have .net framework 4.7 installed on your computer?

**Comment by reiniroosh** [comment]
It looks like no. Let me try that...
