### ISSUE TITLE
Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#1464]
got below error while working in visual studio
Please let me know if you need any details

[Error - 11:19:54 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/didChange' failed with error: 'Specified argument was out of the range of valid values.
Parameter name: length'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.TextSpan..ctor(Int32 start, Int32 length) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextSpan.cs:line 36
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.<UpdateBuffer>d__7.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeTextDocumentRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeTextDocumentRequestHandler.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by thpeder** [comment]
It is hard to know exactly what went wrong, but if you are able to reproduce the problem that would make it way easier for us to investigate the problem.

**Comment by qutreson** [comment]
Hi @pmohanakrishna, do you have more details to provide us with so that we can try to reproduce and fix this issue?

**Comment by kalberes** [comment]
See also #6320
