### ISSUE TITLE
Error after translation

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#1518]
Hi everybody,

we have refactored our code to work with translation files (https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-work-with-translation-files).

When we just use the generated xlif File it is okay. When we put in our translated xlif file we receive an error (see below) while creating the package (Crtl + Shift + B).

We added the target-language and target Tag per label.
Could it be that we have to change some values because of umlauts and other characters (see target value in screenshot)? 
Is there a list of translation characters?

![2018-01-30 09_08_14-d365onixappv2 12 - d365onixappv2 eastus cloudapp azure com_3389 - remotedeskto](https://user-images.githubusercontent.com/14943914/35554773-2fafb282-059d-11e8-96dd-d45d88e0b109.png)

**Error message in VS Code**
[Error - 7:46:37 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Value cannot be null.
Parameter name: value'
StackTrace:
   at Microsoft.CodeAnalysis.CSharp.ObjectDisplay.FormatLiteral(String value, ObjectDisplayOptions options)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.GetLabelDataTypeFieldInitializer(TypeSymbol typeSymbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Defaults.cs:line 275
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitFieldInitializer(TypeSymbol typeSymbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Defaults.cs:line 115
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectEmitHelper.EmitGlobalFieldDeclarations(ImmutableArray`1 globalVariables) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ApplicationObjectEmitHelper.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectEmitHelper.EmitGlobalVariables(ImmutableArray`1 globalVariables, SyntaxKind onClearAccessModifier, ClassDeclarationSyntax classDeclaration) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ApplicationObjectEmitHelper.cs:line 139
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectCodeEmitter.Emit() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ObjectCodeEmitter.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectCodeEmitter.Emit() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ApplicationObjectCodeEmitter.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectEmitter.EmitObjectCode() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ApplicationObjectEmitter.cs:line 39
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitObjectCode(ObjectTypeSymbol containingType) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 267
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 239
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 216
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 152
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 810
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 787
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 531
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 312
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by jiwanovski87** [comment]
Okay I replaced the umlauts like Ä and Ö and the error doesn't appear now.

**Comment by jiwanovski87** [comment]
Another question to that issue:

How should we replace the umlauts?
When I use the HTML Versions (Ä = &Auml;) I can create the the app file.
When I use the XML Verion (Ä = &#196;) I cannot create the app file and receive this error Message in VS Code:

 

**Error Message**
[Error - 9:55:06 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Value cannot be null.
Parameter name: value'
StackTrace:
   at Microsoft.CodeAnalysis.CSharp.ObjectDisplay.FormatLiteral(String value, ObjectDisplayOptions options)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.GetLabelDataTypeFieldInitializer(TypeSymbol typeSymbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Defaults.cs:line 275
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitFieldInitializer(TypeSymbol typeSymbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Defaults.cs:line 115
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectEmitHelper.EmitGlobalFieldDeclarations(ImmutableArray`1 globalVariables) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ApplicationObjectEmitHelper.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectEmitHelper.EmitGlobalVariables(ImmutableArray`1 globalVariables, SyntaxKind onClearAccessModifier, ClassDeclarationSyntax classDeclaration) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ApplicationObjectEmitHelper.cs:line 139
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectCodeEmitter.Emit() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ObjectCodeEmitter.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectCodeEmitter.Emit() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ApplicationObjectCodeEmitter.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ApplicationObjectEmitter.EmitObjectCode() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Code\ApplicationObjectEmitter.cs:line 39
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitObjectCode(ObjectTypeSymbol containingType) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 267
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 239
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 216
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 152
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 810
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 787
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 531
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 312
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by jiwanovski87** [comment]
It seems that German umlauts haven't been considered yet.
I tested to get the translation when I put in the umlauts in a caption and generate a new translation file. 

But there I still can see the umlauts. 
German common umlauts are:
Ä, ä, Ö, ö, Ü, ü, ß

**Comment by DominikDitoIvosevic** [comment]
Thank you for the very detailed analysis. I will try and see how I can enable as many of these scenarios as possible

**Comment by DominikDitoIvosevic** [comment]
Hi @jiwanovski87 . I'm afraid I cannot repro your issue locally. Could you please upload here a sample small extension which crashes because of umlauts?
If I try to copy paste your characters to either AL code or xliff file I don't get any issues when building or packaging.

**Comment by jiwanovski87** [comment]
Hi @DominikDitoIvosevic can you tell me if you translated the umlauts (as example Ä) to any other value? Which value? Ä = &Auml;? Ä = &#196;?

**Comment by jiwanovski87** [comment]
Ohh GitHub interprets my examples... I meant:
 `Ä = &Auml;`? 
`Ä = &#196;`?
Any other translation?

**Comment by DominikDitoIvosevic** [comment]
@jiwanovski87 I think I'm understanding something incorrectly. Are you saying this extension would fail to build for you? Could you please upload a small extensions which fails to build for you?

[MyAlProject.zip](https://github.com/Microsoft/AL/files/1740362/MyAlProject.zip)
