### ISSUE TITLE
Processing of message 'al/downloadSymbols' failed with error: 'Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jigneshdhandha** [Microsoft/AL#1964]
Hello Team,

We are currently using Visual Studio Code - Version 1.22.1 and also AL Language - 0.15.18771 is installed. while we creating the package system is giving an error as per below.

Processing of message 'al/downloadSymbols' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.<ProcessRequestAsync>d__3.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by StanislawStempin** [comment]
Can you share the launch.json that you are using and the server version?

**Comment by atoader** [comment]
Hi @jigneshdhandha ! Could you please provide more information about your project and your environment? What is the version of your server? What does your launch.json contain? What does your app.json contain?
