### ISSUE TITLE
severity: 'Error' message: 'Internal error: 'Object reference not set to an instance of an object.', Stack trace=unknown' at: '1,1' source: 'AL'

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#198]
When preparing a class around the new development tools I get this error when I create a table extension with this procedure

tableextension 72051234 CustomerFormatAddress extends Customer
{
    procedure FormatAddress(VAR AddrArray : ARRAY [8] OF Text[90]);
    var
        FormAddr : Codeunit "Format Address";
    begin
        FormAddr.Customer(AddrArray, Rec);
    end;
}

Output window:

[Error - 13:39:56] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/hover' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Conversions.HasImplicitRecordConversion(TypeSymbol source, TypeSymbol destination) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\Conversions\Conversions.cs:line 641
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.GetVarArgumentCompatibility(HashSet`1& useSiteDiagnostics, TypeSymbol argType, TypeSymbol parameterType) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 588
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.CheckArgumentForConversionApplicability(BoundExpression argument, ParameterSymbol parameter, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 573
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.IsApplicable(EffectiveParameters parameters, AnalyzedArguments arguments, BoundExpression receiverOpt, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 375
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.IsApplicable[TMember](TMember member, AnalyzedArguments arguments, EffectiveParameters effectiveParameters, BoundExpression receiverOpt, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 335
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.ResolveDefaultMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:line 1748
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.ResolveMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:line 1717
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindMethodGroupInvocation(SyntaxNode syntax, SyntaxNode expression, String methodName, BoundMethodGroup methodGroup, Boolean isStatement, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 141
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode expression, String methodName, BoundExpression boundExpression, Boolean isStatement, Boolean asProperty, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 99
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics, Boolean isStatement) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 32
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindExpressionStatement(SyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 477
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 78
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 921
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.GetBoundNodes(SyntaxNode node) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 394
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.GetLowerBoundNode(SyntaxNode node) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 334
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.GetBoundNodes(SyntaxNode node, SyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 203
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 115
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxTreeSemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SyntaxTreeSemanticModel.cs:line 115
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 573
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken) in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 422
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetSymbolAtPositionAsync>d__8.MoveNext() in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetSymbolAtPositionAsync>d__7.MoveNext() in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.HoverRequestHandler.<InternalHandleAsynch>d__1.MoveNext() in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\HoverRequestHandler.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsynch>d__1.MoveNext() in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\GenericRequestHandlerBase.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__5.MoveNext() in C:\Agent\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 60

**Comment by waldo1001** [comment]
Not sure this is your exact issue - but you are using "Rec" .. and Rec in a new proc in a TableExtension is not working yet: https://github.com/Microsoft/AL/issues/172

**Comment by esbenk** [comment]
It doesn't repro on the our current code-base and most likely fixed by #172.
