### ISSUE TITLE
CU 5 The AL server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by gnaaktgeboren** [Microsoft/AL#2165]
After installing CU 5 to following error is shown:
The AL server crashed 5 times in the last 3 minutes. The server will not be restarted.

The output window show the stack trace below.
What can I do to solve this?

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 14:43:51] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 14:43:51] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 14:43:51] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 14:43:51] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Error - 14:43:52] Connection to server got closed. Server will not be restarted.

```

**Comment by dennisfrostlander** [comment]
We apologize for this issue. The hotfix is already in progress.
As a workaround, you could manually edit the following file:

```
C:\Users\<your user>\.vscode\extensions\Microsoft.al-<your-extension>\bin\Microsoft.Dynamics.Nav.EditorServices.Host.exe.config
```

and replace:
`<bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />`

with:
`<bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="9.0.0.0" />`

E.g. change newVersion from 10.0.0.0 to 9.0.0.0.

Then restart VSCode.

**Comment by bwdeleeuw** [comment]
Any update on the hotfix for this?

**Comment by gnaaktgeboren** [comment]
@bwdeleeuw See the comment from @dennisfrostlander. That solved it for me.

**Comment by dennisfrostlander** [comment]
The blog post [Cumulative Update 05 for Microsoft Dynamics NAV 2018 has been released](https://blogs.msdn.microsoft.com/nav/2018/05/07/cumulative-update-05-for-microsoft-dynamics-nav-2018-has-been-released/) has been updated with the new download link for VSCode extension:
http://download.microsoft.com/download/9/A/3/9A3B0D52-B94F-4A4C-9168-F1CF58CA71C4/al-0.12.14734.vsix

**Comment by StanislawStempin** [comment]
You can now download the hotfixed extension from:
http://download.microsoft.com/download/9/A/3/9A3B0D52-B94F-4A4C-9168-F1CF58CA71C4/al-0.12.14734.vsix

**Comment by bwdeleeuw** [comment]
@gnaaktgeboren @dennisfrostlander thank you both!
