### ISSUE TITLE
CU4 Adding fields using in designer crashes web client

### ISSUE THREAD

**Issue by CBlasek** [Microsoft/AL#2166]
I am using CU4 on an upgraded database. I am able to publish and table / page extension from VS code in an upgraded DB. 

When I go to add a field using the web client-designer the application crashes when dragging the field from the available fields to the list page. 

Error accessing Website 
Raw Url: 
Url: 
Type: Microsoft.Dynamics.Nav.Types.GenericException
Message: Could not find target of extension objects during compilation. Make sure that system symbols are published.
The name 'Search Name' does not exist in the current context
The target Page "Chart of Accounts" for the extension object is not found
StackTrace:
   at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod, ServerCallOptions options) in S:\Depot\NAV\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionStateManager.cs:line 151
   at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod) in S:\Depot\NAV\Platform\Client\Shared\Prod.Client.ServiceConnection\ServiceConnection.cs:line 2011
   at Microsoft.Dynamics.Nav.Client.FormBuilder.NavDesignerService.AddLogicalControlCore(LogicalControl parentControl, Int32 newIndex, RowEntry controlInfo) in S:\Depot\NAV\Platform\Client\Shared\Prod.Client.Builder\BuilderSession\UIServices\NavDesignerService.cs:line 264
   at Microsoft.Dynamics.Framework.UI.InteractionInvoker.Invoke[T](String interactionName, Action`1 invokeMethod, T input) in S:\Depot\NAV\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 42
   at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in S:\Depot\NAV\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 40
   at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_0.<InvokeInteractions>b__3() in S:\Depot\NAV\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 125
Source: Microsoft.Dynamics.Nav.Client.ServiceConnection----------------------------------
Type: Microsoft.Dynamics.Nav.Types.GenericException
Message: Could not find target of extension objects during compilation. Make sure that system symbols are published.
The name 'Search Name' does not exist in the current context
The target Page "Chart of Accounts" for the extension object is not found
StackTrace:

Source:

**Comment by kalberes** [comment]
Looks similar to #1853

**Comment by kalberes** [comment]
You mean you that if you run Get-NavAppInfo -servername <your> -symbolsonly then you get something lime this too besides  teh System symbols.
Id            : e070cd4c-f452-46b7-b572-545b37df1e33
Name          : **Application**
Version       : 13.0.21845.0
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global

**Comment by StanislawStempin** [comment]
We believe this is fixed on CU6. Please contact regular support for further assistance.
