### ISSUE TITLE
Installing CU5 crashes VS Code

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#2223]
On installing a 100% standard Dynamics NAV 2018 CU5 and installing the equivalent vsix file (0.12.20065), VS Code  gives the error message shown below.

Installing the Dynamics 365 BC version (0.15.18771) everything works fine.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 4:59:26 PM] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 4:59:27 PM] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 4:59:27 PM] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 4:59:27 PM] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Error - 4:59:27 PM] Connection to server got closed. Server will not be restarted.

**Comment by kalberes** [comment]
see issue #2165 .

**Comment by DominikDitoIvosevic** [comment]
Closing as duplicate
