### ISSUE TITLE
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by MesutGulsuyu** [Microsoft/AL#2271]
I created the NAV objects for Turkey Localization. I succesfully created app file then I'm getting the error: `Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'`

[Error - 18:04:23] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.GetBoundOptionValueOrdinal(BoundEqualsPropertyExpression expression) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 149
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.GetConstConditionValue(BoundEqualsPropertyExpression expression) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 242
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.WriteFilterAttributes(XmlWriter writer, BoundEqualsPropertyExpression equalsExpression, String filterValueAttribute, String filterTypeAttribute, String filterGroup, Boolean isCondition) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 295
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass1_1.<WriteTableFilters>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 51
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.WriteTableFilters(XmlWriter writer, Boolean isCondition, String metadataElement, BoundTableRelationConditionExpression tableRelationExpression, String filterGroup) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 49
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass2_0.<WriteCalculationFormulaPropertyValue>b__1() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 78
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass2_0.<WriteCalculationFormulaPropertyValue>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 76
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableBaseMetadataEmitter`1.TryUseSpecialPropertyValueMetadataEmitter(XmlWriter xmlWriter, PropertySymbol property) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableBaseMetadataEmitter.cs:line 128
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter.WritePropertyValueMetadata(XmlWriter xmlWriter, PropertySymbol property) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitter.cs:line 50
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteElementProperties(XmlWriter xmlWriter, IEnumerable`1 properties, Action`2 writePropertyMetadata) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 62
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableBaseMetadataEmitter`1.<>c__DisplayClass4_0.<WriteField>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableBaseMetadataEmitter.cs:line 48
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableMetadataEmitter.<>c__DisplayClass3_0.<WriteFields>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableMetadataEmitter.cs:line 82
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableMetadataEmitter.<EmitMetadata>b__1_0(XmlWriter xmlWriter) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableMetadataEmitter.cs:line 38
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter`1.EmitMetadata(Action`1 content) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\GenericObjectMetadataEmitter.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 239
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 216
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 150
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 810
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 787
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 531
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 312
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by DominikDitoIvosevic** [comment]
Hi @MesutGulsuyu . Please tell us a version which you are using of the platform and the compiler and provide us with a reproducible scenario, best would be if you could make a small example extension which demonstrates your issue

**Comment by qutreson** [comment]
Hi @MesutGulsuyu, by looking at the stack trace, the null reference seems to be related to a filter expression involving a const with an option `const(OptionValue)` used in a property somewhere in a table object. Can you see if you can find a small repro of your issue based on this information?

**Comment by thpeder** [comment]
I'm closing the issue since we haven't heard from you for some time. If you are still experiencing the problem then just add a comment or open a new issue.

**Comment by MesutGulsuyu** [comment]
Hi @DominikDitoIvosevic 

I am using the following platforms:
•	Visual Studio Code,
•	Dynamics NAV 2018 Build 20783
•	Extension 2.0

I want to make Turkey Lozalizasyon Extension. I have a error in Exchange Notes Module. 

Only 3 tables and some objects give this error. I am removing these objects and making mistakes. You can find some objects that github link  to the Extension Objects. Tables 50003525, 50003562 and 50003570 from these objects give this error to the tables.

https://github.com/MesutGulsuyu/ExchangeNotesExtension

**Comment by MesutGulsuyu** [comment]
Hi @thpeder 

I solved this problem for now.
