### ISSUE TITLE
Error when publishing an app: "Error: A task was canceled"

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#2356]
I am trying to publish an app using bcinsider.azurecr.io/bcsandbox-master:ca image (Build 22070) and al language extension 0.15.14407 and I'm getting errors both from VS Code and from PowerShell.  Also had this same issue with older builds of bcsandbox-master:ca.

C/side is modified inside container with few publishers, nothing fancy. 

VS code is successfully creating package, but publishing fails with this message:

 ``
[2018-05-25 08:45:01.31] Publishing package to tenant 'default'
[2018-05-25 08:45:01.32] Sending request to http://ivan:7049/NAV/dev/apps?tenant=default&SchemaUpdateMode=recreate
[2018-05-25 08:50:01.37] Error: A task was canceled.
``

From PowerShell when trying:

````
Publishing c:\run\XX_Solution_11.19281.1.1.app
WARNING: This license is not compatible with this version of Dynamics NAV.
App successfully published

PS C:\Windows\system32> Install-NavContainerApp -containerName ivan -tenant default -appName "XX Solution"

Installing XX Solution on default
WARNING: This license is not compatible with this version of Dynamics NAV.
The extension 'XX by XX 11.19281.1.1' is not synchronized.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.8.5\AppHandling\Install-NavContainerApp.ps1:25 char:5
+     Invoke-Command -Session $session -ScriptBlock { Param($appName, $ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.InstallNavApp
    + PSComputerName        : 9ea30dd40174b573a4e5c08ac8491842aad673d7f5926d3d87242e53f1a3dc72
 
````

Event log is showing one error:

![image](https://user-images.githubusercontent.com/20359384/40545280-9423779c-602b-11e8-9b57-ebbc52e68dd8.png)

````
The description for Event ID 0 from source Microsoft.Dynamics.Nav.Management.dll cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Type: System.InvalidOperationException
Message: The extension 'XX Solution by XX11.19281.1.1' is not synchronized.
HResult: -2146233079

````

Any ideas of what could be causing this or where to look?

**Comment by ivandjordjevic** [comment]
I tried today with newer build (AL Language version 0.17.16611) and changed "schemaUpdateMode to Synchronize.

I'm getting success message from VS Code even though I can't start the client:

``
[2018-05-28 12:18:02.19] Publishing package to tenant 'default'
[2018-05-28 12:18:02.20] Sending request to http://ivan:7049/NAV/dev/apps?tenant=default&SchemaUpdateMode=synchronize
[2018-05-28 12:19:49.46] Success: The package 'XX Solution_11.19281.1.1.app' has been published to the server.
``

Client is reporting just "Sorry, that didn't work" and event log one erorr and several warning messages:

![image](https://user-images.githubusercontent.com/20359384/40622971-8fb5128a-62a4-11e8-8c05-d34417f3e32b.png)

**Error message**:

````
The description for Event ID 0 from source MicrosoftDynamicsNAVClientWebClient cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Error accessing Website 
Type: System.ArgumentException
Message: An item with the same key has already been added.
StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Dynamics.Nav.Client.Builder.NavFormDescriptionBuilder.GetExpressionColumns(IList`1 expressions) in S:\Depot\NAV\platform\client\Shared\Prod.Client.UI\Builder\NavFormDescriptionBuilder.cs:line 425
   at Microsoft.Dynamics.Nav.Client.Builder.NavFormDescriptionBuilder.Create(MetaTable metaTable, MasterPage masterPage) in S:\Depot\NAV\platform\client\Shared\Prod.Client.UI\Builder\NavFormDescriptionBuilder.cs:line 34
   at Microsoft.Dynamics.Nav.Client.Builder.NavBindingManagerBuilder.CreateBindingManager(IService service, MasterPage masterPage, String personalizationId, LogicalThread asyncThread) in S:\Depot\NAV\platform\client\Shared\Prod.Client.UI\Builder\NavBindingManagerBuilder.cs:line 358
   at Microsoft.Dynamics.Nav.Client.FormBuilder.BindingManagerFactory.Create(MasterPage definition, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\BuilderSession\BindingManagerFactory.cs:line 64
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.Build(MasterPage definition, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Framework\PageBuilder.cs:line 259
   at Microsoft.Dynamics.Nav.Client.FormBuilder.InfopartBuilderBase`1.CreatePart(TDefinition definition, FormHostControl infopart, UIBuilderContext partContext, Boolean filteringAllowed) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Builders\InfopartBuilderBase.cs:line 103
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageInfopartBuilder.CreatePagePart(InfopartPageDefinition infoPartDefinition, FormHostControl infopart, UIBuilderContext partContext, Boolean filteringAllowed) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Builders\PageInfopartBuilder.cs:line 246
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageInfopartBuilder.DoBuildFactbox(InfopartPageDefinition definition, LogicalControl parent, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Builders\PageInfopartBuilder.cs:line 66
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PlaceholderBuilder.BuildFactBoxArea(ControlContainerPlaceHolder definition, LogicalControl parent, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Builders\PlaceHolderBuilder.cs:line 99
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PlaceholderBuilder.DoBuild(ControlContainerPlaceHolder definition, LogicalControl parent, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Builders\PlaceHolderBuilder.cs:line 28
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.AddInfoParts(MasterPage definition, LogicalForm form, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Framework\PageBuilder.cs:line 658
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.TryAddInfoParts(MasterPage definition, LogicalForm form, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Framework\PageBuilder.cs:line 87
   at Microsoft.Dynamics.Nav.Client.FormBuilder.ListPageBuilder.DoBuild(MasterPage definition, BindingManager bindingManager, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Builders\ListPageBuilder.cs:line 125
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.Build(MasterPage definition, BindingManager bindingManager, UIBuilderContext context) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\Framework\PageBuilder.cs:line 117
   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(MasterPage metadata, FormState formState) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\BuilderSession\BuilderSession.cs:line 328
   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(Int32 formId, FormState formState, Int32 retryCounter) in S:\Depot\NAV\platform\client\Shared\Prod.Client.Builder\BuilderSession\BuilderSession.cs:line 275
   at Microsoft.Dynamics.Nav.Client.NavRunPagePropertyBagInvokedAction.InvokePropertyBagAction(UISession uiSession) in S:\Depot\NAV\platform\client\Shared\Prod.Client.UI\NavRunPagePropertyBagInvokedAction.cs:line 337
   at Microsoft.Dynamics.Nav.Client.NavPropertyBagInvokedActionBase.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in S:\Depot\NAV\platform\client\Shared\Prod.Client.UI\NavPropertyBagInvokedActionBase.cs:line 72
   at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(LogicalControl logicalControl, IDictionary state, UISession uiSession) in S:\Depot\NAV\platform\client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 497
   at Microsoft.Dynamics.Framework.UI.LogicalFormActivator.<>c__DisplayClass4_0.<ValidateAndInvokePropertyBag>b__0() in S:\Depot\NAV\platform\client\Shared\Prod.ClientFwk\URL\LogicalFormActivator.cs:line 64
   at Microsoft.Dynamics.Framework.UI.WindowsThreadingDispatcher.Invoke(Action method) in S:\Depot\NAV\platform\client\Shared\Prod.ClientFwk\Dispatchers\WindowsThreadingDispatcher.cs:line 205
   at Microsoft.Dynamics.Framework.UI.LogicalFormActivator.ValidateAndInvokePropertyBag(FormPropertyBag propertyBagToUse, UISession uiSession, Object invocationState) in S:\Depot\NAV\platform\client\Shared\Prod.ClientFwk\URL\LogicalFormActivator.cs:line 66
   at Microsoft.Dynamics.Framework.UI.OpenFormInteraction.InvokeCore(OpenFormInteractionInput logicalInteractionInput) in S:\Depot\NAV\platform\client\Shared\Prod.ClientFwk\Interactions\SystemInteractions\OpenFormInteraction.cs:line 0
   at Microsoft.Dynamics.Framework.UI.InteractionInvoker.Invoke[T](String interactionName, Action`1 invokeMethod, T input) in S:\Depot\NAV\platform\client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 42
   at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in S:\Depot\NAV\platform\client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 40
   at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_0.<InvokeInteractions>b__3() in S:\Depot\NAV\platform\client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 125
Source: mscorlib
````

**Warning message**:

````
The description for Event ID 705 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: NAV
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 00000000-0000-0000-0000-000000000000
EventTime: 05/28/2018 16:18:57
Message Action completed successfully, but it took longer than the given threshold.
  Execution time: 1535 ms
  Threshold: 1000 ms
  Message: Long running SQL statement 
  Task ID: 3
  Connection ID: 3
  Database Name: FinancialsCA
  Statement: SELECT DISTINCT CT.SYS_CHANGE_VERSION, 0[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Object Metadata], @maxChangeTrackingNumberObjectMetadata) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 1[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [Debugger Breakpoint], @maxChangeTrackingNumberDebuggerBreakpoint) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 2[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Add-in], @maxChangeTrackingNumberAddIn) CT WHERE CT.SYS_CHANGE_OPERATION = 'U'
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 3[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], CT.[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Object Metadata], @maxChangeTrackingNumberNavAppObjectMetadata) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 4[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[App Package ID], CT.[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Tenant App], @maxChangeTrackingNumberNavAppTenantApp) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 5[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App], @maxChangeTrackingNumberNavApp) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 6[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[App Package ID], CT.[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Publish Reference], @maxChangeTrackingNumberNavAppPublishReference) CT
  
ProcessId: 21608
Tag: 000007L
ThreadId: 87
CounterInformation: 
````

````

The description for Event ID 202 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: NAV
Tenant: default
Session type: Background
Session ID: 81
This license is not compatible with this version of Business Central.
````

Seems like I can open web client but as soon as I navigate to page that has been modified through extension I get a failure.

**Comment by cmrudolph-msft** [comment]
For reference (since you seem to be able to use the IDE again) to the question above about using PowerShell - the missing ingredient is Sync-NavContainerApp between publishing and installing. Search for Sync-NavApp for general info about the underlying cmdlet.

The newest error will require a bit of investigation on our part.

**Comment by cmrudolph-msft** [comment]
@ivandjordjevic we are fixing the latest issue in a future platform build. The underlying problem is that there are multiple expressions on the given page with the same name. Since the final set of expressions is a last-minute decision (runtime), the best we can do is fail at extension install time with a clear message indicating where the duplication lies.

In the meantime, this means the best I can offer you is a suggestion to evaluate your use of global variables in your code. Something is colliding with either the base app, a dependency, or another installed extension.

**Comment by ivandjordjevic** [comment]
@cmrudolph-msft So the workaround would be to have unique Page control names and variables and also try to avoid name conflicts between extension and base app?

Strange thing is that if I look at Extension Management page I can see my App installed. But whenever I navigate to a page that has been customized or added through extension I get a failure.  

However, some of the few simple new pages from extension that I run through web client URL using PageID are working!

**Comment by ivandjordjevic** [comment]
@cmrudolph-msft You were right, renaming some global variables in page extension object which existed with the same name in base app fixed the issue with running that page.

We have total around 800 .al files, and around 140 Page extension objects so we'll have to check all of them for this issues. 

Any chance you know when will this fix be delivered for insider builds?

**Comment by cmrudolph-msft** [comment]
@ivandjordjevic the platform change it making its way into our master branch right now. We release insiders builds once daily, so this should be available in the next 2-3 days depending on how everything lines up. **I can let you know the build number when this becomes official.**

I am also having a discussion with the compiler team about changing the internal behavior around expression name generation to produce unique names. If done, the name uniqueness requirements in source would become more relaxed. It's too early to share specifics, but be aware that some changes may be coming.

**Regardless, if you are okay renaming your variables for uniqueness now, this is the safest course of action.**

**Comment by cmrudolph-msft** [comment]
@ivandjordjevic - insider builds with build number of at least 22414 will have the change. Attempts to install an extension violating the expression uniqueness rules will raise an error. Unlike true compilation failures, issues detected at this phase terminate metadata loading immediately (so you'll see them one-by-one).

Whatever changes are decided on by the compiler team should also help this situation eventually. If stricter rules get rolled into the compiler itself, these type of errors will become evident at compile time. If what is emitted by the compiler changes, the conflicts will not occur anymore.

**Comment by ivandjordjevic** [comment]
After resolving some of the naming conflicts we identified on our page extension objects we are able to publish app. 

Thanks!
