### ISSUE TITLE
Processing of message 'textDocument/codeLens' failed with error: 'Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral,..

### ISSUE THREAD

**Issue by zuhadmahmood** [Microsoft/AL#2431]
The issue occurs just after i download of symbols completed attaching the stack trace.Please help me to resolve this issue asap Thanks . 

[2018-05-30 16:12:53.55] All reference symbols have been downloaded.
[Error - 4:12:53 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeLens' failed with error: 'Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral'.'
Stack Trace:- 
 at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.IsolatedDotNetTypeLoader..ctor(IAssemblyLocator locator)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.DotNetResolverFactory..ctor(IEnumerable`1 assemblyProbingPaths, Boolean cachePathsToAssembliesInCurrentAppDomain) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\DotNet\DotNetResolverFactory.cs:line 27
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.<>c__DisplayClass6_0.<TryGetService>b__0(Type svctype) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 62
   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue](ImmutableDictionary`2& location, TKey key, Func`2 valueFactory)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.TryGetService(Type serviceType, ILanguageService& service) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 58
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.GetService[TLanguageService]() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 43
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Project.get_SupportsCompilation() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Project.cs:line 91
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Document.<GetSemanticModelAsync>d__19.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Document.cs:line 0
--- End of stack trace from previous location where exception was thrown ---

**Comment by atoader** [comment]
Hi! What version of the .NET Framework runtime do you have installed? Please install .NET 4.7 or higher.

**Comment by zuhadmahmood** [comment]
hi! thanks for your help there was the issue with my .NET framework i have updated it to .NET 4.7.2. Now it works fine.

thanks
