### ISSUE TITLE
Gzip MagicNumber Error on SOAP https://api.businesscentral.dynamics.com

### ISSUE THREAD

**Issue by Martin-Lavigne** [Microsoft/AL#2442]
Hi, 
We are having issue right now communicating with all SOAP Webservice on a Trial version of BusinessCentral. 

We have an app that create a webservice that we are able to reach using both ODataV4 and SOAP url in our Azure Dev VM. But when we try to access a Trial version of Business Central we have issue. 
Calling the OdataV4 URL works fine, althought when we try to access the SOAP URL on a Trial Version of Business Central, we receive the following error : 

> The magic number in GZip header is not correct. Make sure you are passing in a GZip stream.

We have tried to update the Service Reference in Visual Studio but it didn't fix the error. Do we need to specify something on the binding to manage correctly the GZIP? 

This is a code sample : 
`Dim oJobList As New Job_ListWS.Job_List_PortClient
Dim binding As ServiceModel.BasicHttpBinding
            
binding = New ServiceModel.BasicHttpBinding()

           
binding.Security.Transport.ClientCredentialType = ServiceModel.HttpClientCredentialType.Basic
binding.Security.Mode = ServiceModel.BasicHttpSecurityMode.Transport

oJobList = New Job_ListWS.Job_List_PortClient(binding, New ServiceModel.EndpointAddress("https://api.businesscentral.dynamics.com/v1.0/BUSINESSCENTRALTEST/Page/Job_List"))
oJobList.ClientCredentials.UserName.UserName = "MYUSER"
oJobList.ClientCredentials.UserName.Password = "MYPASSWORD"
oJobList.Read("TEST")`

If anyone have come across this error and could help us it would be really apreciated! 
Regards,
Martin Lavigne.

**Comment by Martin-Lavigne** [comment]
Server stack trace: 
   at System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.ServiceModel.Channels.HttpInput.WebResponseHttpInput..ctor(HttpWebResponse httpWebResponse, IHttpTransportFactorySettings settings, ChannelBinding channelBinding)
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateRequestReplyResponse(HttpWebRequest request, HttpWebResponse response, HttpChannelFactory`1 factory, WebException responseException, ChannelBinding channelBinding)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

**Comment by Martin-Lavigne** [comment]
I used Fiddler and the response is defined as Gzip, but the body isn't zipped. 
The same error occured when Fiddler try to decode the response. ( See File in attachement) 
![fiddlerbusinesscentralcall](https://user-images.githubusercontent.com/32858696/40803266-3ab80d3e-64e6-11e8-91fa-168e50e78f51.png)

**Comment by StanislawStempin** [comment]
This was a bug on our side. The fix will be deployed next week.

**Comment by StanislawStempin** [comment]
The fix has been now deployed, you should no longer see this problem.
