### ISSUE TITLE
Deploying on cloud sandbox is failing: Unauthorized

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#2471]
Since it's asking me to put this on github...

I'm trying to develop from VSCode against a cloud sandbox, and all of a sudden, all is unauthorized .. no clear reason.

Here are the details

```
[2018-06-05 17:17:22.75] Using reference symbols cache path: c:\Users\Waldo\Dropbox (Personal)\Presentations\iFacto\2018\2018-06-07 Klantenevent\Customization\Twitter\./.alpackages
[2018-06-05 17:17:22.75] Authenticating...
[2018-06-05 17:17:23.10] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=12.0.0.0
[2018-06-05 17:17:23.10] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=12.0.0.0
[2018-06-05 17:17:23.26] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=12.0.0.0 failed with code Unauthorized. Reason: Web service call failed because user could not be authenticated or authorized.
[2018-06-05 17:17:23.29] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=12.0.0.0 failed with code Unauthorized. Reason: Web service call failed because user could not be authenticated or authorized.
[Error - 17:17:23] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'Unsupported authentication method AAD
Parameter name: Authentication'
StackTrace:
   at Microsoft.Dynamics.Nav.Deployment.OnPremiseHttpClientFactory..ctor(EmitLogger logger, ConnectionOptions connectionOptions) in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\OnPremiseHttpClientFactory.cs:line 29
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\46\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

```

I have been clearing credentials and resetting sandboxes about 10 times ...

**Comment by dennisfrostlander** [comment]
Could you please try to re-use symbol packages from another project (so that your extension builds locally) and then publish to the sandbox with F5? Would you get a permission error saying that you don't have access to TableData Nav App?
If this is the case, could you please check that you are either a SUPER user on the sandbox or you have Extension MGT permission set for an _empty_ company?
This would explain the 401 Unauthorized error.

The exception for al/downloadSymbols that you get afterwards is an incorrect handling of 401 error in the AL extension. It has already been fixed in the latest codebase.

**Comment by waldo1001** [comment]
Well - can't say what the problem was, but all of a sudden, it started to work again.

strange...
