### ISSUE TITLE
"Object reference not set to an instance of an object" when referencing fields from another extension

### ISSUE THREAD

**Issue by HeidiAlfordTM** [Microsoft/AL#2490]
I am working on a test suite for our new extension. The new test suite has a dependency upon our extension and is set to a target of 'Internal'. We cannot use any other target without getting errors from attempts to reference the 'Assert' codeunit etc. (Not allowed for extension development).

When attempting to publish/install I get the error "failed with code 422. Reason: Object reference not set to an instance of an object.".

As a test I created a new project, then wrote a simple test codeunit as follows:-

```
codeunit 60001 TestCodeunit
{
    Subtype=Test;
    var
        Assert : Codeunit Assert;
        LibraryTestInitialize : Codeunit "Library - Test Initialize";
        isInitialized : Boolean;
        LibraryWhse : Codeunit "Library - Warehouse";
        LibraryPurchase : Codeunit "Library - Purchase";
        LibraryInventory : Codeunit "Library - Inventory";
        Location : Record Location;
        PurchaseHeader : record "Purchase Header";
        Vendor : record Vendor;
        DeviceUser : Record "Device Warehouse User";

    [Test]
    procedure TestOne()
    var
        Vendor : Record Vendor;
    begin
        Initialize();
        LibraryPurchase.CreateVendor(Vendor);

        DeviceUser.Init();
        DeviceUser."User ID" := 'TEST';
        DeviceUser.Insert(true);

        assert.IsFalse(DeviceUser."Prompt for Specific Pick", 'Prompt for specific pick should be false');

    end;

    local procedure Initialize()
    begin
        LibraryTestInitialize.OnTestInitialize(Codeunit::"Testcodeunit");
        if isInitialized then
            exit;
        LibraryTestInitialize.OnBeforeTestSuiteInitialize(Codeunit::"Testcodeunit");
        isInitialized := true;

        LibraryWhse.CreateLocationWithInventoryPostingSetup(Location);
        isInitialized := true;

        Commit();
        LibraryTestInitialize.OnAfterTestSuiteInitialize(Codeunit::"Testcodeunit");

    end;
   
}
```

**Device Warehouse User** is a table in our extension, it works until attempting to assign a value to a field in a table in our extension.

Application log shows:-
```
Server instance: DynamicsNAV110
Category: Development
ClientSessionId: {00000000-0000-0000-0000-000000000000}
ClientActivityId: {00000000-0000-0000-0000-000000000000}
ServerSessionUniqueId: {9fdcedbd-c364-4c38-9ad1-661f31dd66d3}
ServerActivityId: {ba4573bd-5d26-4f98-9d08-2560c8942767}
EventTime: ‎2018‎-‎06‎-‎06T16:02:07.064742600Z
Message Failed request -- Method:POST; Url:<ii>http://localhost:7049/DynamicsNAV110/dev/apps?SchemaUpdateMode=recreate</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"Object reference not set to an instance of an object.\r\n"}</pi>
ProcessId: 9952
Tag: 00000LY
ThreadId: 41
CounterInformation: 
```

Removing the ```Assert.IsFalse``` gives a different error on publish/install: "The left-hand side of an assignment must be a variable or field".

```
Server instance: DynamicsNAV110
Category: Development
ClientSessionId: {00000000-0000-0000-0000-000000000000}
ClientActivityId: {00000000-0000-0000-0000-000000000000}
ServerSessionUniqueId: {9fdcedbd-c364-4c38-9ad1-661f31dd66d3}
ServerActivityId: {ba4573bd-5d26-4f98-9d08-2560c8942767}
EventTime: ‎2018‎-‎06‎-‎06T16:03:08.541974500Z
Message Failed request -- Method:POST; Url:<ii>http://localhost:7049/DynamicsNAV110/dev/apps?SchemaUpdateMode=recreate</ii>; StatusCode:422; ReasonPhrase:Unprocessable Entity; ResponseBody: <pi>{"Message":"Extension compilation failed\r\nTestCodeunit.al(26,9): error AL0129: The left-hand side of an assignment must be a variable or field\r\n"}</pi>
ProcessId: 9952
Tag: 00000LY
ThreadId: 107
CounterInformation: 
```

AL Language extension 0.15.18771, Dynamics NAV 2018 CU5.

**Comment by atoader** [comment]
Hi @HeidiAlfordTM ! I am investigating the issue to see if I can repro it. Please make sure to read our FAQs https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use . It seems that you are using a version of the AL Language extension that doesn't match your runtime.

**Comment by HeidiAlfordTM** [comment]
You are correct! I thought I'd imported the vsix from the CU5 media, but clearly I got confused somewhere along the line. I switched to 0.12.20065 and I now get the following error upon starting VS Code...

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 10:06:42] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 10:06:42] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 10:06:42] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Info  - 10:06:42] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Error - 10:06:42] Connection to server got closed. Server will not be restarted.
```

**Comment by HeidiAlfordTM** [comment]
Done as you requested. Still getting the error:
```Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)```

**Comment by atoader** [comment]
Ok. You hit another bug. Can you follow the instructions provided in this issue to download a newer version of the extension https://github.com/Microsoft/AL/issues/2165 ?

**Comment by HeidiAlfordTM** [comment]
Thanks for your help so far.

I may have the wrong end of the stick but the "Newer" version (0.12.14734) was older than the version that ships with CU5 (0.12.20065)? I did try it, but it didn't resolve the error.

Anyway, I did the ```Microsoft.Dynamics.Nav.EditorServices.Host.exe.config``` change instead which seems to have moved me forward a bit. Wasn't sure what else to try.

I now get this error from the output log when I uncomment the problem code:-

```
[Error - 14:06:03] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Object reference not set to an instance of an object.
StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesService.FindReferencedSymbolsAsync(Document document, Int32 position, CancellationToken cancellationToken) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesService.cs:line 25
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensResolveRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensResolveRequestHandler.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59
```

I get this error when I try to build:-

```
[Error - 14:11:49] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolutionResult`1.ReportBadArgumentError(DiagnosticBag diagnostics, AnalyzedArguments arguments, ImmutableArray`1 symbols, TMember method, Int32 arg) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolutionResult.cs:line 506
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolutionResult`1.HadBadArguments(DiagnosticBag diagnostics, AnalyzedArguments arguments, ImmutableArray`1 symbols) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolutionResult.cs:line 478
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolutionResult`1.ReportDiagnostics[T](Location location, DiagnosticBag diagnostics, String name, AnalyzedArguments arguments, ImmutableArray`1 memberGroup, Boolean isMethodGroupConversion) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolutionResult.cs:line 232
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpressionContinued(SyntaxNode node, SyntaxNode expression, String methodName, OverloadResolutionResult`1 result, AnalyzedArguments analyzedArguments, MethodGroup methodGroup, Boolean isStatement, DiagnosticBag diagnostics) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 238
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindMethodGroupInvocation(SyntaxNode syntax, SyntaxNode expression, String methodName, BoundMethodGroup methodGroup, Boolean isStatement, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 191
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode expression, String methodName, BoundExpression boundExpression, Boolean isStatement, Boolean asProperty, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 98
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics, Boolean isStatement) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 31
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindExpressionStatement(SyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 517
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatements(SyntaxList`1 syntaxStatements, DiagnosticBag diagnostics, Binder binder) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.BindMethodBody(MethodSymbol method, DiagnosticBag diagnostics) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 463
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethod(MethodSymbol methodSymbol) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 385
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMembers(ContainerSymbol containingType) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 309
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 233
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 216
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 150
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 810
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 787
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 531
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 312
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59
```

**Comment by atoader** [comment]
Long story, short: we migrated to a new build system between those two releases and the build numbers got reset. 
Let's give it one more try:
1. Upgrade to CU6
2. Uninstall the current extension
3. Install the extension from CU6
4. Make sure you have the latest symbols
5. Try to compile your code

If you still get the failure, could you please post a self-contained sample here?

**Comment by HeidiAlfordTM** [comment]
Sorry, have been tied up with other work. I have gotten as far as re-installing with CU6 but was having issues with launch.json (I seem to get a lot of 'Please provide server settings' warnings when I switch between different versions).

My plan was to look at it again this week. Can I have a little more time?

**Comment by HeidiAlfordTM** [comment]
OK, this seems to be working now. As an aside using vscode workspaces resulted in the error "Please provide server settings" whenever I tried to download symbols or build/deploy. I've abandoned workspaces and just open as a folder now.

I'm happy everything else is working as it should, so thanks very much for the help.

**Comment by atoader** [comment]
Hi @HeidiAlfordTM ! Thank you very much for looking into this :) I think the workspaces feature was freshly implemented for NAV 2018 and didn't get much use. A lot of work has been put into making it work well in the next release. I will close this issue. If you have other problems, please open a new issue.
