### ISSUE TITLE
Unexpected value 'ClassType' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind'

### ISSUE THREAD

**Issue by XceSx6** [Microsoft/AL#2612]
I am getting the this Build Error, and no clue what, where, or why ..
Previous issues about 'Unexptected ...' did not clarify what / where the problem could be.

Processing of message 'al/createPackage' failed with error: 'Unexpected value 'ClassType' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind''
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitExpression(BoundExpression expr, Boolean suppressTarget, Boolean isStatement) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 101
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitToVariantConversion(BoundConversion conversion) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Conversions.cs:line 517
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitExpression(BoundExpression expr, Boolean suppressTarget, Boolean isStatement) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 59
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitArgumentExpression(ParameterSymbol parameterSymbol, BoundExpression argumentExpression) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 580
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitArguments(InvocationExpressionSyntax invocation, BoundCall call) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 406
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitBuiltInMethodCall(BoundCall call) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 255
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitExpression(BoundExpression expr, Boolean suppressTarget, Boolean isStatement) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 45
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitArgumentExpression(ParameterSymbol parameterSymbol, BoundExpression argumentExpression) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 580
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitArguments(InvocationExpressionSyntax invocation, BoundCall call) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 406
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitUserLocalMethodCall(BoundCall call) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 326
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitUserMethodCall(BoundCall call, Boolean isStatement) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 289
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitExpression(BoundExpression expr, Boolean suppressTarget, Boolean isStatement) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 45
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitToTextConversion(BoundConversion conversion) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Conversions.cs:line 148
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitExpression(BoundExpression expr, Boolean suppressTarget, Boolean isStatement) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 59
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitArgumentExpression(ParameterSymbol parameterSymbol, BoundExpression argumentExpression) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 580
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitArguments(InvocationExpressionSyntax invocation, BoundCall call) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 406
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitBuiltInMethodCall(BoundCall call) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 255
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenerator.EmitExpression(BoundExpression expr, Boolean suppressTarget, Boolean isStatement) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenerator_Expressions.cs:line 45
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitExpressionStatement(BoundExpressionStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 25
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 219
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitStatement(BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitCaseLineStatement(BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 796
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitCaseStatementAsIfThenElse(ArrayBuilder`1 statementList, BoundCaseStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 783
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitCaseStatement(ArrayBuilder`1 statementList, BoundCaseStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 737
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 254
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitStatement(BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 258
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitStatement(BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitIfStatement(BoundIfStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 308
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 239
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitBlock(BoundBlock block) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 117
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 235
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitStatement(BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitIfStatement(BoundIfStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 308
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 239
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitStatement(BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitNativeForEachStatement(ArrayBuilder`1 statementList, BoundForEachStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 418
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 245
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitBlock(BoundBlock block) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 117
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitScopeRunMethod() in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator.cs:line 629
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitScopeClass() in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator.cs:line 251
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.Generate() in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator.cs:line 104
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethod(MethodSymbol methodSymbol) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 431
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMembers(ContainerSymbol containingType) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 304
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 220
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass14_0.<CompileObjectAsTask>b__0() in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 201
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 152
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 816
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 791
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 551
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 414
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 313
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\36\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by thpeder** [comment]
Hi @XceSx6,
It is hard to tell only from the stacktrace but it looks like you have a foreach statement with a case statement inside which calls a built-in procedure and the arguments to that call is a invocation to a nother procedure.

I hope that helps to find the code that causes the error so we can get a good repro and fix it.

**Comment by XceSx6** [comment]
Unfortunately no.,. I've done a search on 'foreach'.. even removing all of these an building again throws the exact same error.

How can we go about finding out what File / Line the compiler seems to have a problem with ?
CodeCops indicate 0 Problems ..

**Comment by thpeder** [comment]
It is not the foreach statement itself, it is the code inside it.
So you could try comment out all the code inside the foreach statements, and maybe find which one makes it fail.

**Comment by XceSx6** [comment]
I have removed the entire 'foreach' statements: including the content, the entire code blocks..
Unfortunately still the same error

**Comment by thpeder** [comment]
What version of the extension are you running?
That seems strange since the stack trace shows that it tries to compile a foreach statement, but then how about checking all your case statements.

**Comment by XceSx6** [comment]
Dear Thomas,

Thank you kindly for your help, i have found the problem .. (i had missed a CASE)
I was checking the CASE statements one by one, building as i go..
Finally found what it was .. although it would have saved ma alot of time should VSCode have thrown Filename+LineNumber in its Compiler Stack Trace ;)

I used to have a table field named "Report".. obviously this is not desired, so I had renamed it to "Report Text" Text[250] URL ..
However, i had missed something:
>> CopyStr("Report Text", 1, MaxStrLen(**Report**));
Which needs to be "CopyStr("Report Text", 1, MaxStrLen(**Report Text**));"
This was the last within a CASE, within a FOREACH.. so you were a 100% correct in your first assessment.
I had looked passed this one ..

Thank you kindly for your guidance.

**Comment by thpeder** [comment]
I'll mark it as a bug, since you should of course not see a stack trace for that.
Thanks for reporting the issue.

**Comment by DominikDitoIvosevic** [comment]
@XceSx6 could you please try creating a code snippet which reproduces the issue? I cannot reproduce by just using what you wrote so far

**Comment by XceSx6** [comment]
create an AL file and Paste, then try to Compile this:

table 50111 "Example"
{
    fields
    {
        field(10; KeyValue; Integer)
        {
            AutoIncrement = true;
        }
        field(20; "Report Text"; Text[250])
        {
            ExtendedDatatype = URL;
        }
    }

    keys
    {
        key(key1; KeyValue)
        {
            Clustered = true;
        }
    }

}

codeunit 50111 "Execute Example"
{
    trigger OnRun()
    var
        ExampleRecord: Record Example;
        NewTextValue: Label 'https://github.com/Microsoft/AL/issues/2612', Locked = true;
    begin
        ExampleRecord."Report Text" := CopyStr(NewTextValue, 1, MaxStrLen(Report))
    end;
}

= Processing of message 'al/createPackage' failed with error: 'Unexpected value 'ClassType' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind''
