### ISSUE TITLE
txt2al fails or deadlocks intermittently.

### ISSUE THREAD

**Issue by rdebath** [Microsoft/AL#2704]
Version: 13.0.22621
This run failed; immediately following (scripted) run succeeded without problem.

Problem has occurred several times at different points in addition `txt2al.exe` sometimes hangs while using 100% of all CPUs. But, most of the time the conversion is successful.

Errors are... 
A long list of objects (approx 200 of the 300 objects) with the error:
```
----ERROR----
Error converting file:c:\usr\vscode\Delta\COD65601.DELTA
Index was outside the bounds of the array.

```

And at the end:
```
----ERROR----
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.MultiLanguageOutputter.<>c__DisplayClass6_1.<FinalizeExtraction>b__0()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.<>c__DisplayClass2_0.<WriteDefaultNodesAndContinue>b__3()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.<>c__DisplayClass2_0.<WriteDefaultNodesAndContinue>b__2()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.<>c__DisplayClass2_0.<WriteDefaultNodesAndContinue>b__1()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.<>c__DisplayClass2_0.<WriteDefaultNodesAndContinue>b__0()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.WriteDefaultNodesAndContinue(XmlWriter writer, String appName, String targetLanguage, Action groupContentWriter)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.MultiLanguageOutputter.FinalizeExtraction(Action`2 processTranslationFile)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.TranslationExtractor.FinalizeExtraction(Action`2 processTranslationFile)
   at Txt2Al.Program.ExportTranslationFiles(AlExportOptions exporterOptions, AlExporterCommandLineOptions options, ITranslationExtractor translationExtractor)
   at Txt2Al.Program.ConvertFilesFromDirectory(AlExporterCommandLineOptions options)

Total Time: 0:00:01.0002488
Errors: 227
```

**Comment by rdebath** [comment]
Another random error, perhaps related; seems to happen to only one object at a time; different object each time.
```
----ERROR----
Error converting file: c:\usr\vscode\tmp\Delta\COD65605.DELTA
Object reference not set to an instance of an object.
```

**Comment by qutreson** [comment]
Hi @rdebath, can you provide us with some code from COD65605.DELTA in order for us to reproduce this error?

**Comment by rdebath** [comment]
I've now switched to 13.0.23094 for this test (the fix to #2714 is working nicely).

Four out of the (currently) 29 Codeunits occasionally give this error. The '04 object is the simplest (and probably the only one it's reasonable to show publicly)

This object is mostly tiny event subscribers. the '01 codeunit contains no event subscribers.

The conversion actually succeeds about 65% of the time (300 tests), these errors occur around 5-10% of the time, sometimes more than one in a run.

The 'Index out of range' error is about 2% of the time, the 100% on all CPUs hang only happens less than 1% of the time.

This version doesn't seem to show the stack trace any more; just the text of the exception at the end.

The arguments used are:
```
txt2al.exe --source=C:\usr\vscode\tmp\Delta --target=C:\usr\vscode\tmp\alcopy --rename --extensionStartId 7000000
```

Files that sometimes get `Object reference not set to an instance of an object.`

```
Error converting file: c:\usr\vscode\tmp\Delta\COD60000.DELTA
Error converting file: c:\usr\vscode\tmp\Delta\COD65601.DELTA
Error converting file: c:\usr\vscode\tmp\Delta\COD65604.DELTA
Error converting file: c:\usr\vscode\tmp\Delta\COD65605.DELTA
```

The 65604 codeunit.

```
OBJECT Codeunit 65604 Agency Time Event Linkage
{
  OBJECT-PROPERTIES
  {
    Date=20180703D;
    Time=190837.3T;
    Modified=true;
    Version List=ATV7.012;
  }
  PROPERTIES
  {
    OnRun=BEGIN
          END;

  }
  CODE
  {

    [EventSubscriber(Codeunit,9170,OnDefaultRoleCenterID,"",Skip,Skip)]
    LOCAL PROCEDURE OnDefaultRoleCenterID@1000087004(VAR RoleCenterID@1000087000 : Integer);
    BEGIN
      RoleCenterID := PAGE::"Agency Time Role Center";
    END;

    [EventSubscriber(Table,17,OnAfterCopyGLEntryFromGenJnlLine)]
    LOCAL PROCEDURE OnAfterCopyGLEntryFromGenJnlLine@1000000000(VAR GLEntry@1000000000 : Record "G/L Entry";VAR GenJournalLine@1000000001 : Record "Gen. Journal Line");
    VAR
      TempAttributes@1000000002 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      TempAttributes.TRANSFERFIELDS(GenJournalLine);
      GLEntry.TRANSFERFIELDS(TempAttributes);
    END;

    [EventSubscriber(Table,21,OnAfterCopyCustLedgerEntryFromGenJnlLine)]
    LOCAL PROCEDURE OnAfterCopyCustLedgerEntryFromGenJnlLine@1000000003(VAR CustLedgerEntry@1000087000 : Record "Cust. Ledger Entry";GenJournalLine@1000087001 : Record "Gen. Journal Line");
    VAR
      TempAttributes@1000000002 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      TempAttributes.TRANSFERFIELDS(GenJournalLine);
      CustLedgerEntry.TRANSFERFIELDS(TempAttributes);
      CustLedgerEntry."AT Invoice Type" := GenJournalLine."AT Invoice Type";
    END;

    [EventSubscriber(Table,25,OnAfterCopyVendLedgerEntryFromGenJnlLine)]
    LOCAL PROCEDURE OnAfterCopyVendLedgerEntryFromGenJnlLine@1000000004(VAR VendorLedgerEntry@1000087000 : Record "Vendor Ledger Entry";GenJournalLine@1000087001 : Record "Gen. Journal Line");
    VAR
      TempAttributes@1000000002 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      TempAttributes.TRANSFERFIELDS(GenJournalLine);
      VendorLedgerEntry.TRANSFERFIELDS(TempAttributes);
    END;

    [EventSubscriber(Codeunit,408,OnAfterSetupObjectNoList)]
    LOCAL PROCEDURE OnAfterSetupObjectNoList@1000000001(VAR TempAllObjWithCaption@1000000000 : TEMPORARY Record AllObjWithCaption);
    VAR
      DimensionManagement@1000000001 : Codeunit DimensionManagement;
    BEGIN
      DimensionManagement.InsertObject(TempAllObjWithCaption,DATABASE::"AT Contractor");
    END;

    [EventSubscriber(Codeunit,11,OnAfterCheckGenJnlLine)]
    LOCAL PROCEDURE OnAfterCheckGenJnlLineCheckDimVars@1000000002(VAR GenJournalLine@1000000000 : Record "Gen. Journal Line");
    VAR
      DimMatchingError@1000000003 : TextConst 'ENU=has a dimension inconsistency.;ENG=has a dimension inconsistency.';
      GLSetup@1000000001 : Record "General Ledger Setup";
      DimSetEntry@1000000004 : Record "Dimension Set Entry";
    BEGIN
      // Check the shortcut dim variables for consistency.
      // This is a paranoia check; should never happen ... Riiiight!

      GLSetup.GET;
      with GenJournalLine do begin
        if GLSetup."Global Dimension 1 Code" <> '' then begin
          if not DimSetEntry.GET("Dimension Set ID", GLSetup."Global Dimension 1 Code") then
            CLEAR(DimSetEntry);
          if "Shortcut Dimension 1 Code" <> DimSetEntry."Dimension Value Code" then
            FIELDERROR("Shortcut Dimension 1 Code", DimMatchingError);
        end else
          TESTFIELD("Shortcut Dimension 1 Code", '');

        if GLSetup."Global Dimension 2 Code" <> '' then begin
          if not DimSetEntry.GET("Dimension Set ID", GLSetup."Global Dimension 2 Code") then
            CLEAR(DimSetEntry);
          if "Shortcut Dimension 2 Code" <> DimSetEntry."Dimension Value Code" then
            FIELDERROR("Shortcut Dimension 2 Code", DimMatchingError);
        end else
          TESTFIELD("Shortcut Dimension 2 Code", '');
      end;
    END;

    [EventSubscriber(Table,288,OnBeforeInsertEvent)]
    LOCAL PROCEDURE OnBeforeInsertEventVendorBankAccount@1000000005(VAR Rec@1000000000 : Record "Vendor Bank Account";RunTrigger@1000000001 : Boolean);
    VAR
      Vendor@1000000002 : Record Vendor;
    BEGIN
      with Rec do begin
        if (Name = '') and ("Vendor No." <> '') then begin
          if Vendor.GET("Vendor No.") then
            Name := Vendor.Name;
        end;
      end;
    END;

    [EventSubscriber(Codeunit,103,OnBeforeCustLedgEntryModify)]
    LOCAL PROCEDURE OnBeforeCustLedgEntryModify@1000087001(VAR CustLedgEntry@1000087000 : Record "Cust. Ledger Entry";FromCustLedgEntry@1000087001 : Record "Cust. Ledger Entry");
    BEGIN
      CustLedgEntry.VALIDATE("Reported to Bank", FromCustLedgEntry."Reported to Bank");
    END;

    [EventSubscriber(Table,254,OnAfterCopyFromGenJnlLine)]
    LOCAL PROCEDURE OnAfterCopyFromGenJnlLine@1000087002(VAR VATEntry@1000087000 : Record "VAT Entry";GenJournalLine@1000087001 : Record "Gen. Journal Line");
    VAR
      TempAttributes@1000087002 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      TempAttributes.TRANSFERFIELDS(GenJournalLine);
      VATEntry.TRANSFERFIELDS(TempAttributes);
    END;

    [EventSubscriber(Codeunit,80,OnBeforePostCustomerEntry)]
    LOCAL PROCEDURE OnBeforePostCustomerEntry@1000087007(VAR GenJnlLine@1000087000 : Record "Gen. Journal Line";SalesHeader@1000087001 : Record "Sales Header";VAR TotalSalesLine@1000087002 : Record "Sales Line";VAR TotalSalesLineLCY@1000087003 : Record "Sales Line");
    VAR
      TempAttributes@1000087004 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      TempAttributes.TRANSFERFIELDS(SalesHeader); //TVT02
      GenJnlLine.TRANSFERFIELDS(TempAttributes);  //TVT02
    END;

    [EventSubscriber(Table,49,OnAfterInvPostBufferPrepareSales)]
    LOCAL PROCEDURE OnAfterInvPostBufferPrepareSales@1000087008(VAR SalesLine@1000087000 : Record "Sales Line";VAR InvoicePostBuffer@1000087001 : Record "Invoice Post. Buffer");
    VAR
      TempAttributes@1000087002 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      TempAttributes.TRANSFERFIELDS(SalesLine);

      TempAttributes.VALIDATE("Attribute Hash");
      InvoicePostBuffer.TRANSFERFIELDS(TempAttributes);
      InvoicePostBuffer."Additional Grouping Identifier" := TempAttributes."Attribute Hash";
    END;

    [EventSubscriber(Table,49,OnAfterInvPostBufferPreparePurchase)]
    LOCAL PROCEDURE OnAfterInvPostBufferPreparePurchase@1000087010(VAR PurchaseLine@1000087000 : Record "Purchase Line";VAR InvoicePostBuffer@1000087001 : Record "Invoice Post. Buffer");
    VAR
      TempAttributes@1000087002 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      TempAttributes.TRANSFERFIELDS(PurchaseLine);

      TempAttributes.VALIDATE("Attribute Hash");
      InvoicePostBuffer.TRANSFERFIELDS(TempAttributes);
      InvoicePostBuffer."Additional Grouping Identifier" := TempAttributes."Attribute Hash";
    END;

    [EventSubscriber(Table,81,OnAfterCopyGenJnlLineFromInvPostBuffer)]
    LOCAL PROCEDURE OnAfterCopyGenJnlLineFromInvPostBufferT81@1000087000(InvoicePostBuffer@1000087000 : Record "Invoice Post. Buffer";VAR GenJournalLine@1000087001 : Record "Gen. Journal Line");
    VAR
      TempAttributes@1000087002 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      TempAttributes.TRANSFERFIELDS(InvoicePostBuffer);
      GenJournalLine.TRANSFERFIELDS(TempAttributes);

      if TempAttributes."Attribute Hash" <> '' then begin
        TempAttributes.TESTFIELD("Attribute Hash", TempAttributes.ComputeHash);
        InvoicePostBuffer.TESTFIELD("Additional Grouping Identifier", TempAttributes."Attribute Hash");
      end else
        InvoicePostBuffer.TESTFIELD("Additional Grouping Identifier", '');
    END;

    [EventSubscriber(Codeunit,80,OnBeforePostInvPostBuffer)]
    LOCAL PROCEDURE OnBeforePostInvPostBufferCU80@1000087009(VAR GenJnlLine@1000087000 : Record "Gen. Journal Line";VAR InvoicePostBuffer@1000087001 : Record "Invoice Post. Buffer";SalesHeader@1000087002 : Record "Sales Header");
    BEGIN
      // See previous
    END;

    [EventSubscriber(Codeunit,90,OnBeforePostInvPostBuffer)]
    LOCAL PROCEDURE OnBeforePostInvPostBufferCU90@1000087011(VAR GenJnlLine@1000087000 : Record "Gen. Journal Line";VAR InvoicePostBuffer@1000087001 : Record "Invoice Post. Buffer";VAR PurchHeader@1000087002 : Record "Purchase Header");
    BEGIN
      // See previous
    END;

    [EventSubscriber(Table,81,OnAfterCopyGenJnlLineFromPurchHeader)]
    LOCAL PROCEDURE OnAfterCopyGenJnlLineFromPurchHeader@1000087003(PurchaseHeader@1000087000 : Record "Purchase Header";VAR GenJournalLine@1000087001 : Record "Gen. Journal Line");
    VAR
      TempAttributes@1000087002 : TEMPORARY Record "Attribute Buffer";
    BEGIN
      //tvt10b
      PurchaseHeader.CALCFIELDS("CIS Tax Deductable");
      GenJournalLine."CIS Tax Deductable" := PurchaseHeader."CIS Tax Deductable";
      GenJournalLine."CIS Code" := PurchaseHeader."CIS Code";
      GenJournalLine."CIS Verification No." := PurchaseHeader."CIS Verification No.";
      //tvt10e

      TempAttributes.TRANSFERFIELDS(PurchaseHeader);
      GenJournalLine.TRANSFERFIELDS(TempAttributes);
    END;

    [EventSubscriber(Table,81,OnAfterCopyGenJnlLineFromSalesHeader)]
    LOCAL PROCEDURE OnAfterCopyGenJnlLineFromSalesHeader@1000087006(SalesHeader@1000087000 : Record "Sales Header";VAR GenJournalLine@1000087001 : Record "Gen. Journal Line");
    BEGIN
      GenJournalLine."AT Invoice Type" := SalesHeader."AT Invoice Type";
    END;

    [EventSubscriber(Report,393,OnUpdateTempBufferFromVendorLedgerEntry)]
    LOCAL PROCEDURE OnUpdateTempBufferFromVendorLedgerEntry@1000087012(VAR TempPaymentBuffer@1000087000 : TEMPORARY Record "Payment Buffer";VendorLedgerEntry@1000087001 : Record "Vendor Ledger Entry");
    BEGIN
      TempPaymentBuffer."External Document No." := VendorLedgerEntry."External Document No.";
    END;

    [EventSubscriber(Table,23,OnBeforeDeleteEvent)]
    LOCAL PROCEDURE OnBeforeDeleteVendor@1000087013(VAR Rec@1000087000 : Record Vendor;RunTrigger@1000087001 : Boolean);
    VAR
      CISTaxLedger@1000087002 : Record "CIS Tax Ledger Entry";
      CISEntriesExistError@1000087003 : TextConst 'ENU=You cannot delete this Vendor when CIS Tax Legder Entries exist.;ENG=You cannot delete this Vendor when CIS Tax Legder Entries exist.';
    BEGIN
      // nle 22/02/2016 Check CIS
      if RunTrigger then begin
        CISTaxLedger.SETRANGE("Vendor No.", Rec."No.");
        if not CISTaxLedger.ISEMPTY then
          ERROR(CISEntriesExistError);
      end;
    END;

    [EventSubscriber(Table,38,OnAfterValidateEvent,"Buy-from Vendor No.")]
    LOCAL PROCEDURE OnAfterValidateBuyFromVendorNo@1000087005(VAR Rec@1000087000 : Record "Purchase Header";VAR xRec@1000087001 : Record "Purchase Header";CurrFieldNo@1000087002 : Integer);
    VAR
      Vend@1000087003 : Record Vendor;
    BEGIN
      if Vend.GET(Rec."Buy-from Vendor No.") then
        Rec."Time Created" := Vend."Time Created";
    END;

    BEGIN
    END.
  }
}

```

**Comment by qutreson** [comment]
Hi @rdebath, I think I could reproduce the second error you described (the one with null reference exception), but I still couldn't reproduce the error you mentioned here.

Can you try running: `txt2al.exe --source=C:\usr\vscode\tmp\Delta --target=C:\usr\vscode\tmp\alcopy --rename --extensionStartId 7000000 --StackTrace` ? We recently added the new command flag `StackTrace` in order to display the stack trace when an error occurs in the txt2al. I don't know if it is available in the version you are using or if it is not available yet, but can you give it a try?

**Comment by rdebath** [comment]
The stacktrace flag is accepted and gives bigger log files (txt2al version 13.0.23094).
The deadlock issue still gives no errors, it just pegs all cores until killed, even with stacktrace.

The "Index bounds" error logs are a bit large so I've put them into a gist
https://gist.github.com/rdebath/46d3b89e36e6df197a31553d36a61d5d

Three files, two of them have an identical list of stack traces (but different processing order), the third is over twice the size.

Is there an option to turn off the multi-threading? If it's good running on just one core that would confirm that it's a missing critical region/locking issue.

**Comment by qutreson** [comment]
For now, there is no option to turn off the multi-threading, but you are right, both issues are related to it.
I have now a clear repro of the issue and will work on a fix for it. Thank you!
