### ISSUE TITLE
AL Project not build in Windows 10 after installing .Net Framwork 4.6.1

### ISSUE THREAD

**Issue by ndpatel0074u** [Microsoft/AL#2797]
Processing of message 'textDocument/codeLens' failed with error: 'Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.IsolatedDotNetTypeLoader..ctor(IAssemblyLocator locator)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.DotNetResolverFactory..ctor(IEnumerable`1 assemblyProbingPaths, Boolean cachePathsToAssembliesInCurrentAppDomain) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\DotNet\DotNetResolverFactory.cs:line 27
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.<>c__DisplayClass6_0.<TryGetService>b__0(Type svctype) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 62
   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue](ImmutableDictionary`2& location, TKey key, Func`2 valueFactory)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.TryGetService(Type serviceType, ILanguageService& service) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 58
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.GetService[TLanguageService]() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 43
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Project.get_SupportsCompilation() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Project.cs:line 91
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Document.<GetSemanticModelAsync>d__19.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Document.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetDeclaredSymbolsAsync>d__10.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<GetSymbolInformations>d__0.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensRequestHandler.<HandleAsync>d__3.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensRequestHandler.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

[Error - 12:19:52 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/hover' failed with error: 'Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.IsolatedDotNetTypeLoader..ctor(IAssemblyLocator locator)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.DotNetResolverFactory..ctor(IEnumerable`1 assemblyProbingPaths, Boolean cachePathsToAssembliesInCurrentAppDomain) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\DotNet\DotNetResolverFactory.cs:line 27
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.<>c__DisplayClass6_0.<TryGetService>b__0(Type svctype) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 62
   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue](ImmutableDictionary`2& location, TKey key, Func`2 valueFactory)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.TryGetService(Type serviceType, ILanguageService& service) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 58
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.GetService[TLanguageService]() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 43
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Project.get_SupportsCompilation() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Project.cs:line 91
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Document.<GetSemanticModelAsync>d__19.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Document.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetSymbolAtPositionAsync>d__8.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetSymbolAtPositionAsync>d__7.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.HoverRequestHandler.<HandleAsync>d__3.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\HoverRequestHandler.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by Gallimathias** [comment]
If I am informed correctly Dynamics  needs at least.NET 4.7 as of version 2018.

**Comment by Gallimathias** [comment]
I don't understand that statement. 4.7 is also installed with the Fall Creators Update. So you don't need 4.6.1 because.NET is downward compatible. In this case until at least 4.5

**Comment by qutreson** [comment]
Hi @ndpatel0074u, in order to use the new compiler, you need to have .NET 4.7 installed. 

See #1439 and #2431.
