### ISSUE TITLE
Error in command: AL: Package

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/AL#2864]
I want to build the app using the **AL: Package** command.
What could be the reason of this error?

```
Microsoft (R) AL Compiler version 0.16.19969
Copyright (C) Microsoft Corporation. All rights reserved


Process is terminated due to StackOverflowException.
[Info  - 14:40:58] Connection to server got closed. Server will restart.
[Error - 14:40:58] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at Socket.<anonymous> (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
[Error - 14:40:58] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at Socket.<anonymous> (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by ajkauffmann** [comment]
Looked together with Bart to this issue. Seems to be a specific setting in an object, but we couldn't nail it down yet. Whatever it is, it causes a crash, while it should produce a compilation error.

**Comment by thpeder** [comment]
Hi @bvbeek,
If you can produce a small example that would be the best case, but isn't there any stack traces that looks more like C# code?

**Comment by bvbeek** [comment]
Hi @thpeder 
Tried with one object, then it works.
How can I find the source problem here in 450+ objects?


> isn't there any stack traces that looks more like C# code?

Where should I look?

**Comment by thpeder** [comment]
We have a log file here:
"C:\Users\<User>\.vscode\extensions\microsoft.al-<Version>\bin\EditorServices.log"

**Comment by bvbeek** [comment]
Hi Thomas,

This is the log output.
I don't see any Event Viewer log or something.

```
12-7-2018 13:37:23 [NORMAL] - Method "SetupEnvironment" at line 161 of C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs

    Editor Services Host v0.16.19969 starting (pid 7532)...

12-7-2018 13:37:23 [NORMAL] - Method "Main" at line 127 of C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs

    Editor Services Host started!

12-7-2018 13:39:39 [NORMAL] - Method "SetupEnvironment" at line 161 of C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs

    Editor Services Host v0.16.19969 starting (pid 14796)...

12-7-2018 13:39:39 [NORMAL] - Method "Main" at line 127 of C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs

    Editor Services Host started!
```


Output in VS Code:

```
Microsoft (R) AL Compiler version 0.16.19969
Copyright (C) Microsoft Corporation. All rights reserved


Process is terminated due to StackOverflowException.
[Info  - 13:39:38] Connection to server got closed. Server will restart.
[Error - 13:39:38] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\bvbeek\.vscode\extensions\ms-dynamics-smb.al-0.16.19969\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by thpeder** [comment]
I don't think your issue is connected to 2867 since that is a problem with the debugger and this is when you are building the package.
Can you try and build your project with the command line tool Alc.exe and see if it also crashes.

**Comment by bvbeek** [comment]
![image](https://user-images.githubusercontent.com/28626283/42691207-5de6c31c-86a7-11e8-8ea1-e969dc07e564.png)

**Comment by thpeder** [comment]
@bvbeek Do you have access to Collaborate, if so could you please try with a recent Docker image.

**Comment by bvbeek** [comment]
Hi Thomas, I made this docker-vm on 5 July , so I think it's really recent right?

**Comment by thpeder** [comment]
Hey Bart,

Do you also get the exception when compiling just the file?
I don't think having an arbitrary limit of what is a big object is a great experience either, we should rather see what we can do to make your project compile even with files that size.

**Comment by bvbeek** [comment]
Hi Thomas,

I investigate this issue as wel, and the size of the object is not the problem.
The reason is a large OutStream.WriteText(**large string**).
The **large string** contains an base64 image to import it in a demo-item.

The string is 72 characters long and counts 3637 lines

**Comment by thpeder** [comment]
Hey Bart,

Thanks for investigating it, but I don't quite know what you mean by 3637 lines, since AL doesn't support to have multiline text literals, and I can't reproduce the problem locally.

**Comment by bvbeek** [comment]
More detailed investigation:

174675 characters will compile
174676 characters will not compile

![image](https://user-images.githubusercontent.com/28626283/42755667-6c7d23ea-88f9-11e8-81d6-6df6f660b516.png)

**Comment by thpeder** [comment]
Thanks, I'm now able to reproduce it.

**Comment by thpeder** [comment]
Hi @bvbeek,
As a workaround for now, you should be able to write it all out in one line instead of doing all concatenations.

**Comment by bvbeek** [comment]
Hi Thomas,

Thanks for the suggestion, good luck to solve this!
