### ISSUE TITLE
Get error when deploy AL table extension to local server. "System.NullReferenceException: Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by jackyxu75** [Microsoft/AL#2892]
Error stack trace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.GetBoundOptionValueOrdinal(BoundEqualsPropertyExpression expression) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 149
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.GetConstConditionValue(BoundEqualsPropertyExpression expression) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 241
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.WriteFilterAttributes(XmlWriter writer, BoundEqualsPropertyExpression equalsExpression, String filterValueAttribute, String filterTypeAttribute, String filterGroup, Boolean isCondition) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 294
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass1_1.<WriteTableFilters>b__0() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 51
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.WriteTableFilters(XmlWriter writer, Boolean isCondition, String metadataElement, BoundTableRelationConditionExpression tableRelationExpression, String filterGroup) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 49
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass2_0.<WriteCalculationFormulaPropertyValue>b__1() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 78
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertyExpressionEmitterHelper.<>c__DisplayClass2_0.<WriteCalculationFormulaPropertyValue>b__0() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PropertyExpressionEmitterHelper.cs:line 76
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableBaseMetadataEmitter`1.TryUseSpecialPropertyValueMetadataEmitter(XmlWriter xmlWriter, PropertySymbol property) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableBaseMetadataEmitter.cs:line 128
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter.WritePropertyValueMetadata(XmlWriter xmlWriter, PropertySymbol property) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitter.cs:line 50
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteElementProperties(XmlWriter xmlWriter, IEnumerable`1 properties, Action`2 writePropertyMetadata) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 62
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableBaseMetadataEmitter`1.<>c__DisplayClass4_0.<WriteField>b__0() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableBaseMetadataEmitter.cs:line 48
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitHelper.WriteStartEndElement(XmlWriter xmlWriter, String elementName, Action action) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ObjectMetadataEmitHelper.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.TableExtensionMetadataEmitter.<EmitMetadata>b__1_0(XmlWriter xmlWriter) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\TableExtensionMetadataEmitter.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter`1.EmitMetadata(Action`1 content) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\GenericObjectMetadataEmitter.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 239
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 216
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 150
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 806
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 783
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 531
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 312
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\196\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

- AL Extension Version: 
0.12.25327

- Server Version: 
US Dynamics NAV 11.0 (23019)

tableextension 50100 JobTaskExt extends "Job Task"
{
    fields
    {
        // Add changes to table fields here
        field(50100; "Bill Rate"; Decimal)
        {
            Description='Bill Rate';
            Editable = false;
            FieldClass = FlowField;
            InitValue = 0;
            CalcFormula = Lookup("Job Resource Price"."Unit Price" 
                where ("Job No."=FIELD("Job No."),Type=CONST(2)));
            BlankZero = false;
        }
        field(50101; "Schedule (Quantity)"; Decimal)
        {
            Description = 'Schedule (Quantity)';
            Editable = false;
            FieldClass = FlowField;
            InitValue = 0;
            CalcFormula =Sum("Job Planning Line".Quantity 
                WHERE ("Job No."=FIELD("Job No."),
                    "Job Task No."=FIELD("Job Task No."),
                    "Job Task No."=FIELD(FILTER("Totaling")),
                    "Schedule Line"=const(true),
                    "Planning Date"=FIELD("Planning Date Filter")));
            BlankZero = false;
            trigger OnValidate();
            var
                decBudget : Decimal;
            begin
                CalcFields("Bill Rate");
                decBudget := "Bill Rate" * "Schedule (Quantity)";
                "Budget (Cost)" := decBudget;
            end;            
        }
        field(50102; "Budget (Cost)"; Decimal)
        {
            Description = 'Budget (Cost)';
            Editable = false;
            FieldClass = Normal;
            InitValue = 0;
            BlankZero = false;
        }
    }
}

**Comment by jackyxu75** [comment]
Sorry, just find the answer based on the solution of issue "2654". (https://github.com/Microsoft/AL/issues/2654)
