### ISSUE TITLE
error when using codeAnalyzers

### ISSUE THREAD

**Issue by OlivierHellmann** [Microsoft/AL#2942]
I am getting this error, when trying to use codeAnalyzers: 
```
[jsonc] End of file expected.
```
My Settings.json file looks like this:
```
"al.enableCodeAnalysis": true,
"al.codeAnalyzers": [
    "${AppSourceCop}"
]
```
 I am working with the al language version 0.17.27795

Also when i hover over the al.codeAnalyzers i get following error:
```
[Error - 09:11:41] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 09:13:19] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 09:13:56] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 09:14:04] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 09:14:05] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 09:28:02] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 09:28:27] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 09:30:03] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
[Error - 09:30:26] Error while computing hover for file:///c%3A/Users/OHELLMANN/Documents/AL/DV/.vscode/settings.json: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:27)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:317:55)
    at step (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:311:55
    at Immediate.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:672:20)
```

**Comment by thpeder** [comment]
Hi @OlivierHellmann,
So you added the few lines to your settings file and the Stacktrace showed up, or what are the steps to reproduce it?
It looks like a bug in VS Code based on the StackTraces you are showing us.

**Comment by OlivierHellmann** [comment]
hi @thpeder 
yeah I just added the codeAnalyzers to my settings. First the codeAnalyzers weren't recognized and then after i looked in an AL file to see if it's just visual I got the first error in the Problems sections of the debug console. Then I looked again at the codeAnalyzers and when I hovered over it I got the Stacktrace.

**Comment by thpeder** [comment]
I still think there is something wrong with your VSCode instance, could you try updating it.

**Comment by OlivierHellmann** [comment]
I was at the newest Version(1.25.1) but I reinstalled it anyway. It gives me the same errors. I still get both Errors, first the jsonc error and second the Stacktrace error. The jsonc underlines my colon in ``` "al.enableCodeAnalysis": true, ```  It says "End of file expected"

**Comment by OlivierHellmann** [comment]
i just edited the file by clicking on the edit button in the Default user settings. It showed me an error that the file is "dirty". It gave me the Option to save and retry and now it works. 
I would love to know what that means the file is "dirty"?
