### ISSUE TITLE
Error - Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#307]
After uninstalling and unpublishing all extentions, an publishing the extention below ...

![image](https://user-images.githubusercontent.com/25268332/27439725-eb0023e8-5768-11e7-86aa-855c1cde11d4.png)

... I'm no longer able to use the Customer list / card.

![image](https://user-images.githubusercontent.com/25268332/27439873-5a40f944-5769-11e7-9a97-7e5c43516dca.png)

Here's an extract of the even viewer:

Type: System.IndexOutOfRangeException
Message: <ii>Index was outside the bounds of the array.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.MutableRecordBuffer.get_Item(Int32 index)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.GetFieldValue(NCLMetaField field)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.GetFieldValue(NCLMetaField metaField)
     at Microsoft.Dynamics.Nav.Service.NSRecordBase.SetCLRCellFromTableField(NsDataAccess recDataAccess, NCLMetaField metaField, Int32 fieldIndex, NavDataRow dataRow)
     at Microsoft.Dynamics.Nav.Service.NSRecordBase.PopulateCLRTable(NavDataTable dataTable, NsDataAccess recDataAccess, NavDataRow dataRow)
     at Microsoft.Dynamics.Nav.Service.NSPage.PopulateOneRow(NsDataAccess recDataAccess, NavDataTable dataTable)
     at Microsoft.Dynamics.Nav.Service.NSPage.PopulateSpecificPage(NavDataSet dataSet, NsDataAccess recDataAccess, Boolean& moreDataInReadDirection, Boolean& moreDataInOppositeDirection)
     at Microsoft.Dynamics.Nav.Service.NSPage.PopulateCLRDataSet(NavDataSet dataSet, NsDataAccess recDataAccess, Boolean& moreDataInReadDirection, Boolean& moreDataInOppositeDirection)
     at Microsoft.Dynamics.Nav.Service.NSPage.GetPageData(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSPage.GetPage(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.Microsoft.Dynamics.Nav.Types.INavService.GetPage(PageRequestDefinition pageRequestDefinition, NavRecordState state)
     at SyncInvokeGetPage(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass23_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass23_0.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233080
</ii>

**Comment by fvet** [comment]
@StanislawStempin Any ideas / hints what might have caused the issue? Have you been able to reproduce the same? I'm currently stuck in publishing new extentions, most of them result in the same error.

**Comment by StanislawStempin** [comment]
We cannot reproduce the issue on the latest bits. Can you share in more details what steps you followed? Have you had deployment errors prior to this one? Have you used the in-client Designer to create some extensions? Have you published the same extension multiple times but with changed app.json values like version, name or publisher?
Also, could you share the contents of your Nav App and Nav App Dependencies tables?

In terms of a workaround it looks like you would need to start with a fresh VM unfortunately.

**Comment by fvet** [comment]
As far as I remember, I'd created a fresh VM, made a Customer table extension with 20 text[250] fields, added a second Customer table extension with 20 additional text[250] fields (to check if any record size limits still apply), and then the problems arose.

Will try setting up a new VM and reproduce the above steps.

**Comment by waldo1001** [comment]
Did you create a table in your extension with ID 70050001?

Two customer table extensions?  Is that supported?

**Comment by StanislawStempin** [comment]
We identified one of the root causes of this issue to be stale data cache. If you are still experiencing it we might have a workaround. Could you please try adding the following codeunit to your project and deploy it:
```
codeunit 70000001 ClearCaches
{
    [EventSubscriber(ObjectType::Codeunit, 1, 'OnAfterCompanyOpen', '', false, false)]
    procedure Clear();
    begin
        SelectLatestVersion;
    end;
}
```

**Comment by fvet** [comment]
The problem seems to be caused by 2 separate extensions each extending the same 'Customer' table. I was able to reproduce the issue using these steps:

1. Creating a first project and publishing the below extension works:

> tableextension 70050000 MyCustomer extends Customer
{
    fields
    {
        // Add changes to table fields here
        field(50000;Description2;Text[250])
        {            
        }
    }
}

> pageextension 70050001 MyCustomerLisExtension extends "Customer List"
{
    layout
    {
        // Add changes to page layout here
        addlast(Control1)
        {
            field(Description2;Description2)
            {                       
            }
        }
    }
}`

2. Create a second project with following code, makes the webclient crash (and returns an IndexOutOfRangeException)

> tableextension 70050002 MyCustomer2 extends Customer
{
    fields
    {
        // Add changes to table fields here
        field(50002;Description3;Text[250])
        {   
        }
    }
}`
