### ISSUE TITLE
Error - Visual Studio Code - When Change Language Mode

### ISSUE THREAD

**Issue by linhquang27** [Microsoft/AL#3427]
- AL Extension Version: 0.16.19969
- Server Version: W1 12.2 (23097)

On my laptop, I change the language mode to AL then it shows the error below, I use the snippet just ok for the first time when open the VSC after that the error shows then I cannot use again.
Please help me to fix that.
Thank You.

[Error - 8:15:37 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'workspace/didChangeConfiguration' failed with error: 'Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.IsolatedDotNetTypeLoader..ctor(IAssemblyLocator locator)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.DotNetResolverFactory..ctor(IEnumerable`1 assemblyProbingPaths, Boolean cachePathsToAssembliesInCurrentAppDomain) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\DotNet\DotNetResolverFactory.cs:line 27
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.<>c__DisplayClass6_0.<TryGetService>b__0(Type svctype) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 62
   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue](ImmutableDictionary`2& location, TKey key, Func`2 valueFactory)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.TryGetService(Type serviceType, ILanguageService& service) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 58
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.GetService[TLanguageService]() in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 43
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.ProjectState.FixProjectInfo(ProjectInfo projectInfo) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\ProjectState.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.ProjectState..ctor(ProjectInfo projectInfo, AbstractHostLanguageServices languageServices, SolutionServices solutionServices) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\ProjectState.cs:line 59
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Solution.AddProject(ProjectInfo projectInfo) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Solution.cs:line 606
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Workspace.OnProjectAdded_NoLock(ProjectInfo projectInfo, Boolean silent) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Workspace.cs:line 369
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Workspace.OnProjectAdded(ProjectInfo projectInfo, Boolean silent) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Workspace.cs:line 359
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.AddProject(ProjectInfo projectInfo) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 399
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.SetCurrentProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, List`1& projectLoadingDiagnostics) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 131
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TrySetCurrentProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, IList`1& diagnostics, Boolean& missingManifest, Boolean& missingSymbols) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 74
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TrySetCurrentProject(SettingsRequest request, CancellationToken cancellationToken) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 32
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeConfigurationRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeConfigurationRequestHandler.cs:line 49
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

[Error - 8:15:37 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/setActiveWorkspace' failed with error: 'Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.IsolatedDotNetTypeLoader..ctor(IAssemblyLocator locator)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNet.DotNetResolverFactory..ctor(IEnumerable`1 assemblyProbingPaths, Boolean cachePathsToAssembliesInCurrentAppDomain) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\DotNet\DotNetResolverFactory.cs:line 27
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.<>c__DisplayClass6_0.<TryGetService>b__0(Type svctype) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 62
   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue](ImmutableDictionary`2& location, TKey key, Func`2 valueFactory)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.TryGetService(Type serviceType, ILanguageService& service) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 58
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Host.HostLanguageServices.GetService[TLanguageService]() in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Host\HostLanguageServices.cs:line 43
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.ProjectState.FixProjectInfo(ProjectInfo projectInfo) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\ProjectState.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.ProjectState..ctor(ProjectInfo projectInfo, AbstractHostLanguageServices languageServices, SolutionServices solutionServices) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\ProjectState.cs:line 59
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Solution.AddProject(ProjectInfo projectInfo) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Solution.cs:line 606
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Workspace.OnProjectAdded_NoLock(ProjectInfo projectInfo, Boolean silent) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Workspace.cs:line 369
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Workspace.OnProjectAdded(ProjectInfo projectInfo, Boolean silent) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Workspace.cs:line 359
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.AddProject(ProjectInfo projectInfo) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 399
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.SetCurrentProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, List`1& projectLoadingDiagnostics) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 131
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TrySetCurrentProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, IList`1& diagnostics, Boolean& missingManifest, Boolean& missingSymbols) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 74
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TrySetCurrentProject(SettingsRequest request, CancellationToken cancellationToken) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 32
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SetActiveWorkspaceRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SetActiveWorkspaceRequestHandler.cs:line 24
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\73\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by qutreson** [comment]
Hi @linhquang27, do you have .NET 4.7 installed on your computer?

See #2431.
