### ISSUE TITLE
Unable to create Table Extension for Document Attachment table

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/AL#3486]
Hi, I noticed some strange issues when I created table extension for table 1173 Document Attachment. I managed to skin down this issue and it's easy to replicate just by extending table with one field...

I'm using bcinsider.azurecr.io/bcsandbox-master:13.0.23638.0-ca image, and al compiler: 0.17.30289.

I created just one .al file in my project:

````
tableextension 50100 "F.Document Attachment Ext." extends "Document Attachment"
{
    fields
    {
        field(50100; "Posting Date"; Date)
        {
            CaptionML = ENU = 'Posting Date',
                        ENC = 'Posting Date';
        }
    }
}
````

After publishing to server each time I try to post Sales Order with attachment:
![image](https://user-images.githubusercontent.com/20359384/44779370-a60f0a80-ab7f-11e8-8498-85e1b1ad51d8.png)

I get error:
![image](https://user-images.githubusercontent.com/20359384/44779415-c048e880-ab7f-11e8-8a3c-b39205ad3cc0.png)

The line when it breaks is during CopyAttachmentsForPostedDocs in DocAttachForPostedSalesDocs event subscriber in COD1173. 

Here is event log:

````
The description for Event ID 216 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: NAV
Tenant ID: default
Session type: RoleTailoredClient
Session ID: 140
User: IVAN2\idordevic
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
StackTrace:    at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147467261
StackTrace:    at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
----------------------------------
Type: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
StackTrace:
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
Source: mscorlib
HResult: -2146232828
StackTrace:
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
----------------------------------
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.GetWritableSqlValue(NCLMetaField field, NavValue value)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.ExecuteInsert(IRecordBuffer record, NavAppTableContext tableContext, NavValue resolvedIdentityValue, NavDatabase database, Int32 companyIndex, Nullable`1 companyId)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.<>c__DisplayClass34_1.<DoInsertForCompanionTables>b__1(NavSqlCommand command)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteCommandAndCacheOnSuccess[T](NavSqlCommandCacheKey commandKey, Func`1 newCommandFunc, Func`2 executeFunc)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.DoInsertForCompanionTables(NavDatabase database, NCLMetaTable table, Int32 companyIndex, IRecordBuffer record, NavSqlConnectionScope conScope, NavValue identityValue)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.Insert(NavDatabase database, NCLMetaTable table, Int32 companyIndex, IRecordBuffer record, Boolean retrieveTimestamp, NavValue& identityValue, NavBigInteger& timestampValue)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.Insert(NavDatabase database, NCLMetaTable table, Int32 companyToken, IRecordBuffer recordBuffer, NavValue& identityValue, NavBigInteger& timestampValue)
     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.Insert(Int32 companyToken, MutableRecordBuffer recordBuffer, Boolean allowBuffering, ReadOnlyRecordBuffer& outputRecordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.DataAccess.Insert(Int32 companyToken, MutableRecordBuffer recordBuffer, Boolean allowBuffering, MutableRecordBuffer& newRecordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.InsertRecord(DataError errorLevel)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.Insert(DataError errorLevel, Boolean runApplicationTrigger, Boolean runGlobalTrigger)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALInsert(DataError errorLevel, Boolean runApplicationTrigger)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1173.CopyAttachmentsForPostedDocs_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1173.CopyAttachmentsForPostedDocs(ByRef`1 fromRecRef, ByRef`1 toRecRef)
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1173.DocAttachForPostedSalesDocs(INavRecordHandle salesHeader, INavRecordHandle salesInvoiceHeader, INavRecordHandle salesCrMemoHeader)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.CallEventSubscriberInternal(NavEventSubscription subscriber, NavApplicationObjectBase subscriberInstance, Object[] parameters)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.CallEventSubscriber(NavApplicationObjectBase callingApplicationObject, NavEventSubscription subscriber, NavApplicationObjectBase subscriberInstance, Object[] parameters)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.ProcessCallToTypeAndManualSubscriptions(NavApplicationObjectBase callerApplicationObject, NavEventSubscription[] subscriptions, PrepareParametersCallBack prepareParameters)
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.OnRunEvent()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.OnBeforeDeleteAfterPosting(INavRecordHandle salesHeader, INavRecordHandle salesInvoiceHeader, INavRecordHandle salesCrMemoHeader, ByRef`1 skipDelete, Boolean commitIsSuppressed)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.DeleteAfterPosting_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.DeleteAfterPosting(INavRecordHandle salesHeader)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.FinalizePosting_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.FinalizePosting(INavRecordHandle salesHeader, Boolean everythingInvoiced, INavRecordHandle tempDropShptPostBuffer)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.OnRun_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.OnRun(INavRecordHandle εrec)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError errorLevel, NavRecord record)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.RunCodeunit(DataError errorLevel, Int32 objectId, NavRecord record)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81.Code_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81.Code(INavRecordHandle salesHeader, Boolean postAndSend)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81.OnRun_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81.OnRun(INavRecordHandle εrec)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError errorLevel, NavRecord record)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.RunCodeunit(DataError errorLevel, Int32 objectId, NavRecord record)
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Record36.SendToPosting(Int32 postingCodeunitID)
     at Microsoft.Dynamics.Nav.BusinessApplication.Record36.OnInvoke(Int32 memberId, Object[] args)
     at Microsoft.Dynamics.Nav.BusinessApplication.Page42.Post_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Page42.Post(Int32 postingCodeunitID, Int32 navigate)
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Page42.Post_a45_OnAction()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147467261
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.GetWritableSqlValue(NCLMetaField field, NavValue value)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.ExecuteInsert(IRecordBuffer record, NavAppTableContext tableContext, NavValue resolvedIdentityValue, NavDatabase database, Int32 companyIndex, Nullable`1 companyId)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.<>c__DisplayClass34_1.<DoInsertForCompanionTables>b__1(NavSqlCommand command)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteCommandAndCacheOnSuccess[T](NavSqlCommandCacheKey commandKey, Func`1 newCommandFunc, Func`2 executeFunc)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.DoInsertForCompanionTables(NavDatabase database, NCLMetaTable table, Int32 companyIndex, IRecordBuffer record, NavSqlConnectionScope conScope, NavValue identityValue)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.Insert(NavDatabase database, NCLMetaTable table, Int32 companyIndex, IRecordBuffer record, Boolean retrieveTimestamp, NavValue& identityValue, NavBigInteger& timestampValue)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.Insert(NavDatabase database, NCLMetaTable table, Int32 companyToken, IRecordBuffer recordBuffer, NavValue& identityValue, NavBigInteger& timestampValue)
     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.Insert(Int32 companyToken, MutableRecordBuffer recordBuffer, Boolean allowBuffering, ReadOnlyRecordBuffer& outputRecordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.DataAccess.Insert(Int32 companyToken, MutableRecordBuffer recordBuffer, Boolean allowBuffering, MutableRecordBuffer& newRecordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.InsertRecord(DataError errorLevel)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.Insert(DataError errorLevel, Boolean runApplicationTrigger, Boolean runGlobalTrigger)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALInsert(DataError errorLevel, Boolean runApplicationTrigger)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1173.CopyAttachmentsForPostedDocs_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1173.CopyAttachmentsForPostedDocs(ByRef`1 fromRecRef, ByRef`1 toRecRef)
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1173.DocAttachForPostedSalesDocs(INavRecordHandle salesHeader, INavRecordHandle salesInvoiceHeader, INavRecordHandle salesCrMemoHeader)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.CallEventSubscriberInternal(NavEventSubscription subscriber, NavApplicationObjectBase subscriberInstance, Object[] parameters)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.CallEventSubscriber(NavApplicationObjectBase callingApplicationObject, NavEventSubscription subscriber, NavApplicationObjectBase subscriberInstance, Object[] parameters)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.ProcessCallToTypeAndManualSubscriptions(NavApplicationObjectBase callerApplicationObject, NavEventSubscription[] subscriptions, PrepareParametersCallBack prepareParameters)
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.OnRunEvent()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.OnBeforeDeleteAfterPosting(INavRecordHandle salesHeader, INavRecordHandle salesInvoiceHeader, INavRecordHandle salesCrMemoHeader, ByRef`1 skipDelete, Boolean commitIsSuppressed)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.DeleteAfterPosting_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.DeleteAfterPosting(INavRecordHandle salesHeader)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.FinalizePosting_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.FinalizePosting(INavRecordHandle salesHeader, Boolean everythingInvoiced, INavRecordHandle tempDropShptPostBuffer)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.OnRun_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit80.OnRun(INavRecordHandle εrec)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError errorLevel, NavRecord record)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.RunCodeunit(DataError errorLevel, Int32 objectId, NavRecord record)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81.Code_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81.Code(INavRecordHandle salesHeader, Boolean postAndSend)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81.OnRun_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81.OnRun(INavRecordHandle εrec)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError errorLevel, NavRecord record)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.RunCodeunit(DataError errorLevel, Int32 objectId, NavRecord record)
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Record36.SendToPosting(Int32 postingCodeunitID)
     at Microsoft.Dynamics.Nav.BusinessApplication.Record36.OnInvoke(Int32 memberId, Object[] args)
     at Microsoft.Dynamics.Nav.BusinessApplication.Page42.Post_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Page42.Post(Int32 postingCodeunitID, Int32 navigate)
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Page42.Post_a45_OnAction()
````
Same issue when I run from web client. Seems like there is SQL issue during DoInsertForCompanionTables procedure.

**Comment by kalberes** [comment]
This has been fixed for the Fall release of BC.
