### ISSUE TITLE
Error Enum

### ISSUE THREAD

**Issue by vlkov** [Microsoft/AL#3640]
- AL Extension Version: 0.17.23984

- Server Version: 13.0.24267

When change in standart  option field property "Extensible" to yes. Then download symbols and have an error in output. 

Processing of message 'al/gotodefinition' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceEnumTypeSymbol.<LazyGetMembers>b__18_0(EnumValueDefinition v) in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceEnumTypeSymbol.cs:line 63
   at Microsoft.Dynamics.Nav.CodeAnalysis.ImmutableArrayExtensions.AsImmutableOrEmpty[T,OT](OT[] items, Func`2 creator) in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Collections\ImmutableArrayExtensions.cs:line 64
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceEnumTypeSymbol.LazyGetMembers() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceEnumTypeSymbol.cs:line 63
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceEnumTypeSymbol.GetMembers() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceEnumTypeSymbol.cs:line 80
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertOptionType(TypeSymbol type) in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 466
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.GetDataTypeSyntax(TypeSymbol type) in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 426
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntaxTable.ConvertTableFields(IEnumerable`1 fields) in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax_Table.cs:line 63
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntaxTable.ConvertTable(TableTypeSymbol table) in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax_Table.cs:line 32
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.Convert(ISymbol symbol, ConvertOptions option) in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.ReferenceSymbolContentProvider.CreateMetadataContent(IApplicationObjectTypeSymbol symbol) in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 259
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.<TryGetDefinitionFromReference>d__8.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.<GetResponseForSymbol>d__5.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.<ProcessRequestAsync>d__4.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by qutreson** [comment]
Hi @vlkov, looking at the stack trace, it seems that the error you are getting is when trying to go to definition (F12) on an Enum reference. Can you provide us with some code snippet that can reproduce it?

**Comment by vlkov** [comment]
Hi @qutreson, I'm trying to use enum. When writing after enum variable operator "::" .Then have this exception. 
` trigger OnOpenPage();`
`    var` 
  `     EntryType : Enum DetCustLedgerEntryType;`
    `begin`
       ` EntryType::`
    `end;`
`}`

**Comment by qutreson** [comment]
I just tried reproducing it on our latest master and it seems to have been fixed there as you can see on the gif below. I also tried using F12 and it seems to work as expected.

![enumvalue](https://user-images.githubusercontent.com/31541422/45412627-69f7a180-b677-11e8-9098-26c9e78094a8.gif)

**Comment by vlkov** [comment]
But I would like to extend  "Entry Type" field from table "Detailed Cust. Ledg. Entry"(379)

**Comment by vlkov** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43178739/45419394-ded6d580-b68f-11e8-9624-c28dc4c715bf.gif)

**Comment by qutreson** [comment]
I can now reproduce the issue, thank you

**Comment by AndreyKorepanov** [comment]
It does not seem to be reproducible with the latest build. Could you try it with the latest version of AL extension from Marketplace (2.0.48254+).

**Comment by GreatScott000** [comment]
I am able to reproduce this problem with the October 18 On-Prem RTM release (build 24623) using the AL Language Extension 2.0.48254.
