### ISSUE TITLE
Error when comparing files

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#378]
after checking out files from GIT and trying to merge the conflict the following error can be found in OUTPUT:
[Error - 9:52:42 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/hover' failed with error: 'Specified argument was out of the range of valid values.
Parameter name: index'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 684
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 75
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetSymbolAtPositionAsync>d__7.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.HoverRequestHandler.<InternalHandleAsynch>d__1.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\HoverRequestHandler.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsynch>d__1.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\GenericRequestHandlerBase.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__5.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 60

**Comment by dennisfrostlander** [comment]
Might be that our 'hover' handler does not expect certain constructs created by a merge.

**Comment by dennisfrostlander** [comment]
@AndriusAndrulevicius do you still have a repro for this? It looks like your code had some merge symbols inserted by git, and you have placed your mouse cursor above something.
If you could reconstruct an example of the file and share it wit us, it would be very helpful.

**Comment by dennisfrostlander** [comment]
Found a repro
