### ISSUE TITLE
Nested Repeater in Word Layouts.

### ISSUE THREAD

**Issue by A-R-Shaji** [Microsoft/AL#3880]
We want to add the Sales Invoice Comments in the existing Sales invoice report. I added the comments table inside the existing sales invoice line table as shown below. If I run the report, comments are not showing.
<img width="776" alt="image" src="https://user-images.githubusercontent.com/39764447/46143028-674f9b80-c276-11e8-9959-31ab2b849486.png">

**Comment by pborring** [comment]
It is hard to see from the screenshot exactly what is happening as table grid is not showing. Is the comment a singleton or a collection of lines? In the latter case you need an additional nested repeater. Given your title I assume it is, so verify that
* you have two three table rows (header line, item line and comment line). 
* the outer repeater (for the line) is spanning the two last rows 
* there is an inner repeater on the last row (for the comment)

Is this how it is currently set up?

![image](https://user-images.githubusercontent.com/28434210/46792321-66713c00-cd43-11e8-805d-4175376cdd70.png)

**Comment by dkatson** [comment]
@pborring how did you create this in word? I try to reproduce and no results.

**Comment by pborring** [comment]
@dkatson This specific case?
* Added a new table row within the outer #Nav:/Header/Line repeater, after first row
* Merged some of the columns to allow wider spacing for nested repeater (looks like I merged from Description to VATPctLine
* Selected target merged cell in new line and inserted (nested) repeater for Lines Details (data must of course be nested in data set)

**Comment by pborring** [comment]
@dkatson If modifying existing one row layout, it can be hard to create a second row within the outer repeater (easier when creating structure from scratch, select rows and add repeater spanning all row). Once you have multiple rows within a repeater, it is easier to add additional ones.

Try this
Image 1:
- Go to Developer pane (enable in Ribbon Customization)
- Select control tag, e.g., /Header/Line
- Click Properties 
- Deselect "Allow users to add and remove sections"
- Change Color to be able to see boundary better

Image 2
- Select row and right click
- Select Insert > Insert Below from context menu

Image 3
- Select newly created row (notice that inserted within (colored) outer repeater)
- Select Remove Content Control from context menu to clear out content

Image 4
- There should now be a second row to insert nested repeaters in
- Consider enabling View Guidelines in Layout to better see table cell boundaries.
![Repeater 1](https://user-images.githubusercontent.com/28434210/78813188-eaee5a80-79cc-11ea-98ed-542cb2737209.jpg)
![Repeater 2](https://user-images.githubusercontent.com/28434210/78813182-e9bd2d80-79cc-11ea-9cec-2bed243a9c16.jpg)
![Repeater 3](https://user-images.githubusercontent.com/28434210/78813186-ea55c400-79cc-11ea-8a63-992c21396b07.jpg)
![Repeater 4](https://user-images.githubusercontent.com/28434210/78813187-eaee5a80-79cc-11ea-8725-ccb835f3ae22.jpg)

**Comment by dkatson** [comment]
Hi @pborring 
Thanks for such detailed explanations! 

I was able to add a new line, with nested repeater and control.
![image](https://user-images.githubusercontent.com/29101017/78867729-c4333100-7a6b-11ea-8625-a93ff2f30cdd.png)

In the dataset new dataitem is nested as well
![image](https://user-images.githubusercontent.com/29101017/78868040-5f2c0b00-7a6c-11ea-82b5-f5494ca08a97.png)

AL compiler gives me 0 errors.
But when I try to package the app it gives me the next error
`Compilation ended at '10:13:49.141'.

[Error - 10:13:49 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'One or more errors occurred. (Invalid Custom Xml part format)'
Details:
System.AggregateException: One or more errors occurred. (Invalid Custom Xml part format)
 ---> System.InvalidOperationException: Invalid Custom Xml part format
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.CalculateElementInfo(XElement element, String parentPath) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 71
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.MapElementsToDictionary(Dictionary`2 oldElements, XElement oldXml, String parentPath) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 136
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.MapElementsToDictionary(Dictionary`2 oldElements, XElement oldXml, String parentPath) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 134
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.MapElementsToDictionary(Dictionary`2 oldElements, XElement oldXml, String parentPath) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 134
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.CompareReportMetadata(XElement oldXml, XElement newXml, String customXmlRootName) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 45
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.OfficeCustomXmlPartDiff.GetChangedCustomXmlList(XElement oldXml, XElement newXml, String customXmlRootName, String& xmlNamespace, Boolean& forceCustomXmlUpdate) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\OfficeCustomXmlPartDiff.cs:line 46
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.WordDocumentUpdate.ApplyFieldWordRenames(XDocument oldCustomXmlPart, Stream wordLayoutSource) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\WordDocumentUpdate.cs:line 627
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.WordDocumentUpdate.UpdateWordDocumentLayout(Stream wordLayout, Stream outputStream, XDocument oldXmlPart) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\WordDocumentUpdate.cs:line 142
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportWordUtilities.UpdateWordFile(IFileSystem fileSystem, String docName, String officeCustomXmlPart, String officeCustomXmlPart_Extended) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\ReportWordUtilities.cs:line 82
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsGenerator.GenerateLayout(SourceReportTypeSymbol symbol, DiagnosticBag diagnostics, PropertyKind propertyKind, Action`3 generator, String layoutType) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsGenerator.cs:line 63
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.Emit(DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:line 27
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitNonObjectCode(Action`1 emitter) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 195
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 173
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.VisitObjectType(ObjectTypeSymbol symbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 140
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileModule(ModuleSymbol moduleSymbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 122
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 103
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 939
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 906
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver, Predicate`1 filterOpt, Predicate`1 radCompilationFilter) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 689
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 529
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 476
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 332
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.Build(Project builtProject, StreamingTextWriter outputWriter, Boolean isRad, IList`1 args, CancellationToken cancellationToken, Boolean forceBuild, PooledList`1 outputFiles) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 174
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.HandleAsync(CreatePackageRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 54
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80
`

**Comment by dkatson** [comment]
I found some similar issue https://github.com/microsoft/AL/issues/5337
And seems that this compiler bug was fixed in the VS Code Extension Version 5.0.196585.

But I have 5.0.25558

**Comment by dkatson** [comment]
Playing with the custom layouts I found a more readable error 

![image](https://user-images.githubusercontent.com/29101017/78873122-88509980-7a74-11ea-8ad0-d5f1ee13c505.png)

So, when I added a new Row at the step 2 it was somewhere assigned a new XML tag (Line [2]), and my dataset XML has only Line item. Investigating further

**Comment by Heroeskitchen** [comment]
> Playing with the custom layouts I found a more readable error
> 
> ![image](https://user-images.githubusercontent.com/29101017/78873122-88509980-7a74-11ea-8ad0-d5f1ee13c505.png)
> 
> So, when I added a new Row at the step 2 it was somewhere assigned a new XML tag (Line [2]), and my dataset XML has only Line item. Investigating further

I've also run into this issue and haven't been able to find a resolution other than to develop the report as an RDLC layout.  I would love to be able to use WordLayout, however, there is something with the way that the nested repeaters get named where BC cannot identify the mapping properly.

**Comment by luisfmartinezwipfli** [comment]
Hi,

I'm receiving the same error, and I know its been a while. The only way around it is to create an RDLC report? My requirement is way simpler, I do not need a nested repeater. I just need an extra line. But as soon as I add the line within the repeater (Header/Line) I cannot build the package.

Wondering if you guys were able to resolve this
