### ISSUE TITLE
Error while publishing object: ""Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/AL#4001]
Hey Guys, 
While publishing extensions i keep getting this error: 'Object reference not set to an instance of an object.'.

I cannot find the source file that it's causing it (i have >1650 files in my project). I'm seeking for advice how to find the file causing the issue.

I thought by enabling CodeAnalyzers will help to find the root cause. It gave some hint, but still not enough to identify the file that it's causing it. CodeAnalyzer shows errors with similar message but it's linked with app.json file, not the file that it's causing it:

` Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Readability.Rule005OnlyUseBeginEndForCompoundStatements' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'",`

full message:
```
{
	"resource": "/c:/Users/gps/Documents/Repositories/MV-AL/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Readability.Rule005OnlyUseBeginEndForCompoundStatements' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

In addition, I checked event viewer for error messages. There's a very long exception related to evaluate. Not sure if CodeAnalyzer, and EventViewer messages are related to the same issue. But this is all i have for now. 

```
RootException: NullReferenceException
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavDateEvaluator.DayMonthYearEvaluate(NavDate& value, String source, Int32 position, Boolean isClosingDate, String originalString)
   at Microsoft.Dynamics.Nav.Runtime.NavDateEvaluator.InternalEvaluate(DataError dataError, NavDate& value, INavValueMetadata metadata, String source, Int32 number)
   at Microsoft.Dynamics.Nav.Runtime.NavValueEvaluator`1.Evaluate(DataError dataError, T& value, INavValueMetadata metadata, String source, Int32 number)
   at Microsoft.Dynamics.Nav.Runtime.NavValueEvaluator`1.Evaluate(DataError dataError, NavValue& value, INavValueMetadata metadata, String source, Int32 number)
   at Microsoft.Dynamics.Nav.Runtime.ALSystemVariable.EvaluateIntoNavValue(DataError dataError, INavValueMetadata metadata, String source, Int32 number)
   at Microsoft.Dynamics.Nav.Runtime.FilterExpressionParser.ValueFilterExpression.TryGetValue(NavValue& parsedValue, NavBaseException& exception, DataError dataError)
   at Microsoft.Dynamics.Nav.Runtime.FilterExpressionParser.ValueFilterExpression.ToExpression(Boolean negated, Boolean useOnlyVariableResolver, DataError dataError)
   at Microsoft.Dynamics.Nav.Runtime.FilterExpressionParser.Parse(Boolean useOnlyVariableResolver, DataError dataError)
   at Microsoft.Dynamics.Nav.Runtime.FilterExpressionParser.ParseFilterTokensWithoutBalancing(List`1 filterTokens, FilterExpressionContext expressionContext, Func`3 customVariableResolver, Int32 unknownVariableResolverDepth, NavValue[] values, Int32& expressionLeafCount, Boolean& hasVariables, Boolean useOnlyVariableResolver, Boolean cultureInvariant, DataError dataError)
   at Microsoft.Dynamics.Nav.Runtime.FilterExpressionParser.ParseWithoutBalancing(String expression, FilterExpressionContext expressionContext, Func`3 customVariableResolver, Int32 unknownVariableResolverDepth, NavValue[] values, Int32& expressionLeafCount, Boolean& hasVariables, Boolean cultureInvariant, DataError dataError)
   at Microsoft.Dynamics.Nav.Runtime.FilterExpressionParser.Parse(String expression, FilterExpressionContext expressionContext, Func`3 customVariableResolver, Int32 unknownVariableResolverDepth, Boolean& hasVariables, NavValue[] values, Boolean cultureInvariant)
   at Microsoft.Dynamics.Nav.Runtime.FilterExpressionParser.Parse(String expression, FilterExpressionContext expressionContext, Boolean allowExpressionEvaluation, Boolean& hasVariables, NavValue[] values)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateTableFiltersAndMarksFromDataItemFieldFilters(NCLMetaQueryDataItem dataItemBeingCreated, List`1 fieldFilters, Boolean allowExpressionEvaluation, Boolean& tableFilterHasVariables)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass61_1.<CreateDataItemsFromDesignMetadata>b__1(NCLMetaQueryDataItem dataItemBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDataItem..ctor(NCLMetaQueryDefinition parentQueryDefinition, DataItemLinkType dataItemLinkType, Int32 tableNo, DataLockState lockState, String name, Func`2 queryColumnsCreator, Func`2 tableFiltersAndMarksCreator, Func`2 dataItemLinksCreator, List`1 metaQueryFieldFilters, Int32 appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateDataItemsFromDesignMetadata(NCLMetaQueryDefinition parentQueryDefinition, MetaQuery metaQuery, Boolean allowExpressionEvaluation, Boolean& tableFilterHasVariables)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass62_1.<ParseMetadata>b__0(NCLMetaQueryDefinition queryDefinitionBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDefinition..ctor(NCLMetaQueryDataItem parentDataItem, Int32 topRows, Func`2 dataItemsCreator, Func`2 orderBysCreator)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.ParseMetadata(MetaQuery metaQuery, Boolean allowExpressionEvaluation)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.LoadMetadata()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroupNewObject(NavAppGroup appGroup, NavAppGroupObjectMetadataSummary newObjectSummary)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeNewAppQueries(NavAppGroup appGroup, InitializeAppGroupProfiler profiler, IReadOnlyList`1 newObjectsFromApps)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroup(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NavAppSyncManagementTasks.SyncNavApp(SyncNavAppArguments args)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Diagnostic.NavDiagnostics.ComposeAndSendExceptionTraceTag(String tag, Category category, Exception exception, DiagnosticParameter message, Verbosity verbosity, Guid clientSessionId, Guid clientActivityId, String diagnosticsContext, Boolean forceLog)
   at Microsoft.Dynamics.Nav.Diagnostic.NavDiagnostics.SendExceptionTag(String tag, Category category, Exception exception, Verbosity verbosity, DiagnosticParameter message, String diagnosticsContext, Boolean forceLog)
   at Microsoft.Dynamics.Nav.Runtime.NavAppSyncManagementTasks.SyncNavApp(SyncNavAppArguments args)
   at Microsoft.Dynamics.Nav.Service.NSAdminService.<>c__DisplayClass132_0.<Microsoft.Dynamics.Nav.Types.ITenantDatabaseManagementService.SyncNavApp>b__0()
   at Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.<>c__DisplayClass2_0`1.<RetryOperationWithTransientError>b__0()
   at Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.InternalRetryOperationWithTransientError[T](Action operation, Int32 maxRetryCount, Int32 retryIntervalInSeconds, String callerName, String additionaInfo, Boolean expectedType)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.RetryOperationWithTransientError[T](Func`1 operation, Int32 maxRetryCount, Int32 retryIntervalInSeconds, String caller, String additionalContext)
   at Microsoft.Dynamics.Nav.Service.NSAdminService.Microsoft.Dynamics.Nav.Types.ITenantDatabaseManagementService.SyncNavApp(SyncNavAppArguments syncNavAppArguments)
   at Microsoft.Dynamics.Nav.Service.Dev.DevService.SyncNavApp(NavAppManifest manifest, String tenantId, NavAppSyncMode mode)
   at Microsoft.Dynamics.Nav.Service.Dev.DevService.<>c__DisplayClass6_1.<PublishAndInstallExtension>b__0()
   at Microsoft.Dynamics.Nav.Service.Dev.DevService.PublishAndInstallExtension(NavSession session, Stream packageStream, PerformanceLog performanceLog, SchemaUpdateMode schemaUpdateMode)
   at Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.AppsController.<PublishAndInstall>d__0.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

- AL Extension Version: 2.0.48254
- Server Version: 13.0.24623

Best Regards, 
Gintautas

**Comment by strophanthus** [comment]
I'm not having issues with publishing but I am getting this warning as well for the app.json file when the CodeCop analyzer is enabled. 

![warnings](https://user-images.githubusercontent.com/32313731/46736910-7e40b580-cc9a-11e8-954d-15dce1e04782.png)

**Comment by josnelissen** [comment]
I was having  the same problem and solved it as following:
**
case Expression of
        '0010':
         begin
	       //Generates error in app.json
          end;
         '0100':
	      ;   //No Error
end;
**	

So using begin-end without code seems to generate the error

**Comment by gintuoklis** [comment]
Hey @StanislawStempin, 
Do i understand correctly, i could test it on insider build _bcinsider.azurecr.io/bcsandbox-master_ already ?

**Comment by StanislawStempin** [comment]
Probably in a few days since we have a slight delay between our internal build and the refreshed docker image
