### ISSUE TITLE
OnAssistEdit trigger causes Txt2AL to fail

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#402]
I have a page field with code in the OnAssistEdit trigger of a custom field.  When running TXT2AL (from the DELTA) I get the error below.  This should be likely moved to an Event but I don't see an event I can subscribe to for OnAssistEdit.  How should I handle this?

The OnAssistEdit trigger looks like this in this DELTA:
```
                           { 1190000022;2;Field  ;
                                       Name=Type 1 attachment;
                                       SourceExpr="Type 1 attachment";
                                       OnAssistEdit=VAR
                                                      FileMgt@1190000004 : Codeunit 419;
                                                    BEGIN
                                                      "Type 1 attachment" := FileMgt.OpenFileDialog('Attachment Link','','');
                                                    END;
                                                     }
```
TXT2AL Error (run from inside PowerShell).
```
----ERROR----
System.ArgumentException: Element OnAssistEdit does not support property ActionType
   at Microsoft.Dynamics.Nav.MetaModel.ElementExtension.GetStringProperty(IElement element, PropertyType property)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.
Page.PageSectionsExporter.GetElementTypeName(IElement child)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.ExporterLocator.GetElementKey(IElement element)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.NestedElementExporter.GetElementExporter(IElement child
)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.NestedElementExporter.<>c__DisplayClass16_0.<Export>b__0()
   at Microsoft.Dynamics.Nav.Txt2AlConverter.AlWriter.WriteSection(Action writeSectionContent)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.NestedE
lementExporter.Export(ElementTreeNode element, IAlWriter writer)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.Modification.ChangeElementExporter.Export(ElementTreeNode element, IAlWriter writer)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Expo
rters.Modification.InsertionSectionExporter.<>c__DisplayClass5_0.<ExportSubElements>b__0(ElementTreeNode child)
   at Microsoft.Dynamics.Nav.MetaModel.ElementExtension.ForEach[T](IEnumerable`1 elements, Action`1 action)
   at Microsoft.Dynamics.Nav.Txt2A
lConverter.Exporters.Modification.InsertionSectionExporter.ExportSubElements(IEnumerable`1 subElements, INestedElementExporter subElementExporter, IAlWriter writer)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.Modification.InsertionSectionExport
er.<>c__DisplayClass4_0.<ExportSection>b__0()
   at Microsoft.Dynamics.Nav.Txt2AlConverter.AlWriter.WriteSection(String sectionName, Action writeSectionContent)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.Modification.InsertionSectionExporter.
ExportSection(IElement element, IAlWriter writer, INestedElementExporter subElementExporter, ElementType targetElementType)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.Modification.InsertionSectionExporter.Export(IElement element, IAlWriter wri
ter)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.Modification.PageExtensionExporter.ExportChangeSection(IElement changeSection, IAlWriter writer, IExporterLocator 
exporterLocator, ElementType targetElementType)
   at Microsoft.Dynamics.Nav.Txt
2AlConverter.Exporters.Modification.PageExtensionExporter.<>c__DisplayClass2_0.<ExportLayoutChanges>b__1(IElement change)
   at Microsoft.Dynamics.Nav.MetaModel.ElementExtension.ForEach[T](IEnumerable`1 elements, Action`1 action)
   at Microsoft.Dynamics
.Nav.Txt2AlConverter.Exporters.Modification.PageExtensionExporter.<>c__DisplayClass2_0.<ExportLayoutChanges>b__0()
   at Microsoft.Dynamics.Nav.Txt2AlConverter.AlWriter.WriteSection(String sectionName, Action writeSectionContent)
   at Microsoft.Dynamics
.Nav.Txt2AlConverter.Exporters.Modification.PageExtensionExporter.ExportLayoutChanges(IEnumerable`1 layoutChanges, IAlWriter writer, IExporterLocator exporterLocator)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.Modification.PageExtensionExporte
r.Export(IElement element, IAlWriter writer)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.Modification.ChangeContentExporter.Export(IElement element, IAlWriter writer)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.ElementWithDocumentationExporte
r.Export(IElement element, IAlWriter writer)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.Exporters.Modification.ModificationContentExporter.Export(IElement element, IAlWriter writer)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.ApplicationObjectExporter
.<>c__DisplayClass4_0.<Export>b__0()
   at Microsoft.Dynamics.Nav.Txt2AlConverter.AlWriter.WriteSection(String sectionName, Action writeSectionContent)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.ApplicationObjectExporter.Export(ApplicationObject applic
ationObject, IAlWriter writer)
   at Microsoft.Dynamics.Nav.Txt2AlConverter.AlExporter.ExportObjects(IEnumerable`1 applicationObjects, Stream stream, Action progressAction)
   at Txt2Al.Program.ExportObjectsToString(List`1 ao, AlExportOptions options)
 
  at Txt2Al.Program.ExportApplicationObject(Tuple`2 fileAndApplicationObject, AlExporterCommandLineOptions options, AlExportOptions exporterOptions, ConcurrentQueue`1 
errorsStorage)
   at Txt2Al.Program.<>c__DisplayClass4_1.<ConvertFilesFromDirectory>b__1
(Tuple`2 fileAndApplicationObject)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskB
ase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by GreatScott000** [comment]
The error still occurs but I have figured out how to add the OnAssistEdit trigger.  It was a "doh" moment.

**Comment by atoader** [comment]
We will take a look at this and see if we can fix it easily. Thanks for reporting!

**Comment by DominikDitoIvosevic** [comment]
@GreatScott000 could you please check that this still reproduces? I'm having problems finding a repro for this
