### ISSUE TITLE
AL Extension Deployment -  Error: An internal error has occurred

### ISSUE THREAD

**Issue by kavila02** [Microsoft/AL#4091]
When I go to deploy an extension from VS Code to my NAV environment (hosted locally with Docker), I get the following error message:
Microsoft (R) AL Compiler version 0.16.26913
Copyright (C) Microsoft Corporation. All rights reserved

Success: The package is created.
[2018-10-19 13:14:42.26] Sending request to http://mybizcentralapp:7049/NAV/dev/apps?SchemaUpdateMode=synchronize
[Error - 1:14:44 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/openPageDesigner' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.Deployment.Publishing.Publisher.<SendPackage>d__6.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Publishing\Publisher.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.Deployment.Publishing.Publisher.<Publish>d__5.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Publishing\Publisher.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPageDesignerRequestHandler.<ProcessRequestAsync>d__3.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPageDesignerRequestHandler.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59
I can access NAV through the web client and can access the database for the NAV instance but can't deploy an extension. I have no errors in my extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/42249333/47233260-1f68f380-d3a0-11e8-99d3-673a2cfc21e0.png)

**Versions:**
AL Compiler Version: 0.16.26913

**Comment by ThomasBrendel** [comment]
I have same error and cant publish the DEMO App into Docker with recent "BC onprem"  

[2018-10-21 18:24:03.97] Sending request to http://navbconprem:7049/NAV/dev/apps?SchemaUpdateMode=synchronize
**[2018-10-21 18:24:37.82] Error: An internal error has occurred**

but no other information available. My dockercontainer is healthy and restartet. Just one dockercontainer is started on the machine. 

checked that licencefile is in that dockercontainer,

launch.json:
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "al",
            "request": "launch",
            "name": "NAVBConPrem",
            "server": "http://NAVBConPrem",
            "serverInstance": "NAV",
            "authentication": "UserPassword",
            "startupObjectId": 22
        }
    ]
}

app.json
{
  "id": "ad47661e-253f-4958-9065-f609350775ef",
  "name": "ALProject1",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}

**Comment by StanislawStempin** [comment]
Closing this issue. Please make sure that you're using the latest AL Language extension:
- From the VS Code Marketplace if working with cloud tenants or any released versions of Business Central
- From the Docker image if working with insider preview builds
