### ISSUE TITLE
PageLayout

### ISSUE THREAD

**Issue by stephanweidmann** [Microsoft/AL#4115]
If a new field is used as anchor for a Standard field in moveafter, the compilation Fails.

    layout
    {
        addafter(Base_FieldA)
        {
            field(Ext_Field1; Ext_Field1) { }
            // field(Ext_Field2; Ext_Field2 { }
        }
        moveafter(Ext_Field1; Base_FieldC)
    }
}

If Moveafter is moved before the "AddAfter", a warning is shown. ({
	"message": "Cannot use '\"Total Amount (LCY)\"' before it is declared",},
if it is moved after the declaration, the compile crashes.

My Goal was to Show the fields in the sequence Base_FieldA, Ext_Field1, Base_FieldC, Ext_Field2

Expection: This should either be working or given an error message.

Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.<>c__DisplayClass12_0.<VisitSymbolWithProperties>b__1(PropertySymbol property) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 77
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.EnumerableExtensions.Do[T](IEnumerable`1 source, Action`1 action) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\EnumerableExtensions.cs:line 55
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitSymbolWithProperties(Symbol symbolWithProperties) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 70
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.DefaultVisit(Symbol symbol) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 29
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitMembersOfSymbol(Symbol symbol) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 118
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitMembersOfSymbol(Symbol symbol) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 118
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitMembersOfSymbol(Symbol symbol) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 118
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespacee) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.WriteDefaultNodesAndContinue(XmlWriter writer, String appName, String targetLanguage, Action groupContentWriter) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\XliffOutputter.cs:line 65
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LanguageFileOutputter.OutputLanguageFile(Compilation compilation, Stream outputStream, String appName) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LanguageFileOutputter.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.OutputLanguageFile(Compilation compilation, CompilerTextWriter consoleOutput, ErrorLogger errorLogger) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 512
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 440
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 313
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__4.MoveNext() in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by StanislawStempin** [comment]
Please follow the issue templates
