### ISSUE TITLE
The stream was already consumed. It cannot be read again.when put operation performed

### ISSUE THREAD

**Issue by pavan2017git** [Microsoft/AL#4126]
I have implemented polly retry mechanism for api calls.When client perform put operation on given api for some reason it fails in that situation this exception **The stream was already consumed. It cannot be read again.**was thrown by polly.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. I have performed put operation on my service

**Expected behavior**
shouldn't throw this error.It has to throw actual service error

**Screenshots**
Code Implementatio here
```
  var retryPolicy = Policy
                    .Handle<HttpRequestException>()
                    .OrResult<BackendResponse>(r => Retryable(r.HttpVerbs,r.StatusCode))
                    .WaitAndRetryAsync(maxRetryAttempts, i => pauseBetweenFailures);

                return await retryPolicy.ExecuteAsync(async () =>
               {
                   retryCount++;
                   response = await _apiClient.SendAsync(backendRequest);
                   return response;
               });

 private bool Retryable(HttpMethod httpMethod,HttpStatusCode statusCode)
        {
            HttpStatusCode statusValue = statusCode;
            int code = (int)statusValue;

            if (code.ToString().StartsWith("5"))
            {
                switch (retryablePolicy)
                {
                    case RetryableEnum.RetryableIdempotent5XX:
                        // GET, HEAD, OPTIONS,TRACE  and DELETE
                        
                        return (httpMethod == HttpMethod.Get || httpMethod == HttpMethod.Head || httpMethod == HttpMethod.Options
                                  || httpMethod == HttpMethod.Trace || httpMethod == HttpMethod.Put || httpMethod == HttpMethod.Delete) ? true : false;

                    case RetryableEnum.RetryableAll5XX:
                        return true;
                    default:
                        break;
                }
                              
            }
            return false;
        }
```
Providing here full stack error info
```
**Full error stacktrace:{"message": "**
The stream was already consumed. It cannot be read again.**","stackTrace": " 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ExternalHttpClient.<InternalSendAsync>d__9.MoveNext() in C:\\BuildAgent\\work\\3f97ad4eb996d51b\\src\\ExternalHttpClient.cs:line 92— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ExternalHttpClient.<SendAsync>d__8.MoveNext() in **
```
**Versions:
 - dot net core 2.0
Please help me out of this problem. looking forward for your valuable solution :)

**Comment by atoader** [comment]
Hi @pavan2017git ! Where is that stacktrace coming from? What  AL code are you running?

**Comment by pavan2017git** [comment]
on controller I have PUT method when I was performed put operation the above error got thrown

**Comment by atoader** [comment]
The above error doesn't look like an AL error or anything related to the compiler. Please provide a fully contained repro.

**Comment by pavan2017git** [comment]
Actually I implemented Polly retry mechanism on API. I am not sure from where this issue arised.
could you tell me what is reason behind it to throw above error.

**Comment by atoader** [comment]
I am cannot know what is wrong with your code if you do not provide a proper repro. It looks like your problem is not caused by the AL development environment. You might be able to get help using one of the following resources:

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
