### ISSUE TITLE
Unable to cast object of type SimpleNavTypeSymbol to IDotNetTypeSymbol

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/AL#4127]
Getting this while compiling extension. Any thoughts what might be causing it?

```
Internal error: System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SimpleNavTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IDotNetTypeSymbol'.
   at Microsoft.Dynamics.Nav.CodeAnalysis.ConversionDotNet.ClassifyByRefConversion(TypeSymbol source, TypeSymbol byRefTarget) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\Conversions\ConversionDotNet.cs:line 579
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.GetVarArgumentCompatibility(HashSet`1& useSiteDiagnostics, TypeSymbol argType, TypeSymbol parameterType) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 602
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.CheckArgumentForConversionApplicability(BoundExpression argument, ParameterSymbol parameter, HashSet`1& useSiteDiagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 580
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.IsApplicable(EffectiveParameters parameters, AnalyzedArguments arguments, BoundExpression receiverOpt, HashSet`1& useSiteDiagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 373
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.IsApplicable[TMember](TMember member, AnalyzedArguments arguments, EffectiveParameters effectiveParameters, BoundExpression receiverOpt, HashSet`1& useSiteDiagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 332
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.ResolveDefaultMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, HashSet`1& useSiteDiagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:line 2155
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.ResolveMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, HashSet`1& useSiteDiagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:line 2124
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindMethodGroupInvocation(SyntaxNode syntax, SyntaxNode expression, String methodName, BoundMethodGroup methodGroup, Boolean isStatement, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 142
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode expression, String methodName, BoundExpression boundExpression, Boolean isStatement, Boolean asProperty, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 98
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics, Boolean isStatement) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 31
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindExpressionStatement(SyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 521
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatements(SyntaxList`1 syntaxStatements, DiagnosticBag diagnostics, Binder binder) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 80
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindIfStatement(IfStatementSyntax node, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 554
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatements(SyntaxList`1 syntaxStatements, DiagnosticBag diagnostics, Binder binder) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.RepeatBinder.BindRepeatParts(DiagnosticBag diagnostics, Binder originalBinder) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\RepeatBinder.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 101
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindIfStatement(IfStatementSyntax node, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 546
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatements(SyntaxList`1 syntaxStatements, DiagnosticBag diagnostics, Binder binder) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.BindMethodBody(MethodSymbol method, DiagnosticBag diagnostics) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 482
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethod(MethodSymbol methodSymbol) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 404
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMembers(ContainerSymbol containingType) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 328
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 218
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass14_0.<CompileObjectAsTask>b__0() in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 202
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 152
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 162
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 146
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 624
```

**Versions:**
 - AL Langauge: 2.0.48254

Best Regards,
Gintautas

**Comment by atoader** [comment]
Hi @gintuoklis ! Could you try installing the latest-latest extension distributed through Collaborate and let me know if you still see the failure?

**Comment by gintuoklis** [comment]
I tried it using 

Extension language from bcinsider.azurecr.io/bcsandbox latest build. Pull it 6 days ago. There's no newer one. Let me know if I should use extension from different image.

**Comment by atoader** [comment]
I think that should be good enough. Is there any chance you can find the code causing the issue? It seems to be inside a repeat statement and you are calling a method taking a .NET parameter.

**Comment by gintuoklis** [comment]
Can you tell me how can i do it? I've been asking this question for so many time and still did not receive clear answer. Is it possible to debug or trace where AL Language compiler is crashing? I see no way to identify an issue when you have thousands of files within an extension.

**Comment by StanislawStempin** [comment]
On the latest version of AL Language you can enable a setting: 
`"al.editorServicesLogLevel": "Verbose"`

This will log detailed information about the compilation process into EditorServices.log file in the AL Language extension folder. You can then inspect that log file to see which application object and which symbol is potentially causing the crash.

**Comment by gintuoklis** [comment]
Hey @StanislawStempin,
I did as you adviced. Enabled verbose logging, and checked the log file. I see no any additional information that could help me to identify which file compiler is crashing on. It basically gives the same error message as in the output window. Please check the file attached.

[EditorServices.log](https://github.com/Microsoft/AL/files/2529195/EditorServices.log)

**Comment by thpeder** [comment]
Hey @gintuoklis,
We have a bug in the logger, so it should have given you more information but unfortunately it doesn't at the moment.

From looking at the StackTrace it seems like you are invoking a .net function and we guess the type incorrectly, and it seems like it might be a Ref parameter.

It is a construct that goes something like:
Procedure
If Block
Repeater Block
If Block
.net Function invocation

**Comment by gintuoklis** [comment]
Did logger worked before? Perhaps i could use older version of AL where logging functionality works?

Thanks for tip how to the find the problem, but I already went through similar journey on different case and don't want to repeat. It just takes way too much time, and honestly that's not development experience should be. If you want to try it for yourself, I could share code with you guys.

**Comment by thpeder** [comment]
@gintuoklis I thought it didn't work until I discovered that we initialize the loggers when we start-up the VSCode extension, so you need to change the configuration, save the file, and then restart VSCode and after that you should see more information in the log file.

**Comment by gintuoklis** [comment]
I'm pretty sure, I restarted VSCode multiple times after changing this setting. If you look at the log file I attached, you should be able to see **verbose** messages. So it seems logging works, but it's not detailed enough. Unless there should be another log messages

```
30-10-2018 11:28:45 [VERBOSE] - Method "Process" at line 53 of C:\a\459\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs

    Process:
    
    al/createPackage
```

**Comment by thpeder** [comment]
There should have been more messages in there about parsing, binding and what not of objects, but I can't get it to work on the version in the VSCode marketplace either so I unfortunately think you need to wait for the next version to be released.
If you are part of the ReadyToGo program then the docker image contains daily builds of the VSCode extension which you could try with.

**Comment by gintuoklis** [comment]
hey @thpeder, 
Parsing works fine with the latest daily build. It shows information about parsing & binding. But it does not really help. If i understand correctly it's all done in parallel and you cannot tell which file cause the failure. If you would like, i could share the log file. I don't want to upload it here publicly, please let me know how i could do it in private.

**Comment by atoader** [comment]
Hi @gintuoklis ! Could you compile using the alc with the parallel build disabled and verbose logging enabled? This should help narrow down the problem. You should pass: ```/loglevel:Verbose /parallel-``` to the alc

**Comment by gintuoklis** [comment]
Thanks for the tip @atoader , managed to find the problem using your method.

Had few functions that were passing XmlNode type to function that it's using System.Xml.XmlNode types. Apparently they are not compatible. 

Here's the code how you could replicate the issue:

```
page 50101 TestDummyFunction
{
    var
        XMLDOMgt: Codeunit "XML DOM Management";
    local procedure DummyFunction(var TargetString: Text; var CriteriaXMLNode: XmlNode; var TargetXMLNode: XmlNode)
    begin
        XMLDOMgt.AddElement(TargetXMLNode, 'criteria', TargetString, '', CriteriaXMLNode);
    end;
}
```

Of course, it's not over yet and it just leads to another problem. Will make another request for it.

**Comment by atoader** [comment]
I tried compiling the sample and I get the following errors:
```
Compilation started for project 'ALProject5' containing '1' files at '9:53:26.217'.

c:\Users\altoader\Documents\AL\ALProject5\HelloWorld.al(8,29): error AL0133: Argument 1: cannot convert from 'XmlNode' to 'DotNet "System.Xml.XmlNode"'
c:\Users\altoader\Documents\AL\ALProject5\HelloWorld.al(8,74): error AL0133: Argument 5: cannot convert from 'XmlNode' to 'DotNet "System.Xml.XmlNode"'

Compilation ended at '9:53:26.370'.

Error: The package could not be created.
```
but with no crash. Can you repro with that code in an new extension?

**Comment by atoader** [comment]
Your scenario is not officially supported: 

From the change log of the extension:
```
... This means that in the near future you will be able to install the AL Language extension from the Visual Studio Code marketplace and use it to develop solutions for:

Microsoft cloud sandbox
Business Central, April 2018 release
Business Central, Fall 2018 release
And more
Please note that at the moment there are no plans to make this AL Language extension version backwards compatible with Dynamics NAV. For Dynamics NAV development, the traditional method should be used – install the VS Code extension from the ALLanguage.vsix file shipped on the DVD.
```
A bit more context:
There are two parts to the development process: 
1. Development and compilation locally, in VSCode
2. Server publishing

No. 1 benefits from the monthly updates of the extension and any fixes we make to the compiler. When you install the extension, you get the latest version of the compiler and extension installed in your VSCode extension folder. This will let you try out the latest features and benefit from the latest bug fixes. The extension does not depend on any NAV dlls and it does not install any other dependencies on your system.

No 2. is the one where things get complicated. When you publish an extension to the server, the whole package gets recompiled with the compiler that is **bundled** with the server. This means that even if we fix a crash in the AL Language Extension that is released to the marketplace, the fix does not get automatically applied to the compiler that is bundled with your server. That fix comes only through CUs for on-prem or monthly updates for the cloud and only if we get a request through support for fixing the issue. 

What abou the "runtime" flag? That helps prevent you from using features that are not available in your targeted environment. For example, if we add a function Foo that is available only from runtime 3.0, and you set your runtime to 2.0, you will get a compile time error saying that you cannot use that function.

**Comment by gintuoklis** [comment]
thanks @atoader for the explanation. I guess we can close the case then.

**Comment by atoader** [comment]
Thanks!
