### ISSUE TITLE
Go To Definition not working and erroring in BC

### ISSUE THREAD

**Issue by bgadhvi1** [Microsoft/AL#4144]
Hi All

So I am building an extension and whenever I want to see the source code (Go To Definition) it errors with the below error (even asks me to post the issue on here!)

[Error - 8:24:25 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/previewDocument' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertAttributeArgument(AttributeSymbol attribute) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 430
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertAttributes(IEnumerable`1 attributes) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 278
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertProceduresAndTriggers(IEnumerable`1 procedures) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 137
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertMembers(ImmutableArray`1 members) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 73
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntaxTable.ConvertTable(TableTypeSymbol table) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax_Table.cs:line 47
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.Convert(ISymbol symbol) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 37
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPreviewDocumentRequestHandler.SymbolToPreviewText(ISymbol symbol) in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPreviewDocumentRequestHandler.cs:line 64
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPreviewDocumentRequestHandler.<HandleAsync>d__3.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPreviewDocumentRequestHandler.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\16\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

To reproduce  click on Go To Definition from any object you are extending.

AL Version is 2.0.48254
BC Version is GB Dynamics NAV 13.0 (25432)

Any idea what is wrong here?

**Comment by bgadhvi1** [comment]
No ideas people, still receiving the same error when trying to either go to definition or even peek definition...

**Comment by kalberes** [comment]
Can you provide an example. From your description things are just too vague.

**Comment by bgadhvi1** [comment]
Hi

The base object, I've tried both go to definition for base objects and methods within the base object and neither work, I cannot see the base code from AL, have tried numerous different objects go to definition and I cannot access any of the base code, but the symbols download fine.

**Comment by StanislawStempin** [comment]
Could you please paste your launch.json here for reference?
Also, make sure that you have deleted any old symbol files that you might have had and redownloaded fresh ones from the server

**Comment by StanislawStempin** [comment]
Another question would be where does your server come from? Is it online sandbox, docker image or a DVD installation? 
If it's on-prem installation, have the base application symbols been generated correctly?

**Comment by bgadhvi1** [comment]
Hi Stanislaw

Apologies for the delay, so the launch.json is below:

![image](https://user-images.githubusercontent.com/44622284/48499897-704df980-e831-11e8-9639-00bdae9b7811.png)

Its fine as far as I can see. I've deleted any symbol files, re-downloaded the symbols no luck. Its not an on-prem installation, its a cloud one, and symbols are being generated correctly. Weird thing is it works on my Azure machine in VSCode, I can download the symbols and go to definition, some be something wrong with windows 10 on a Surface Pro 3 and VSCode...

**Comment by kalberes** [comment]
Can you please provide a small sample that issues that exception
