### ISSUE TITLE
Unexpected behaviour of Application.

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#4198]
Hi Experts,

I developed an extension and also able to publish it on **Cloud Sandbox** and on my local **BC130** on-prem instance without any error.

But when tried to run a page based on this extension I got and unexpected error on cloud sandbox like below.
**Something went wrong.
An error has occurred
Date and time: Wed, 14 Nov 2018 07:38:51 GMT
Azure AD tenant ID: 6b8d6b2e-e671-4ddd-be75-adcbe0d9fd35
Client operation ID: 2b82c067-0d2d-442f-ae79-561c55693214
Go back home**

As I was not able to see what was issue behind this error on cloud sandbox. So I took a chance to publish it on local on-premise solution. Here also I got an error. Below is the log from **Event Viewer**.

```Type: Microsoft.Dynamics.Nav.Client.NavClientClosingException
Fatal: False
ShowError: True
Message: The server "DynamicsNAV130" was unable to process the request. The application will close.
StackTrace:
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.DoExecute(Func`1 execute)
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.DoRethrowWithCatchException(Exception exception, Boolean designMode)
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.WinFormsDispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs eventArgs)
     at Microsoft.Dynamics.Framework.UI.WinForms.WinFormsDispatcher.HandleDispatcherException(Object sender, Exception e)
     at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
     at System.Windows.Forms.Control.WndProcException(Exception e)
     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
     at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
     at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
     at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
     at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
     at Microsoft.Dynamics.Nav.Client.WinClient.NavWinFormsClientSession.RunMessagePump()
     at Microsoft.Dynamics.Nav.Client.WinClient.NavWinFormsClientSession.RunCore()
     at Microsoft.Dynamics.Nav.Client.WinClient.NavClientErrorHandler.ExecuteAndCatchExceptions(Func`1 execute)
Source: Microsoft.Dynamics.Nav.Client.WinClient
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.DoExecute(Func`1 execute)
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.DoRethrowWithCatchException(Exception exception, Boolean designMode)
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.WinFormsDispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs eventArgs)
     at Microsoft.Dynamics.Framework.UI.WinForms.WinFormsDispatcher.HandleDispatcherException(Object sender, Exception e)
     at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
     at System.Windows.Forms.Control.WndProcException(Exception e)
     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
     at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
     at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
     at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
     at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
     at Microsoft.Dynamics.Nav.Client.WinClient.NavWinFormsClientSession.RunMessagePump()
     at Microsoft.Dynamics.Nav.Client.WinClient.NavWinFormsClientSession.RunCore()
     at Microsoft.Dynamics.Nav.Client.WinClient.NavClientErrorHandler.ExecuteAndCatchExceptions(Func`1 execute)
----------------------------------
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException
Message: The server "DynamicsNAV130" was unable to process the request. The application will close.
StackTrace:
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.<>c__DisplayClass11_0.<DoRethrowWithCatchException>b__0()
     at Microsoft.Dynamics.Nav.Client.WinClient.NavClientErrorHandler.ExecuteAndCatchExceptions(Func`1 execute)
Source: Microsoft.Dynamics.Nav.Client.WinClient
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Client.WinClient.ExceptionHandler.<>c__DisplayClass11_0.<DoRethrowWithCatchException>b__0()
     at Microsoft.Dynamics.Nav.Client.WinClient.NavClientErrorHandler.ExecuteAndCatchExceptions(Func`1 execute)
----------------------------------
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException
Message: The server "DynamicsNAV130" was unable to process the request. The application will close.
StackTrace:
     at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod, ServerCallOptions options)
     at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod)
     at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.OpenForm(NavOpenFormArguments& mainForm, NavOpenFormArguments[]& subForms)
     at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.OpenForm(LogicalForm mainForm, Collection`1 subForms)
     at Microsoft.Dynamics.Nav.Client.UIPatterns.OnFormOpeningPattern.OpenForm(LogicalForm form)
     at System.EventHandler.Invoke(Object sender, EventArgs e)
     at Microsoft.Dynamics.Framework.UI.LogicalForm.BuildForm(Action customBuild)
     at Microsoft.Dynamics.Nav.Client.Builder.NavSessionHelper.BuildForm(LogicalForm form, Action customBuild)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.Build(MasterPage definition, BindingManager bindingManager, UIBuilderContext context)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(MasterPage metadata, FormState formState)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(Int32 formId, FormState formState, Int32 retryCounter)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(String name)
     at Microsoft.Dynamics.Framework.UI.UISession.CreateLogicalForm(String name, Boolean reuseActiveForm)
     at Microsoft.Dynamics.Framework.UI.UX2006.NavigationService.OpenEmbeddedForm(String formName)
     at Microsoft.Dynamics.Framework.UI.UX2006.NavigateToFormAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession)
     at Microsoft.Dynamics.Nav.Client.Actions.NavNavigateToFormAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession)
     at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession)
     at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(LogicalControl logicalControl, IDictionary state, UISession uiSession)
     at Microsoft.Dynamics.Framework.UI.UX2006.NavigationService.NavigateToNode(LogicalControl logicalControl, NavigationNode node)
     at Microsoft.Dynamics.Framework.UI.UX2006.WinForms.PageSearchBar.WndProc(Message& m)
     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Source: Microsoft.Dynamics.Nav.Client.ServiceConnection
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod, ServerCallOptions options)
     at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod)
     at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.OpenForm(NavOpenFormArguments& mainForm, NavOpenFormArguments[]& subForms)
     at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.OpenForm(LogicalForm mainForm, Collection`1 subForms)
     at Microsoft.Dynamics.Nav.Client.UIPatterns.OnFormOpeningPattern.OpenForm(LogicalForm form)
     at System.EventHandler.Invoke(Object sender, EventArgs e)
     at Microsoft.Dynamics.Framework.UI.LogicalForm.BuildForm(Action customBuild)
     at Microsoft.Dynamics.Nav.Client.Builder.NavSessionHelper.BuildForm(LogicalForm form, Action customBuild)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.Build(MasterPage definition, BindingManager bindingManager, UIBuilderContext context)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(MasterPage metadata, FormState formState)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(Int32 formId, FormState formState, Int32 retryCounter)
     at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(String name)
     at Microsoft.Dynamics.Framework.UI.UISession.CreateLogicalForm(String name, Boolean reuseActiveForm)
     at Microsoft.Dynamics.Framework.UI.UX2006.NavigationService.OpenEmbeddedForm(String formName)
     at Microsoft.Dynamics.Framework.UI.UX2006.NavigateToFormAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession)
     at Microsoft.Dynamics.Nav.Client.Actions.NavNavigateToFormAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession)
     at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession)
     at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(LogicalControl logicalControl, IDictionary state, UISession uiSession)
     at Microsoft.Dynamics.Framework.UI.UX2006.NavigationService.NavigateToNode(LogicalControl logicalControl, NavigationNode node)
     at Microsoft.Dynamics.Framework.UI.UX2006.WinForms.PageSearchBar.WndProc(Message& m)
     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
----------------------------------
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException
Message: The server "DynamicsNAV130" was unable to process the request. The application will close.
HResult: -2146233088
----------------------------------
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.CrmDataProvider.EntityToRecordBuffer(IXrmEntity entity, IRecordBuffer originalBuffer)
     at Microsoft.Dynamics.Nav.Runtime.CrmDataProvider.<FindByPositionImplementation>d__53.MoveNext()
     at Microsoft.Dynamics.Nav.Runtime.ResultSet.TryGetAtIndexWithoutBuffer(Int32 index, ReadOnlyRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryGetRecordBufferFromResultSet(Int32 fetchIndex, MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryMoveNextImpl(MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Advance(Int32 steps, Boolean moveBackwards, Boolean automaticFindFromPositionOnInvalid, Boolean& resultSetValid, Int32 setSize)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.IssueFindRequest(DataError errorLevel, Boolean reversed, FindType findType, Boolean useCache)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecordImp(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecord(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALFind(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.Runtime.DataItemIterator.ExecuteDataItemLoop(DataItem dataItem)
     at Microsoft.Dynamics.Nav.Runtime.DataItemIterator.LoopRootDataItems()
     at Microsoft.Dynamics.Nav.Runtime.DataItemIterator.ExecuteDataItemIterator()
     at Microsoft.Dynamics.Nav.Runtime.NavReport.RunReportInternal(NavRecord record, Boolean displayResult)
     at Microsoft.Dynamics.Nav.Runtime.NavReport.RunReport(Nullable`1 requestWindow, Nullable`1 systemPrinter, Boolean runReportModal, NavRecord record, IList`1 reportTextualFilters, RunMode mode)
     at Microsoft.Dynamics.Nav.Runtime.NavReport.RunReport(Int32 reportId, Nullable`1 requestWindow, Nullable`1 systemPrinter, Boolean isRunningAsModal, NavRecord record, IList`1 textualFilters, RunMode runMode)
     at Microsoft.Dynamics.Nav.Runtime.NavReport.RunModal(Int32 reportId, Boolean requestWindow, Boolean systemPrinter)
     at Microsoft.Dynamics.Nav.BusinessApplication.Page50115.OnOpenPage_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Page50115.OnOpenPage()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnOpenPage()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.OpenForm()
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.HandleRegistrateDataAccess(FormOpenResponse openResponse)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFormRequest form)
     at SyncInvokeOpenForm(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass24_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass24_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147467261
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.CrmDataProvider.EntityToRecordBuffer(IXrmEntity entity, IRecordBuffer originalBuffer)
     at Microsoft.Dynamics.Nav.Runtime.CrmDataProvider.<FindByPositionImplementation>d__53.MoveNext()
     at Microsoft.Dynamics.Nav.Runtime.ResultSet.TryGetAtIndexWithoutBuffer(Int32 index, ReadOnlyRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryGetRecordBufferFromResultSet(Int32 fetchIndex, MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryMoveNextImpl(MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Advance(Int32 steps, Boolean moveBackwards, Boolean automaticFindFromPositionOnInvalid, Boolean& resultSetValid, Int32 setSize)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.IssueFindRequest(DataError errorLevel, Boolean reversed, FindType findType, Boolean useCache)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecordImp(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecord(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALFind(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.Runtime.DataItemIterator.ExecuteDataItemLoop(DataItem dataItem)
     at Microsoft.Dynamics.Nav.Runtime.DataItemIterator.LoopRootDataItems()
     at Microsoft.Dynamics.Nav.Runtime.DataItemIterator.ExecuteDataItemIterator()
     at Microsoft.Dynamics.Nav.Runtime.NavReport.RunReportInternal(NavRecord record, Boolean displayResult)
     at Microsoft.Dynamics.Nav.Runtime.NavReport.RunReport(Nullable`1 requestWindow, Nullable`1 systemPrinter, Boolean runReportModal, NavRecord record, IList`1 reportTextualFilters, RunMode mode)
     at Microsoft.Dynamics.Nav.Runtime.NavReport.RunReport(Int32 reportId, Nullable`1 requestWindow, Nullable`1 systemPrinter, Boolean isRunningAsModal, NavRecord record, IList`1 textualFilters, RunMode runMode)
     at Microsoft.Dynamics.Nav.Runtime.NavReport.RunModal(Int32 reportId, Boolean requestWindow, Boolean systemPrinter)
     at Microsoft.Dynamics.Nav.BusinessApplication.Page50115.OnOpenPage_Scope.OnRun()
     at Filter.InvokeWithFilter(NavMethodScope )
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Page50115.OnOpenPage()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnOpenPage()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.OpenForm()
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.HandleRegistrateDataAccess(FormOpenResponse openResponse)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFormRequest form)
     at SyncInvokeOpenForm(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass24_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass24_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
```

Please help me out on this.

Thanks 
Kind Regards
SUD

**Comment by qutreson** [comment]
Hi @SUD-D365, can you provide us with more information for us in order to try reproducing it?
From what I understood, you already know which page is causing the error. Can you isolate this page in a smaller extension and share it with us so that we can look into it?

**Comment by SUD-D365** [comment]
Hi @qutreson 
Thanks for your prompt revert.
Yes the page is 50115, but same solution was working fine on a BC instance before that October release of BC.
But recently the extension was automatically removed from my BC sandbox instance.
So I am trying to uploading it again on this Sandbox instance. 

Here is the code on that page50115.

page 50115 "Contract List"
{
    // version Fibersmartz1.0

    CardPageID = "Contract Card";
    Caption = 'Contracts';
    PageType = List;
    SourceTable = "Fib Contracts";
    UsageCategory = Lists;
    ApplicationArea = All;

    layout
    {
        area(content)
        {
            repeater(Group)
            {
                field("Job Id";"Job Id")
                {
                    ApplicationArea = All;
                }
                field("Contract Name";"Contract Name")
                {
                    ApplicationArea = All;
                }
                field(CustomerUniqueCode;CustomerUniqueCode)
                {
                    Caption = 'Customer No.';
                    ApplicationArea=All;
                }
                field("CRM Customer Name";"CRM Customer Name")
                {
                    Caption = 'Customer Name';
                    ApplicationArea=All;
                }
                field("CRM Sales Order No.";"CRM Sales Order No.")
                {
                    Caption = 'Sales Order No.';
                    ApplicationArea=All;
                }
            }
        }
    }

    actions
    {
        area(creation)
        {
            action("Run Trail Invoice Buffer")
            {
                Caption = 'Run Trail Invoice Buffer';
                Promoted = true;
                RunObject = Report "Process Trial Run Entries";
                ApplicationArea=All;
            }
            action("Created Trail Entries")
            {
                Caption = 'Performa Invoice';
                Promoted = true;
                PromotedCategory = Process;
                RunObject = Page "Contract Schedule Buffer";
                RunPageLink = JobID=field("Job Id");
                ApplicationArea=All;
            }
            action("Create Sales Invoice")
            {
                Caption = 'Generate Final Invoices';
                Image = ExecuteAndPostBatch;
                Promoted = true;
                PromotedCategory = Process;
                RunObject = Report "Create Contract SI";
                ApplicationArea=All;
            }
            action("Final Sales Invoice")
            {
                Caption = 'View Sales Invoices';
                Image = SalesInvoice;
                Promoted = true;
                PromotedCategory = Process;
                RunObject = page "Sales Invoice List";
                //RunPageLink = JobID = field("Job Id");
                ApplicationArea=All;
            }
        }
    }

    trigger OnAfterGetRecord();
    begin
        /*
        IF "Job Id"<>'' THEN
        //  MESSAGE('jobid%1',"Job Id");
          TransferTracker;
        */

    end;

    var
        Schedulebuffer : Record "Contract Schedule Buffer";
        contract1 : Record "Fib Contracts";
        circuit1 : Record Circuits;
        csl1 : Record "Contract Schedule Line";
        ItemRec : Record Item;
        trigger OnOpenPage()
        var
        begin
            // If Schedulebuffer.Findset() then
            // Schedulebuffer.DeleteAll();
            // If contract1.findset() then
            // contract1.DeleteAll();
            // If circuit1.findset() then
            // circuit1.DeleteAll();
            // If csl1.Findset then
            // csl1.DeleteAll();
            // ItemRec.RESET;
            // ItemRec.SetRange("No.",'%1','FB*');
            // If ItemRec.FindSet() then
            // ItemRec.DeleteAll();
            REPORT.RUNMODAL(50103,FALSE,TRUE);
            REPORT.RUNMODAL(50104,FALSE,TRUE);
        end;
}

**Comment by SUD-D365** [comment]
Hi @qutreson 

FYI
One more thing , this extension is about integration b/w D365 for Sales and BC for custom entities.

**Comment by SUD-D365** [comment]
Hi @qutreson 

Any update on this. 
I am able to get data in my another buffer tables from CRM. But only one table causing issue.
Which is **salesorder** in CRM.

**Comment by AndersLarsenMicrosoft** [comment]
I am a bit puzzled here 
You have a page based on this table 
SourceTable = "Fib Contracts";
I can see that you are working on D365 for Sales and BC for custom entities.
And now it looks like you are down to having issues with salesorder in CRM.
Are you still facing issues here?
And if so could you share some more insight on “issues with salesorder in CRM”
Thanks
Anders

**Comment by JohanStenberg100** [comment]
@SUD-D365 I will now clsoe this issue since you have not responded to @AndersLarsenMicrosoft's request. Open a new issue with the information Anders requests provided if you are still experiencing this issue.
