### ISSUE TITLE
Not able to add Action to group "Finance" in Rolecenter 9022 "Business Manager Role Center"

### ISSUE THREAD

**Issue by orange-gobbler** [Microsoft/AL#426]
Error Stack when trying to add new action to group "Finance" in Role Center 9022:

```
Microsoft (R) AL Compiler version 0.7.11459
Copyright (C) Microsoft Corporation. All rights reserved

[Error - 10:54:03 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.IsSourceSymbol(ISymbol symbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:line 109
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.GetSyntax(ISymbol symbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:line 114
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.ToReportingString(ISymbol symbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:line 127
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emitter.Utility.ActionAddMetadataBuilder.ContainerGetter(ActionSymbol anchor) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Utility\ActionAddMetadataBuilder.cs:line 32
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emitter.Utility.ContentDestinationMetadataBuilder`2.SetContentMetadata(ContentDestinationMetadata& metadata, ChangeKind changeKind, TV anchor) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Utility\ContentDestinationMetadataBuilder.cs:line 69
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emitter.Utility.ContentAddMetadataBuilder`3.SetContentMetadata(ContentAddMetadata& metadata) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\Utility\ContentAddMetadataBuilder.cs:line 100
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.PageExtensionMetadataEmitter.WriteContentAdd(XmlWriter xmlWriter, SourceChangeAddSymbol addContentSymbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PageExtensionMetadataEmitter.cs:line 187
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.PageExtensionMetadataEmitter.HandleChangeSymbols(XmlWriter xmlWriter, Symbol sym) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PageExtensionMetadataEmitter.cs:line 103
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.PageExtensionMetadataEmitter.<EmitMetadata>b__1_0(XmlWriter xmlWriter) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\PageExtensionMetadataEmitter.cs:line 51
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ObjectMetadataEmitter`1.EmitMetadata(Action`1 content) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\GenericObjectMetadataEmitter.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 232
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass16_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 210
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 150
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 160
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 794
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 771
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 419
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 299
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<InternalHandleAsynch>d__1.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsynch>d__1.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\GenericRequestHandlerBase.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__5.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 60

```

Steps to reproduce:

1. Add PageExtension for Page 9022
![image](https://user-images.githubusercontent.com/1138628/28714770-3d98d530-7395-11e7-9a4c-278ec5c14ee6.png)

2. Run Build Task

When doing the same with group "Advanced Finance" everything is fine...
![image](https://user-images.githubusercontent.com/1138628/28714733-11d67f92-7395-11e7-9a95-b838834a8740.png)

**Comment by atoader** [comment]
I will investigate and get back to you as soon as we have a resolution.

**Comment by atoader** [comment]
Hi! Sorry for taking so long to get back to you. The crash does not occur anymore, but you will encounter another problem:
![image](https://user-images.githubusercontent.com/3097909/29311055-87999588-81b0-11e7-8377-db395c90ae60.png)

You will get the error that the symbol 'Finance' is ambiguous. This is happening due to the way we are generating the reference packages. We have a slice for solving this problem.
