### ISSUE TITLE
Exception in event with enum as parameter

### ISSUE THREAD

**Issue by stefanoPrimo** [Microsoft/AL#4329]
**Describe the bug**
I'm trying to convert from enum datatype to option using events.
When the event is called the client crashes and return this error:
```
Server instance: DynamicsNAV130
Tenant ID: default
Session type: WebClient
Session ID: 320
User: MyUser
Type: System.ArgumentException
Message: Object of type 'System.Int32' cannot be converted to type 'Microsoft.Dynamics.Nav.Runtime.NavOption'.
StackTrace:    at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147024809
StackTrace:    at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
```

here is where my event is called:
```
Handled := false;
ParseApplytoDocTypeEnumToGenJournalLine(Entry."Document Type", GenJnlLine, Handled);
```

here my Integration Event:
```
[IntegrationEvent(false, false)]
    local procedure ParseApplytoDocTypeEnumToGenJournalLine(EnumDocumentType: Enum "EOS Comp. Document Type"; var GenJournalLine: record "Gen. Journal Line"; var Handled: Boolean)
    begin
    end; 
```

here my event subscriber:
```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"EOS Compensation Mgt.", 'ParseApplytoDocTypeEnumToGenJournalLine', '', true, false)]
    local procedure ParseDocumentTypeEnumToOption(EnumDocumentType: enum "EOS Comp. Document Type";
                                                  var GenJournalLine: Record "Gen. Journal Line";
                                                  var Handled: Boolean)
    begin
        if handled then
            exit;

        case EnumDocumentType of
            EnumDocumentType::None:
                begin
                    GenJournalLine."Applies-to Doc. Type" := GenJournalLine."Applies-to Doc. Type"::" ";
                    Handled := true;
                end;
            EnumDocumentType::Payment:
                begin
                    GenJournalLine."Applies-to Doc. Type" := GenJournalLine."Applies-to Doc. Type"::Payment;
                    Handled := true;
                end;
            EnumDocumentType::Invoice:
                begin
                    GenJournalLine."Applies-to Doc. Type" := GenJournalLine."Applies-to Doc. Type"::Invoice;
                    Handled := true;
                end;
            EnumDocumentType::CreditMemo:
                begin
                    GenJournalLine."Applies-to Doc. Type" := GenJournalLine."Applies-to Doc. Type"::"Credit Memo";
                    Handled := true;
                end;
            EnumDocumentType::FinanceChargeMemo:
                begin
                    GenJournalLine."Applies-to Doc. Type" := GenJournalLine."Applies-to Doc. Type"::"Finance Charge Memo";
                    Handled := true;
                end;
            EnumDocumentType::Reminder:
                begin
                    GenJournalLine."Applies-to Doc. Type" := GenJournalLine."Applies-to Doc. Type"::Reminder;
                    Handled := true;
                end;
            EnumDocumentType::Refund:
                begin
                    GenJournalLine."Applies-to Doc. Type" := GenJournalLine."Applies-to Doc. Type"::Refund;
                    Handled := true;
                end;
        end;
    end;
```

For now, my workaround is to not use the enum datatype as parameter but instead using a record datatype.

**Versions:**

 - AL Langauge: 2.0.43900

 - Business Central: RTM IT

**Comment by atoader** [comment]
Hi @stefanoPrimo ! Can you please try your code on the latest dev-preview? Does the crash still occur?

**Comment by stefanoPrimo** [comment]
Hi,
I've repeated the test in a docker environment with the daily build and it seems that the bug was fixed!
Thanks for the support!
