### ISSUE TITLE
AL Language package installation throws an error

### ISSUE THREAD

**Issue by MarkPost** [Microsoft/AL#4368]
Installing the latest AL Language produces this error
[Error - 4:35:00 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/setActiveWorkspace' failed with error: 'Invalid URI: The format of the URI could not be determined.'
Details:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.PathUtilities.CreateUriFilePath(String filePath) in C:\a\811\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\PathUtilities.cs:line 417
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.CreateProjectInfo(String projectPath, String assemblyName, CompilationOptions options, ParseOptions parseOptions, String packageCachePath, String[] probingFolders, String ruleSetPath) in C:\a\811\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 630
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.SetCurrentProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, List`1& projectLoadingDiagnostics) in C:\a\811\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 139
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TrySetCurrentProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, IList`1& diagnostics, Boolean& missingManifest, Boolean& missingSymbols) in C:\a\811\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 71
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TrySetCurrentProject(SettingsRequest request, CancellationToken cancellationToken) in C:\a\811\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 31
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SetActiveWorkspaceRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in C:\a\811\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SetActiveWorkspaceRequestHandler.cs:line 24
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in C:\a\811\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\811\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by MarkPost** [comment]
Removed all folders and created a new folder and the error is gone
