### ISSUE TITLE
While executing command AL.DOWNLOAD SYMBOL on Visual Studio Code getting error:

### ISSUE THREAD

**Issue by madhukarpuri** [Microsoft/AL#4405]
**While executing command AL.DOWNLOAD SYMBOL on Visual Studio Code getting error:**
[2018-12-27 11:42:28.66] Using reference symbols cache path: c:\Users\puri\Documents\AL\ALProject1\./.alpackages
[Error - 11:42:28 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
Details:
System.TypeLoadException: Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Solution.CompilationTracker.Fork(ProjectState newProject, CompilationTranslationAction translate, Boolean clone, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Solution.ForkProject(ProjectState newProjectState, CompilationTranslationAction translate, Boolean withProjectReferenceChange, ImmutableDictionary`2 newLinkedFilesMap, Boolean forkTracker) in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Solution.cs:line 1815
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Solution.RemoveSymbolReferences(ProjectId projectId, IEnumerable`1 symbolReferences) in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Solution.cs:line 1093
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.FindReferencesToDownload(DownloadSymbolsRequest request, Project project, ImmutableArray`1 allReferences) in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 87
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.<ProcessRequestAsync>d__3.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\512\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**To Reproduce**
Steps and/or AL code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Versions:**

 - AL Langauge: 

 - Business Central:

**Comment by StanislawStempin** [comment]
Could you please fill out the missing parts of the template? How to reproduce the problem and which versions are you using?
