### ISSUE TITLE
Critical Error starting service tier with extension installed including pageextension object

### ISSUE THREAD

**Issue by JakobAaen** [microsoft/AL#4753]
**Description**
Only tested for Business Central CU3 (13.3.27233.0). On-prem issue.
Service tier won't start after restart and no other service tier will start from the same on-prem database. 

An extension has been installed with pageextension to a standard page in the action section. An action has been added to an existing group. When restarting service tier the following error occurs: Metadata error from pageextension with action group not found.

Possible Metadata/symbol error.

**To Reproduce**
Tested on standard BC-onprem installation and reproducable in Docker container.

1. Added extension with pageextension adding action last in standard action group
2. Edit standard object in C/SIDE: adding new action group before extended action group and compile object
2.a. (It is possible to open object)
3. Restart service tier
4. Error occurs: service tier won't start see event log.

It is possible hereafter to revert changes to C/SIDE object (deleting the action group) and service tier will now restart without errors.

**Event Log**
```
TimeGenerated : 20-03-2019 10:35:58
EntryType     : Error
Message       : Server instance: NAV
                Category: Extensions
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: cf192cee-020e-4c83-8386-bec40c74fbb6
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: af87ecdd-3d32-4e55-a609-fd6a0dbfdf30
                EventTime: 03/20/2019 09:35:58
                Message (NavAppObjectMetadataException): RootException: NavAppO
                bjectMetadataException
                An error occurred while applying changes from the 'Extension by Publisher 1.0.0.0' app to the applicati
                on object of type 'PageExtension' with the ID '50100'. The er
                ror was: InvalidOperationException - Metadata delta application
                 failed due to the following error(s): The metadata object Docu
                ments was not found.
                ExceptionStackTrace:
                   at Microsoft.Dynamics.Nav.Apps.MetadataDeltas.RuntimeDeltaAp
                plicationAdapter.HandleException(Exception ex, ApplicationObjec
                tId objectId, DeltaAdapterContext deltaAdapterContext)
                   at Microsoft.Dynamics.Nav.Apps.MetadataDeltas.DeltaApplicati
                onAdapterBase`2.PerformDeltaApplicationWithErrorHandling(Applic
                ationObjectId objectId, TDelta deltas, Action applicationAction
                )
                   at Microsoft.Dynamics.Nav.Apps.MetadataDeltas.DeltaApplicati
                onAdapterBase`2.ApplyDeltas(ApplicationObjectId objectId, Objec
                t subject, IEnumerable`1 deltas, DeltaRuleEnforcer ruleEnforcer
                , PerformanceLog performanceLog)
                   at Microsoft.Dynamics.Nav.Apps.MetadataDeltas.MetadataRuntim
                eDeltaApplicator.ApplyDeltas(ApplicationObjectId objectId, Obje
                ct subject, IEnumerable`1 deltas, PerformanceLog performanceLog
                , IDeltaValidationFilter[] filters)
                   at Microsoft.Dynamics.Nav.Runtime.NCLApplicationObjectExtens
                ion`1.ApplyRuntimeDeltas(TSubject subject, PerformanceLog perfo
                rmanceLog)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.A
                pplyExtensionObjects[T](IEnumerable`1 extensions, T subject)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaForm.LoadMetadata()
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.P
                opulate()
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppG
                roupModifiedObject(NavAppGroup appGroup, NavAppGroupObjectMetad
                ataSummary modifiedSummary)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeModi
                fiedBaseObjects(NavAppGroup appGroup, InitializeAppGroupProfile
                r profiler, IReadOnlyList`1 baseObjectsModifiedBySomething)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppG
                roup(NavAppGroup appGroup)
                CallerStackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppG
                roup(NavAppGroup appGroup)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppG
                roup(NavAppGroup appGroup)
                   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppGroupUpdater.Up
                dateGroupForChangedTenant(NavTenant tenant)
                   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.Initia
                lizeAppsForTenant(NavTenant tenant)
                   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.Initia
                lizeTenant(NavTenant tenant, NavTenantSettings tenantSettings,
                Boolean overwriteTenantIdInDatabase, Boolean verifyDatabaseConn
                ection, Boolean ensureDatabaseExclusiveState)
                   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddTen
                ant(NavTenantMountingParameters mountingParameters)
                   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.MountD
                efaultTenant(String databaseServerName, String databaseName, St
                ring databaseUserName, ProtectedDatabasePassword databasePasswo
                rd, EncryptionProvider encryptionProvider, AzureKeyVaultSetting
                s azureKeyVaultSettings, Boolean verifyServerInstanceKey)
                   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSin
                gleLegacyTenant(String databaseServerName, String databaseName,
                 String databaseUserName, ProtectedDatabasePassword databasePas
                sword, EncryptionProvider encryptionProvider, AzureKeyVaultSett
                ings azureKeyVaultSettings)
                   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.Config
                ureTenants(ServerUserSettings settings, String encryptionKey)
                   at Microsoft.Dynamics.Nav.Runtime.NavTaskFactory.<>c__Displa
                yClass11_0.<StartNewTask>b__0()
                   at System.Threading.Tasks.Task.Execute()
                   at System.Threading.ExecutionContext.RunInternal(ExecutionCo
                ntext executionContext, ContextCallback callback, Object state,
                 Boolean preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext ex
                ecutionContext, ContextCallback callback, Object state, Boolean
                 preserveSyncCtx)
                   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&
                currentTaskSlot)
                   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPrevent
                DoubleExecution)
                   at System.Threading.ExecutionContext.RunInternal(ExecutionCo
                ntext executionContext, ContextCallback callback, Object state,
                 Boolean preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext ex
                ecutionContext, ContextCallback callback, Object state, Boolean
                 preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext ex
                ecutionContext, ContextCallback callback, Object state)
                   at System.Threading.ThreadHelper.ThreadStart(Object obj)


                ProcessId: 6460
                Tag: 000009W
                ThreadId: 12
                CounterInformation:
```

**Comment by qutreson** [comment]
Hi @JakobAaen, can you reproduce it using the latest developer preview and the new Base Application on AL? If yes, please open another issue and reference this one.

Closing now this issue as this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
