### ISSUE TITLE
Error Value Cannot be null.  Parameter name: projectId

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/AL#4797]
Received this error message few times in the last week.  BCoP 13.03

It seems to happen when I sync my local repository to the remote repository (download only no upload in this case).

> [Error - 11:24:28] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
> Processing of message 'workspace/didChangeWatchedFiles' failed with error: 'Value cannot be null.
> Parameter name: projectId'
> Details:
> System.ArgumentNullException: Value cannot be null.
> Parameter name: projectId
>    at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentId.CreateNewId(ProjectId projectId, String debugName) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\DocumentId.cs:line 74
>    at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.TryAddTransientDocument(String filePath, String text, DocumentId& documentId) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:line 175
>    at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeWatchedFilesRequestHandler.HandleAsync(DidChangeWatchedFilesRequest request, Int32 requestId, CancellationToken cancellationToken) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeWatchedFilesRequestHandler.cs:line 36
>    at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59
> 

AL Info:
> Name: AL Language
> Id: ms-dynamics-smb.al
> Description: AL development tools for Dynamics 365 Business Central
> Version: 2.1.109895
> Publisher: Microsoft
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
> 
Azure Repos Info:
> Name: Azure Repos
> Id: ms-vsts.team
> Description: Connect to Azure Repos and work with Git and Team Foundation Version Control (TFVC) repositories. Manage your pull requests, work items, and more.
> Version: 1.149.2
> Publisher: Microsoft
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vsts.team
> 

VS Code Info:
> Version: 1.32.3 (user setup)
> Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
> Date: 2019-03-14T23:43:35.476Z
> Electron: 3.1.6
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

**Comment by GreatScott000** [comment]
The Git Version is: git version 2.20.1.windows.1

**Comment by GreatScott000** [comment]
And if it matters the path to my folder where the changes would be download has spaces and parentheses "()" in it.
