### ISSUE TITLE
Processing of message 'al/createPackage' failed with error: 'Invalid Custom Xml part format'

### ISSUE THREAD

**Issue by MBK75** [microsoft/AL#4799]
I am trying to add a blank line in a repeater on a Word layout for a copy of the standard Purchase Order report.  When I do that and set the row to be a size of .1" with the size set to match Exactly then I get the compiler error below.  When I delete the blank row, the compiler error goes away.

Microsoft (R) AL Compiler version 2.1.1.44361
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'MyProject' containing '6' files at '10:21:29.200'.

Compilation ended at '10:21:29.486'.

[Error - 10:21:29 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Invalid Custom Xml part format'
Details:
```
System.InvalidOperationException: Invalid Custom Xml part format
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.CalculateElementInfo(XElement element, String parentPath) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 84
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.MapElementsToDictionary(Dictionary`2 oldElements, XElement oldXml, String parentPath) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 136
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.MapElementsToDictionary(Dictionary`2 oldElements, XElement oldXml, String parentPath) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 134
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.MapElementsToDictionary(Dictionary`2 oldElements, XElement oldXml, String parentPath) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 134
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.CompareReportMetadata(XElement oldXml, XElement newXml, String customXmlRootName) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 45
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.OfficeCustomXmlPartDiff.GetChangedCustomXmlList(XElement oldXml, XElement newXml, String customXmlRootName, String& xmlNamespace, Boolean& forceCustomXmlUpdate) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\OfficeCustomXmlPartDiff.cs:line 41
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.WordDocumentUpdate.ApplyFieldWordRenames(XDocument oldCustomXmlPart, Stream wordLayoutSource) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\WordDocumentUpdate.cs:line 593
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.WordDocumentUpdate.UpdateWordDocumentLayout(Stream wordLayout, Stream outputStream, XDocument oldXmlPart) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\WordDocumentUpdate.cs:line 166
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportWordUtilities.UpdateWordFile(IFileSystem fileSystem, String docName, String officeCustomXmlPart, String officeCustomXmlPart_Extended) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\ReportWordUtilities.cs:line 51
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.GenerateLayout(DiagnosticBag diagnostics, PropertyKind propertyKind, Action`3 generator, String layoutType) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:line 31
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.Emit(DiagnosticBag diagnostics) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitNonObjectCode(ObjectTypeSymbol containingType, Action`1 emitter) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 236
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 222
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass14_0.<CompileObjectAsTask>b__0() in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 202
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 152
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 162
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 146
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 886
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 861
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 577
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 435
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 313
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__4.MoveNext() in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__10.MoveNext() in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\35\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59
```

**Comment by thpeder** [comment]
Hi @MBK75,
Could you please try if the bug still reproduces on the latest developer preview.

**Comment by RobynGee** [comment]
I am getting the same error with word layout xml with 3.0.126381

[Error - 11:03:57 am] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Invalid Custom Xml part format'
Details:
System.InvalidOperationException: Invalid Custom Xml part format
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.CalculateElementInfo(XElement element, String parentPath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 84
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.MapElementsToDictionary(Dictionary`2 oldElements, XElement oldXml, String parentPath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 136
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.CompareReportMetadata(XElement oldXml, XElement newXml, String customXmlRootName) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 45
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.OfficeCustomXmlPartDiff.GetChangedCustomXmlList(XElement oldXml, XElement newXml, String customXmlRootName, String& xmlNamespace, Boolean& forceCustomXmlUpdate) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\OfficeCustomXmlPartDiff.cs:line 41
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.WordDocumentUpdate.ApplyFieldWordRenames(XDocument oldCustomXmlPart, Stream wordLayoutSource) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\WordDocumentUpdate.cs:line 587
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.WordDocumentUpdate.UpdateWordDocumentLayout(Stream wordLayout, Stream outputStream, XDocument oldXmlPart) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\WordDocumentUpdate.cs:line 163
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportWordUtilities.UpdateWordFile(IFileSystem fileSystem, String docName, String officeCustomXmlPart, String officeCustomXmlPart_Extended) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\ReportWordUtilities.cs:line 52
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.GenerateLayout(DiagnosticBag diagnostics, PropertyKind propertyKind, Action`3 generator, String layoutType) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:line 34
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.Emit(DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:line 26
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitNonObjectCode(ObjectTypeSymbol containingType, Action`1 emitter) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 212
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 198
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass15_0.<CompileObjectAsTask>b__0() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 175
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 151
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 136
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 125
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 827
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 802
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, Compilation analyzerCompilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver, Predicate`1 filterOpt, Predicate`1 radCompilationFilter) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 636
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, Compilation analyzerCompilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 477
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 429
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 330
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

**Comment by thpeder** [comment]
Thanks for giving it a second try.
Could you please provide a small sample project that reproduces the issue to make it easier for me to hunt down the bug.

**Comment by bbrown5962** [comment]
I am encountering this problem in a newer AL version

Microsoft (R) AL Compiler version 3.0.2.21748
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'NightOwl' containing '40' files at '10:4:21.524'.


Compilation ended at '10:4:21.901'.

[Error - 10:04:21 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Invalid Custom Xml part format'

In this case, the customer originally modified the Word layout for Report 1306 and provided that Word layout document for use in creating a custom invoice document. If I use that Word layout document unmodified with my custom dataset, everything compiles fine and I can run the report.

However if a make even a simple change and save the Word document, the compile fails with the above message.  An example of a simple change is to remove 1 letter from a text string in the Word document.

I have attached the following files from my project:

"NightOwl Custom Sales Invoice 1306.docx" - Original Word layout from customer

"REP50000.NightOwl Sales Invoice by Work.NOWL" - Modified Word Layout. The change was to remove the E from INVOICE

"REP50000.NightOwl Sales Invoice by Work.NOWL" - The AL code for the report. This a copy of report 1306 and a work in process.  ignore that it does not print any lines.

[To GitHub.zip](https://github.com/microsoft/AL/files/3497381/To.GitHub.zip)

**Comment by RobynGee** [comment]
Still getting this error with word layouts

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 3.0.168874
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

[Error - 2:02:59 pm] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Invalid Custom Xml part format'
Details:
System.InvalidOperationException: Invalid Custom Xml part format
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.CalculateElementInfo(XElement element, String parentPath) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 84
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.MapElementsToDictionary(Dictionary`2 oldElements, XElement oldXml, String parentPath) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 136
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportChangeMetadataComparer.CompareReportMetadata(XElement oldXml, XElement newXml, String customXmlRootName) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\ReportChangeMetadataComparer.cs:line 45
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.OfficeCustomXmlPartDiff.GetChangedCustomXmlList(XElement oldXml, XElement newXml, String customXmlRootName, String& xmlNamespace, Boolean& forceCustomXmlUpdate) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\OfficeCustomXmlPartDiff.cs:line 41
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.WordDocumentUpdate.ApplyFieldWordRenames(XDocument oldCustomXmlPart, Stream wordLayoutSource) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\WordDocumentUpdate.cs:line 587
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.WordDocumentUpdate.UpdateWordDocumentLayout(Stream wordLayout, Stream outputStream, XDocument oldXmlPart) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\Word\WordDocumentUpdate.cs:line 163
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportWordUtilities.UpdateWordFile(IFileSystem fileSystem, String docName, String officeCustomXmlPart, String officeCustomXmlPart_Extended) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportEmitterUtilities\ReportWordUtilities.cs:line 52
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.GenerateLayout(DiagnosticBag diagnostics, PropertyKind propertyKind, Action`3 generator, String layoutType) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:line 34
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.ReportLayoutsEmitter.Emit(DiagnosticBag diagnostics) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\ReportLayoutsEmitter.cs:line 26
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.EmitNonObjectCode(ObjectTypeSymbol containingType, Action`1 emitter) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 212
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 198
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass15_0.<CompileObjectAsTask>b__0() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 175
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 151
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 136
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 125
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 827
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 802
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver, Predicate`1 filterOpt, Predicate`1 radCompilationFilter) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 639
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 481
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 433
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 330
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\296\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

It compiles to an app file once, then errors on second attempt to package.
App and source code attached.

[Default publisher_WordCompileError_1.0.0.0.zip](https://github.com/microsoft/AL/files/3567714/Default.publisher_WordCompileError_1.0.0.0.zip)

**Comment by qutreson** [comment]
@RobynGee, I was able to reproduce the issue based on the project attached in your latest comment.

**Comment by junecrotty** [comment]
Has anyone found a solution to this?  I have the exact same issue on a modified Purchase Order.

**Comment by RobynGee** [comment]
Using AL 5.0.236243 through to v5.0.311667 the layouts I was having problems compiling are now ok.
What version of AL are you using?

**Comment by junecrotty** [comment]
I am using v5.0.312966
