### ISSUE TITLE
Processing of message 'textDocument/hover' failed with error: 'Position: 3659, FullSpan: (0..0)

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/AL#4816]
**Describe the bug**
I've been working in a container for about a week now. All of a sudden, out of the blue, it's giving me 51 problems and a request to report this on github. I've been getting periodic "oops something went wrong" messages (which is SO unhelpful, and that cuteness in that message is REALLY irritating, I'd rather have a generically cryptic system message). Usually a restart of the container will fix that, but this time when it restarted, I got this error message and the 51 problems in my workspace.

**OUTPUT**
[Error - 5:02:43 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/hover' failed with error: 'Position: 3659, FullSpan: (0..0)
Parameter name: position'
Details:
System.ArgumentOutOfRangeException: Position: 3659, FullSpan: (0..0)
Parameter name: position
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 763
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetTokenAtPositionAsync>d__19.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 360
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<IsPositionNotOnTokenTrivia>d__7.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.HoverRequestHandler.<HandleAsync>d__3.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\HoverRequestHandler.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

**Versions:**
 - AL Langauge: 3.0.115791
 - Business Central: GB Dynamics NAV 13.4 (29517)

**Comment by MarceeMarc** [comment]
Having the same issue as of this morning. 

Versions:

    AL Langauge: 3.0.115791
    Business Central: GB Dynamics NAV 13.4 (28871)

**Comment by larswestman** [comment]
Same here on 3.0.115791 and BCoP
Runtime: 13.0.27183.0
Application: 13.3.27233.0

But I only have this issue on an azure server to wich I clone the repo so my colleagues can do testing. On my local PC with the same AL Language version and runtime version I don't have this issue.

**Comment by TheDenSter** [comment]
In trying to solve this issue, I tried to download symbols and I received this error:
[Error - 7:48:17 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
Details:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]

**Comment by abouraoui** [comment]
Hi there, 

having the same issue, no error were found in the project until this morning
![image](https://user-images.githubusercontent.com/45698976/55489051-34a8a600-55ff-11e9-9ae5-344673667bd4.png)
 the problems I got on my project linked to objects names !!!!!!
![image](https://user-images.githubusercontent.com/45698976/55489140-599d1900-55ff-11e9-920c-723e6de2b40e.png)

**Comment by MarceeMarc** [comment]
This is exactly what I've been experiencing. No problem downloading symbols, no problem referencing standard objects, issues are with bespoke object type references. 

See output below:

[Error - 16:18:17] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/hover' failed with error: 'Position: 1178, FullSpan: (0..0)
Parameter name: position'
Details:
System.ArgumentOutOfRangeException: Position: 1178, FullSpan: (0..0)
Parameter name: position
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 763
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetTokenAtPositionAsync>d__19.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 360
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<IsPositionNotOnTokenTrivia>d__7.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.HoverRequestHandler.<HandleAsync>d__3.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\HoverRequestHandler.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

**Comment by BartPermentier** [comment]
installing https://dotnet.microsoft.com/download/dotnet-framework/net472 did the trick.
If you can't install it then use the vsix from the cd.

**Comment by TheDenSter** [comment]
Installed .net framework, created a new container based on the same image. Had to change the target runtime to 2.4 and my app deployed to the new container. Went back to the original container, and now I have 'an internal error has occurred' issue. Changing the schemaupdatemode to recreate also did not do the trick.

**Comment by TheDenSter** [comment]
refreshed my image (weird that the image has the same version as last week, I would ave expected a igher number), re-installed navcontainerhelper, re-created my container, installed the vsix from the container (2.1.106652) and still 'internal error'. Nothing in the problems window.

I am dead in the water again, no idea what to do about this.

**Comment by abouraoui** [comment]
installing https://dotnet.microsoft.com/download/dotnet-framework/net472 fixed my problem.
Thank you.

**Comment by TheDenSter** [comment]
Got a step further. Removed all my containers, removed all my images, re-pulled the GB image, re-created my container and now I am able to publish my app. Haven't tested it yet but at least it published the app itself.

**Comment by larswestman** [comment]
> refreshed my image (weird that the image has the same version as last week, I would have expected a higher number), re-installed navcontainerhelper, re-created my container, installed the vsix from the container (2.1.106652) and still 'internal error'. Nothing in the problems window.
> 
> I am dead in the water again, no idea what to do about this.

Do you use -alwaysPull when pulling images? Otherwise you are not guaranteed to get the latest version . I guess there's some caching going on in Docker.

**Comment by TheDenSter** [comment]
I don't use that switch, but I did pull the image yesterday and I was very annoyed that it did not seem to get the latest version until after I removed the image first. I've been getting a lot of problems with containers that stop working lately and it is irritating to lose this much time that my customers are not really happy about paying.

**Comment by larswestman** [comment]
I don't trust Docker for my daily work. It's been to much problems with thing suddenly not working because of update x or z or y. I use Docker for testing apps on different version/localizations.

**Comment by TheDenSter** [comment]
I've gotten rid of this container so the issue kind of stopped being an issue. It is frustrating to have these sudden issues with local sandbox containers. As the project is progressing there is more data to set up and recreating new containers is becoming more of a pain in the neck. I don't really like how an existing container can be affected this much by an update to the image or the AL language. I've seen a tweet float by that it is possible to have multiple sandboxes in multiple versions at the same time, I hope that this is also going to be possible for local sandbox containers. I can't afford to be dead in the water for days every time this happens

**Comment by MarceeMarc** [comment]
Getting rid of the container did it for me also. New one is fine. Also installed dotnet 4.2, but didn't immediatley solve the problem. Thanks for all the help on this one!
