### ISSUE TITLE
Create Package Error: 'al/createPackage' failed with error: 'Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.SystemOptionTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.OptionTypeSymbol'.'

### ISSUE THREAD

**Issue by JohnnyUndercover** [Microsoft/AL#482]
I don't know if i did anything wrong, but i got the following error on creating the package of my extension with F5 (with F6 also):

```
[Error - 2:30:04 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.SystemOptionTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.OptionTypeSymbol'.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.TryGetOptionMembers(TypeSymbol type) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:line 575
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.<>c.<ConvertMethods>b__22_3(ParameterSymbol p) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:line 472
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.<>c.<ConvertMethods>b__22_2(MethodSymbol method) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:line 464
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ConvertMethods(ApplicationObjectTypeSymbol applicationObject) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:line 457
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ConvertPages(IEnumerable`1 pages) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:line 316
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ConvertModuleToSerializableSymbolModel(IModuleSymbol module) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:line 24
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageModuleOutputter.FinalizeModule() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageModuleOutputter.cs:line 281
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.WriteToOutput(ModuleOutputter outputter, ModuleBuilder moduleBuilder, ModuleSymbol compiledModuleSymbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 764
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 443
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 299
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<InternalHandleAsynch>d__1.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsynch>d__1.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\GenericRequestHandlerBase.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__5.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 60
```

**Comment by thpeder** [comment]
You haven't done anything wrong.
It is a bug in the compiler that means you can't specify a system defined option type in procedure parameters.

Thanks for reporting it.
