### ISSUE TITLE
error: Cannot add part for the specified URI because it is already in the package.

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#484]
Microsoft (R) AL Compiler version 0.7.11459
Copyright (C) Microsoft Corporation. All rights reserved

[Error - 10:45:12 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Cannot add part for the specified URI because it is already in the package.'
StackTrace:
   at System.IO.Packaging.Package.CreatePart(Uri partUri, String contentType, CompressionOption compressionOption)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageWriter.WriteStream(Stream stream, String path) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageWriter.cs:line 113
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageModuleOutputter.WriteFile(String filePath, String packagePath) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageModuleOutputter.cs:line 363
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageModuleOutputter.WriteMedia() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageModuleOutputter.cs:line 349
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.WriteToOutput(ModuleOutputter outputter, ModuleBuilder moduleBuilder, ModuleSymbol compiledModuleSymbol) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 764
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 443
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 299
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<InternalHandleAsynch>d__1.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsynch>d__1.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\GenericRequestHandlerBase.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__5.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 60

The error is thrown if same screenshot is specified multiple times - extract from app.json:
  "screenshots": [
    "./Resources/Images/Logo.jpg",
    "./Resources/Images/Logo.jpg"
  ],

**Comment by dennisfrostlander** [comment]
Thanks for finding the root cause.
