### ISSUE TITLE
Could not download reference symbols for multitenant

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#485]
When developing in multitenant environment it's impossible to download symbols:
VSCode information:
[2017-08-09 10:57:06.61] Using reference symbols cache path: c:\Users\<username>\Documents\AL\ALProject8\packages
[2017-08-09 10:57:06.62] Downloading from http://localhost:7049/navision_main/dev/packages?publisher=Microsoft&appName=US&versionText=10.0.0.0 ... Error (Unauthorized)
[2017-08-09 10:57:06.62] Downloading from http://localhost:7049/navision_main/dev/packages?publisher=Microsoft&appName=System&versionText=10.0.0.0 ... Error (Unauthorized)
[2017-08-09 10:57:06.62] Could not download reference symbols

Event viewer information:
Server instance: Navision_main
Tenant ID: 
<ii>User: <username>
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavTenantNotFoundException
SuppressMessage: False
DiagnosticsSuppress: False
SuppressExceptionCreatedEvent: False
FatalityScope: None
Message: <ii>A tenant was not specified, but is needed because the system has multiple tenants. Contact your system administrator.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.get_DefaultTenant()
     at Microsoft.Dynamics.Nav.Service.ServiceAuthenticationHelper.AuthenticateForServiceCallCore(Func`1 getNavTenant, Func`1 getRequestProperties, Func`1 getWindowsIdentity, Func`3 createException)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
</ii>

**Comment by dennisfrostlander** [comment]
This is a bug, the &tenant= parameter is missing from the URL.
