### ISSUE TITLE
Error when installing AL Extension

### ISSUE THREAD

**Issue by CBlasek** [Microsoft/AL#4858]
**Describe the bug**
Error when installing AL Extension in VS Code

[Error - 8:32:23 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'workspace/didChangeConfiguration' failed with error: 'The network path was not found.

Details:
```
System.IO.IOException: The network path was not found.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.AddDocumentsFromPath(String rootPath) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 192
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.SetCurrentProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, List`1& projectLoadingDiagnostics) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 144
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TrySetCurrentProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, IList`1& diagnostics, Boolean& missingManifest, Boolean& missingSymbols) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 75
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TrySetCurrentProject(SettingsRequest request, CancellationToken cancellationToken) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 36
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeConfigurationRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeConfigurationRequestHandler.cs:line 69
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64
```

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
Download VS Code March Release
Install AL Extension from Marketplace

**Versions:**

 - AL Langauge:  

Version: 3.0.115791

**Comment by thpeder** [comment]
Hi @CBlasek,
When the extension starts up it reads all the al source code files from disk, and it looks like it failed at that.
Are these files stored on a network share?
Did you remove some of the files while it was loading them?

I'm marking this as a bug since we should handle the IO exception.

**Comment by PooyaKharamesh** [comment]
closing this issue since the fix is applied and will be part of the upcoming release.

/Pooya
