### ISSUE TITLE
Getting Error : System.AggregateException: One or more errors occurred. - when trying to rename Object refrence

### ISSUE THREAD

**Issue by rishiaurrishabh** [Microsoft/AL#4859]
I am trying to rename table object name by providing prefix at the beginning using F2 so that it also updates the references. but after 2-3 objects may be because of long error list VS Code gets stuck and continues to run progress bar on top once I press Enter.

![image](https://user-images.githubusercontent.com/39942971/55701968-a9f6eb00-59f2-11e9-893f-87b165b8eab6.png)

Error Log on output : 

Processing of message 'codeLens/resolve' failed with error: 'One or more errors occurred.'
Details:
```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.GetRelatedTableSymbol(ISymbol symbol) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:line 865
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetTableExpressionContextForLinkFields(PropertyValueSyntax propertyValue, DiagnosticBag diagnostics, BoundBadPropertyValue& boundBadPropertyValue) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1842
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.TryGetTableExpressionContext(PropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics, BoundBadPropertyValue& boundBadPropertyValue) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1763
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.TryGetExpressionContext(PropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics, BoundBadPropertyValue& boundBadPropertyValue) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1863
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindTableFilterStatement(TableFilterPropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1541
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetBoundPropertyValue(PropertySyntax syntax, DiagnosticBag diagnostics, PropertyValueSyntax propertyValue, PropertyTypeInfo info) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 173
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindProperty(PropertySyntax syntax, DiagnosticBag diagnostics) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 69
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.LazyGetProperty() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 173
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.get_Property() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 111
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertySemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\PropertySemanticModel.cs:line 172
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxTreeSemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SyntaxTreeSemanticModel.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 564
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 403
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.FindReferenceCache.<>c__DisplayClass3_0.<GetSymbolInfo>b__0(SyntaxNode n) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\FindReferenceCache.cs:line 37
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.FindReferenceCache.GetSymbolInfo(SemanticModel model, SyntaxNode node, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\FindReferenceCache.cs:line 37
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.<>c__DisplayClass12_0.<GetStandardSymbolsNodeMatchFunction>b__0(SyntaxNode node, SemanticModel model) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 132
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.<FindReferencesInTokensAsync>d__13.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.<FindReferencesInDocumentUsingIdentifierAsync>d__10.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessDocumentAsync>d__14.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessDocumentAsync>d__14.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessDocumentQueueAsync>d__13.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessDocumentQueueAsync>d__13.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessProjectAsync>d__25.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessProjectAsync>d__24.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessProjectAsync>d__23.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessProjectsAsync>d__22.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessAsync>d__9.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.SymbolFinder.<FindReferencesAsync>d__9.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\SymbolFinder_References.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.SymbolFinder.<FindReferencesAsync>d__7.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\SymbolFinder_References.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesService.<FindReferencedSymbolsInternalAsync>d__1.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesService.cs:line 46
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesService.FindReferencedSymbolsAsync(Document document, Int32 position, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesService.cs:line 25
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensResolveRequestHandler.<HandleAsync>d__3.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensResolveRequestHandler.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.GetRelatedTableSymbol(ISymbol symbol) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:line 865
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetTableExpressionContextForLinkFields(PropertyValueSyntax propertyValue, DiagnosticBag diagnostics, BoundBadPropertyValue& boundBadPropertyValue) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1842
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.TryGetTableExpressionContext(PropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics, BoundBadPropertyValue& boundBadPropertyValue) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1763
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.TryGetExpressionContext(PropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics, BoundBadPropertyValue& boundBadPropertyValue) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1863
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindTableFilterStatement(TableFilterPropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1541
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetBoundPropertyValue(PropertySyntax syntax, DiagnosticBag diagnostics, PropertyValueSyntax propertyValue, PropertyTypeInfo info) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 173
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindProperty(PropertySyntax syntax, DiagnosticBag diagnostics) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 69
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.LazyGetProperty() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 173
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.get_Property() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 111
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertySemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\PropertySemanticModel.cs:line 172
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxTreeSemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SyntaxTreeSemanticModel.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 564
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 403
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.FindReferenceCache.<>c__DisplayClass3_0.<GetSymbolInfo>b__0(SyntaxNode n) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\FindReferenceCache.cs:line 37
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.FindReferenceCache.GetSymbolInfo(SemanticModel model, SyntaxNode node, CancellationToken cancellationToken) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\FindReferenceCache.cs:line 37
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.<>c__DisplayClass12_0.<GetStandardSymbolsNodeMatchFunction>b__0(SyntaxNode node, SemanticModel model) in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 132
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.<FindReferencesInTokensAsync>d__13.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.<FindReferencesInDocumentUsingIdentifierAsync>d__10.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessDocumentAsync>d__14.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessDocumentAsync>d__14.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessDocumentQueueAsync>d__13.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessDocumentQueueAsync>d__13.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessProjectAsync>d__25.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessProjectAsync>d__24.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessProjectAsync>d__23.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessProjectsAsync>d__22.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<ProcessAsync>d__9.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.<FindReferencesAsync>d__8.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.SymbolFinder.<FindReferencesAsync>d__9.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\SymbolFinder_References.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.SymbolFinder.<FindReferencesAsync>d__7.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\SymbolFinder_References.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesService.<FindReferencedSymbolsInternalAsync>d__1.MoveNext() in F:\a\8\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesService.cs:line 46<---
```

**Comment by thpeder** [comment]
Hi @rishiaurrishabh,
Thanks for reporting the issue.
We believe that we saw and fixed the same issue last week.

**Comment by rishiaurrishabh** [comment]
Hi @thpeder ,
Thanks for the information.
I am using the latest update on Visual studio code and Vsix as AL Extension for Business Central from April release.
will this update be shipped in future release, if yes then request you to please help us with a workaround for now.

Thanks.

**Comment by rishiaurrishabh** [comment]
Hi @thpeder ,

I think I have found the reason for the issue, once I comment my xmlport(all lines) this error goes out and I see all the NAV developer friendly errors :)
