### ISSUE TITLE
Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list

### ISSUE THREAD

**Issue by ivansarac** [Microsoft/AL#4897]
**Describe the bug**
AL server in Visual Studio Code crashes when code analysis is turned on. Looks like duplicate of #4628.

`Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.Contract.ProtocolDiagnostic..ctor(Diagnostic diagnostic) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\LanguageServerContract\ProtocolDiagnostic.cs:line 34
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.CreateProtocolDiagnostic(Diagnostic d, Int32& combinedHashCode) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 374
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.AddDiagnosticsFromSyntaxTreeToBuilder(ImmutableArray`1 diagnostics, Int32& combinedHashCode, ArrayBuilder`1 builder, SyntaxTree syntaxTree) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 337
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<CreateDiagnosticResponse>d__7.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<>c__DisplayClass1_1.<<GetDiagnostics>b__0>d.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 08:41:54] Connection to server got closed. Server will restart.

Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.Contract.ProtocolDiagnostic..ctor(Diagnostic diagnostic) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\LanguageServerContract\ProtocolDiagnostic.cs:line 34
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.CreateProtocolDiagnostic(Diagnostic d, Int32& combinedHashCode) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 374
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.AddDiagnosticsFromSyntaxTreeToBuilder(ImmutableArray`1 diagnostics, Int32& combinedHashCode, ArrayBuilder`1 builder, SyntaxTree syntaxTree) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 337
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<CreateDiagnosticResponse>d__7.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<>c__DisplayClass1_1.<<GetDiagnostics>b__0>d.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 08:42:05] Connection to server got closed. Server will restart.

Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.Contract.ProtocolDiagnostic..ctor(Diagnostic diagnostic) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\LanguageServerContract\ProtocolDiagnostic.cs:line 34
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.CreateProtocolDiagnostic(Diagnostic d, Int32& combinedHashCode) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 374
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.AddDiagnosticsFromSyntaxTreeToBuilder(ImmutableArray`1 diagnostics, Int32& combinedHashCode, ArrayBuilder`1 builder, SyntaxTree syntaxTree) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 337
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<CreateDiagnosticResponse>d__7.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<>c__DisplayClass1_1.<<GetDiagnostics>b__0>d.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 08:42:14] Connection to server got closed. Server will restart.

Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.Contract.ProtocolDiagnostic..ctor(Diagnostic diagnostic) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\LanguageServerContract\ProtocolDiagnostic.cs:line 34
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.CreateProtocolDiagnostic(Diagnostic d, Int32& combinedHashCode) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 374
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.AddDiagnosticsFromSyntaxTreeToBuilder(ImmutableArray`1 diagnostics, Int32& combinedHashCode, ArrayBuilder`1 builder, SyntaxTree syntaxTree) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 337
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<CreateDiagnosticResponse>d__7.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<>c__DisplayClass1_1.<<GetDiagnostics>b__0>d.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 08:42:23] Connection to server got closed. Server will restart.

Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.Contract.ProtocolDiagnostic..ctor(Diagnostic diagnostic) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\LanguageServerContract\ProtocolDiagnostic.cs:line 34
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.CreateProtocolDiagnostic(Diagnostic d, Int32& combinedHashCode) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 374
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.AddDiagnosticsFromSyntaxTreeToBuilder(ImmutableArray`1 diagnostics, Int32& combinedHashCode, ArrayBuilder`1 builder, SyntaxTree syntaxTree) in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 337
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<CreateDiagnosticResponse>d__7.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<>c__DisplayClass1_1.<<GetDiagnostics>b__0>d.MoveNext() in F:\a\185\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Error - 08:42:32] Connection to server got closed. Server will not be restarted.`

**To Reproduce**
Steps and to reproduce the behavior:
1. set "al.enableCodeAnalysis": true

**Expected behavior**
AL server does not crash.

**Versions:**

 - AL Language: 3.0.115791

 - Business Central: 14.0.29530.0

**Comment by hemisphera** [comment]
Same here. It looks like it depends on something in the sources. But I was not yet able to make out what exactly causes AL to crash. On some projects it does, on some it does not.

I have just updated my ALC to 3.0.118998 prior to testing it with the official ALC that comes with BC14 OnPrem as well as with the one currently on the VSCode Marketplace. None of them seem to resolve it.

**Comment by hemisphera** [comment]
@qutreson : I can confirm that this problem has been resolved. Thank you very much for the quick response.

**Comment by ivansarac** [comment]
Yes, it is working now, thank you!
