### ISSUE TITLE
I got an error message 'This request operation sent to net.tcp://localhost:7045/NAV/HealthService did not receive a reply within the configured timeout (00:01:00).  ...'

### ISSUE THREAD

**Issue by monchangg** [microsoft/AL#4995]
Hi All,
I downloaded Business Central's Spring Release 19 and run it on docker container. But when I debug AL code, it always freezes debugger. And then I executed 'Get-NavContainerEventLog' command and got following error. I guess this error maybe caused me to be unable to debug code. Does any one know how to resolve this error? I'll very appreciated if any one can help me to resolve it.

AL version: 3.0.126610
Business Central Version: 14.0.29537.31808

The description for Event ID 0 from source MicrosoftDynamicsNAVClientWebClient cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Error accessing Website 
Type: System.TimeoutException
Message: This request operation sent to net.tcp://localhost:7045/NAV/HealthService did not receive a reply within the configured timeout (00:01:00).  The time allotted to this operation may have been a portion of a longer timeout.  This may be because the service is still processing the operation or because the service was unable to send a reply message.  Please consider increasing the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client.
StackTrace:

Server stack trace: 
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Dynamics.Nav.Types.IHealthService.IsSystemHealthy()
   at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult,TChannel](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`3 operationWithContext, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\platform\client\web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 302
Source: mscorlib

**Comment by shashiBssi** [comment]
got the same errors

**Comment by shashiBssi** [comment]
try to create your container with -additionalParameters @('--cpu-count 4')


https://freddysblog.com/2019/06/03/debugging-hangs-in-business-central-spring-2019-rtm-and-cu1/

(with a different workaround as well)

**Comment by atoader** [comment]
Hi @monchangg ! Did the solution provided by Freddy work for you? Are you still facing this issue?

**Comment by monchangg** [comment]
@shashiBssi @atoader  Thank you very much. That can resolve my issue.
