### ISSUE TITLE
System.AggregateException with pagecustomization

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/AL#5013]
**Describe the bug**
I createtd a new pagecustomization and got the following error.

```
pagecustomization "WMS Whse. Pick Sub." customizes "Whse. Pick Subform"
{
    layout
    {
        modify("Action Type")
        {
            Visible = true;
        }
        modify("Lot No.")
        {
            Visible = true;
        }
        modify("Zone Code")
        {
            Visible = true;
        }
        modify("Bin Code")
        {
            Visible = true;
        }
    }
}
```

```
error AL0999: Internal error: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.InvalidCastException: Das Objekt des Typs "Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePageCustomizationTypeSymbol" kann nicht in Typ "Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.PageExtensionTypeSymbol" umgewandelt werden.
   bei System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.<QueryAllActions>d__73.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:Zeile 1063.
   bei System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.InternalCheckTriggerEventElementArgument(SourceMethodOrTriggerSymbol methodSymbol, TriggerEventTypeInfo triggerEvent, AttributeArgumentSymbol eventNameArg, AttributeArgumentSymbol elementNameArg, IApplicationObjectTypeSymbol publisherApplicationObject, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 297.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.InternalCheckTriggerEvent(SourceMethodOrTriggerSymbol triggerSymbol, TriggerEventTypeInfo triggerEvent, AttributeArgumentSymbol eventNameArg, AttributeArgumentSymbol elementNameArg, ImmutableArray`1 subscriberParameters, IApplicationObjectTypeSymbol publisherApplicationObject, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 210.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.CheckEventAttribute(AttributeSymbol attribute, SourceMethodOrTriggerSymbol methodSymbol, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 96.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.CheckAttribute() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 293.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 258.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceMethodOrTriggerSymbol.ForceCompleteAttributes(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 358.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceMethodOrTriggerSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 296.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceMembersCompleteAndCheckUniqueness(SourceLocation locationOpt, DiagnosticBag diagnostics, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 171.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceCompleteMembers(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 768.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 734.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceCodeunitTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceCodeunitTypeSymbol.cs:Zeile 52.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:Zeile 209.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:Zeile 180.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:Zeile 109.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:Zeile 889.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:Zeile 583.
---> (Interne Ausnahme #0) System.InvalidCastException: Das Objekt des Typs "Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePageCustomizationTypeSymbol" kann nicht in Typ "Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.PageExtensionTypeSymbol" umgewandelt werden.
   bei System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.<QueryAllActions>d__73.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:Zeile 1063.
   bei System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.InternalCheckTriggerEventElementArgument(SourceMethodOrTriggerSymbol methodSymbol, TriggerEventTypeInfo triggerEvent, AttributeArgumentSymbol eventNameArg, AttributeArgumentSymbol elementNameArg, IApplicationObjectTypeSymbol publisherApplicationObject, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 297.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.InternalCheckTriggerEvent(SourceMethodOrTriggerSymbol triggerSymbol, TriggerEventTypeInfo triggerEvent, AttributeArgumentSymbol eventNameArg, AttributeArgumentSymbol elementNameArg, ImmutableArray`1 subscriberParameters, IApplicationObjectTypeSymbol publisherApplicationObject, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 210.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.CheckEventAttribute(AttributeSymbol attribute, SourceMethodOrTriggerSymbol methodSymbol, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 96.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.CheckAttribute() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 293.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 258.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceMethodOrTriggerSymbol.ForceCompleteAttributes(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 358.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceMethodOrTriggerSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 296.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceMembersCompleteAndCheckUniqueness(SourceLocation locationOpt, DiagnosticBag diagnostics, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 171.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceCompleteMembers(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 768.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 734.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceCodeunitTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceCodeunitTypeSymbol.cs:Zeile 52.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:Zeile 209.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:Zeile 180.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Interne Ausnahme #1) System.InvalidCastException: Das Objekt des Typs "Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePageCustomizationTypeSymbol" kann nicht in Typ "Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.PageExtensionTypeSymbol" umgewandelt werden.
   bei System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   bei Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.<QueryAllControls>d__75.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:Zeile 1114.
   bei System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.InternalCheckTriggerEventElementArgument(SourceMethodOrTriggerSymbol methodSymbol, TriggerEventTypeInfo triggerEvent, AttributeArgumentSymbol eventNameArg, AttributeArgumentSymbol elementNameArg, IApplicationObjectTypeSymbol publisherApplicationObject, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 310.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.InternalCheckTriggerEvent(SourceMethodOrTriggerSymbol triggerSymbol, TriggerEventTypeInfo triggerEvent, AttributeArgumentSymbol eventNameArg, AttributeArgumentSymbol elementNameArg, ImmutableArray`1 subscriberParameters, IApplicationObjectTypeSymbol publisherApplicationObject, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 210.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EventSubscriberAttributeValidator.CheckEventAttribute(AttributeSymbol attribute, SourceMethodOrTriggerSymbol methodSymbol, DiagnosticBag diagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\AttributeValidators\EventSubscriberAttributeValidator.cs:Zeile 96.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.CheckAttribute() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 293.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceAttributeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceAttributeSymbol.cs:Zeile 258.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceMethodOrTriggerSymbol.ForceCompleteAttributes(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 358.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceMethodOrTriggerSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceMethodOrTriggerSymbol.cs:Zeile 296.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceMembersCompleteAndCheckUniqueness(SourceLocation locationOpt, DiagnosticBag diagnostics, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 171.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceCompleteMembers(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 768.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:Zeile 734.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceCodeunitTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceCodeunitTypeSymbol.cs:Zeile 52.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:Zeile 209.
   bei Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:Zeile 180.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
```

The following pagecustomization can be created without an error.

```
pagecustomization "PB365 WMS Whse. Put-Away Sub." customizes "Whse. Put-away Subform"
{
    layout
    {
        modify("Action Type")
        {
            Visible = true;
        }
        modify("Lot No.")
        {
            Visible = true;
        }
        modify("Zone Code")
        {
            Visible = true;
        }
        modify("Bin Code")
        {
            Visible = true;
        }
    }
}
```

**Versions:**
 - AL Language:  3.0.126610

**Comment by qutreson** [comment]
Hi @FSchneiderYav, I tried creating an extension with the page customization code above, but I couldn't reproduce your issue. 

Looking at the stack trace, the error you are experiencing seems to be related to an event subscriber that is being validated.

Do you have any event subscriber subscribing to one of the events of the page "Whse. Pick Subform" ? My guess is that the combination of the two is causing the issue.

**Comment by qutreson** [comment]
I could reproduce a similar stack trace by triggering intellisense at the position ^ in the code below:

```
pagecustomization "WMS Whse. Pick Sub." customizes "Whse. Pick Subform"
{
}

codeunit 50120 MyCodeunit
{
    [EventSubscriber(ObjectType::Page, Page::"Whse. Pick Subform", 'OnOpenPageEvent', , true, true)]
    local procedure MyProcedure()
    begin
    end;
}
```

Stack trace:
```
Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePageCustomizationTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.PageExtensionTypeSymbol'.'
Details:
System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePageCustomizationTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.PageExtensionTypeSymbol'.
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.<QueryAllActions>d__73.MoveNext() in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:line 1060
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.EventSubscriberArgumentRecommender.ShouldFilterByActions(MemberSyntaxContext syntaxContext, PageTypeSymbol page, AttributeSymbol eventSubscriber) in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\TextRecommenders\EventSubscriberArgumentRecommender.cs:line 323
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.EventSubscriberArgumentRecommender.<RecommendTextAsync>d__3.MoveNext() in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\TextRecommenders\EventSubscriberArgumentRecommender.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.TextCompletionProvider.<ProvideCompletionsAsync>d__1.MoveNext() in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\TextCompletionProvider.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetContextAsync>d__24.MoveNext() in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 371
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__17.MoveNext() in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.<HandleAsync>d__4.MoveNext() in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\git\Platform-ModernDev\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64
```

**Comment by eivindgiske** [comment]
I did review #5013 before posting #5055. Not sure if it's the same issued as 5055. In 5055, if you remove the event subscriber, it will compile. So it's not the PagCust-object itself. It's the combination with Event Sub and PagCust. @thloke Will you review this?

**Comment by thloke** [comment]
@eivindgiske - Yes, the root cause for #5013 and #5055 is the same, and as you mention, require both a `PageCustomization` and a `EventSubscriber` that references the customized page. I am preparing a fix for both these issues, so it should be available in the near future.

Until the fix gets deployed, one workaround would be to use a `PageExtension` instead of a `PageCustomization` if this is applicable for your business case.

**Comment by dkip05** [comment]
Has this issue been fixed?
