### ISSUE TITLE
AL:GO! Creates Folder but returns error - Can not resolve workspace folder

### ISSUE THREAD

**Issue by DigiTecKid** [microsoft/AL#5052]
AL:Go! asks for the folder, creates the folder and HelloWorld project files (except the launch.json), then in the EXPLORER shows a slash over the folder icon with an error saying : "Can not resolve workspace folder", it also returns multiple errors in the PROLEMS tab below, it asks for the server then completes
I've tried this running VSC as administrator and not.

**To Reproduce**
Steps and to reproduce the behavior:
1. Press SHIFT-CTRL-P
2. Enter or Select:  AL: GO!
3. Enter a folder name
4. Enter a server

**Expected behavior**
As soon as you enter the requested folder name the PROBLEMS tab starts filling in with:
```
[Error - 3:21:34 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'workspace/didChangeConfiguration' failed with error: 'Invalid URI: The format of the URI could not be determined.'
Details:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.PathUtilities.CreateUriFilePath(String filePath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\PathUtilities.cs:line 394
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.CreateProjectInfo(String projectPath, String assemblyName, CompilationOptions options, ParseOptions parseOptions, String packageCachePath, String[] probingFolders, String ruleSetPath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 648
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.SetCurrentProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, List`1& projectLoadingDiagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 137
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TrySetCurrentProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, IList`1& diagnostics, Boolean& missingManifest, Boolean& missingSymbols) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 74
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TrySetCurrentProject(SettingsRequest request, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 36
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeConfigurationRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeConfigurationRequestHandler.cs:line 69
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

[Error - 3:21:34 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/setActiveWorkspace' failed with error: 'Invalid URI: The format of the URI could not be determined.'
Details:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.PathUtilities.CreateUriFilePath(String filePath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\PathUtilities.cs:line 394
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.CreateProjectInfo(String projectPath, String assemblyName, CompilationOptions options, ParseOptions parseOptions, String packageCachePath, String[] probingFolders, String ruleSetPath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 648
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.SetCurrentProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, List`1& projectLoadingDiagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 137
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TrySetCurrentProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, IList`1& diagnostics, Boolean& missingManifest, Boolean& missingSymbols) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 74
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TrySetCurrentProject(SettingsRequest request, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 36
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SetActiveWorkspaceRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SetActiveWorkspaceRequestHandler.cs:line 24
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

[Error - 3:21:40 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/setActiveWorkspace' failed with error: 'Invalid URI: The format of the URI could not be determined.'
Details:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.PathUtilities.CreateUriFilePath(String filePath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\PathUtilities.cs:line 394
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.CreateProjectInfo(String projectPath, String assemblyName, CompilationOptions options, ParseOptions parseOptions, String packageCachePath, String[] probingFolders, String ruleSetPath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 648
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.SetCurrentProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, List`1& projectLoadingDiagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 137
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TrySetCurrentProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, IList`1& diagnostics, Boolean& missingManifest, Boolean& missingSymbols) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 74
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TrySetCurrentProject(SettingsRequest request, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 36
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SetActiveWorkspaceRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SetActiveWorkspaceRequestHandler.cs:line 24
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

[Error - 3:21:41 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/setActiveWorkspace' failed with error: 'Invalid URI: The format of the URI could not be determined.'
Details:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.PathUtilities.CreateUriFilePath(String filePath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\PathUtilities.cs:line 394
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.CreateProjectInfo(String projectPath, String assemblyName, CompilationOptions options, ParseOptions parseOptions, String packageCachePath, String[] probingFolders, String ruleSetPath) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 648
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.SetCurrentProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, List`1& projectLoadingDiagnostics) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 137
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TrySetCurrentProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, IList`1& diagnostics, Boolean& missingManifest, Boolean& missingSymbols) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 74
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TrySetCurrentProject(SettingsRequest request, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 36
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SetActiveWorkspaceRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SetActiveWorkspaceRequestHandler.cs:line 24
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64
```

**Screenshots**
![image](https://user-images.githubusercontent.com/38542883/59128092-192b8580-8937-11e9-9dee-3bf424e0aa0c.png)

**Versions:**
- Visual Studio Code:
Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

 - AL Language: 3.0.126610

 - Business Central: 14.0.29537.0

**Comment by thpeder** [comment]
Hi @DigiTecKid, 
We have seen this issue before but weren't able to successfully reproduce it.
Is this still an issue for you?

**Comment by DigiTecKid** [comment]
Same error, New Version:

Version: 1.39.1 (user setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by DigiTecKid** [comment]
Just an FYI.  The error happens even before I specify the server...
![image](https://user-images.githubusercontent.com/38542883/66856526-66f27300-ef53-11e9-8de1-e5a029e68c3d.png)

**Comment by thpeder** [comment]
When you use AL:Go does the the path starts with \Users\... and if so could you try prefix with the system drive letter so it becomes something like C:\Users\....

**Comment by DigiTecKid** [comment]
I used C:\temp\algo (making sure to give "Everyone" full permissions to the folder) and it's the same error:
![image](https://user-images.githubusercontent.com/38542883/67407877-25cb1600-f586-11e9-9438-70e4ca35f884.png)

**Comment by kalberes** [comment]
Can you please tell us what is teh version of the AL extension you are using?

**Comment by DigiTecKid** [comment]
I had an old version of the Microsoft AL Language installed along with the newest:
AL Language 0.12.28462
was installed along with 
AL Language 4.0.191880

Once I removed the VSC extension AL Language 0.12.28462 The AL:Go! function created the folders correctly and tried to connect to BC to get symbols.

**Comment by atoader** [comment]
Thank you for verifying! I will close this issue as it appears it has been fixed.
