### ISSUE TITLE
'al/downloadSymbols' failed with error

### ISSUE THREAD

**Issue by mikestrat58** [microsoft/AL#5065]
**Describe the bug**
Error 1...

[Error - 1:37:35 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
Details:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

Errors 2...app.json

{
	"resource": "/c:/Users/mdejager/Documents/AL/HipgnosisIV/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AL1045",
	"severity": 8,
	"message": "The package cache c:\\Users\\mdejager\\Documents\\AL\\HipgnosisIV\\./.alpackages could not be found.",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

Error 3...HelloWorld.al 
{
	"resource": "/c:/Users/mdejager/Documents/AL/HipgnosisIV/HelloWorld.al",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AL0999",
	"severity": 8,
	"message": "Internal error: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

 
**To Reproduce**
Steps and to reproduce the behavior:
1. Select > Ctrl + Shift + P 
2. Select AL> GO
3. Define a new folder
4. Select > Sandbox
 Error appears - new "Hello" world page extension appears

**Expected behavior**
Create a Extension Environment connected to customers Sandbox Environment
**Screenshots**

**Versions:**

 - AL Language: version 3.0.126610

 - Business Central: version 14

**Comment by mikestrat58** [comment]
Screenshot...

**Comment by thloke** [comment]
Hi @mikestrat58,

This occurs because you do not have the .net 4.7.2 framework installed. In the future, we may package the redaistributbles with the extension so it isn't a dependency, but for now it is required.

You can get the framework here: https://dotnet.microsoft.com/download/dotnet-framework/net472

Thanks,
Thaddeus

**Comment by mikestrat58** [comment]
Hello Thaddeus

Very grateful for this mate, thank you…massive help.

Kind regards
Mike
