### ISSUE TITLE
Debugging in the Cloud Sandbox not (anymore) possible

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#5086]
**Describe the bug**
Debugging is currently not possible in the Cloud Sandbox. It does not work with the standard sandbox "Sandbox" nor with any other sandbox with a different name. The extension can be published to the sandbox and installed, but Visual Studio code cannot start the debug process.

**To Reproduce**
Steps and to reproduce the behavior:
1. Add a new launch option to the launch.json file. This looks like this.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Microsoft cloud sandbox",
            "type": "al",
            "request": "launch",
            "startupObjectId": 22,
            "breakOnError": true,
            "breakOnRecordWrite": false,
            "launchBrowser":true            
        }
    ]
}
```
I have activated the detailed log in the settings. It contains the following error which is probably responsible for the fact that debugging does not work:

```
 initialize
06/26/2019 07:54:22 [/6] Process:

 launch
06/26/2019 07:55:11 [/13] Process:

 disconnect
06/26/2019 07:55:11 [/13] 05:54:50.3468991 - null - ChangeState(Disconnected, Connecting)
05:55:11.4297311 - null - Disconnected
05:55:11.4307441 - null - Transport.Dispose()
05:55:11.4307441 - null - Closed
05:55:11.4457379 - null - Error: System.Net.Http.HttpRequestException: Error sending the request. ---> System.Net.WebException: The connection to the remote server cannot be established. ---> System.Net.Sockets.SocketException: A connection attempt failed because the remote peer did not respond correctly after a certain period of time, or the established connection was faulty because the connected host did not respond 52.166.8.14:7049
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of internal exception stack monitoring ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of internal exception stack monitoring ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.DebugAdapter.DebuggerService.<OpenConnectionAsync>d__53.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\DebugAdapter\ServerConnection\DebuggerService.cs:Line 201.
--- End of stack monitoring from the previous location where the exception was raised. ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.DebugAdapter.DebugAdapterLaunchRequestHandler.<StartDebugging>d__8.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\DebugAdapter\DebugAdapterLaunchRequestHandler.cs:Line 267.
--- End of stack monitoring from the previous location where the exception was raised. ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.DebugAdapter.DebugAdapterLaunchRequestHandler.<HandleAsync>d__4.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\DebugAdapter\DebugAdapterLaunchRequestHandler.cs:Line 90.
05:55:11.4737396 - null - Error: System.Net.Http.HttpRequestException: Error sending the request. ---> System.Net.WebException: The connection to the remote server cannot be established. ---> System.Net.Sockets.SocketException: A connection attempt failed because the remote peer did not respond correctly after a certain period of time, or the established connection was faulty because the connected host did not respond 52.166.8.14:7049
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of internal exception stack monitoring ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of internal exception stack monitoring ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.DebugAdapter.DebuggerService.<OpenConnectionAsync>d__53.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\DebugAdapter\ServerConnection\DebuggerService.cs:Line 201.
--- End of stack monitoring from the previous location where the exception was raised. ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.DebugAdapter.DebugAdapterLaunchRequestHandler.<StartDebugging>d__8.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\DebugAdapter\DebugAdapterLaunchRequestHandler.cs:Line 267.
--- End of stack monitoring from the previous location where the exception was raised. ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.DebugAdapter.DebugAdapterLaunchRequestHandler.<HandleAsync>d__4.MoveNext() in F:\a\435\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\DebugAdapter\DebugAdapterLaunchRequestHandler.cs:Line 90.
```

**Expected behavior**
Debugging must be possible again in the Business Central Cloud Sandbox. Connection question: How is it possible that port 7049 is also used in the cloud? Has this been the case so far? I thought that was purely for the on-premises variant.

**Versions:**

 - AL Language: 3.0.126610

 - Business Central: 14.0.29537.29654 and 14.1.33107.0, tried both

**Comment by thloke** [comment]
Hi! Let's get the issue to customer support as we will require more detailed information on the issue.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
