### ISSUE TITLE
[Error - 11.33.45] Please report this issue

### ISSUE THREAD

**Issue by MariaFrederiksen** [microsoft/AL#5383]
**Describe the bug**
My extension is all red.

**To Reproduce**
Tried to update extension AL Language from version 0.12.28462 to newest version

**Expected behavior**
Just an updage

**Screenshots**
![image](https://user-images.githubusercontent.com/43133864/67390984-fde7ac80-f59d-11e9-9295-dd78fd712d6f.png)

**5. Versions:**

 - AL Language: 0.12.28462

 - Business Central: 15.5 - but I don't get so far.

[Error - 11.33.45] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/hover' failed with error: 'Position: 87, FullSpan: (0..0)
Parameter name: position'
Details:
System.ArgumentOutOfRangeException: Position: 87, FullSpan: (0..0)
Parameter name: position
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position) in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 763
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetTokenAtPositionAsync>d__19.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 360
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<IsPositionNotOnTokenTrivia>d__7.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.HoverRequestHandler.<HandleAsync>d__3.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\HoverRequestHandler.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

[Error - 11.35.30] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/hover' failed with error: 'Position: 136, FullSpan: (0..0)
Parameter name: position'
Details:
System.ArgumentOutOfRangeException: Position: 136, FullSpan: (0..0)
Parameter name: position
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position) in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 763
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<GetTokenAtPositionAsync>d__19.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 360
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.<IsPositionNotOnTokenTrivia>d__7.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.HoverRequestHandler.<HandleAsync>d__3.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\HoverRequestHandler.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\586\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

**Comment by AndreyKorepanov** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by MariaFrederiksen** [comment]
No, no, not close. 

You just send me a mail, where you wrote “the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central” And it is the latest version of Visual Studio Code, latest version of d365 and latest version of extension Language AL

Now I have an extension, that have failed, and it is not possible to code in it, to make extension or even put on the old version of Language AL

I need some help what to do.

Regards Maria

 

 

 

 

Fra: AndreyKorepanov <notifications@github.com> 
Sendt: 23. oktober 2019 16:39
Til: microsoft/AL <AL@noreply.github.com>
Cc: MariaFrederiksen <maria@svaneit.dk>; Author <author@noreply.github.com>
Emne: Re: [microsoft/AL] [Error - 11.33.45] Please report this issue (#5383)

 

Closed  <https://github.com/microsoft/AL/issues/5383> #5383.

**Comment by AndreyKorepanov** [comment]
Hi @MariaFrederiksen, currently we do not support the version 0.12.x and can not guarantee a backward compatibility for that version. Basically, you have to bring your code in line with the latest AL specification. Please open a support request as I mentioned in the previous comment. 
Here you can find some farther info (please take a look at the section "I found an issue in a version of the product that is not the latest, what do I do?"): 
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by MariaFrederiksen** [comment]
HI

 

Thanks for answering  me.

 

I know that you don’t support 0.12x, but I just tried to get the old Language AL back, which have worked on my Visual Studio Code (Version 1.39.2).

 

I do have the newest version of Visual Studio Code, but it is not possible to get Language AL running on it. I get the message, that I send to you in the first place. 

 

I don’t use NAV 2018, I only code Extensions for Business Central version 15.0.36560.0

 

Sorry for my English, 

 

Regards Maria

 

 

Fra: AndreyKorepanov <notifications@github.com> 
Sendt: 24. oktober 2019 15:33
Til: microsoft/AL <AL@noreply.github.com>
Cc: MariaFrederiksen <maria@svaneit.dk>; Mention <mention@noreply.github.com>
Emne: Re: [microsoft/AL] [Error - 11.33.45] Please report this issue (#5383)

 

Hi @MariaFrederiksen <https://github.com/MariaFrederiksen> , currently we do not support the version 0.12.x and can not guarantee a backward compatibility for that version. Basically, you have to bring your code in line with the latest AL specification. Please open a support request as I mentioned in the previous comment.
Here you can find some farther info (please take a look at the section "I found an issue in a version of the product that is not the latest, what do I do?"):
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by MariaFrederiksen** [comment]
Hi

 

Now I got the point. I started all over to install Visual Studio Code, and I see what you mean now.

 

Sorry for all the trouble and have a nice day.

 

Regards 

Maria

 

Fra: AndreyKorepanov <notifications@github.com> 
Sendt: 24. oktober 2019 15:33
Til: microsoft/AL <AL@noreply.github.com>
Cc: MariaFrederiksen <maria@svaneit.dk>; Mention <mention@noreply.github.com>
Emne: Re: [microsoft/AL] [Error - 11.33.45] Please report this issue (#5383)

 

Hi @MariaFrederiksen <https://github.com/MariaFrederiksen> , currently we do not support the version 0.12.x and can not guarantee a backward compatibility for that version. Basically, you have to bring your code in line with the latest AL specification. Please open a support request as I mentioned in the previous comment.
Here you can find some farther info (please take a look at the section "I found an issue in a version of the product that is not the latest, what do I do?"):
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
