### ISSUE TITLE
Exception of type 'Microsoft.Dynamics.Nav.Types.Exceptions.NavNotSupportedException' was thrown.

### ISSUE THREAD

**Issue by HennieBink** [microsoft/AL#5416]
Error on pages with property QueryCategory is set.

Exception of type 'Microsoft.Dynamics.Nav.Types.Exceptions.NavNotSupportedException' was thrown.

Example page 16 Chart of Accounts.
When I clear the property QueryCategory the page run without error.

Property is used in several standard pages. 

We use Business Central OnPrem version 14.0.36457

How can we fix this error without clearing the property QueryCategory in the standard objects?

**Comment by HennieBink** [comment]
Event viewer 1/2

Server instance: ******
Category: Extensions
ClientSessionId: b7a2353c-7fb7-468c-bf04-33776b1c60e3
ClientActivityId: 22c421aa-eb1f-49ce-b5fa-9b960a0a4e93
ServerSessionUniqueId: f53d7320-d205-4b82-8191-48d68ecb6f94
ServerActivityId: 2d2383f8-ac71-4dea-84b5-f8f7c138e7d9
EventTime: 11/05/2019 09:49:59
Message Fatal error during metadata load -- Type:Query; Id:50; MetadataGroup:0; MetadataLoaded:False; CLRLoaded:False; ThreadGroup:0
ProcessId: 14224
Tag: 00007YQ
ThreadId: 22
CounterInformation:

**Comment by HennieBink** [comment]
Event viewer 2/2

Server instance: ******
Category: Extensions
ClientSessionId: b7a2353c-7fb7-468c-bf04-33776b1c60e3
ClientActivityId: 22c421aa-eb1f-49ce-b5fa-9b960a0a4e93
ServerSessionUniqueId: f53d7320-d205-4b82-8191-48d68ecb6f94
ServerActivityId: 2d2383f8-ac71-4dea-84b5-f8f7c138e7d9
EventTime: 11/05/2019 09:49:59
Message (NavNotSupportedException): RootException: NavNotSupportedException
Exception of type 'Microsoft.Dynamics.Nav.Types.Exceptions.NavNotSupportedException' was thrown.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass65_0.<CreateSubQueryForFlowFieldCalculation>b__2(NCLMetaQueryDefinition subQueryBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDefinition..ctor(NCLMetaQueryDataItem parentDataItem, Int32 topRows, Func`2 dataItemsCreator, Func`2 orderBysCreator)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass65_0.<CreateSubQueryForFlowFieldCalculation>b__0(NCLMetaQueryDataItem dataItemBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDataItem..ctor(NCLMetaQueryDefinition parentQueryDefinition, DataItemLinkType dataItemLinkType, Func`2 subQueryCreator, String name, Func`2 queryColumnsCreator, Func`2 dataItemLinksCreator, Int32 appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateSubQueryForFlowFieldCalculation(NCLMetaQueryDataItem baseDataItem, MetaQueryColumn flowFieldColumn, Int32 nextColumnId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateDataItemsFromDesignMetadata(NCLMetaQueryDefinition parentQueryDefinition, MetaQuery metaQuery, Boolean allowExpressionEvaluation, Boolean& tableFilterHasVariables)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass68_1.<ParseMetadata>b__0(NCLMetaQueryDefinition queryDefinitionBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDefinition..ctor(NCLMetaQueryDataItem parentDataItem, Int32 topRows, Func`2 dataItemsCreator, Func`2 orderBysCreator)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.ParseMetadata(MetaQuery metaQuery, Boolean allowExpressionEvaluation)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.LoadMetadata()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.QueryDataProvider.<GetValuesWithinRangeForKeyField>d__3.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at Microsoft.Dynamics.Nav.Runtime.ResultSet.TryGetAtIndexWithoutBuffer(Int32 index, ReadOnlyRecordBuffer& recordBuffer)
   at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryGetRecordBufferFromResultSet(Int32 fetchIndex, MutableRecordBuffer& recordBuffer)
   at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryMoveNextImpl(MutableRecordBuffer& recordBuffer)
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Advance(Int32 steps, Boolean moveBackwards, Boolean automaticFindFromPositionOnInvalid, Boolean& resultSetValid, Int32 setSize)
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.IssueFindRequest(DataError errorLevel, Boolean reversed, FindType findType, Boolean useCache)
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecordImp(DataError errorLevel, String searchMethod)
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecord(DataError errorLevel, String searchMethod)
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALFind(DataError errorLevel, String searchMethod)
   at Microsoft.Dynamics.Nav.XmlMetadata.QueryCategoryCache.QueryCategoryInfo.LoadQueryCategoriesFromMetadata()
   at Microsoft.Dynamics.Nav.XmlMetadata.QueryCategoryCache.QueryList(Int32 appId, String category)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.UpdatePageDefinitionWithQueryActions(Int32 appGroupId, PageDefinition pageDefinition)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMergedMasterPage(Int32 id, DataSourceType dataSourceType, Boolean applyPersonalization, String viewName)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMasterPageUnsolved(Int32 id, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, String viewName)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMasterPage(Int32 id, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, Boolean forceElementRemovalOptionIfApplicable, String viewName)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMetadataForPage(Int32 pageId, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, Boolean forceElementRemovalOptionIfApplicable, String viewName)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMetadataForPageAndAllItsDependencies(Int32 pageId, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, ICollection`1 tablesToSkip, String viewName)
   at SyncInvokeGetMetadataForPageAndAllItsDependencies(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationDuration(Stopwatch stopWatch, Action action)
   at Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationAction(Action action, NavSession session)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(Boolean& alreadyResumedNoLock)
   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProcessing(IResumeMessageRpc resume)
   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


ProcessId: 14224
Tag: 00007YR
ThreadId: 22
CounterInformation:

**Comment by atoader** [comment]
Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by johngentile** [comment]
Hello, I am seeing the same issue, has the bug been submitted?

**Comment by aytacakma** [comment]
My observation is: "a flowfield that has a sub type of count , is the problem"
