### ISSUE TITLE
ShowCaption still not working

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#5530]
I would actually want to reopen #3495 as this issues exist also in BC, which at that time I could not verify. As you can see in the screenshot (taken in BC15) the caption SeminarDateName1 should not be shown as it is defind as:

```
group(ThisPeriod)
{
    Caption = 'This Period';
    field(SeminarDateName1; SeminarDateName[1])
    {
        ApplicationArea = Advanced;
        ShowCaption = false;
    }
```

![image](https://user-images.githubusercontent.com/18466198/70426519-75e93380-1a73-11ea-80d8-6301bba7b3aa.png)

**Comment by AndreyKorepanov** [comment]
Hi @lvanvugt, thank you for reporting the issue. Could you please provide the BC/AL version and the source code/project demonstrating the issue. It will significantly help us reproduce the bug. Thank you.

**Comment by lvanvugt** [comment]
> Could you please provide the BC/AL version

So far as I have seen it's on any version. As reported #3495 it was there on NAV 2018 (with it's AL extension on VSCode) and is still there on recent BC 15 with AL extension for VSCode from the marketplace.

**Comment by lvanvugt** [comment]
> Could you please provide the ... source code/project demonstrating the issue.

[AL Solution Development.zip](https://github.com/microsoft/AL/files/3988552/AL.Solution.Development.zip)


Find attached the project.

**Comment by AndreyKorepanov** [comment]
Hi @lvanvugt, I tried the code attached, it seems the issue is not reproducible anymore. Could you try it with the latest daily build.

[ALProject53.zip](https://github.com/microsoft/AL/files/4813864/ALProject53.zip)

**Comment by lvanvugt** [comment]
> Could you try it with the latest daily build.

Do you mean BC17 insider?

**Comment by AndreyKorepanov** [comment]
@lvanvugt, yes try that please, it might be already fixed there. Let us know if the issue is still there, thanks.

**Comment by lvanvugt** [comment]
@AndreyKorepanov, trying now to test it my VSCode deployment, with a report I would like to verify this on, crashes. I know this is not the topic here, but I ned to get it fixed to allow me to test.

### What is the case?

1. I have deployed a BC17 insider container using image:

`$bcdockerimage = 'bcinsider.azurecr.io/bcsandbox-master:base'`

2. I have installe the BC17 AL Language extension form the docker folder
3. I have donwloaded the symbols an build the .app (so that's working fine)
4. Now deploying with F5 I get a whole list of errors (being actually due to 5 times the same attempt):
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 44
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.Start(ChannelBase channel, MessageProtocolType messageProtocolType, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27


   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 156
[Info  - 09:19:36] Connection to server got closed. Server will restart.
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 44
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.Start(ChannelBase channel, MessageProtocolType messageProtocolType, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27


   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 156
[Info  - 09:19:38] Connection to server got closed. Server will restart.
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 44
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.Start(ChannelBase channel, MessageProtocolType messageProtocolType, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27


   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 156
[Info  - 09:19:38] Connection to server got closed. Server will restart.
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 44
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.Start(ChannelBase channel, MessageProtocolType messageProtocolType, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27


   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 156
[Info  - 09:19:39] Connection to server got closed. Server will restart.
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 44
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.Start(ChannelBase channel, MessageProtocolType messageProtocolType, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27


   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 156
[Error - 09:19:39] Connection to server got closed. Server will not be restarted.

```
I never experienced this on any image of previous version (BC16 and down). Is this an image issue?

**Comment by AndreyKorepanov** [comment]
Ok, @lvanvugt now we got another issue. It seems the assembly "Newtonsoft.Json, Version=11.0.0.0" is missed. Does the re-installing the vsix an restarting VSCode helps? 
Otherwise you can try to get a repro on the previous daily build.

**Comment by lvanvugt** [comment]
> Ok, @lvanvugt now we got another issue. It seems the assembly "Newtonsoft.Json, Version=11.0.0.0" is missed. Does the re-installing the vsix an restarting VSCode helps?

No.
> Otherwise you can try to get a repro on the previous daily build.

How do I get that using docker image? In other words, what is the url for that?

**Comment by AndreyKorepanov** [comment]
@lvanvugt, if you still experience a problem with the latest build, please report a separate issue. Let's come back to working environment, have you tried the project I attached? I used it to verify the issue and maybe I missed some details. Please let me know if the "show caption" issue is there, then I'll create a bug. Thank you.

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
