### ISSUE TITLE
Merge branch from master error

### ISSUE THREAD

**Issue by joachimcarrein** [microsoft/AL#5552]
**Describe the bug**
When merging branch with master using commandline in vscode an error pops up.

**To Reproduce**
branch which is behind master, instead of syncing master, I did in the terminal "git pull origin master" which will merge master into the branch

**Expected behavior**
no error

**Screenshots**
Error shown:
```
[Error - 17:28:09] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'workspace/didChangeWatchedFiles' failed with error: 'Value cannot be null.
Parameter name: projectId'
Details:
System.ArgumentNullException: Value cannot be null.
Parameter name: projectId
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentId.CreateNewId(ProjectId projectId, String debugName) in F:\a\1036\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\DocumentId.cs:line 74
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.TryAddTransientDocument(String filePath, String text, Boolean handleRad, DocumentId& documentId) in F:\a\1036\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:line 176
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeWatchedFilesRequestHandler.HandleAsync(DidChangeWatchedFilesRequest request, Int32 requestId, CancellationToken cancellationToken) in F:\a\1036\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeWatchedFilesRequestHandler.cs:line 30
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\1036\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\1036\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64
```

**5. Versions:**

 - AL Language: 4.0.209944

 - Business Central: N/A

**Comment by AndreyKorepanov** [comment]
Hi @joachimcarrein, thank you for reporting issue. It looks like a development time issue, nothing actually related to the AL extension codebase. Generally working with SVN can change the project files in unpredictable way which in turn causes inconsistent data sent from VSCode. The best way to handle such kind of issues is just reopen the project. If it does not help, please report the issue. 
Please follow the template and provide adequate information to reproduce the issue.
