### ISSUE TITLE
Processing of message 'textDocument/formatting' failed with error: 'Unexpected false'

### ISSUE THREAD

**Issue by iachininotomarco** [microsoft/AL#5683]
**Describe the bug**
Suddenly autoformat (after pressing CTRL+S) doesn't work anymore. The popup "Running Save Participants for 'src\xxx': Formatting" appears without terminating and in output I can read: 
 
Processing of message 'textDocument/formatting' failed with error: 'Unexpected false'
Details:
System.InvalidOperationException: Unexpected false
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Utilities.Contract.Fail(String message) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Utilities\Contract.cs:line 114
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.Rules.IndentBlockOperation..ctor(SyntaxToken baseToken, SyntaxToken startToken, SyntaxToken endToken, TextSpan textSpan, Int32 indentationDelta, IndentBlockOption option) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\Operations\IndentBlockOperation.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.IndentBlockFormattingRule.AddAlignmentBlockOperation(List`1 list, SyntaxNode node, OptionSet optionSet) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\IndentBlockFormattingRule.cs:line 139
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.IndentBlockFormattingRule.AddIndentBlockOperations(List`1 list, SyntaxNode node, OptionSet optionSet, NextAction`1 nextOperation) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\IndentBlockFormattingRule.cs:line 29
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.<.ctor>b__8_2(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.NextAction`1.Invoke(List`1 arguments) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\NextAction`1.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.Rules.AbstractFormattingRule.AddIndentBlockOperations(List`1 list, SyntaxNode node, OptionSet optionSet, NextAction`1 nextOperation) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\AbstractFormattingRule.cs:line 26
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.<.ctor>b__8_2(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.NextAction`1.Invoke(List`1 arguments) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\NextAction`1.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.Rules.AbstractFormattingRule.AddIndentBlockOperations(List`1 list, SyntaxNode node, OptionSet optionSet, NextAction`1 nextOperation) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\AbstractFormattingRule.cs:line 26
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.<.ctor>b__8_2(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.NextAction`1.Invoke(List`1 arguments) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\NextAction`1.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.IndentUserSettingsFormattingRule.AddIndentBlockOperations(List`1 list, SyntaxNode node, OptionSet optionSet, NextAction`1 nextOperation) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\IndentUserSettingsFormattingRule.cs:line 18
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.<.ctor>b__8_2(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.NextAction`1.Invoke(List`1 arguments) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\NextAction`1.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.Rules.AbstractFormattingRule.AddIndentBlockOperations(List`1 list, SyntaxNode node, OptionSet optionSet, NextAction`1 nextOperation) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\AbstractFormattingRule.cs:line 26
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.<.ctor>b__8_2(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.NextAction`1.Invoke(List`1 arguments) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\NextAction`1.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.Rules.AbstractFormattingRule.AddIndentBlockOperations(List`1 list, SyntaxNode node, OptionSet optionSet, NextAction`1 nextOperation) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\AbstractFormattingRule.cs:line 26
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.<.ctor>b__8_2(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.NextAction`1.Invoke(List`1 arguments) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\NextAction`1.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.Rules.AbstractFormattingRule.AddIndentBlockOperations(List`1 list, SyntaxNode node, OptionSet optionSet, NextAction`1 nextOperation) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Rules\AbstractFormattingRule.cs:line 26
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.<.ctor>b__8_2(Int32 index, List`1 list, SyntaxNode node, SyntaxToken lastToken, NextAction`1 next) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.ChainedFormattingRules.AddContinuedOperations[TArg1](Int32 index, List`1 arg1, SyntaxNode node, SyntaxToken lastToken, IActionHolder`1 actionCache) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\ChainedFormattingRules.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.AbstractFormatEngine.<>c__DisplayClass16_0.<CreateNodeOperationTasks>b__5(List`1 l, SyntaxNode n) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\AbstractFormatEngine.cs:line 149
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.AbstractFormatEngine.<>c__DisplayClass17_2`1.<AddOperations>b__2(SyntaxNode n) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\AbstractFormatEngine.cs:line 197
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.TaskExecutor.SynchronousExecutor.ForEach[T](IEnumerable`1 source, Action`1 action, CancellationToken cancellationToken) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Utilities\TaskExecutor.cs:line 102
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.AbstractFormatEngine.AddOperations[T](List`1 nodes, Action`2 addOperations, CancellationToken cancellationToken) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\AbstractFormatEngine.cs:line 210
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.AbstractFormatEngine.<>c__DisplayClass16_0.<CreateNodeOperationTasks>b__1(Task`1 task) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\AbstractFormatEngine.cs:line 148
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.TaskExecutor.SynchronousExecutor.ContinueWith[T1,T2](Task`1 previousTask, Func`2 nextAction, CancellationToken cancellationToken) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Utilities\TaskExecutor.cs:line 88
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.AbstractFormatEngine.CreateNodeOperationTasks(CancellationToken cancellationToken) in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\AbstractFormatEngine.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.AbstractFormatEngine.<FormatAsync>d__12.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Engine\AbstractFormatEngine.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.LanguageServices.SyntaxFormattingService.<FormatIndividuallyAsync>d__11.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\LanguageServices\SyntaxFormattingService.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.LanguageServices.SyntaxFormattingService.<FormatAsync>d__8.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\LanguageServices\SyntaxFormattingService.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.Formatter.<FormatAsync>d__24.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Formatter.cs:line 293
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Formatting.Formatter.<FormatAsync>d__16.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Formatting\Formatter.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.FormattingHelper.<FormatDocument>d__0.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\FormattingHelper.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.FormatDocumentRequestHandler.<HandleAsync>d__3.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\FormatDocumentRequestHandler.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\1326\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

**5. Versions:**
 - Business Central: 15.2.39060.0
 - AL Language: 4.0.229715 
 - AZ AL Dev Tools/AL Code Outline: 1.0.29
 - ESLint: 2.0.15
 - waldo's CRS AL Language Extension: 1.1.22

**Comment by atoader** [comment]
Hi! Can you please provide a sample to reproduce this issue?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
