### ISSUE TITLE
RuleInvalidObsoleteTagsNotAllowed exception

### ISSUE THREAD

**Issue by hougaard** [microsoft/AL#5695]
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 5.0.235548
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

Analyzer 'Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RuleInvalidObsoleteTagsNotAllowed' threw an exception of type 'System.ArgumentNullException' with message 'System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.Dynamics.Nav.AppSourceCop.AppSourceCopConfigurationProvider.GetTargetVersion(Compilation compilation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.AppSourceCop\AppSourceCopConfigurationProvider.cs:line 109
   at Microsoft.Dynamics.Nav.AppSourceCop.Upgrade.RuleInvalidObsoleteTagsNotAllowed.CompilationStart(CompilationStartAnalysisContext context) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.AppSourceCop\Upgrade\RuleInvalidObsoleteTagsNotAllowed.cs:line 49
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass32_1.<ExecuteCompilationStartActions>b__0() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 214
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1079'

**Comment by hougaard** [comment]
Seems to be fixed in 16.1.11414.0

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
