### ISSUE TITLE
Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized.

### ISSUE THREAD

**Issue by monchangg** [microsoft/AL#5803]
**Describe the bug**
I created a list page. And then created action button to open that list page on Customer Card page. But sometimes, I got attached 
![Annotation 2020-04-14 114754](https://user-images.githubusercontent.com/22004532/79184112-d800dd80-7e45-11ea-9d22-6dbe870dd6f8.png)
error message when I click the action button.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a List Page
2. Create an action button to open that list page on Customer Card page
3. Click that action button again and again

**Expected behavior**
Should not have this error message.
Sometimes but not everytime will got the "Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized." error message.

Following is the error details on Help & Support.
ERROR DETAILS
Error Text: Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized.
Error Code: NotInitialized:NotInitialized
ERROR CALLSTACK: 
Customer(Table 18).CalcOverdueBalance line 14 - Base Application by Microsoft
ERROR OBJECT:
```
Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLNotInitializedException: Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized. ---> Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLNotInitializedException: Microsoft.Dynamics.Nav.Runtime.NavHttpContent variable not initialized.
   at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.OpenForm(LogicalForm mainForm, Collection`1 subForms) in s:
repo
src
Platform
Client
Shared
Prod.Client.UI
Databinder
NSTDataAccess.cs:line 1156
   at Microsoft.Dynamics.Nav.Client.UIPatterns.OnFormOpeningPattern.OpenForm(LogicalForm form, Boolean retry) in s:
repo
src
Platform
Client
Shared
Prod.Client.UI
UIPatterns
OnFormOpeningPattern.cs:line 60
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Microsoft.Dynamics.Framework.UI.LogicalForm.BuildForm(Action customBuild) in s:
repo
src
Platform
Client
Shared
Prod.ClientFwk
Forms
LogicalForm.cs:line 1121
   at Microsoft.Dynamics.Nav.Client.Builder.NavSessionHelper.BuildForm(LogicalForm form, Action customBuild) in s:
repo
src
Platform
Client
Shared
Prod.Client.UI
Builder
NavSessionHelper.cs:line 735
   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.Build(MasterPage definition, BindingManager bindingManager, UIBuilderContext context) in s:
repo
src
Platform
Client
Shared
Prod.Client.Builder
Framework
PageBuilder.cs:line 162
   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.CreateLogicalForm(MasterPage metadata, FormState formState) in s:
repo
src
Platform
Client
Shared
Prod.Client.Builder
BuilderSession
BuilderSession.cs:line 350
   at Microsoft.Dynamics.Nav.Client.PageRunCallbackHandler.RunPage(FormRunRequest formRequest) in s:
repo
src
Platform
Client
Shared
Prod.Client.UI
PageRunCallbackHandler.cs:line 137
   at Microsoft.Dynamics.Nav.Client.ServiceClientCallback.InternalProcessServerCallbackRequests(Queue`1 requests) in s:
repo
src
Platform
Client
Shared
Prod.Client.UI
ServiceClientCallback.cs:line 1201
   at Microsoft.Dynamics.Nav.Client.ServiceClientCallback.<>c__DisplayClass25_0.<ProcessServerRequests>b__0() in s:
repo
src
Platform
Client
Shared
Prod.Client.UI
ServiceClientCallback.cs:line 264
   at Microsoft.Dynamics.Nav.Client.ServiceClientCallback.<>c__DisplayClass16_0.<RunClientRequest>b__0() in s:
repo
src
Platform
Client
Shared
Prod.Client.UI
ServiceClientCallback.cs:line 107
   at Microsoft.Dynamics.Nav.Client.ServerInvocationManager.DoClientRequestAndCatch(Action clientRequest, Action`1 sendToServerIfNotFaulted) in s:
repo
src
Platform
Client
Shared
Prod.Client.ServiceConnection
ServerInvocationManager.cs:line 401
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.Service.ServiceCall.GetClientReturnValue(Action invokeCallback) in s:
repo
src
Platform
Server
Prod.Service
ServiceCall.cs:line 145
   at Microsoft.Dynamics.Nav.Runtime.NavDialog.ProcessServerRequests() in s:
repo
src
Platform
Server
Prod.Ncl
AL
ALDialog.cs:line 461
   at Microsoft.Dynamics.Nav.Runtime.NavQuery.RunOnBeforeOpentrigger() in s:
repo
src
Platform
Server
Prod.Ncl
Runtime
NavQuery.cs:line 766
   at Microsoft.Dynamics.Nav.Runtime.NavQuery.NavigateQueryInternal() in s:
repo
src
Platform
Server
Prod.Ncl
Runtime
NavQuery.cs:line 1122
   at Microsoft.Dynamics.Nav.Runtime.NavQuery.ALOpen(DataError errorLevel) in s:
repo
src
Platform
Server
Prod.Ncl
AL
ALQuery.cs:line 533
   at Microsoft.Dynamics.Nav.BusinessApplication.Record18.CalcOverdueBalance_Scope_1648862090.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run() in s:
repo
src
Platform
Server
Prod.Ncl
Runtime
NavMethodScope.cs:line 514
   at Microsoft.Dynamics.Nav.BusinessApplication.Record18.CalcOverdueBalance()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record18.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Page21.<OnMetadataLoaded>b__66_66()
   at Microsoft.Dynamics.Nav.Runtime.NavFormSourceExpression.TryExecuteAndHandleExceptionMappingSourceExpressionGetter(NavFormSourceExpressionGetter getter) in s:
repo
src
Platform
Server
Prod.Ncl
Runtime
NavFormSourceExpression.cs:line 170
   at Microsoft.Dynamics.Nav.Service.NSRecordBase.SetCLRCellFromSourceExpression(NavDataRow dataRow, NavFormSourceExpression expression) in s:
repo
src
Platform
Server
Prod.Service
NSRecordBase.cs:line 217
   at Microsoft.Dynamics.Nav.Service.NSRecordBase.PopulateCLRTable(NavDataTable dataTable, NsDataAccess recDataAccess, NavDataRow dataRow) in s:
repo
src
Platform
Server
Prod.Service
NSRecordBase.cs:line 69
   at Microsoft.Dynamics.Nav.Service.NSField.ActionField(NavSession con) in s:
repo
src
Platform
Server
Prod.Service
NSField.cs:line 384
   at Microsoft.Dynamics.Nav.Service.NSField.Action(NavSession session) in s:
repo
src
Platform
Server
Prod.Service
NSField.cs:line 376
   at SyncInvokeActionField(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs) in s:
repo
src
Platform
Server
Prod.Service
ServiceOperationInvoker.cs:line 353
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs) in s:
repo
src
Platform
Server
Prod.Service
ServiceOperationInvoker.cs:line 734
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs) in s:
repo
src
Platform
Server
Prod.Service
ServiceOperationInvoker.cs:line 374
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs) in s:
repo
src
Platform
Server
Prod.Service
ServiceOperationInvoker.cs:line 734
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs) in s:
repo
src
Platform
Server
Prod.Service
ServiceOperationInvoker.cs:line 319
```

**Screenshots**

**5. Versions:**
 - AL Language: 4.0.249486
 - Business Central:15.4.41023.41669

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
