### ISSUE TITLE
Error trying to use Event Lookup in VS Coded

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/AL#5806]
**Describe the bug**
When tryring to use the Event Lookup (Shift+Alt+E), I get an error

**To Reproduce**
Open Codeunit object
Press Shift+ALT+E, 
``` AL Code to reproduce the issue ```
No code required.

**Expected behavior**

**Screenshots**
None
Output Window information
[Error - 10:56:27] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/getEventPublishersRequest' failed with error: 'One or more errors occurred. (One or more errors occurred. (Nullable object must have a value.)) (Nullable object must have a value.)'
Details:
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Nullable object must have a value.)) (Nullable object must have a value.)
 ---> System.InvalidOperationException: Nullable object must have a value.
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.CreateMethodSignature(ISymbol s, IApplicationObjectTypeSymbol appObj, String appObjName) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 73
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.<>c.<HandleAsync>b__3_3(ISymbol e) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 56
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.SortHelper`2.BuildKeysFromSource(GrowingArray`1& keys, List`1& values)
   at System.Linq.Parallel.SortHelper`2.Sort()
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.Spool(QueryTaskGroupState groupState, PartitionedStream`2 partitions, Shared`1 results, TaskScheduler taskScheduler)
   at System.Linq.Parallel.OrderPreservingMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.SelectQueryOperator`2.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.SortQueryOperatorResults`2.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 childPartitionedStream)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStreamNotIndexed[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, QuerySettings settings)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStream[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStreamNotIndexed[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, QuerySettings settings)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStream[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.SortQueryOperatorResults`2.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.HandleAsync(GetEventPublishersRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 45
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 54
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**5. Versions:**
 - AL Language: 5.0.254558
 - Business Central: 14.0.41143 On premise

**Comment by atoader** [comment]
Can you provide a repro for this issue? A project and a video recording would help enormously.

**Comment by GreatScott000** [comment]
Hi, yes I can.  It will take a day or two to get back to you.  In crunch mode for a delivery.

**Comment by GreatScott000** [comment]
Just one note on this.  I have tested it on BC16 CU01 it works.  But is does NOT work for a BC14 implementation (noted in original issue).

**Comment by GreatScott000** [comment]
Attached is a sample app that causes the error:

[ALProject13.zip](https://github.com/microsoft/AL/files/4752150/ALProject13.zip)

**Comment by GreatScott000** [comment]
Any update on this?

**Comment by SO-MECA** [comment]
I got the same error in a BC 14 Project. Do you have any update for us?

**Comment by wansong-yu** [comment]
same issue on BC 14.3 -- any update?

**Comment by SBalslev** [comment]
Hi! Thank you for reporting this crash in the Event Lookup (Shift+Alt+E) — the stack trace was very helpful.

We've confirmed this was fixed in **BC 24.0**. The crash occurred when the Find Event command encountered events on extension objects whose target could not be resolved, causing a NullReferenceException in CreateMethodSignature. The fix (with an accompanying regression test) gracefully skips events on unresolved objects instead of crashing.

If you encounter similar issues with Event Lookup on a current version, please don't hesitate to open a new issue.

Thank you for helping us improve the AL developer experience!
