### ISSUE TITLE
CodeCop bug System.InvalidCastException

### ISSUE THREAD

**Issue by kasperdj** [microsoft/AL#5821]
**Describe the bug**
We keep getting the following 2 exception errors in our app.json

```
Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule214BlindWriteLocalRecord' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundFieldAccess' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IInvocationExpression'.
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule214BlindWriteLocalRecord.ProcessingInvocation(SyntaxNode syntaxNode, PooledDictionary`2 processInvocations, SyntaxNodeAnalysisContext syntaxNodeAnalysisContext)
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule214BlindWriteLocalRecord.<>c.<Analyze>b__5_0(SyntaxNodeAnalysisContext syntaxNodeAnalysisContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule214BlindWriteLocalRecord.cs:line 46
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 742
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1079'
```

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new Project for BC15.
2. Use the attached screenshots for app.json and settings.json to provoke the error.

``` AL Code to reproduce the issue ```

**Expected behavior**
No bugs reported by the CodeCop.

**Screenshots**
![image](https://user-images.githubusercontent.com/54669593/79732891-96b07800-82f4-11ea-8cb4-b7d4fc66ade4.png)
![image](https://user-images.githubusercontent.com/54669593/79733059-d5dec900-82f4-11ea-9b42-c26d2d1d9369.png)
![image](https://user-images.githubusercontent.com/54669593/79733117-eabb5c80-82f4-11ea-9036-87cc50f101a4.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: 15 RTM DK, Runtime 4.0, Target=Cloud

**Comment by MarcHansenMicrosoft** [comment]
Known issue.
see dup:
https://github.com/microsoft/AL/issues/5694
