### ISSUE TITLE
Exception Rule087DoOnlyLowerPermissionsInsideTestProcedures

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/AL#5904]
**Describe the bug**
Analyzer ```
'Microsoft.Dynamics.Nav.CodeCop.Design.Rule087DoOnlyLowerPermissionsInsideTestProcedures' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableListDeclarationSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VariableDeclarationSyntax'.
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule087DoOnlyLowerPermissionsInsideTestProcedures.AnalyzeVariableList(SyntaxNodeAnalysisContext ctx) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule087DoOnlyLowerPermissionsInsideTestProcedures.cs:line 45
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass52_1.<ExecuteSyntaxNodeAction>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 742
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1079'
```

I do not have any test codeunit in the app

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to '...'

``` AL Code to reproduce the issue ```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**5. Versions:**
<!-- Go to Visual Studio Code → Extensions panel → AL Language -->
 - AL Language: 
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.262190
Publisher: Microsoft

<!-- In the client search for: System Information -->
 - Business Central: BC160 RTM (but I don't think is related to the BC version)

**Comment by dtkb** [comment]
What file is the diagnostic attributed to? `app.json`? If so, then bugs already exist for this.

**Comment by stefanoPrimo** [comment]
yeah, it throws it under app.json.
Sorry I didn't see the same issue that was already posted!
Thanks
