### ISSUE TITLE
Feature GenerateCaptions issue with Interfaces

### ISSUE THREAD

**Issue by mcolomboit** [microsoft/AL#5920]
When GenerateCaption functionality is used in the app.json file, and an Interface is declared in the code, the app cannot be compiled with the following error message:

[Error - 17:39:39] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitSymbolWithProperties(Symbol symbolWithProperties) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.DefaultVisit(Symbol symbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 59
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LabelWriterVisitor.VisitMembersOfSymbol(Symbol symbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LabelWriterVisitor.cs:line 225
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor.VisitModule(ModuleSymbol node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SymbolVisitor.Generated.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LanguageFileOutputter.<>c__DisplayClass1_0.<OutputLanguageFile>b__0() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LanguageFileOutputter.cs:line 40
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.<>c__DisplayClass2_0.<WriteDefaultNodesAndContinue>b__3() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\XliffOutputter.cs:line 100
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespace) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:line 25
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.<>c__DisplayClass2_0.<WriteDefaultNodesAndContinue>b__2() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\XliffOutputter.cs:line 97
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespace) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:line 25
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.<>c__DisplayClass2_0.<WriteDefaultNodesAndContinue>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\XliffOutputter.cs:line 96
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespace) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:line 25
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.<>c__DisplayClass2_0.<WriteDefaultNodesAndContinue>b__0() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\XliffOutputter.cs:line 84
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.XmlUtilities.WriteStartEnd(XmlWriter writer, String nodeName, Action action, String namespace) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\XmlUtilities.cs:line 25
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.XliffOutputter.WriteDefaultNodesAndContinue(XmlWriter writer, String appName, String targetLanguage, Action groupContentWriter) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\XliffOutputter.cs:line 78
   at Microsoft.Dynamics.Nav.CodeAnalysis.Translation.LanguageFileOutputter.OutputLanguageFile(Compilation compilation, Stream outputStream, String appName, DiagnosticBag diagnosticBag) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Translation\LanguageFile\LanguageFileOutputter.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.OutputLanguageFile(Compilation compilation, CompilerTextWriter consoleOutput, ErrorLogger errorLogger, DiagnosticBag diagnosticBag) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 606
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.GenerateLanguageFile(Compilation compilation, CompilerTextWriter consoleOutput, ErrorLogger errorLogger) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 560
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 521
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 476
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 332
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.Build(Project builtProject, StreamingTextWriter outputWriter, Boolean isRad, IList`1 args, CancellationToken cancellationToken, Boolean forceBuild, PooledList`1 outputFiles) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 173
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.HandleAsync(CreatePackageRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 102
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 54
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**To Reproduce**

```
- app.json

...
"features": [ "TranslationFile", "GenerateCaptions" ]
...

- IGenericInterface.Interface.al

interface IGenericInterface
{
    procedure MyProcedure();

    procedure MyNextProcedure(): Text;
    
}

```

**Versions:**
 - AL Language: 5.0.279165
 - Business Central: 16.1.12629.13286

**Comment by robertosb** [comment]
I have the same issue, is there a fix for this?

**Comment by atoader** [comment]
The issue has been fixed and it will be available in the next developer preview and in a future CU of the 2020 Wave 1 release.
