### ISSUE TITLE
Please report this issue

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/AL#5929]
**Describe the bug**
I'm just programming away and I get this message in the problems window:
[Error - 2:19:26 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/didChange' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'
Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 661
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 67
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.UpdateBuffer(DidChangeTextDocumentRequest updateRequest, CancellationToken token)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeTextDocumentRequestHandler.HandleAsync(DidChangeTextDocumentRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeTextDocumentRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 54
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

Steps and to reproduce the behavior:
I don't know how to reproduce this in a clean environment. I am on a weekend trip with my wife and I am not going to spend any more time on this. My app does compile and publish, but the problems window is asking me to report this, so here you are.

**5. Versions:**

 - AL Language: 5.0.280447

 - Business Central: Version: US Business Central 16.1 (Platform 16.0.12630.12758 + Application 16.1.12629.12805)

**Comment by pradog** [comment]
In the code you are using an array variable whose index is out of bounds. Increase the array dimensions to correct the issue.

**Comment by dtkb** [comment]
No, that's an internal VScode error, not a compiler error with the user's code.

**Comment by TheDenSter** [comment]
There is no array in my workspace

**Comment by qutreson** [comment]
@TheDenSter are you still facing this issue?

**Comment by TheDenSter** [comment]
yes it is popping up every once in a while, it usually goes away when I restart VSCode or delete the alcache folders.

**Comment by kalberes** [comment]
dup #6320
