### ISSUE TITLE
Still incomplete .dal files

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#5942]
Hi @kalberes 
although I am using the latest AL language extension version from Marketplace, 5.0.280447, I am still experiencing the bug #5914 while developing on a 5.0 runtime (BC 16.0). I had re-downloaded the symbols from my local docker container, but I did not update my container since.

What are all requirements to correct the issue?

**Comment by NKarolak** [comment]
BTW it *does* work on another repo, also 5.0 runtime, same AL language extension version, and even targeting the very same docker container as in my initial post.

**Comment by kalberes** [comment]
If you specify a runtime <= 5.1 in you app.json things should work. 
For runtimes > 5.,2 gotodefinition will only resolve if you have a >= 16.2 NSt runtime on base app symbols. On other third party symbols gotodefinition wiill work when they are rebuilt and republished with the 16.2 runtime.
An empty DAL can also be caused by the fact that your connection to the NST failed for some reason. Or the symbol could not resolve (showmycode= true, nondebuggable attribute, etc).
Hard to tell.

**Comment by NKarolak** [comment]
Again: I have two repos for Saas development
- both runtime 5.0
- both opened with the same version of the AL Language extension
- both targeting the very same docker container in launch.json
- both with the very same dependencies to the base app and system app (incl. version)
- I could not detect any other mentionable difference between the two app.json files
- both with refreshed symbols after AL language update
- one is an older project, one is a newer project: the dal files are incomplete for the older project only (F12 on table "Sales Line"), hence for the app that had been published first on the target database.

**Now comes the most confusing part:**
- The downloaded base app symbol file *does* contain the complete table definition for "Sales Line" for _both_ repos
![image](https://user-images.githubusercontent.com/34504100/83970419-ec0d0c80-a8d5-11ea-9d72-14c4bcb67d38.png)

However, for my old repo, VS Code does not _display_ the full content on F12:
![image](https://user-images.githubusercontent.com/34504100/83970449-0ba43500-a8d6-11ea-9d5e-72be0683ac38.png)
How is that possible?

**Comment by kalberes** [comment]
I do not know.  If you have a metadata DAL it means that the server could not provide the AL file information from the database. Any hints in teh event viewer for the server?

**Comment by NKarolak** [comment]
I've tried these: 
- https://www.hougaard.com/get-an-eventlog-from-a-docker-container/
- https://stackoverflow.com/questions/41215471/how-do-i-access-windows-eventlog-of-a-docker-container

Nothing helpful was logged, unfortunately.

**Comment by NKarolak** [comment]
Sorry, that was a bit too quick. I've searched only for logs from the time that I was trying to view the symbols. Upon starting the container, there are in fact some warnings and errors. In chronological order only those that might have something to do with the issue:

Warning
```
Server instance: BC
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 4d3ddb6e-937a-4da6-b8ae-9af1ff2dc5c0
EventTime: 06/09/2020 05:22:17
Message Action completed successfully, but it took longer than the given threshold.
  Execution time: 1191 ms
  Threshold: 750 ms
  Message: Long running SQL statement
  Task ID: 3
  Connection ID: 1
  SQL server session ID: 51
  Client Type: 
  Database Name: Financialsde
  Current Company Name: 
  Statement: SELECT [Package ID], [Object Type], [Object ID], [Metadata] FROM [Application Object Metadata] WHERE ([Metadata Hash] = '' OR LEN([Metadata Hash]) <> 64) AND [Metadata] IS NOT NULL
  
ProcessId: 2288
Tag: 000007L
ThreadId: 8
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

```

warning
```
Server instance: BC
Category: Extensions
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: c7b4dfa5-d608-49b8-89bc-94c59a08e82b
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 4d3ddb6e-937a-4da6-b8ae-9af1ff2dc5c0
EventTime: 06/09/2020 05:22:41
Message Object metadata load attempted with no thread app group context defined -- Type:Page; Id:130650; MetadataGroup:19
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.ApiWebServiceEntryHelper.GetAllVersions(ObjectType objectType, Int32 objectId, PackageId packageId, NavAppGroup group, HashSet`1 paths, Boolean throwOnEndpointDuplicate)
   at Microsoft.Dynamics.Nav.Runtime.ApiWebServiceEntryHelper.GetEntriesFromNavApp(NavTenant tenant, HashSet`1 paths)
   at Microsoft.Dynamics.Nav.Runtime.WebServiceHelper.GetApiWebServices(NavTenant tenant)
   at Microsoft.Dynamics.Nav.Service.Api.ApiRouteManager.ConfigureCommonRoutesForAllTenants()
   at Microsoft.Dynamics.Nav.Service.Api.GraphApiHost.ConfigureHost(WebApiHost context, IAppBuilder builder, Category telemetryCategory, AuthenticationSchemes authenticationScheme, DelegatingHandler handler, WebApiAssemblyResolver resolver)
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.<StartInternal>b__46_0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.StartInternal()
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.Open(String machineName, ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartOwinServices(ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartAllServices(ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

ProcessId: 2288
Tag: 00007YP
ThreadId: 8
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 
```

Error
```
Server instance: BC
Category: Runtime
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: c7b4dfa5-d608-49b8-89bc-94c59a08e82b
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 4d3ddb6e-937a-4da6-b8ae-9af1ff2dc5c0
EventTime: 06/09/2020 05:22:41
Message (NavMetadataNotFoundException): RootException: NavMetadataNotFoundException
The metadata object Enum 100 was not found.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetEnumMetadata(Int32 id)
   at Microsoft.Dynamics.Nav.Runtime.NCLFieldEnumMetadata.GetEnumMetadataFromMetadataProvider()
   at Microsoft.Dynamics.Nav.Runtime.NCLFieldEnumBaseMetadata.GetAppGroupAwareEnumMetadata()
   at Microsoft.Dynamics.Nav.Runtime.NCLFieldEnumBaseMetadata.get_OrdinalValues()
   at Microsoft.Dynamics.Nav.Runtime.NCLOptionMetadata.HasNonAscendingOptionValues()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaTable.ApplyAppGroupAwareEnumMetadata(MetaTable metaTable)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaTable.GetMetaTableClone()
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetTableMetadata(Int32 id, Int32 appGroupId, Boolean requireCompiled)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.FieldFromTableNoResolver(Int32 tableNo, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Types.Metadata.MetaQuery.ApplyLanguage(String language, String primaryLanguage, Func`3 fieldFromTableNoResolver)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.LoadMetadata()
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.LoadMetadata()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.ApiWebServiceEntryHelper.GetAllVersions(ObjectType objectType, Int32 objectId, PackageId packageId, NavAppGroup group, HashSet`1 paths, Boolean throwOnEndpointDuplicate)
   at Microsoft.Dynamics.Nav.Runtime.ApiWebServiceEntryHelper.GetEntriesFromNavApp(NavTenant tenant, HashSet`1 paths)
   at Microsoft.Dynamics.Nav.Runtime.WebServiceHelper.GetApiWebServices(NavTenant tenant)
   at Microsoft.Dynamics.Nav.Service.Api.ApiRouteManager.ConfigureCommonRoutesForAllTenants()
   at Microsoft.Dynamics.Nav.Service.Api.GraphApiHost.ConfigureHost(WebApiHost context, IAppBuilder builder, Category telemetryCategory, AuthenticationSchemes authenticationScheme, DelegatingHandler handler, WebApiAssemblyResolver resolver)
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.<StartInternal>b__46_0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.StartInternal()
   at Microsoft.Dynamics.Nav.Service.WebApi.WebApiHost.Open(String machineName, ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartOwinServices(ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartAllServices(ServerUserSettings settings)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


ProcessId: 2288
Tag: 000028Z
ThreadId: 8
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId
```

Only to name a few. I will send you the whole event log by mail (GitHub does not allow this file type).

**Comment by NKarolak** [comment]
Solved:

Reason for my runtime 5.0 repository not showing the dal files completely, was a multiple configuration in the launch.json (and a AL Language extension fix, not yet provided).
The moment I reduced it to one configuration only, the dal files were displayed completely again. No need to reload/restart client or download symbols again.

Thanks @kalberes for proposing the final hint (by e-mail)!
