### ISSUE TITLE
Intellicense error thrown

### ISSUE THREAD

**Issue by kvamsdal** [microsoft/AL#5985]
**Describe the bug**
Cannot use intellisense.

**Expected behavior**
Ctrl + Space = help

**Screenshots**
[Error - 14.52.35] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'Node span: 0-0, position: 1
Parameter name: position'
Details:
System.ArgumentOutOfRangeException: Node span: 0-0, position: 1
Parameter name: position
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1002
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Func`2 findInsideTrivia) in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1025
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 989
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsEntirelyWithinStringLiteral(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 501
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.MemberSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ContextQuery\MemberSyntaxContext.cs:line 172
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionProvider.<CreateMemberContextAsync>d__12.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionProvider.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<GetPerContextSymbols>d__18.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__13.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<ProvideCompletionsAsync>d__12.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetContextAsync>d__24.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 372
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__17.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.<HandleAsync>d__4.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.<HandleAsync>d__9.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in F:\a\957\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by AndreyKorepanov** [comment]
Hi @kvamsdal, thank you for reporting the issue. Could you please provide a sample project with your code demonstrating the issue along with the AL/BC version? For future issues, please follow the template It helps us greatly in identifying the root cause with higher efficiency.

**Comment by JulienDecottignies** [comment]
Hi,

Same issue here. 

It seems to happen "randomly" when I hit CTRL + Space keys. Sometines even when I start to write a method name, as IsolatedStorage().

After **F1 + Reload Window**, I can use again the intellisense but only for a short time.  

Using **AL Language 5.0.288712**

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity from the owner of the issue. Please open a new issue with a project reproducing the issue if you believe this has not been resolved and reference the current issue.
