### ISSUE TITLE
Al Language Extensión not Working Kubuntu 20.04

### ISSUE THREAD

**Issue by Entreri86** [microsoft/AL#5992]
**Describe the bug**

When I try to use the VsCode AL Language extension, no command of the extension is activated nor does Intellisense work.

**To Reproduce**

1. Run VsCode on Kubuntu 20.04.
2. Install the extension.
3. Open an AL folder or work environment.
4. Execute any command or perform Ctrl + Space

``` AL Code to reproduce the issue ```

**Expected behavior**

To be able to make extensions from Linux.

**Screenshots**

![image](https://user-images.githubusercontent.com/15688332/85928860-9dd5a280-b8b0-11ea-80af-59bbec4244ac.png)

[2020-06-27 19:26:26.071] [exthost] [error] [ms-dynamics-smb.al] provider FAILED
[2020-06-27 19:26:26.072] [exthost] [error] Error: Language client is not ready yet
	at LanguageClient.sendRequest (/home/entreri/.vscode/extensions/ms-dynamics-smb.al-5.0.288712/node_modules/vscode-languageclient/lib/client.js:1789:19)
	at LanguageClientImpl.sendRequest (/home/entreri/.vscode/extensions/ms-dynamics-smb.al-5.0.288712/out/src/services/languageClientImpl.js:12:36)
	at ServerProxy.sendRequestInternal (/home/entreri/.vscode/extensions/ms-dynamics-smb.al-5.0.288712/out/src/services/serverProxy.js:53:42)
	at /home/entreri/.vscode/extensions/ms-dynamics-smb.al-5.0.288712/out/src/services/serverProxy.js:49:18
	at new Promise (<anonymous>)
	at ServerProxy.sendRequest (/home/entreri/.vscode/extensions/ms-dynamics-smb.al-5.0.288712/out/src/services/serverProxy.js:48:16)
	at AlDefinitionProvider.<anonymous> (/home/entreri/.vscode/extensions/ms-dynamics-smb.al-5.0.288712/out/src/services/alDefinitionProvider.js:47:37)
	at Generator.next (<anonymous>)
	at fulfilled (/home/entreri/.vscode/extensions/ms-dynamics-smb.al-5.0.288712/out/src/services/alDefinitionProvider.js:8:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**5. Versions:**
- VsCode: Versión: 1.46.1
Confirmación: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Fecha: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
Sistema Operativo: Linux x64 5.4.0-39-generic

 - AL Language: v5.0.288712

 - Business Central:

All

**Comment by AndreyKorepanov** [comment]
Hi @Entreri86, thank you for reporting the issue. Unfortunately, BC/AL is not supported for Linux, so I'll close the issue.
In your case, it seems the LSP server is not running (AL extension runs it when you start VSCode), you can check it in htop/atop/ps, check if the .Net framework of the right version is installed etc. etc.. 
We did not test the LSP server in Linux and we do not have any work planned for the upcoming release in this area. Please go ahead and post this to our Ideas forum at [https://aka.ms/BusinessCentralideas](https://aka.ms/BusinessCentralideas), or vote up the idea if its already there. This will help us allocate time and resources for improving this scenario.

**Comment by Entreri86** [comment]
Hi @AndreyKorepanov !

I have already opened the petition on the web you are commenting on. I will continue testing, in fact to get the capture error I had to change the file name
"Microsoft.Dynamics.Nav.EditorServices.Host.exe" to "Microsoft.Dynamics.Nav.EditorServices.Host" I imagine I will have to change paths, file names etc and testing.

Thank you very much for everything @AndreyKorepanov!
