### ISSUE TITLE
Connection to server got closed. Server will not be restarted

### ISSUE THREAD

**Issue by Pellic** [microsoft/AL#5993]
**Describe the bug**
Connection to server got closed. Server will not be restarted. 

**To Reproduce**
Steps and to reproduce the behavior:
1. Get artifact Get-BCArtifactUrl -country it -storageAccount bcinsider -sasToken $sasToken
2. Install vsix v6.0.285154 from the latest major IT artifact
When starting or creating a new project the extension stop to work after 5 attempt:
Connection to server got closed. Server will not be restarted. 
Full log:
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 44
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.Start(ChannelBase channel, MessageProtocolType messageProtocolType, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 156
[Info  - 11:29:39] Connection to server got closed. Server will restart.
[Error - 11:29:41] Connection to server is erroring. Shutting down server.
[Error - 11:29:41] Connection to server is erroring. Shutting down server.
[Error - 11:29:41] Connection to server is erroring. Shutting down server.
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 44
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.Start(ChannelBase channel, MessageProtocolType messageProtocolType, DiagnosticServiceOptions diagnosticServiceOptions) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 156

**Expected behavior**

**Screenshots**
<img width="337" alt="2020-06-28_11h30_03" src="https://user-images.githubusercontent.com/49358567/85944030-36613680-b934-11ea-8174-a678c8f09d84.png">

**5. Versions:**
 - AL Language: v6.0.285154 

 - Business Central:
    "country":  "IT",
    "database":  "BusinessCentral-IT.bak",
    "isBcSandbox":  true,
    "version":  "17.0.14257.0",
    "platform":  "16.0.13877.0"

**Comment by Pellic** [comment]
solved Downloading the latest major us platform and installing the 6.0.293448 of the ALLanguage.vsix.
