### ISSUE TITLE
'al/createPackage' failed with error: 'Part URI cannot contain a Fragment component.'

### ISSUE THREAD

**Issue by mboon75** [microsoft/AL#6022]
**Describe the bug**
Package creation fails with the message Part Uri cannot contain a Fragment component.
**To Reproduce**
It happens when i try to create my TestApp (with 248) files and is dependent on a couple of other apps.
The package is created, but upon Publish i get again the same error.
**Expected behavior**
A package should be created without problems
**Screenshots**
[Error - 11:19:58] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Part URI cannot contain a Fragment component.'
Details:
System.ArgumentException: Part URI cannot contain a Fragment component.
   at System.IO.Packaging.PackUriHelper.CreatePartUri(Uri partUri)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageWriter.GetOrCreatePackagePart(String packagedPath) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageWriter.cs:line 122
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageWriter.WriteBytes(Byte[] content, String path) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageWriter.cs:line 73
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageModuleOutputterBase.AddVariousValidFilesStatic(IFileSystem fileSystem, DiagnosticBag diagnostics, HashSet`1 writtenFiles, IPackageWriter writer, NavAppManifest manifest) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageModuleOutputterBase.cs:line 262
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageModuleOutputterBase.AddVariousValidFiles(IFileSystem fileSystem, DiagnosticBag diagnostics, HashSet`1 writtenFilesToPackage, IPackageWriter writer) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageModuleOutputterBase.cs:line 358
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageModuleOutputterBase.FinalizeModule() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageModuleOutputterBase.cs:line 136
   at Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageModuleOutputter.FinalizeModule() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Packaging\PackageModuleOutputter.cs:line 30
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.WriteToOutput(ModuleOutputter outputter, ModuleBuilder moduleBuilder, ModuleSymbol compiledModuleSymbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 893
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver, Predicate`1 filterOpt, Predicate`1 radCompilationFilter) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 728
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 529
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 476
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 332
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.Build(Project builtProject, StreamingTextWriter outputWriter, Boolean isRad, IList`1 args, CancellationToken cancellationToken, Boolean forceBuild, PooledList`1 outputFiles) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 173
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.HandleAsync(CreatePackageRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 102
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 54
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**5. Versions:**

 - AL Language: 5.0.288712

 - Business Central: NL Business Central 16.2 (platform 16.0.14073.14195 + toepassing 14.8.38650.0)

**Comment by qutreson** [comment]
Can you provide us with a project that would reproduce the issue?

**Comment by mboon75** [comment]
Yes, i can, but how? It is quite a project.

**Comment by qutreson** [comment]
Can you try to remove some files from the projects to have a smaller one that still reproduces the issue?

From the stack trace, it does not seem related to the AL files, but it looks more like an issue when writing one of the followings: Reports layout, Table data, Migration file, Translations, Entitlements,  Web Services, or Permissions. 

Can you try taking these out of your project and see whether creating the package succeeds? That would give us some better indication of where the issue is happening

**Comment by mboon75** [comment]
[Hello-World.zip](https://github.com/microsoft/AL/files/4934086/Hello-World.zip)
Hi i reproduced it with the attached project. It seems it is caused by the XML file with a # in the filename.

**Comment by atoader** [comment]
Thank you for the repro! I've marked this as a bug.
