### ISSUE TITLE
SOAP web service throws Object Disposed Exception

### ISSUE THREAD

**Issue by hbulens** [microsoft/AL#6047]
**Describe the bug**

I received two support tickets from customers who have experienced issues with NAV Web Services in Business Central 16. One uses version W1 16.0 (Platform 16.0.11233.12061 + Application 16.0.11240.12076) while the other is using 16.0.12630.12758. We also had a case with an older version but this was fixed by a CU update and the topic discussed [here](https://forum.mibuso.com/discussion/74072/nav-bc-soap-navuserpassword-error-216-http-500).

For one case it seems we solved the issue by bumping up the server with an extra core. The other case is slightly different in that Business Central is hosted on an Azure A2MV2 virtual machine.

**To Reproduce**

There is very little information on the subject. It seems that the SOAP service _sometimes_ works but most of the time it throws an exception. The only reliable information I can give is the stack trace:

Exception Type:  System.ObjectDisposed
Exception Message: Message is closed.

StackTrace:
     at System.ServiceModel.Channels.BufferedMessage.get_Headers()
     at Microsoft.Dynamics.Nav.Diagnostic.ServiceCallCorrelationProvider.GetCorrelationId[T](CorrelationIdType type)
     at Microsoft.Dynamics.Nav.Runtime.NavCurrentThread.get_GatewayCorrelationId()
     at Microsoft.Dynamics.Nav.Service.SOAP.ServiceDiagnosticState..ctor()
     at Microsoft.Dynamics.Nav.Service.SOAP.ServiceDiagnosticState..ctor(OperationContext context)
     at Microsoft.Dynamics.Nav.Service.SOAP.NavWebService.ProcessMessage(Message message)
     at SyncInvokeProcessMessage(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
Source: System.ServiceModel
HResult: -2146232798
StackTrace:
     at System.ServiceModel.Channels.BufferedMessage.get_Headers()
     at Microsoft.Dynamics.Nav.Diagnostic.ServiceCallCorrelationProvider.GetCorrelationId[T](CorrelationIdType type)
     at Microsoft.Dynamics.Nav.Runtime.NavCurrentThread.get_GatewayCorrelationId()
     at Microsoft.Dynamics.Nav.Service.SOAP.ServiceDiagnosticState..ctor()
     at Microsoft.Dynamics.Nav.Service.SOAP.ServiceDiagnosticState..ctor(OperationContext context)
     at Microsoft.Dynamics.Nav.Service.SOAP.NavWebService.ProcessMessage(Message message)
     at SyncInvokeProcessMessage(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

``` AL Code to reproduce the issue ```

**Expected behavior**

The SOAP web service should not throw a ObjectDisposedException.

**Screenshots**
N/A

**5. Versions:**
 W1 16.0 (Platform 16.0.11233.12061 + Application 16.0.11240.12076) and 16.0.12630.12758.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by hendrik244** [comment]
Hi @hbulens,

have you managed to fix this problem somehow?
I'm also currently facing the same issue.

Best regards,
Hendrik

**Comment by hbulens** [comment]
So far we've always been able to solve the issue by bumping up the vCPUs to at least two. Not sure how relevant or effective this workaround is but it seems to do the trick.
