### ISSUE TITLE
Issues when sending Customer Statement (report 1316) in BC OnPrem 15.2

### ISSUE THREAD

**Issue by kelba** [microsoft/AL#6068]
Hi,

We have a customer on BC 15.2 (onPrem) who is experiencing some issues when using report 1316 in BC. 
After filling out the Request Page and submitting, following error occurs:
The error, Initialization of allowed secret names failed., occurred when running report  for Customer: 205.

The error only occurs when choosing Email as Report Output. The e-mail containing the Customer Statement is sent and received by the customer even though the error appears. 

I've attached files containg the request page, Report Selection - sales page, errors in the event viewer and the error in BC.

Thansks

![Page Inspection](https://user-images.githubusercontent.com/48053302/89280774-6abdc600-d649-11ea-8694-6fed257dc4ab.png)
![Report Selection](https://user-images.githubusercontent.com/48053302/89280789-6e514d00-d649-11ea-93c8-bbc0e8dd82e6.png)
![Error BC Client](https://user-images.githubusercontent.com/48053302/89280815-76a98800-d649-11ea-8717-9c81704276f9.png)
![BC Version](https://user-images.githubusercontent.com/48053302/89280984-afe1f800-d649-11ea-9105-7433f81b03ba.png)
![Document Layouts](https://user-images.githubusercontent.com/48053302/89281260-1e26ba80-d64a-11ea-93f9-f7bf0bc35470.png)
![Event Viewer Error](https://user-images.githubusercontent.com/48053302/89280583-1ca8c280-d649-11ea-8207-0cef460b0124.png)

Event Viewer Warning

Server instance: TEST
Category: Runtime
ClientSessionId: 223e4423-4460-4c74-b184-fe761fef4892
ClientActivityId: b35be20e-c5ce-45fa-9c88-4c20a4af6bac
ServerSessionUniqueId: 360cddf0-8f04-4f09-a4d6-76b9d09e7e48
ServerActivityId: 6f57ab8f-7b24-428c-a323-671494c535f7
EventTime: 08/04/2020 09:37:58
Message (Exception): This message had personal data removed. The original may still be in transient telemetry. Find it using the transientTelemetryId.
DotNet invoke error. SessionID:950, Interface:, type:Microsoft.Dynamics.Nav.AzureKeyVaultClient.AzureKeyVaultClientHelper, methodName:GetAzureKeyVaultSecret
RootException: Exception
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.AzureKeyVaultClient.AzureKeyVaultClientHelper.InvokeKeyVaultProviderMethod[T](Func`2 method)
   at Microsoft.Dynamics.Nav.AzureKeyVaultClient.AzureKeyVaultClientHelper.GetAzureKeyVaultSecret(String SecretName)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.CreateNavNCLDotNetInvokeException(String tag, Type interfaceType, String methodName, NavServerHandle serverHandle, Exception e)
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.Invoke[T](String methodName, UInt32 methodIndex, BindingFlags flags, ParameterModifier modifier, Type[] referenceTypes, Object[] arguments)
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.InvokeMethod[T](Boolean isStatic, String methodName, UInt32 methodIndex, Object[] arguments)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.GetSecretFromClient_Scope__1519509596.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.GetSecretFromClient(NavText secretName)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.TryGetSecretFromClient_Scope__1846897473.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.TryGetSecretFromClient(NavText secretName, ByRef`1 secret)
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBase.TryInvoke(Action method)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.InitializeAllowedSecretNames_Scope_1274067374.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.InitializeAllowedSecretNames()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.GetAzureKeyVaultSecret_Scope__221275149.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.GetAzureKeyVaultSecret(NavText secretName, ByRef`1 secret)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2202.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2200.GetAzureKeyVaultSecret_Scope_1425141621.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2200.GetAzureKeyVaultSecret(NavText secretName, ByRef`1 secret)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2200.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit405.HasConfiguration_Scope__650492449.<OnRun>b__12_0()
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBase.TryInvoke(Action method)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit405.HasConfiguration_Scope__650492449.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit405.HasConfiguration()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit405.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit9520.IsGraphEnabled_Scope_370600253.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit9520.IsGraphEnabled()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit9520.IsEnabled_Scope__2119307240.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit9520.IsEnabled()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit9520.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit9520.SendMailOrDownload_Scope__1340223826.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit9520.SendMailOrDownload(INavRecordHandle tempEmailItem, Boolean hideMailDialog)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit9520.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Record9500.Send_Scope_1963862941.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record9500.Send(Boolean hideMailDialog)
   at Microsoft.Dynamics.Nav.BusinessApplication.Record9500.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit260.EmailFileInternal_Scope__361068727.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit260.EmailFileInternal(INavRecordHandle tempEmailItem, NavText attachmentFilePath, NavText attachmentFileName, NavText htmlBodyFilePath, NavText emailSubject, NavText toEmailAddress, NavCode postedDocNo, NavText emailDocName, Boolean hideDialog, Int32 reportUsage, Boolean isFromPostedDoc, NavCode senderUserID)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit260.EmailFile_Scope_1331259511.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit260.EmailFile(NavText attachmentFilePath, NavText attachmentFileName, NavText htmlBodyFilePath, NavCode postedDocNo, NavText toEmailAddress, NavText emailDocName, Boolean hideDialog, Int32 reportUsage)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit260.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.TryEmailReport_Scope_633716814.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.TryEmailReport(NavText tempFilePath, NavText fileName, NavText tempEmailBodyFilePath, INavRecordHandle customReportSelection, ByRef`1 fieldRef2)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.EmailReport_Scope__1959335716.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.EmailReport(ByRef`1 dataRecRef, Int32 reportID, INavRecordHandle customReportSelection)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.RunReportWithCustomReportSelection_Scope_803708992.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.RunReportWithCustomReportSelection(ByRef`1 dataRecRef, Int32 reportID, INavRecordHandle customReportSelection, Boolean emailPrintIfEmailIsMissing)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.ProcessReportPerObject_Scope__1927151248.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.ProcessReportPerObject()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.ProcessReport_Scope_426399378.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.ProcessReport()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.ProcessReportForData(Int32 reportSelectionUsage, ByRef`1 dataRecordRef, NavText sourceJoinFieldName, Int32 dataRecordJoinTable, NavText iteratorTableFieldName, Boolean dataItemTableSameAsIterator)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8800.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8810.RunReport_Scope_1654794699.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8810.RunReport()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit8810.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Report153.OnInitReport_Scope.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Report153.OnInitReport()
   at Microsoft.Dynamics.Nav.Runtime.DataItemIterator.ExecuteTrigger(NavTrigger reportTriggerDelegate)
   at Microsoft.Dynamics.Nav.Runtime.NavReport.EndInitialization()
   at Microsoft.Dynamics.Nav.BusinessApplication.Report153.InitializeComponent()
   at Microsoft.Dynamics.Nav.BusinessApplication.Report153.__Construct(ITreeObject parent, NCLMetaReport metadata)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaReport.CreateObjectInstance(ITreeObject parent, Boolean skipRestoreSavedReportSettings)
   at Microsoft.Dynamics.Nav.Runtime.NavReport.RunReport(Int32 reportId, Nullable`1 requestWindow, Nullable`1 systemPrinter, Boolean isRunningAsModal, NavRecord record, IList`1 textualFilters, RunMode runMode)
   at Microsoft.Dynamics.Nav.Runtime.NavReport.Run(Int32 reportId)
   at Microsoft.Dynamics.Nav.Service.NSService.RunReport(ApplicationMethodRequest applicationMethodRequest)
   at SyncInvokeRunReport(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationDuration(Stopwatch stopWatch, Action action)
   at Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationAction(Action action, NavSession session)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(Boolean& alreadyResumedNoLock)
   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProcessing(IResumeMessageRpc resume)
   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

ProcessId: 6592
Tag: 000016L
ThreadId: 144
CounterInformation: 
CustomParameters: b99a97e1-e3bb-4729-8af9-25ea9017ce32

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
