### ISSUE TITLE
If a referenced workspace folder does not exist (i.e. test), AL Language fails to load

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#6104]
**Describe the bug**
If a referenced workspace folder does not exist (i.e. test), AL Language fails to load.

**To Reproduce**
Steps and to reproduce the behavior:
1. Use an existing AL workspace file and add a non existing path
```
{
	"folders": [
[...]
		{
			"path": "dumb",
			"name": "DUMB"
		}
	],
}

 ```
2. Open the workspace with VSCode
3. After a while, try try to find palette entry AL: Download Symbols. It is missing.

This is caused by the following issue:
```
[exthost] [error] Error: ENOENT: no such file or directory, mkdir 'c:\Temp\FavoriteApp\dumb\.snapshots'
	at mkdirSync (fs.js:764:3)
	at fs.mkdirSync (electron/js2c/asar.js:687:16)
	at Object.fs.mkdirSync (electron/js2c/asar.js:687:16)
	at SnapshotDebuggerService.getSnapshotOutputDirectoryFromFolder (c:\Users\dumbuser\.vscode\extensions\ms-dynamics-smb.al-6.0.314405\out\src\services\snapshotDebuggerService.js:242:18)
	at SnapshotDebuggerService.updateWithExistingSnapshots (c:\Users\dumbuser\.vscode\extensions\ms-dynamics-smb.al-6.0.314405\out\src\services\snapshotDebuggerService.js:375:42)
	at SnapshotDebuggerService.activate (c:\Users\dumbuser\.vscode\extensions\ms-dynamics-smb.al-6.0.314405\out\src\services\snapshotDebuggerService.js:76:14)
	at c:\Users\dumbuser\.vscode\extensions\ms-dynamics-smb.al-6.0.314405\out\src\extension.js:106:38
	at Array.forEach (<anonymous>)
	at AlExtension.activateServices (c:\Users\dumbuser\.vscode\extensions\ms-dynamics-smb.al-6.0.314405\out\src\extension.js:106:23)
	at activate (c:\Users\dumbuser\.vscode\extensions\ms-dynamics-smb.al-6.0.314405\out\src\extension.js:40:31)
	at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:877:509)
	at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:877:160)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:875:492
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
 ```

**Expected behavior**
AL Language extension should properly initialize, even if a path is not found.

**Screenshots**

**5. Versions:**
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 6.0.314405
Publisher: Microsoft

**Comment by kalberes** [comment]
Thanks for finding it. This will be fixed in one of the next internal docker releases.
