### ISSUE TITLE
Error when case statement has the constant 0D in a condition

### ISSUE THREAD

**Issue by jose-lloret** [microsoft/AL#6136]
**Describe the bug**
Discover a bug in the compiler when a case statement has the constant 0D in the condition. 

**To Reproduce**
This is our AL code in a codeunit:

```al
case FechaTope of
0D:
    if (gsidparvar.GsiFAltOPA <> 0D) and (gsidparvar.Gsifbajopa = 0D) and (gsidparvar.GsiEstadoPlantacion <> gsidparvar.GsiEstadoPlantacion::GsiBaja) then
        suma_varietal := suma_varietal + gsidparvar.Gsiusuperf;
else
    if ((gsidparvar.Gsifaltopa <> 0D) and (gsidparvar.Gsifbajopa = 0D) and (gsidparvar.GsiEstadoPlantacion <> gsidparvar.GsiEstadoPlantacion::GsiBaja)) or ((gsidparvar.Gsifaltopa <> 0D) and (gsidparvar.Gsifbajopa <> 0D) and (gsidparvar.Gsifbajopa > FechaTope)) then
        suma_varietal := suma_varietal + gsidparvar.Gsiusuperf;
end;
```

It compiles in VSCode and is sent to the server without any errors or warnings.

This is the C# generated in the server:

```c#
case NavDate.Create(0U):
    if (CStmtHit(47) & ((((NavDate)this.gsidparvar.Target.GetFieldValueSafe(9, NavType.Date)) != NavDate.Create(0U)) & (((NavDate)this.gsidparvar.Target.GetFieldValueSafe(10, NavType.Date)) == NavDate.Create(0U)) & (((NavOption)this.gsidparvar.Target.GetFieldValueSafe(22, NavType.Option)) != NavOption.Create(((NavOption)this.gsidparvar.Target.GetFieldValueSafe(22, NavType.Option)).NavOptionMetadata, 1))))
    {
        StmtHit(48);
        this.suma_varietal = this.suma_varietal + this.gsidparvar.Target.GetFieldValueSafe(16, NavType.Decimal).ToDecimal();
    }

    break;
default:
    if (CStmtHit(49) & (((((NavDate)this.gsidparvar.Target.GetFieldValueSafe(9, NavType.Date)) != NavDate.Create(0U)) & (((NavDate)this.gsidparvar.Target.GetFieldValueSafe(10, NavType.Date)) == NavDate.Create(0U)) & (((NavOption)this.gsidparvar.Target.GetFieldValueSafe(22, NavType.Option)) != NavOption.Create(((NavOption)this.gsidparvar.Target.GetFieldValueSafe(22, NavType.Option)).NavOptionMetadata, 1))) | ((((NavDate)this.gsidparvar.Target.GetFieldValueSafe(9, NavType.Date)) != NavDate.Create(0U)) & (((NavDate)this.gsidparvar.Target.GetFieldValueSafe(10, NavType.Date)) != NavDate.Create(0U)) & (((NavDate)this.gsidparvar.Target.GetFieldValueSafe(10, NavType.Date)) > this.fechaTope))))
    {
        StmtHit(50);
        this.suma_varietal = this.suma_varietal + this.gsidparvar.Target.GetFieldValueSafe(16, NavType.Decimal).ToDecimal();
    }

break;
```
When any of the functions of the codeunit is called an error occurs:

```text
Server instance: BC
Category: Extensions
ClientSessionId: 89011bdc-4b69-4a7c-986f-ff3de85e8bad
ClientActivityId: a99a9dfe-64d0-4586-9328-71f95827da4d
ServerSessionUniqueId: f86717f9-8676-4540-9ffb-c919f9608992
ServerActivityId: c4c9812f-380d-412c-a4a5-f1a18c4bc3d0
EventTime: 09/11/2020 15:00:42
Message (InvalidOperationException): RootException: InvalidOperationException
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\160\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\20\2023472D0B5217F829AFFF488F7DB65F1B31F3C18B175DE893E8D33807AEF203.cs(1649,46): error CS0150: A constant value is expected
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\160\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\20\2023472D0B5217F829AFFF488F7DB65F1B31F3C18B175DE893E8D33807AEF203.cs(1704,46): error CS0150: A constant value is expected

CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.GetClrType(RuntimePackageId runtimePackageId, ApplicationObjectId objectId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.CompileAndLoadClrObject()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
   at Microsoft.Dynamics.Nav.Runtime.NavCodeunitHandle.CreateTarget()
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBaseHandle`1.get_Target()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record7049932.NumFincaUnico_Scope_957391224.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record7049932.NumFincaUnico()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record7049932.OnInsert_Scope.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Record7049932.OnInsert()
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.Insert(DataError errorLevel, Boolean runApplicationTrigger, Boolean runGlobalTrigger, Boolean insertWithSystemId)
   at Microsoft.Dynamics.Nav.Runtime.NavForm.SaveRecord()
   at Microsoft.Dynamics.Nav.Runtime.NavForm.UpdateCore(NavFormUpdateTypes updateType, Boolean saveRecord)
   at Microsoft.Dynamics.Nav.BusinessApplication.Page7049940.GsiNumFinca_a45_OnAssistEdit_Scope.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Page7049940.GsiNumFinca_a45_OnAssistEdit()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
   at Microsoft.Dynamics.Nav.Service.NSField.AssistEditField(NavSession session)
   at Microsoft.Dynamics.Nav.Service.NSField.AssistEdit(NavSession session)
   at SyncInvokeAssistEdit(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(Boolean& alreadyResumedNoLock)
   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProcessing(IResumeMessageRpc resume)
   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

The 1649 and 1704 lines that the error is referring to are the same in the C# script:

```c#
case NavDate.Create(0U):
```

Replacing in the AL code the `case` with an `if` statement works fine.

**Expected behavior**
The application should run smoothly and it isn't when a function in the codeunit is called.

**Screenshots**
No applicable

**5. Versions:**

 - AL Language: v5.0.329509

 - Business Central: ES Business Central 16.5 (Platform 16.0.15884.16418 + Application 16.5.15897.16460)

**Comment by qutreson** [comment]
Hi @jose-lloret, thank you for reporting this issue. I can reproduce it with this code, when running the action on the page:

```
page 50100 MyPage
{
    actions
    {
        area(Processing)
        {
            action(MyAction)
            {
                RunObject = codeunit MyCodeunit;
            }
        }
    }
}

codeunit 50100 MyCodeunit
{
    trigger OnRun()
    var
        dateVar: Date;
    begin
        dateVar := 0D;
        case dateVar of
            0D:
                Message('0D');
            else
                Message('Not 0D');
        end;
    end;
}
``` 

As you mentioned, using an `if` instead of a `case` works and provide a workaround while waiting for this bug to be fixed.
