### ISSUE TITLE
"Invalid URI" error after connecting to VS Code Live Share for AL project

### ISSUE THREAD

**Issue by steveendow** [microsoft/AL#6139]
**Describe the bug**
When I connect to a VS Code Live Share session that is hosting an AL project, VS Code connects, displays the AL project files, and appears to successfully display the live share session, but the AL Language Extension repeatedly displays this "A request has failed" error.  The error only occurs on the "Guest" machine connecting to the live share session.  The "Host" machine where the AL Project resides does not display any errors.

The Live Share session and collaboration appear to work properly, but the AL Extension repeatedly records the errors.

This error info is recorded to the Output log each time the AL Language Extension error dialog appears:

```
[Error - 1:21:36 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/setActiveWorkspace' failed with error: 'Invalid URI: The format of the URI could not be determined.'
Details:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.PathUtilities.CreateUriFilePath(String filePath) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\PathUtilities.cs:line 398
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.CreateProjectInfo(String projectPath, String assemblyName, CompilationOptions options, ParseOptions parseOptions, String packageCachePath, String[] probingFolders, String ruleSetPath, IEnumerable`1 symbolReferences, ProjectDefinition projectDefinition) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 869
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.AddOrUpdateProjectFromPath(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, String dependencyParentProjectPath, Boolean forceCheckDependencies, LanguageClientCompilationOptions languageClientCompilationOptions, List`1& projectLoadingDiagnostics, Boolean& missingSymbols) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 102
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.TryAddOrUpdateProject(String projectPath, String packageCachePath, String[] assemblyProbingPaths, String ruleSetPath, String dependencyParentProjectPath, LanguageClientCompilationOptions languageClientCompilationOptions, IList`1& diagnostics, ProjectManifest& manifest, Boolean& missingSymbols) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 76
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ProjectRequestHandler`1.TryAddOrUpdateProject(SettingsRequest request, CancellationToken cancellationToken, ProjectManifest& manifest) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ProjectRequestHandler.cs:line 53
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SetActiveWorkspaceRequestHandler.HandleAsync(SettingsRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SetActiveWorkspaceRequestHandler.cs:line 26
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 43
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64
```

**To Reproduce**
Steps and to reproduce the behavior:

"Host" Machine:
1. VS Code v1.49.0 with only "AL Language" 5.0.329509 and "Live Share" 1.0.2740 extensions
1. F1 -> AL: Go to create new AL project
2. Set server and serverInstance values in launch.json
3. F1 -> AL: Download Symbols
4. CTRL+F5 to publish test application
5. Click on Live Share at bottom of VS Code to start collaboration session, click OK on dialog
6. Copy live share URL and share with Guest machine

On "Guest" machine:
1. VS Code v1.49.0 with only "AL Language" 5.0.329509 and "Live Share" 1.0.2740 extensions
2. Paste live share URL in browser
3. Click through any prompts to launch VS Code and start live share, sign in on Guest machine if necessary
4. Wait for AL project files to display in Explorer pane and for active file to be displayed
5. Cursor and highlighting should appear to work properly and live share should appear to be active
6. Notification message will appear in bottom right corner of VS code: "A request has failed. See the output for more information.  Source: AL Language (Extension)"

``` Basic AL: Go project with correct server and serverInstance settings, no other changes ```

**Expected behavior**
AL Language Extension errors should not occur

**Screenshots**
![image](https://user-images.githubusercontent.com/11199908/93004778-1dadf900-f4ff-11ea-8b28-ff2b791a82a6.png)

![image](https://user-images.githubusercontent.com/11199908/93004785-31595f80-f4ff-11ea-95eb-6bd920f5adfe.png)

**5. Versions:**
 - VS Code:  v1.49.0  with "Live Share" 1.0.2740 extension
 - AL Language:  5.0.329509
 - Business Central:  (on Docker) US Business Central 16.5 (platform 16.0.15884.16508 + Application 16.5.15897.16521)

**Comment by kalberes** [comment]
I am not sure we support live sharing. Was this ever supported?

**Comment by steveendow** [comment]
After the errors occur for the 'remote' viewers, the Live Sharing session of an AL project appears to work well with multiple viewers, at least for viewing, cursor/code selection, and editing.  I have not yet tried build or publish operations in the remote sessions.

I submitted this issue to see if the error messages could be researched and/or resolved, but if there isn't yet formal support for Live Share with AL projects, I think it would be great to have the VS Code feature formally supported.

I'm happy to assist with research and testing if there is any additional information I can help to collect.

**Comment by kalberes** [comment]
Thanks,
Looks a bigger issue. Unfortunately we have a strong coupling for a local file based architecture. Our workspace, projects system, RAD, publishing you name it,  all rely on physical files to be present under the hood.
We will see what can we do.

**Comment by atoader** [comment]
Removing the in-progress tag and putting it back on the backlog.
