### ISSUE TITLE
In-app designer: Client needs restart when using F6 from VSCode

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#619]
As described on the June Update blog:
> Pressing F6 in Visual Studio Code will open the current extension and allow you to add more changes using the in-app designer. For example, start in VS Code, define a page extension, press F6 to open the web client, then use the in-app designer to move the fields around and finally save your extension to files.

Now on the August Update the (Web) Client crashes and urges me to restart is with that beautiful blue page.
Maybe I am missing something, but it seems a bug to me.

**Note**
I did provide a startupObjectId in the launch.json.

**Comment by lvanvugt** [comment]
**Some more details**
1. I am using the Hello World example (unmodified)
2. Pressing F6 gives the situation as described above
3. The event viewer yields the following error: 
> Error accessing Website Microsoft Dynamics NAV TENERIFE Web Client
> Raw Url: /US/WebClient/cbs?aid=FIN
> Url: http://localhost:8080/US/WebClient/cbs?aid=FIN
> Type: Microsoft.Dynamics.Nav.Types.GenericException
> Message: Codeunit 'HelloWorld' is missing
> StackTrace:
>    at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectFailedEventArgs connectFailedArgs, ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, SpnSetting spnSettingToTry, Boolean allowSpnSettingsSwap, UserSettings& userSettings)
>    at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, UserSettings& userSettings)
>    at Microsoft.Dynamics.Nav.Client.ServiceConnection.OpenConnection()
>    at Microsoft.Dynamics.Nav.Client.ServiceConnection.Initialize()
>    at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSessionInitializer.OpenConnectionToServer()
>    at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSessionInitializer.InitializeCore()
>    at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSessionInitializer.Initialize()
>    at Microsoft.Dynamics.Framework.UI.UISession.Initialize()
>    at Microsoft.Dynamics.Nav.Client.Web.NavWebUISessionInitializer.InitializeCore(UISession session)
>    at Microsoft.Dynamics.Nav.WebClient.NavWebClientUISessionInitializer.InitializeCore(UISession session)
>    at Microsoft.Dynamics.Nav.Client.Web.NavWebUISessionInitializer.Initialize(UISession session)
>    at Microsoft.Dynamics.Framework.UI.Client.OpenFormExecutionStrategy.TryInitializeUiSession(UISession session)
>    at Microsoft.Dynamics.Framework.UI.Web.WebOpenFormExecutionStrategy.TryInitializeUiSession(UISession session)
>    at Microsoft.Dynamics.Framework.UI.Client.OpenFormExecutionStrategy.Execute()
>    at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_0.<InvokeInteractions>b__3()
> Source: Microsoft.Dynamics.Nav.Client.ServiceConnection----------------------------------
> Type: Microsoft.Dynamics.Nav.Types.GenericException
> Message: Codeunit 'HelloWorld' is missing

**Comment by lvanvugt** [comment]
Funny as the HelloWorld.al file with the codeunit 70051001 HelloWorld is clearly in the project folder. And when running the code by clicking Ctrl+F5 everything works just fine.
