### ISSUE TITLE
Value cannot be null. (Parameter 'projectId'

### ISSUE THREAD

**Issue by Riccarr** [microsoft/AL#6262]
**Describe the bug**
Error generated in the VS Code output log: Value cannot be null. (Parameter 'projectId'
Aside from the output error message there are no other side effects. Continued use of the editor is not affected.

Details:
System.ArgumentNullException: Value cannot be null. (Parameter 'projectId')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Solution.GetProject(ProjectId projectId) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\Solution.cs:line 284
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.EnsureCompilationContextIsSet(CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 163
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDefinitionForSymbolAtPositionAsync(Uri previewUri, Position requestPosition, LaunchConfiguration configuration, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 99
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.ProcessRequestAsync(AlDefinitionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**To Reproduce**
Steps and to reproduce the behavior:
1. Randomly focusing the editor tab/changing from one tab to another, and/or initiating a search will generate this error in VS Code Output log

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: v6.1.359074

 - Business Central:

**Comment by PooyaKharamesh** [comment]
Please add a  sample project that clearly reproduces the Issue ?  what do you mean by initiating a search e.g. search in the content of a file, search in the symbols, search in all files content, searching file names and  ...

**Comment by Riccarr** [comment]
In response to your question, a CTRL-F search for string in the current editor tab.]
I'm not sure how to add a project here. I'll look.
Otherwise I would ask you, based on the exception output I pasted above, to check Parameter 'projectId' at **Solution.cs:line 284** and work backward from there to find a hole in the logic that allows a null to be passed to that variable.

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.
