### ISSUE TITLE
Error: Specified argument was out of the range of valid values. (Parameter 'index') during Publish BC170

### ISSUE THREAD

**Issue by guidorobben** [microsoft/AL#6280]
**Describe the bug**
During publishing of my BC170 App I get the following error:

[Error - 15:37:57] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeAction' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'
Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 661
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 67
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SourceTextExtension.GetTextSpan(SourceText sourceText, Range range) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SourceTextExtension.cs:line 16
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeActionRequestHandler.HandleAsync(ProtocolCodeActionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeActionRequestHandler.cs:line 59
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

_D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 661
I would like to know where I can find this file on My PC so I can see the object that is causing this._

**To Reproduce**
Steps and to reproduce the behavior:
1. Open My App
2. CTRL+F5

After that I takes a long time to get this error. The App is never published

``` AL Code to reproduce the issue ```
This I my complete App. I can send you the package or the complete source code

I you need more info let me know.
**Expected behavior**
My App should have been published and the Web client should start

And I wou
**Screenshots**

**5. Versions:**

 - AL Language:  v6.1.362735

 - Business Central: BC170

Cannot find the Item **System Information** in BC170

**Comment by guidorobben** [comment]
I deleted my .alcache folder and tried again. No luck.

**Comment by atoader** [comment]
Can you provide a project to reproduce the issue?

**Comment by guidorobben** [comment]
This is our complete solution. How do you want it? Is the .App file enough? Can I upload it to somewhere secure?

It also gave a similar but different error:
Server instance: BC170
Category: Extensions
ClientSessionId: eb7dd04f-85e3-4865-bb9b-e97de4d9cab6
ClientActivityId: dec23c55-4fb1-4cca-963c-f088c4c2a51d
ServerSessionUniqueId: ff4e3b4b-0dc6-4d77-a34a-c5c8d0be334e
ServerActivityId: 52bc19f3-f559-4ab6-aeba-6125191b4df8
EventTime: 11/06/2020 09:05:28
Message App Sync Exception -- System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaTable.AssignFromMetaTable(MetaTable metaTable, Boolean databaseConvertedFromNav2013, Boolean isAppArchiveTable)
   at Microsoft.Dynamics.Nav.Runtime.Apps.SyncTableBundler.ProcessRawMatchComponents(NavAppRuntimeMetadata targetApp, MetaTable targetTable, AppSyncSnapshotRecord snapshotRecord, List`1 filters, List`1 tableBundles, MigrationType migrationType, TableType targetTableType)
   at Microsoft.Dynamics.Nav.Runtime.Apps.SyncTableBundler.CreateTableBundles(NavAppRuntimeMetadata targetApp, IEnumerable`1 targetAppTables, IEnumerable`1 snapshotsForApp, IEnumerable`1 filters, Boolean allowIdFallback, List`1 migrationTargets, Dictionary`2 nonstructuralTables)
   at Microsoft.Dynamics.Nav.Runtime.Apps.SyncTableBundler.CreateTableBundles(NavAppSyncMode mode, NavAppRuntimeMetadata targetApp, IEnumerable`1 targetAppTables, IEnumerable`1 snapshotsForApp, IEnumerable`1 filters, List`1 migrationTargets, Dictionary`2 nonstructuralTables)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.SynchronizeTenantDatabaseForAppSyncInternal(NavSession session)
ProcessId: 21716
Tag: 00001X1
ThreadId: 336
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId:

**Comment by atoader** [comment]
A .zip of the folder would be ideal. Thanks!

**Comment by guidorobben** [comment]
is there any way I send send this to you securely?

**Comment by guidorobben** [comment]
I have a zip file, but is there any way I send send this to you securely?

**Comment by atoader** [comment]
We can only accept repros that can be shared publicly on GitHub.

**Comment by guidorobben** [comment]
Well then it ends here. I'm not going to put our complete solution on Github. Let me know if you have more tips on how I can find out on what is causing this issue. But know that this strange issues is not helping our whole process of going from C/AL to AL. My first experience has not been a good one.

**Comment by atoader** [comment]
We will take this as a bug and use it to include more telemetry and a better error message. Hopefully that will help in the future with tracing what is causing this.

**Comment by guidorobben** [comment]
BC17.1 didn't solve my problem.

**Comment by guidorobben** [comment]
I found the issue. I had a table extension that adds a Key that has the same name as the primary key. The property enabled=false causes the issue. Renaming the key or setting it true solves the problem. Looking at the help for naming guidelines, ik looks like MS took the easy way out with this. Why isn't using their own guidelines? 

![image](https://user-images.githubusercontent.com/11609736/98788670-88958680-2401-11eb-8137-87eb1a2cb893.png)
