### ISSUE TITLE
Error: AccessByPermission on XMLport causes Publish Error

### ISSUE THREAD

**Issue by guidorobben** [microsoft/AL#6304]
**Describe the bug**
Message (InvalidOperationException): ParentException: InvalidOperationException

There is an error in the XML document.

ExceptionStackTrace:

   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)

   at Microsoft.Dynamics.Nav.Types.Metadata.MetaPage.CreatePageDefinition(XmlDocument pageDocument, Int32 languageAppGroupId)

   at Microsoft.Dynamics.Nav.Runtime.NCLObjectMetadataLoaderExtensions.RetrieveRuntimeObject[T](INCLObjectXmlMetadataLoader loader, ObjectType objectType, Int32 objectId, NavAppGroup appGroup, Func`3 exceptWrapperGenerator, Func`2 objectGenerator)

   at Microsoft.Dynamics.Nav.Runtime.NCLObjectMetadataLoaderExtensions.GetMetaPage(INCLObjectXmlMetadataLoader loader, Int32 pageId, NavAppGroup appGroup, Int32 languageAppGroupId)

   at Microsoft.Dynamics.Nav.Runtime.NCLMetaForm.LoadPageMetadata()

   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroupNewObject(NavAppGroup appGroup, NavAppGroupObjectMetadataSummary newObjectSummary, NavAppGroupInitializationType initializationType)

   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeNewAppObjectsExceptQueries(NavAppGroup appGroup, InitializeAppGroupProfilerSession profilerSession, IReadOnlyList`1 newObjectsFromApps, NavAppGroupInitializationType initializationType)

   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroupObjects(NavAppGroup appGroup, IReadOnlyList`1 extensionSummariesWeCareAbout, IReadOnlyList`1 newObjectsFromApps, IReadOnlyList`1 baseObjectsModifiedBySomething, NavAppGroupInitializationType initializationType)

   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroup(NavAppGroup appGroup, Boolean initializeOwnedObjectsOnly)

   at Microsoft.Dynamics.Nav.Runtime.NavAppSyncManagementTasks.SynchronizeTenantDatabaseForApp(SyncPrecheckHelper precheckHelper, IEnumerable`1 allPublished, List`1 allSynced, NavTenant tenant, NavAppSyncMode mode, String activityId)

   at Microsoft.Dynamics.Nav.Runtime.NavAppSyncManagementTasks.SyncNavApp(SyncNavAppArguments args)

InnerException:

RootException: InvalidOperationException

Instance validation error: 'XmlPort' is not a valid value for AccessByObjectType.

ExceptionStackTrace:

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPageDefinition.Read13_AccessByObjectType(String s)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPageDefinition.Read62_ActionDefinition(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPageDefinition.Read74_ActionBaseDefinition(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPageDefinition.Read65_ActionGroupDefinition(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPageDefinition.Read74_ActionBaseDefinition(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPageDefinition.Read75_ActionContainerDefinition(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPageDefinition.Read105_PageDefinition(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPageDefinition.Read106_PageDefinition()

CallerStackTrace:

   at Microsoft.Dynamics.Nav.Runtime.NavAppSyncManagementTasks.SyncNavApp(SyncNavAppArguments args)

   at Microsoft.Dynamics.Nav.Service.NSAdminService.<>c__DisplayClass142_0.<Microsoft.Dynamics.Nav.Types.ITenantDatabaseManagementService.SyncNavApp>b__0()

   at Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.<>c__DisplayClass2_0`1.<RetryOperationWithTransientError>b__0()

   at Microsoft.Dynamics.Nav.Runtime.NavSqlTransientErrorHelper.InternalRetryOperationWithTransientError[T](Action operation, Int32 maxRetryCount, Int32 retryIntervalInSeconds, String callerName, String additionaInfo, Boolean expectedType)

 Turns out that adding a AccessByPermission on a XmlPort causes this. Isn't this allowed anymore or is this a bug in the compiler?

![image](https://user-images.githubusercontent.com/11609736/99371073-be81b180-28be-11eb-8fac-cfb54ad921c5.png)

**To Reproduce**
Steps and to reproduce the behavior:

add AccessByPermission = XMLport "Import Equip. Maint. Centix"=X on a Action in a RoleCenter

``` AL Code to reproduce the issue ```

**Expected behavior**
It would publish. Building works

**Screenshots**
![image](https://user-images.githubusercontent.com/11609736/99371088-c2153880-28be-11eb-8d8f-349398be4508.png)

**5. Versions:**

 - v6.1.362735: 

 - 17.1

**Comment by guidorobben** [comment]
this one should probably be in ALAppExtensions. Can someone move this?

**Comment by atoader** [comment]
It's at the right place. It is a bug in the AL compiler. We are working on a fix.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 20342 and VS Code Extension Version 7.0.389704. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
