### ISSUE TITLE
System.OperationCanceledException

### ISSUE THREAD

**Issue by mickcarr** [microsoft/AL#6326]
Compiler reports an error in VS Code output when using IntellieSense and starts behaving erratically after the exception is thrown, for example any subsequent attempts to render the IntellieSense prompt fail with the same error.

**To Reproduce**
There's no specific code to reproduce the issue, only seems to happen occasionally when editing any AL file. File path is 99 chars long. This has been removed from the example.

```
Processing of message 'textDocument/codeAction' failed with error: 'An unexpected error happened when processing the document '<filepath removed>' at position 'Line: 9 - Character: 42'. Left token: 'Codeunit'. Target token: 'Codeunit'. Right token: 'librar'. 
Exception details: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.TextCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\TextCompletionProvider.cs:line 38
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"'
Details:
Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionException: An unexpected error happened when processing the document '<filepath removed>' at position 'Line: 9 - Character: 42'. Left token: 'Codeunit'. Target token: 'Codeunit'. Right token: 'librar'. 
Exception details: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.TextCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\TextCompletionProvider.cs:line 38
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.CreateSpellCheckCodeIssueAsync(CodeFixContext context, SyntaxToken nameToken, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 139
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.CheckNodeAsync(CodeFixContext context, Document document, SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 87
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.RegisterCodeFixesAsync(CodeFixContext context) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 67
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(Document document, TextSpan span, ICodeFixProvider fixer, ImmutableArray`1 diagnostics, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 149
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.AppendFixesAsync(Document document, TextSpan span, IEnumerable`1 diagnosticsWithSameSpan, ArrayBuilder`1 result, ICodeFixProvider fixer, Func`2 hasFix, Func`2 getFixes, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 131
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.AppendFixesAsync(Document document, TextSpan span, IEnumerable`1 diagnostics, ArrayBuilder`1 result, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 92
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.GetFixesAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 69
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeActions.ALCodeActionService.GetCodeActionsAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeActions\ALCodeActionService.cs:line 60
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeActionRequestHandler.HandleAsync(ProtocolCodeActionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeActionRequestHandler.cs:line 59
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80
```

**Expected behavior**
IntellieSense should render without raising the System.OperationCanceledException in the VS Code output panel.

**Screenshots**
N/A

**5. Versions:**

 - AL Language: v6.1.362735

 - Business Central: Platform 14.0.44656.0 + Application 44663 (GB Business Central 14.17)

**Comment by g021670** [comment]
Same issue here. 

Any suggestions ?

**Comment by rovelgoenne** [comment]
same issue 

AL Language: newest and v6.1.350698
Platform and Application BC 17.1
17.0.18204

**Comment by TroelsMuffThygesen** [comment]
Same issue. 

AL Language version: v6.1.397164
BC Version: 17.1

**Comment by kalberes** [comment]
Old issue, since no clear repro closing for now. We have fixed and refactored the code actions subsytem for version 11 of the compiler.
