### ISSUE TITLE
don't know how to trigger 

### ISSUE THREAD

**Issue by albgen** [microsoft/AL#6373]
**Describe the bug**

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```

**Expected behavior**

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by albgen** [comment]
[Error - 3:14:38 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/gotodefinition' failed with error: 'Index was outside the bounds of the array.'
Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.FilePathHelper.ParsePreviewFileUrl(Uri uri) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\FilePathHelper.cs:line 97
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDeclaringSymbolAsync(Uri previewUri, CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 137
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetContentAsync(Uri previewUri, LaunchConfiguration configuration, CancellationToken token, Boolean relyOnCachedValue) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 73
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDefinitionForSymbolAtPositionAsync(Uri previewUri, Position requestPosition, LaunchConfiguration configuration, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 101
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.ProcessRequestAsync(AlDefinitionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by g021670** [comment]
Just guessing you have an array which have lets say the size of 3 and you are trying to acces a value > 3.

**Comment by albgen** [comment]
Its not me :) its a bug on the AL extension...

**Comment by dtkb** [comment]
Anything that says "Please report this issue" is an internal compiler error. Moreover, out-of-bounds array indexing is only checked at runtime, even if the index is a compile-time literal (although now that I noticed that, I have to file yet another bug requesting a diagnostic...)

**Comment by albgen** [comment]
Ok

**Comment by maveca** [comment]
I've got something similar while trying to open base app source code. I really didn't need that compiler for my case, but strange thing is the compiler is trying to access location I don't have on my computer: D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices. 
I hope my discovery helps finding the bug for that.

**Comment by linonavcite** [comment]
I've resolved this issue by disabling the extension [AZ AL Dev Tools/AL Code Outline.](https://marketplace.visualstudio.com/items?itemName=andrzejzwierzchowski.al-code-outline) 
Which is a shame. Because it's an otherwise great extension, and have previously been working fine.

Hope this helps.

**Comment by dtkb** [comment]
best to report it at the repo of the author then,, surely?

https://github.com/anzwdev/al-code-outline/issues
