### ISSUE TITLE
VSIX 7.0.399350  "The AL server crashed 5 times in the last 5 minutes. The server will not be restarted"

### ISSUE THREAD

**Issue by mivtf** [microsoft/AL#6424]
- AL Extension Version: 
7.0.399350

Latest Insider AL extension as per 20th jan 2021 (7.0.399350) displays error message "The error server crashed 5 times in the last 5 minutes. The server will not be restarted" as soon as VS Code is opened (and, the AL extension is not working / ignoring all commands).

Starting VS Code as Admin and after a 5 min delay / reboot did not resolve the issue, and uninstalling/reinstalling VSIX 7 didn't help either.

The developer log (trace) do not appear to show anything related to the error. The windows application log do show this same "Unhandled exception" error 5 times in a row (screenshot in danish but translated description is "Process ended due to an unhandled exception"):

![Unhandled exception VSIX 7 0 399350](https://user-images.githubusercontent.com/46669432/105162613-277de380-5b13-11eb-8be3-94cc57cd8947.png)

**Comment by mivtf** [comment]
Addtional info:

I updated VS Code from 1.48.0 to 1.52.1 (was intentionally running old VS Code due to unrelated issue with AL background save would leave open files hanging with incurred losses to modified files).

The issue persists, but VS Code ouput console now proberbly displays this error 5 times in a row:

Ikke-afviklet undtagelse: System.IO.FileLoadException: Filen eller assemblyen 'Microsoft.Dynamics.Nav.EditorServices.Host, Version=7.0.6.6146, Culture=neutral, PublicKeyToken=31bf3856ad364e35' eller en af dens afh�ngigheder kunne ikke indl�ses. Valideringen af det sikre navn mislykkedes. (Undtagelse fra HRESULT: 0x8013141A) ---> System.Security.SecurityException: Valideringen af det sikre navn mislykkedes. (Undtagelse fra HRESULT: 0x8013141A)
   --- Slut p� staksporing af indre undtagelser ---
[Error - 12.10.28] Connection to server got closed. Server will not be restarted.

(Translated: "The file or assembly ... or one of its dependencies could not be solved. Validation of secure name failed...")

**Comment by mivtf** [comment]
Even more info....

Reinstalled everyting (VS Code 1.52.1 , AL 7.0.399350) on a different machine. It helped get a more controlled error. To be clear: VS Code and AL are same versions on the two machines, but results are different. VS Code now no longer displays error (crash) on open and deploying from VS Code to INSIDER docker now displays the messages below from exthost log and debug console.

(Note: The AL 7.0.399350 version is extracted from the related "insider" docker container, build 18.0.21075.0):

**exthost log**

[2021-01-20 12:39:12.751] [exthost] [error] [ms-dynamics-smb.al] provider FAILED
[2021-01-20 12:39:12.751] [exthost] [error] TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\miv\.vscode\extensions\ms-dynamics-smb.al-7.0.399350\node_modules\vscode-languageclient\lib\protocolConverter.js:130:27)
	at asHover (c:\Users\miv\.vscode\extensions\ms-dynamics-smb.al-7.0.399350\node_modules\vscode-languageclient\lib\protocolConverter.js:163:31)
	
**Debug console**	

[2021-01-20 12:41:10.50] Error: This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 7.0
- Web API: 4.0
- Debugger: 4.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 7.0
- Supported Web API: 1.0, 2.0, 3.0, 4.0
- Supported debuggers: 1.0, 2.0, 3.0

**Comment by atoader** [comment]
We had an issue that lead to the last error you are seeing. This should be resolved in the latest Docker preview. cc: @kalberes

**Comment by mivtf** [comment]
Todays insider with AL 7.0.400627 appears to have solved both crashes and deployment issue. 
The errors about about protocolConventer.js from exthost log persists, but appears unrelated.

Thank you for a quick solution.
