### ISSUE TITLE
Go to Definition and hover definition popup fail

### ISSUE THREAD

**Issue by gregwinterstein** [microsoft/AL#6433]
**Describe the bug**
Sometimes, VS Code (or the extension) gets into a state where hovering over a field (or F12 Go to definition) results in an error rather than the expected popup definition (or jump to the code).

Restarting Visual Studio Code does not resolve the issue. It is unclear what triggers this state or resolves it.

When VS Code is in this state, the hover popup shows "Loading..."
![image](https://user-images.githubusercontent.com/68340656/105497797-3203be80-5c74-11eb-826b-1d018954accd.png)

A message appears at the bottom of the screen indicating a request has failed:
![image](https://user-images.githubusercontent.com/68340656/105498066-8b6bed80-5c74-11eb-846d-570db8a44176.png)

An Index Out of Range Exception is added to the Output window:
`[Error - 5:34:37 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/gotodefinition' failed with error: 'Index was outside the bounds of the array.'
Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.FilePathHelper.ParsePreviewFileUrl(Uri uri) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\FilePathHelper.cs:line 97
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDeclaringSymbolAsync(Uri previewUri, CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 137
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetContentAsync(Uri previewUri, LaunchConfiguration configuration, CancellationToken token, Boolean relyOnCachedValue) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 73
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDefinitionForSymbolAtPositionAsync(Uri previewUri, Position requestPosition, LaunchConfiguration configuration, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 101
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.ProcessRequestAsync(AlDefinitionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80`

**To Reproduce**
1. Open page 41 Sales Quote from the Object Designer and go to a field definition
2. Hover over the field expression (second parameter in field) for "Sell-to Contact"
3. Observe the "Loading..." popup, the **A request has failed** message box, and the exception noted above in the Output window of VS Code

Alternatively:
1. Open page 41 Sales Quote from the Object Designer and go to a field definition
2. Place currsor on the field expression (second parameter in field) for "Sell-to Contact"
3. Press F12 (i.e. Go to Defintion)
4. Observe the **A request has failed** message box, and the exception noted above in the Output window of VS Code

``` AL Code to reproduce the issue ```
From Page 41 Sales Quote:
`...
                field("Sell-to Contact"; "Sell-to Contact")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Contact';
                    Editable = "Sell-to Customer No." <> '';
                    ToolTip = 'Specifies the name of the person to contact at the customer.';
                }
...`
**Expected behavior**
In the first case, hovering over the field expression, I expect the popup to appear with the definition without an error
In the second case, F12 (Go to definition), I expect to jump to the field definition.

**Screenshots**
Error Output:
![image](https://user-images.githubusercontent.com/68340656/105499278-15688600-5c76-11eb-8960-a1ccb1c8da58.png)

**5. Versions:**

 - AL Language: v6.1.397164

 - Business Central: 17.2.19367.19525 (from Admin Center, Searching for System Information in BC returns documentation, but no version)

**Comment by kalberes** [comment]
What is the " Object Designer"?  We do not provide (yet) an object designer?
Does this bug happen in the AL language server, or an extension that you use on top of the AL language server that maybe trying to "integrate" with the goto definition API of the AL language server?
The code that fails is in the language server, and it can be more robust. I agree with that. But I ma not sure that if we fix the .net exception gotodefinition will also work for you.
But I wander what happens if you open the AL file that references page 41 Sales Quote in Visual Studio Code without the "Object Designer" and issue a gotodefinition. Then you select the "Sell-to Contact" and issue a goto definition again.
Since it works fine for me.

**Comment by gregwinterstein** [comment]
The "Object Designer" is: https://github.com/martonsagi/al-object-designer

You are correct, that this only happens in the Object Designer. The confusing part is that the error message directed me to report the issue here.

I am closing this issue.
