### ISSUE TITLE
A request has failed when changing code: LeftToken, TargetToken, RightToken

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6462]
**Describe the bug**
System.OperationCanceledException is thrown in the output window while changing code. It does not matter much which code and how. The compiler just seems to lag and therefore incomplete actions are logged. I assume it's related to the project size.
![image](https://user-images.githubusercontent.com/34504100/107772026-f1133d00-6d3b-11eb-9820-5713f6c3d82e.png)

This error is very annoying, and it seems it happens to me much more often than months ago.

**Symptoms / exact error log:**

I strongly believe that other cases are related. 
They all indicate interruption (librar instead of library, Fd instead of FdA, ...):
- #6326 - when using intellisense
`Left token: 'Codeunit'. Target token: 'Codeunit'. Right token: 'librar'. `
- #6439 - when writing a tooltip
`Left token: 'T'. Target token: ';'. Right token: 'RunObject'. `
- my own case: when adding three letters (FdA) to the ApplicationArea property value `OLD`:
`Left token: 'OLDFd'. Target token: '='. Right token: ';'. `
_Full log: see bottom._
- and many, many more occasions.

**To reproduce:**
None of them are simply reproducible. If you try the same action later again, it might work, and fail again shortly after.
In order to reproduce, work in a rather large workspace, containing at least two apps, with code analyzers active:

```
    "al.enableCodeAnalysis": true,
    "al.backgroundCodeAnalysis": true,
    "al.codeAnalyzers": [
        "${CodeCop}",
        "${UICop}",
        "${AppSourceCop}"
    ],
```
Edit: setting it to `"al.backgroundCodeAnalysis": false,` did not help - the error on adding letters to an Application Area still threw the error, this time already after the first new letter.

**Versions:**

 - AL Language: 6.1.397164

Full log:
```
[Error - 13:55:07] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'An unexpected error happened when processing the document 'MyPath/UnitsofMeasure.Page.al' at position 'Line: 33 - Character: 47'. Left token: 'OLDFd'. Target token: '='. Right token: ';'. 
Exception details: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.RecommendPropertiesAsync(Document document, MemberSyntaxContext context, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"'
Details:
Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionException: An unexpected error happened when processing the document 'MyPath/UnitsofMeasure.Page.al' at position 'Line: 33 - Character: 47'. Left token: 'OLDFd'. Target token: '='. Right token: ';'. 
Exception details: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.RecommendPropertiesAsync(Document document, MemberSyntaxContext context, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.HandleAsync(CompletionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 52
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80
```

**Comment by SBalslev** [comment]
Hi! Thank you for reporting this issue — we appreciate you taking the time to document the error details.

Since this was reported, the AL Language Server has undergone significant reworking, including improvements to incremental compilation and token handling. As you noted, the issue appeared to be intermittent and potentially related to project size.

We're closing this as part of a cleanup of older issues. If you still encounter LeftToken/TargetToken errors on a current version of the AL Language extension, please don't hesitate to open a new issue — we'd be happy to investigate.

Thank you for helping us improve the AL developer experience!
