### ISSUE TITLE
'al/createPackage' failed with error: 'An item with the same key has already been added. Key: Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReferenceSpecification'

### ISSUE THREAD

**Issue by boomerama** [microsoft/AL#6474]
- AL Extension Version: v6.5.413786

Version: DE Business Central 17.4 (Plattform 17.0.21485.21516 + Anwendung 17.4.21491.21531)

I am trying to publish my extension:

Error Message
[Error - 10:42:44] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'An item with the same key has already been added. Key: Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReferenceSpecification'
Details:
System.ArgumentException: An item with the same key has already been added. Key: Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReferenceSpecification
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.Dynamics.Nav.CodeAnalysis.ProjectReferencesReferenceManager.AddModuleSymbols(PooledDictionary`2 moduleSymbols, IEnumerable`1 symbols) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\ReferenceLoader\ProjectReferencesReferenceManager.cs:line 185
   at Microsoft.Dynamics.Nav.CodeAnalysis.ProjectReferencesReferenceManager.GetLoadedModules() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\ReferenceLoader\ProjectReferencesReferenceManager.cs:line 74
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.get_CompiledModule() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 142
   at Microsoft.Dynamics.Nav.CodeAnalysis.ProjectReferencesReferenceManager.UpdateModuleSymbolsFromDependentProjects(PooledDictionary`2 moduleSymbols) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\ReferenceLoader\ProjectReferencesReferenceManager.cs:line 293
   at Microsoft.Dynamics.Nav.CodeAnalysis.ProjectReferencesReferenceManager.GetLoadedModules() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\ReferenceLoader\ProjectReferencesReferenceManager.cs:line 74
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.get_CompiledModule() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 142
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxTreeSemanticModel.GetDeclaredContainer(SyntaxNode declarationSyntax, String name) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SyntaxTreeSemanticModel.cs:line 743
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxTreeSemanticModel.GetDeclaredSymbol(ObjectSyntax declarationSyntax, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SyntaxTreeSemanticModel.cs:line 801
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetDeclaredSymbolCore(SyntaxNode declaration, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 793
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.GetDeclaringObjectAsync(Document document, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 276
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.ObjectChangeDocumentManager.UpdateObjectChangesAsync(CancellationToken token, ProjectId id, Boolean requireNoDeclarationDiagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\ObjectChangeDocumentManager.cs:line 147
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.Build(Project builtProject, StreamingTextWriter outputWriter, Boolean isRad, IList`1 args, CancellationToken cancellationToken, Boolean forceBuild, PooledList`1 outputFiles) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 178
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.HandleAsync(CreatePackageRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 100
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by atoader** [comment]
Can you provide a project and a recording to reproduce the issue?

**Comment by boomerama** [comment]
> 
> 
> Can you provide a project and a recording to reproduce the issue?

See #6492

**Comment by atoader** [comment]
Closing it as a dup of #6492
