### ISSUE TITLE
Value cannot be null. (Parameter 'projectId') after git pull

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6487]
This issue might be related with #4797.

**Describe the bug**
AL Language throws a run-time error in the Output tab in VS Code:
```
Processing of message 'workspace/didChangeWatchedFiles' failed with error: 'Value cannot be null. (Parameter 'projectId')'
Details:
System.ArgumentNullException: Value cannot be null. (Parameter 'projectId')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentId.CreateNewId(ProjectId projectId, String debugName) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\DocumentId.cs:line 77
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.TryAddTransientDocument(String filePath, String text, Boolean handleRad, DocumentId& documentId) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:line 176
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeWatchedFilesRequestHandler.HandleAsync(DidChangeWatchedFilesRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeWatchedFilesRequestHandler.cs:line 30
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 63
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 64
```

**To Reproduce**
What I did in chronological order before the error occurred:

1. I deleted a branch on my remote repository 
2. In VS Code
   1. I switched to a branch other than the one I just deleted remotely    
    2. Terminal: `git fetch -p`
    3. Terminal: `git pull`

**5. Versions:**
 - AL Language: 6.5.413786

**Comment by atoader** [comment]
We do not support switching branches while reloading everything from VSCode. The workaround is to restart VSCode. 

I am tempted to mark this as 'Won't fix'. We have looked into this and it is a significant effort while the mitigation is straightforward.

**Comment by NKarolak** [comment]
I don't quite understand:
Reading my reproduction steps, when exactly should I have restarted VS Code?

**Comment by atoader** [comment]
You can:
1. Close VSCode
2. Change branches, pull remote etc
3. Start VSCode

If you want to use the VSCode git integration, you would need to restart it after pulling.

**Comment by NKarolak** [comment]
Partners usually use the git integration inside VS Code, and it's normal to use feature branches, hence we use a git pull when we switch back to any main or development branch.
Usually a git pull has worked without any issues.
Are you sure nothing has changed on your side in the meantime?

**Comment by atoader** [comment]
I don't think so, but if you can provide a project and a zipped up git repository, we can try to debug this.

**Comment by NKarolak** [comment]
I currently have to time for that :-(
And actually, you should be able to create such a project yourself since it is about git integration, and not about specific AL object features.

**Comment by jglathe** [comment]
Still at the workaround game? I have no other tool where I need to do this.

**Comment by kalberes** [comment]
It is still marked as a bug as far as I see it.  That means that when we will have time, we will fix it. For now this scenario is not supported. On the other hand I do have similar tools (I work with every day). But this should not be a blame game either.

**Comment by NKarolak** [comment]
On a side note: my colleague added that the error could be caused if the workspace file contained a few spaces after a comma.
However, I was now not able to reproduce that spaces error myself.

**Comment by SBalslev** [comment]
Hi! Thank you for reporting this issue and for the community discussion — the detailed stack traces were very helpful.

This shares the same root cause as #6692 (ArgumentNullException in project handling) and was addressed internally (PR 36826), shipped in **Business Central runtime 16.0 (2020 Wave 1)**. The language server has received extensive stability improvements since then.

We're closing this as resolved. If you still encounter projectId-related errors after git operations on a current version, please open a new issue.

Thank you for helping us improve the AL developer experience!
