### ISSUE TITLE
Unable to download symbols using docker BC365 onpremise installation

### ISSUE THREAD

**Issue by IvaGroznyj** [microsoft/AL#6532]
**Issue**
Trying to Download Symbols...
Error occures:

_[2021-03-16 13:27:30.28] Using reference symbols cache path: c:\Users\ivan\Documents\AL\HalloWorld\./.alpackages
[2021-03-16 13:27:30.28] Sending request to http://geepzbc365chdev:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=17.0.0.0&tenant=default
[2021-03-16 13:27:30.29] Sending request to http://geepzbc365chdev:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.0.0&tenant=default
[Error - 13:27:34] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/downloadSymbols' failed with error: 'Im Sicherheitspaket sind keine Anmeldeinformationen verfügbar.'
Details:
System.ComponentModel.Win32Exception (0x8009030E): Im Sicherheitspaket sind keine Anmeldeinformationen verfügbar.
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Deployment.Telemetry.TelemetryHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Telemetry\TelemetryHttpClientHandler.cs:line 61
   at Microsoft.Dynamics.Nav.Deployment.Http.NavHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Http\NavHttpClientHandler.cs:line 35
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Dynamics.Nav.Deployment.ApiClients.PackagesApiClient.SendRequest(IHttpClient client, SymbolReferenceSpecification reference) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ApiClients\PackagesApiClient.cs:line 139
   at Microsoft.Dynamics.Nav.Deployment.ApiClients.PackagesApiClient.DownloadPackage(IHttpClient client, SymbolReferenceSpecification specification, String directory, Boolean isSecondLevelDependency) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ApiClients\PackagesApiClient.cs:line 154
   at Microsoft.Dynamics.Nav.Deployment.ApiClients.PackagesApiClient.DownloadPackages(ImmutableArray`1 references, String targetDir) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ApiClients\PackagesApiClient.cs:line 54
   at Microsoft.Dynamics.Nav.Deployment.ReferenceDownloader.NavDevServerPackageDownloader.DownloadPackages(ImmutableArray`1 packages, String targetDirectory) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ReferenceDownloader\NavDevServerPackageDownloader.cs:line 32
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.DownloadFiles(DownloadSymbolsRequest request, String cacheDirectory, ImmutableArray`1 referencesToDownload) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 124
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.ProcessRequestAsync(DownloadSymbolsRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 93
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80_

**launch.json**

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Your own server",
            "request": "launch",
            "type": "al",
            "environmentType": "Production",
            "server": "http://GeepzBC365CHDev",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "tenant": "default",
            "port": 7049
        }
    ]

Service is running. Port have been checked and seem to be ok. I already tried both UserPassword and Windows auth. Te service tier and client run correct under Windows auth. No idea what am I doing wrong...
Please, help ;)
Thx
Ivan

**Comment by IvaGroznyj** [comment]
Thuis is the COntainer:

PS C:\Windows\system32> Get-BcContainerServerConfiguration GeepzBC365CHDev


ContainerName                                               : GeepzBC365CHDev
NetworkProtocol                                             : Default
DatabaseServer                                              : localhost
DatabaseInstance                                            : SQLEXPRESS
DatabaseName                                                : CRONUS
EnableSqlConnectionEncryption                               : false
TrustSQLServerCertificate                                   : false
ServerInstance                                              : BC
EnableSqlInformationDebugger                                : true
AmountOfSqlStatementsInDebugger                             : 10
EnableLongRunningSqlStatementsInDebugger                    : true
LongRunningSqlStatementsInDebuggerThreshold                 : 500
ClientServicesPort                                          : 7046
SOAPServicesPort                                            : 7047
ODataServicesPort                                           : 7048
ManagementServicesPort                                      : 7045
ManagementServicesEnabled                                   : true
ClientServicesEnabled                                       : true
TestAutomationEnabled                                       : true
DeveloperServicesPort                                       : 7049
DeveloperServicesEnabled                                    : true
DeveloperServicesSSLEnabled                                 : false
SnapshotDebuggerServicesPort                                : 7083
SnapshotDebuggerEnabled                                     : true
SnapshotDebuggerServicesSSLEnabled                          : false
ExtensionAllowedTargetLevel                                 : Internal
RequiredExtensions                                          :
SolutionVersionExtension                                    : 00000000-0000-0000-0000-000000000000
ReportPDFFontEmbedding                                      : true
ReportAppDomainIsolation                                    : true
ReportMaxRows                                               : 1000000
ReportDefaultMaxRows                                        : 500000
ReportTimeout                                               : 12:00:00
ReportDefaultTimeout                                        : 06:00:00
ReportMaxDocuments                                          : 500
ReportDefaultMaxDocuments                                   : 200
QueryMaxRows                                                : MaxValue
QueryTimeout                                                : MaxValue
EnableSaveToWordForRdlcReports                              : true
EnableSaveToExcelForRdlcReports                             : true
EnableSaveFromReportPreview                                 : true
CompileBusinessApplicationAtStartup                         : true
SOAPServicesEnabled                                         : true
ODataServicesEnabled                                        : true
ODataServicesV3EndpointEnabled                              : true
ODataServicesV4EndpointEnabled                              : true
SOAPServicesSSLEnabled                                      : false
ODataServicesSSLEnabled                                     : false
ODataMaxConnections                                         : 0
ODataMaxConnectionsPerTenant                                : 0
ODataV4MaxConcurrentRequests                                : 5
ODataV4MaxRequestQueueSize                                  : 95
SOAPMaxConcurrentRequests                                   : 5
SOAPMaxRequestQueueSize                                     : 95
SOAPMaxConnections                                          : 0
SOAPMaxConnectionsPerTenant                                 : 0
DeltaServiceClientTimeout                                   : 00:02:00
ODataServicesOperationTimeout                               : 00:08:00
SOAPServicesOperationTimeout                                : 00:10:00
PublicODataBaseUrl                                          : http://GeepzBC365CHDev:7048/BC/OData
PublicSOAPBaseUrl                                           : http://GeepzBC365CHDev:7047/BC/WS/
PublicWebBaseUrl                                            : http://GeepzBC365CHDev/BC/
PublicWinBaseUrl                                            : DynamicsNAV://GeepzBC365CHDev:7046/BC/
DefaultClient                                               : Web
ServicesOptionFormat                                        : OptionCaption
ServicesLanguage                                            : en-US
CalendarTwoDigitYearMax                                     : -1
SOAPServicesMaxMsgSize                                      : 65536
ServicesUseNTLMAuthentication                               : false
ServicesDefaultTimeZone                                     : UTC
ServicesDefaultCompany                                      :
ODataServicesMaxPageSize                                    : 20000
ClientServicesOperationTimeout                              : MaxValue
ClientServicesProtectionLevel                               : EncryptAndSign
MaxConcurrentCalls                                          : 1000
ClientServicesMaxConcurrentConnections                      : 500
ClientServicesReconnectPeriod                               : 00:10:00
ClientServicesMaxNumberOfOrphanedConnections                : 20
ClientServicesCompressionThreshold                          : 64
ClientServicesMaxUploadSize                                 : 350
EnableDebugging                                             : false
DebuggingAllowed                                            : true
SqlTracingAllowed                                           : true
SqlLockTimeoutOverride                                      : 0
ClientServicesMaxItemsInObjectGraph                         : 512
ClientServicesChunkSize                                     : 28
ClientServicesProhibitedFileTypes                           : ade;adp;asp;bas;bat;chm;cmd;com;cpl;csh;exe;fxp;gadget;hlp;hta;inf;ins;isp;its;js;jse;ksh;lnk;mad;maf;ma
                                                              g;mam;maq;mar;mas;mat;mau;mav;maw;mda;mdb;mde;mdt;mdw;mdz;msc;msi;msp;mst;ops;pcd;pif;prf;prg;pst;reg;sc
                                                              f;scr;sct;shb;shs;url;vb;vbe;vbs;vsmacros;vss;vst;vsw;ws;wsc;wsf;wsh
ClientServicesAllowedFileTypes                              :
NASServicesStartupCodeunit                                  :
NASServicesRunWithAdminRights                               : false
EnableDeadlockMonitoring                                    : false
NASServicesStartupMethod                                    :
NASServicesStartupArgument                                  :
NASServicesEnableDebugging                                  : false
ClientServicesCredentialType                                : Windows
UIElementRemovalOption                                      : LicenseFileAndUserPermissions
ClientServicesTokenSigningKey                               :
ClientServicesFederationMetadataLocation                    :
ServicesCertificateThumbprint                               :
ServicesCertificateValidationEnabled                        : true
DisableTokenSigningCertificateValidation                    : false
TokenSigningCertificateValidationMode                       : IssuerNameValidation
DataCacheSize                                               : 10
SessionEventTableRetainInterval                             : 90.00:00:00
NonInteractiveSessionsLogRetainInterval                     : 5.00:00:00
SqlCommandTimeout                                           : 00:30:00
SqlManagementCommandTimeout                                 : -1
SqlConnectionTimeout                                        : 00:01:30
EnableSqlReadOnlyReplicaSupport                             : false
EnableExclusiveExistsCheckOnModify                          : false
BufferedInsertEnabled                                       : true
DisableSmartSql                                             : false
EnableFullALFunctionTracing                                 : false
Multitenant                                                 : False
SqlConnectionIdleTimeout                                    : 00:05:00
EnableALServerFileAccess                                    : true
EnableApplicationChannelLog                                 : true
EncryptionProvider                                          : LocalKeyFile
AzureKeyVaultAppSecretsPublisherValidationEnabled           : true
ExchangeAuthenticationMetadataLocation                      :
AppIdUri                                                    :
WSFederationLoginEndpoint                                   :
AzureActiveDirectoryClientId                                :
AzureActiveDirectoryClientSecret                            :
AzureActiveDirectoryClientCertificateThumbprint             :
EnableMembershipEntitlement                                 :
EnablePartialRecords                                        : true
MaxRowsToExportToExcel                                      : MaxValue
EnableTaskScheduler                                         : false
TaskSchedulerMaximumConcurrentRunningTasks                  : 3
ClientServicesKeepAliveInterval                             : 00:02:00
UseSimplifiedFilters                                        : false
ExcelAddInAzureActiveDirectoryClientId                      :
DisableWriteInsideTryFunctions                              : true
ExtendedSecurityTokenLifetime                               : 0
ClientServicesIdleClientTimeout                             : MaxValue
ODataEnableExcelAddInAnnotations                            : true
NavHttpClientMaxResponseContentSize                         : 150
NavHttpClientMaxTimeout                                     : 00:05:00
ClientBuildRestriction                                      : WarnClient
TraceLevel                                                  : Normal
ExternalTraceLevel                                          : Error
EnableDataExportImport                                      : true
MaxStreamReadSize                                           : 1000000
ValidAudiences                                              :
DefaultLanguage                                             :
SupportedLanguages                                          :
UnsupportedLanguageIds                                      : 1034
ApiServicesEnabled                                          : True
ApiSubscriptionsEnabled                                     : true
ApiSubscriptionExpiration                                   : 3
ApiSubscriptionNotificationUrlTimeout                       : 5000
ApiSubscriptionSendingNotificationTimeout                   : 30000
ApiSubscriptionDelayTime                                    : 30000
ApiSubscriptionMaxNumberOfNotifications                     : 100
ApiSubscriptionMaxNumberOfSubscriptions                     : 200
EnableSymbolLoadingAtServerStartup                          : False
SqlLongRunningThreshold                                     : 750
SqlLongRunningThresholdForApplicationInsights               : 750
SqlBulkImportBatchSize                                      : 448
UseIncrementalCompanyDelete                                 : false
TaskSchedulerSystemTaskStartTime                            : 00:00:00
TaskSchedulerSystemTaskEndTime                              : 23:59:59
ChildSessionsMaxConcurrency                                 : 5
ChildSessionsMaxQueueLength                                 : 100
PageBackgroundTaskDefaultTimeout                            : 00:02:00
PageBackgroundTaskMaxTimeout                                : 00:10:00
XmlMetadataCacheSize                                        : 500
AllowSessionWhileSyncAndDataUpgrade                         : true
SearchTimeout                                               : 00:00:10
OverwriteExistingTranslations                               : true
LockoutPolicyFailedAuthenticationCount                      : 0
LockoutPolicyFailedAuthenticationWindow                     : 0
ReplaceReportExecutionTimeWithClientTime                    : true
UseFindMinusWhenPopulatingPage                              : true
DisableQueryHintOptimizeForUnknown                          : false
DisableQueryHintForceOrder                                  : true
DisableQueryHintLoopJoin                                    : true
EnableSqlQueryTopParameterization                           : false
SecurityProtocol                                            : Tls12
IntegrationRecordsTableId                                   : 5151
LegacyOptionCaptionResolution                               : false
EnableMultithreadedCompilation                              : true
ApplicationInsightsInstrumentationKey                       :
EnableUserConsistencyValidationOnTasks                      : true
AllowReadingCrossTenantApplicationDatabaseTables            : false
EnableExclusiveApplicationPackageRole                       : true
ALLongRunningFunctionTracingThresholdForApplicationInsights : 10000
ALFunctionTimingEnabled                                     : true
ALCompatibleDateFormatCultureList                           :
EnableCloudReplicationMaintenance                           : false
EnableProfileCacheSynchronization                           : false
AllowSessionCallSuspendWhenWriteTransactionStarted          : true
AzureKeyVaultClientId                                       : 00000000-0000-0000-0000-000000000000
AzureKeyVaultClientCertificateStoreLocation                 : LocalMachine
AzureKeyVaultClientCertificateStoreName                     : My
AzureKeyVaultClientCertificateThumbprint                    :
AzureKeyVaultKeyUri                                         :

**Comment by IvaGroznyj** [comment]
So, I removed the whole staff and created new clean BC container not using default windows authentication but usernamepassword instead. This worked well. It looks lik, the Windows Auth doesn't work with VSC downloading symbols well at the moment.

**Comment by thloke** [comment]
@esbenk  - is this the credential caching bug you are working on? The translated error message is:

Credentials are not available in the security package

**Comment by esbenk** [comment]
No. Mine is a combination of AAD Auth and wrong in-memory caching key.

This is OnPrem and docker. As far as I can see.

/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IvaGroznyj** [comment]
Yes, the combination was **OnPrem, Docker and Windows auth**. This didn't work. The message was as correctly translated above "_Credentials are not available in the security package_". I was disappointed after several tries to workaround it and removed this container replacing it with a similar release but with **UserPassword** auth instead. This worked properl at the first try..
Anyway, for the productive env. I do need Windows Auth, so it would be great to have this solved ;)
Thx and have a nice day
Cheers
Ivan

**Comment by freddydk** [comment]
Your container we setup for Windows Auth, yet in Launch.json you had:

```
server": "http://GeepzBC365CHDev",
"serverInstance": "BC",
"authentication": "UserPassword",
"startupObjectId": 22,
```

Shouldn't that be Windows?

Windows Auth is one of the things, frequently causing issues with Docker, because containers cannot join a domain.
You can use gMSA (group managed Service Accounts), but that is hard to setup.
When you just create a container with Windows auth, the container is just setup with the same username and password as your domain user (specified in credentials) and as long as you have access to your AD server, it should work.
It does not work with cached credentials in Windows (not to be confused with VS Code caching credentials)

When you create a container using Windows Auth, and you can access the Web Client in a Browser without logging in you are fine. If you change your AD password on the host, the container will stop working and has to be recreated.

When the Web Client works - VS code should also work with Windows as authentication setting.

**Comment by IvaGroznyj** [comment]
Hi, thx for the inputs. CLient worked with windows auth correctly, VSC not. That's why I replaced the container with the new one, working with UserPassword. This ist fine for Development, not for production ofcourse. The problem is, there is no AD server behind. This is simple standalone workgroup based windows 10 environment. I persist on UserPwd at the moment to be able to develop the extensions. Thx and have a nice day

**Comment by SBalslev** [comment]
Hi! Thank you for reporting this and for the thorough troubleshooting with the community.

Based on the discussion, this was related to a Docker/Windows authentication configuration mismatch rather than an issue with the AL Language extension itself. For Docker and container setup issues, the best resource is https://github.com/microsoft/navcontainerhelper.

We're closing this to keep the backlog focused on AL tooling issues. If you encounter symbol download problems that you believe are caused by the AL Language extension, please don't hesitate to open a new issue.

Thank you for being part of the Business Central developer community!
