### ISSUE TITLE
Crash after copy'paste an entire codeunit

### ISSUE THREAD

**Issue by hougaard** [microsoft/AL#6556]
Crash happened after this process:
1. Copy all text from a codeunit into the clipboard
2. Right-click to create a new file, foo.al
3. Paste the content from the clipboard
4. double click on the object number
5. Press the delete key
6. Press ctrl-space (to get a new object number in intellisense)

Result below:

[Error - 11:05:42 a.m.] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'An unexpected error happened when processing the document 'xxx.al' at position 'Line: 1 - Character: 10'. Left token: 'codeunit'. Target token: 'codeunit'. Right token: '"Azure Table EFQ"'. 
Exception details: System.ArgumentOutOfRangeException: Node span: 0-0, position: 9 (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Func`2 findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1188
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsEntirelyWithinStringLiteral(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 529
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.MemberSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ContextQuery\MemberSyntaxContext.cs:line 159
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionProvider.CreateMemberContextAsync(Document document, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\CompletionProvider.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetPerContextSymbols(Document document, Int32 position, OptionSet options, IEnumerable`1 relatedDocuments, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 248
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, AbstractSyntaxContext context, TextSpan span, OptionSet options, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 206
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 181
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"'
Details:
Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionException: An unexpected error happened when processing the document 'xxx.al' at position 'Line: 1 - Character: 10'. Left token: 'codeunit'. Target token: 'codeunit'. Right token: '"Azure Table EFQ"'. 
Exception details: System.ArgumentOutOfRangeException: Node span: 0-0, position: 9 (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Func`2 findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1188
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsEntirelyWithinStringLiteral(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 529
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.MemberSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ContextQuery\MemberSyntaxContext.cs:line 159
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionProvider.CreateMemberContextAsync(Document document, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\CompletionProvider.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetPerContextSymbols(Document document, Int32 position, OptionSet options, IEnumerable`1 relatedDocuments, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 248
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, AbstractSyntaxContext context, TextSpan span, OptionSet options, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 206
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 181
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.HandleAsync(CompletionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 52
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

[Error - 11:05:44 a.m.] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'An unexpected error happened when processing the document 'xxx.al' at position 'Line: 1 - Character: 10'. Left token: 'codeunit'. Target token: 'codeunit'. Right token: '"Azure Table EFQ"'. 
Exception details: System.ArgumentOutOfRangeException: Node span: 0-0, position: 9 (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Func`2 findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1188
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsEntirelyWithinStringLiteral(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 529
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.MemberSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ContextQuery\MemberSyntaxContext.cs:line 159
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionProvider.CreateMemberContextAsync(Document document, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\CompletionProvider.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetPerContextSymbols(Document document, Int32 position, OptionSet options, IEnumerable`1 relatedDocuments, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 248
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, AbstractSyntaxContext context, TextSpan span, OptionSet options, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 206
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 181
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"'
Details:
Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionException: An unexpected error happened when processing the document 'xxx.al' at position 'Line: 1 - Character: 10'. Left token: 'codeunit'. Target token: 'codeunit'. Right token: '"Azure Table EFQ"'. 
Exception details: System.ArgumentOutOfRangeException: Node span: 0-0, position: 9 (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Func`2 findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1188
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsEntirelyWithinStringLiteral(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 529
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.MemberSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ContextQuery\MemberSyntaxContext.cs:line 159
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionProvider.CreateMemberContextAsync(Document document, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\CompletionProvider.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetPerContextSymbols(Document document, Int32 position, OptionSet options, IEnumerable`1 relatedDocuments, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 248
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, AbstractSyntaxContext context, TextSpan span, OptionSet options, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 206
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 181
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.HandleAsync(CompletionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 52
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by alexandratorok** [comment]
I have the same issue.

**Comment by BazookaMusic** [comment]
Does not repro anymore closing
