### ISSUE TITLE
BC365-17.5 - SAAS SANDBOX - Visual Code causing error / CodeAnalysis

### ISSUE THREAD

**Issue by cristof-thomas** [microsoft/AL#6579]
Visual code autoCompletion not working anymore even with a close/restart.
Having had the same problem with 'OnPrem' has required to restart the BC instance.
Thanks for your reply.
Regards,

[Error - 14:50:27] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'An unexpected error happened when processing the document 'd:/Documents/GitHub/NLK-KERNEL/src/tableextension/OcrServiceSetup.al' at position 'Line: 1 - Character: 59'. Left token: '"ocr setup"'. Target token: 'extends'. Right token: '"ocr setup"'. 
Exception details: System.ArgumentOutOfRangeException: Node span: 0-0, position: 58 (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Func`2 findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1188
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsEntirelyWithinStringLiteral(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 518
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsInNonUserCode(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 221
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.MemberSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ContextQuery\MemberSyntaxContext.cs:line 173
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionProvider.CreateMemberContextAsync(Document document, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\CompletionProvider.cs:line 82
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetPerContextSymbols(Document document, Int32 position, OptionSet options, IEnumerable`1 relatedDocuments, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 248
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, AbstractSyntaxContext context, TextSpan span, OptionSet options, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 199
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 174
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 385
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"'
Details:
Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionException: An unexpected error happened when processing the document 'd:/Documents/GitHub/NLK-KERNEL/src/tableextension/OcrServiceSetup.al' at position 'Line: 1 - Character: 59'. Left token: '"ocr setup"'. Target token: 'extends'. Right token: '"ocr setup"'. 
Exception details: System.ArgumentOutOfRangeException: Node span: 0-0, position: 58 (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Func`2 findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1188
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 1155
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsEntirelyWithinStringLiteral(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 518
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTreeExtensions.IsInNonUserCode(SyntaxTree syntaxTree, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTreeExtensions.cs:line 221
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.MemberSyntaxContext.CreateContext(Workspace workspace, SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ContextQuery\MemberSyntaxContext.cs:line 173
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionProvider.CreateMemberContextAsync(Document document, Int32 position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\CompletionProvider.cs:line 82
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetPerContextSymbols(Document document, Int32 position, OptionSet options, IEnumerable`1 relatedDocuments, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 248
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, AbstractSyntaxContext context, TextSpan span, OptionSet options, Boolean preselect, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 199
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 174
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 385
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.HandleAsync(CompletionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 52
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by cristof-thomas** [comment]
Again new Completion Crash:
--------------------------------
[Error - 15:35:50] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'Position: 274, FullSpan: (0..273) (Parameter 'position')'
Details:
System.ArgumentOutOfRangeException: Position: 274, FullSpan: (0..273) (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 824
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.ALCompletionService.GetDefaultItemSpanAsync(Document document, SourceText text, Int32 caretPosition, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ALCompletionService.cs:line 57
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 153
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.HandleAsync(CompletionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 52
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

[Error - 15:35:54] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'Position: 278, FullSpan: (0..273) (Parameter 'position')'
Details:
System.ArgumentOutOfRangeException: Position: 278, FullSpan: (0..273) (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxNode.FindToken(Int32 position) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxNode.cs:line 824
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.ALCompletionService.GetDefaultItemSpanAsync(Document document, SourceText text, Int32 caretPosition, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\ALCompletionService.cs:line 57
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 153
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.HandleAsync(CompletionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 52
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by atoader** [comment]
Can you provide a project and a video that shows the repro?

**Comment by thloke** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we would have liked. 

If this is still a problem in the latest insiders build, feel free to raise this issue again.
