### ISSUE TITLE
Extention error - while publishing the app from VS Code

### ISSUE THREAD

**Issue by Nagaraju17** [Microsoft/AL#658]
Hi,

  While creating an extension for one of our NAV component. The package is created successfully but when i try to publish the app from VS, i am facing the below error. Can any one help on this.

![image](https://user-images.githubusercontent.com/30176345/30211481-d7f1e078-94be-11e7-861f-6547672f5b58.png)

Thanks & Regards
Nagaraju

**Comment by Gallimathias** [comment]
@Nagaraju17 Is this the September vm with docker?

**Comment by bachii1010** [comment]
Hi,

No it is August Update.

**Comment by Gallimathias** [comment]
You are apparently using a data type that Nav does not support. mhmm.

Is that a nav in the docker container?

**Comment by kalberes** [comment]
CAn you look up the eventviewer where the server runs. There may be other events related.

**Comment by Nagaraju17** [comment]
HI,
  i could not find any related information.

![image](https://user-images.githubusercontent.com/30176345/30213023-e4057e0a-94c4-11e7-983f-7af6f0519e6e.png)

**Comment by Gallimathias** [comment]
In a Calc FlowField you are using a statement that is not supported. If you post the whole message from the event view you can even be told where ;)

**Comment by Nagaraju17** [comment]
Hi,
Please find the full Message from Event Viewer.

Server instance: NAV
Category: Extensions
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 00000000-0000-0000-0000-000000000000
EventTime: 09/08/2017 13:02:24
Message <ii>(NavNotSupportedException): <ii>Exception of type 'Microsoft.Dynamics.Nav.Types.Exceptions.NavNotSupportedException' was thrown.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass34_0.<CreateSubQueryForFlowFieldCalculation>b__1(NCLMetaQueryDefinition subQueryBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDefinition..ctor(NCLMetaQueryDataItem parentDataItem, Int32 topRows, Func`2 dataItemsCreator, Func`2 orderBysCreator)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass34_0.<CreateSubQueryForFlowFieldCalculation>b__0(NCLMetaQueryDataItem dataItemBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDataItem..ctor(NCLMetaQueryDefinition parentQueryDefinition, DataItemLinkType dataItemLinkType, Func`2 subQueryCreator, String name, Func`2 queryColumnsCreator, Func`2 dataItemLinksCreator, Int32 appGroup)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateSubQueryForFlowFieldCalculation(NCLMetaQueryDataItem baseDataItem, MetaQueryColumn flowFieldColumn, Int32 nextColumnId)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.CreateDataItemsFromDesignMetadata(NCLMetaQueryDefinition parentQueryDefinition, MetaQuery metaQuery, Boolean allowExpressionEvaluation, Boolean& tableFilterHasVariables)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.<>c__DisplayClass37_1.<ParseMetadata>b__0(NCLMetaQueryDefinition queryDefinitionBeingCreated)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQueryDefinition..ctor(NCLMetaQueryDataItem parentDataItem, Int32 topRows, Func`2 dataItemsCreator, Func`2 orderBysCreator)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.ParseMetadata(MetaQuery metaQuery, Boolean allowExpressionEvaluation)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaQuery.LoadMetadata()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.Populate()
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroupNewObject(NavAppGroup appGroup, NavAppGroupObjectMetadataSummary newObjectSummary)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeNewAppQueries(NavAppGroup appGroup, PerformanceLog perfLog, IReadOnlyList`1 newObjectsFromApps)
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroup(NavAppGroup appGroup)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.InitializeAppGroup(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppGroupUpdater.PrepareAppGroups(NavAppGroups groups, PerformanceLog performanceLog)
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.PrepareAllAppGroupsForInstallChain(NavAppInstallPreCheckHelper precheckResult, PerformanceLog outerPerfLog)
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.InternalInstallNavApp(NavAppInstallPreCheckHelper precheckResult, String name, NavTenant tenant, Boolean doNotLoadData, String activityId, PerformanceLog outerPerfLog)
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.<>c__DisplayClass22_0.<InstallNavApp>b__1(NavTenant tenant, NavSession session)
   at Microsoft.Dynamics.Nav.Runtime.NavTenant.Microsoft.Dynamics.Nav.Runtime.ITenantSessionHandler.RunTenantActionInSystemSession(Action`2 action, Boolean throwExceptions, Boolean useCurrentCulture, Boolean allowAppsDisabledMode)
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.<>c__DisplayClass22_0.<InstallNavApp>b__0()
   at Microsoft.Dynamics.Nav.Runtime.NavManagementTasks.InstallNavApp(InstallNavAppArguments installNavAppArguments, Boolean async)
   at Microsoft.Dynamics.Nav.Service.NSAdminService.<>c__DisplayClass51_0.<Microsoft.Dynamics.Nav.Types.INCLAdminService.InstallNavApp>b__0()
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.<>c__DisplayClass1_0`1.<SendTraceTagOnFailure>b__0()
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.SendTraceTagOnFailure(Action operation, String additionalInfo, String callerName)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.SendTraceTagOnFailure[T](Func`1 operation, String additionalInfo, String callerName)
   at Microsoft.Dynamics.Nav.Service.Dev.DevService.<>c__DisplayClass4_1.<PublishAndInstallExtension>b__0()
   at Microsoft.Dynamics.Nav.Service.Dev.DevService.PublishAndInstallExtension(NavSession session, Stream packageStream, PerformanceLog performanceLog)
   at Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.AppsController.<PublishAndInstall>d__0.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Http.HttpContentMultipartExtensions.<ReadAsMultipartAsync>d__0`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
   at System.Net.Http.HttpContentMultipartExtensions.<MultipartReadAsync>d__8.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.<ReadAsync>d__3.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.CompleteFromAsyncResult(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.IOCompleted(HttpRequestStreamAsyncResult asyncResult, UInt32 errorCode, UInt32 numBytes)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

</ii></ii>
ProcessId: 1064
Tag: 000009W
ThreadId: 30
CounterInformation:

**Comment by kalberes** [comment]
The issue is as mentioned above is that it looks like your calcformula is not supported.
That can be by design or it could be a bug. Without seeing your formula it is hard to say.

**Comment by Nagaraju17** [comment]
Hi,

How we can know from which table is getting this error. How we can track this any suggestions..

**Comment by StanislawStempin** [comment]
You'd need to try and narrow down the problem to a smaller subset of objects, ideally to a single table. 
From our side we will look at this stack trace in our telemetry and see if anything can be done.

**Comment by StanislawStempin** [comment]
Closing this issue due to inactivity. Please log a new issue with a more detailed repro if you're still hitting the same problem.
