### ISSUE TITLE
Throw compile error when Handler function is overloaded

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#6600]
**Bug description**
In case I am having, in my test codeunit, a **normal function** and a **handler function** with the same name the AL compiler sees them as overloads of each other. Having linked this name to a test function using the HandlerFunctions attribute no compile occurs as indeed a handler functions exist in the test codeunit.
But when executing the test an _Unhandled UI_ error is thrown.

**Expected behavior**
The AL compiler will flag both the normal and handler functions with an error saying that the function name is already used by the other.

**To Reproduce**
Deploy and run the following test codeunit:

```
codeunit 81050 "Overload on Handler issue"
{
    Subtype = Test;

    [Test]
    [HandlerFunctions('ConfigTemplates')]
    procedure OpenNewCustomerCard()
    var
        CustomerCard: TestPage "Customer Card";
        CustomerNo: Code[20];
    begin
        CustomerCard.OpenNew();
    end;

    procedure ConfigTemplates()
    begin
    end;

    [ModalPageHandler]
    procedure ConfigTemplates(var ConfigTemplates: TestPage "Config Templates")
    begin
        ConfigTemplates.OK().Invoke();
    end;
}
```

**Result of test execution**
Failing test with error with essential part being **Unhandled UI: ModalPage 1340**.

```
Error Message: Unexpected CLR exception thrown.: Microsoft.Dynamics.Framework.UI.FormAbortException: Page New - Customer Card has to close. ---> Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLMissingUIHandlerException: Unhandled UI: ModalPage 1340 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLMissingUIHandlerException: Unhandled UI: ModalPage 1340
at Microsoft.Dynamics.Nav.Runtime.NavTestExecution.FindHandler(NavHandlerType handlerType, NavApplicationObjectBase appObject, Boolean throwIfNotFound, String handlerDescription)
at Microsoft.Dynamics.Nav.Runtime.NavTestExecution.TestHandleModalForm(NavForm form, FormResult& action, NavFormRuntimeParameters parameters)
at Microsoft.Dynamics.Nav.Runtime.NavForm.RunModal(NavRecord record, Int32 fieldNo)
at Microsoft.Dynamics.Nav.Runtime.NavFormHandle.RunModal(NavRecord record, Int32 fieldNo)
at Microsoft.Dynamics.Nav.BusinessApplication.Record1300.NewCustomerFromTemplate_Scope__1848449490.OnRun()
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
at Microsoft.Dynamics.Nav.BusinessApplication.Record1300.NewCustomerFromTemplate(INavRecordHandle customer)
at Microsoft.Dynamics.Nav.BusinessApplication.Record1300.OnInvoke(Int32 memberId, Object[] args)
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1389.CreateCustomerFromConfigTemplate_Scope_587295807.OnRun()
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1389.CreateCustomerFromConfigTemplate(INavRecordHandle customer, ByRef`1 isHandled)
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1389.OnInsertCustomerFromTemplateHandler_Scope.OnRun()
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1389.OnInsertCustomerFromTemplateHandler(INavRecordHandle customer, ByRef`1 result, ByRef`1 isHandled)
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1389.OnInvoke(Int32 memberId, Object[] args)
at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.CallEventSubscriberInternal(NavEventSubscription subscriber, NavApplicationObjectBase subscriberInstance, Object[] parameters)
at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.CallEventSubscriber(NavApplicationObjectBase callingApplicationObject, NavEventSubscription subscriber, NavApplicationObjectBase subscriberInstance, Object[] parameters)
at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.ProcessCallToTypeAndManualSubscriptions(NavApplicationObjectBase callerApplicationObject, NavEventSubscription[] subscriptions, PrepareParametersCallBack prepareParameters)
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.RunEvent()
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1381.OnInsertCustomerFromTemplate(INavRecordHandle customer, ByRef`1 result, ByRef`1 isHandled)
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1381.InsertCustomerFromTemplate(INavRecordHandle customer)
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1381.OnInvoke(Int32 memberId, Object[] args)
at Microsoft.Dynamics.Nav.BusinessApplication.Page21.CreateCustomerFromTemplate_Scope_857168676.OnRun()
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
at Microsoft.Dynamics.Nav.BusinessApplication.Page21.CreateCustomerFromTemplate()
at Microsoft.Dynamics.Nav.BusinessApplication.Page21.OnAfterGetCurrRecord_Scope.OnRun()
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
at Microsoft.Dynamics.Nav.BusinessApplication.Page21.OnAfterGetCurrRecord()
at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnAfterGetCurrRecord()
at Microsoft.Dynamics.Nav.Runtime.NavForm.AfterGetCurrRecord()
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
--- End of inner exception stack trace ---
at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
at Microsoft.Dynamics.Nav.Service.NSFormApplicationCode.<>c__DisplayClass7_0.<Invoke>b__0(NsDataAccess dataAccess)
at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
at INavServiceWrapper.InvokeApplicationMethod(ApplicationMethodRequest , NavRecordState )
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceWrapper.<>c__DisplayClass119_0.<BeginInvokeApplicationMethod>b__0()
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceWrapper.Invoke(Func`1 action, AsyncCallback callback, Object asyncState, Object extraState)
at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.<>c__DisplayClass21_0.<InvokeApplicationMethod>b__0(IAsyncNavService server)
at Microsoft.Dynamics.Nav.Runtime.TestServiceConnection.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod)
at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.InvokeApplicationMethod(ApplicationCodeType objectType, Int32 objectId, String methodName, NavDataSet& dataSet, NavRecordState& state, Object[]& args)
at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.InvokeOnAfterGetCurrentRecord(NavDataSet& navDataSet, NavRecordState& navRecordState)
at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.InvokeOnNewRecord(NavRecord record, NavRecord xrec, NavRecordState state, Object[] args)
at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.OnNewRecord(Boolean clearFormState, NavRecord xrec, Object[] args)
--- End of inner exception stack trace ---
at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.Abort(NavBaseException exception)
at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.OnNewRecord(Boolean clearFormState, NavRecord xrec, Object[] args)
at Microsoft.Dynamics.Nav.Client.DataBinder.NavBindingManager.EnsureOnNewRecordIsUpToDate()
at Microsoft.Dynamics.Nav.Client.DataBinder.NavBindingManager.OnCurrentRowChanged(CurrentRowChangeEventArgs e)
at Microsoft.Dynamics.Framework.UI.BindingManager.set_CurrentCollectionIndex(Int32 value)
at Microsoft.Dynamics.Framework.UI.VirtualRows.UpdateAfterInsert(Int32 index, Boolean needsUpdateCurrentRow)
at Microsoft.Dynamics.Framework.UI.VirtualRows.AddWithoutValidation(RowEntry row, Boolean needsUpdateCall, Boolean needsUpdateCurrentRow, Boolean insertFirst, Boolean raiseEvents)
at Microsoft.Dynamics.Framework.UI.VirtualRows.Insert()
at Microsoft.Dynamics.Nav.Client.TestPageClient.TestPageClientSession.CreateLogicalForm(Int32 formId, FormState formState)
at Microsoft.Dynamics.Nav.Client.TestPageClient.TestPageClientSession.CreatePage(Int32 id, ViewMode mode)
at Microsoft.Dynamics.Nav.Runtime.NavTestPage.Open(ViewMode mode)
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81050.CreateCustomerCard_Scope_865282985.OnRun()
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81050.CreateCustomerCard(NavTestPageHandle customerCard)
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit81050.AssignLookupValueToCustomerCard() - Error Call Stack:

"Mini Customer Template"(Table 1300).NewCustomerFromTemplate line 18 - Base Application by Microsoft
"Template Feature Event Handler"(CodeUnit 1389).CreateCustomerFromConfigTemplate line 9 - Base Application by Microsoft
"Template Feature Event Handler"(CodeUnit 1389).OnInsertCustomerFromTemplateHandler line 5 - Base Application by Microsoft
"Customer Templ. Mgt."(CodeUnit 1381).OnInsertCustomerFromTemplate line 2 - Base Application by Microsoft
"Customer Templ. Mgt."(CodeUnit 1381).InsertCustomerFromTemplate line 4 - Base Application by Microsoft
"Customer Card"(Page 21).CreateCustomerFromTemplate line 11 - Base Application by Microsoft
"Customer Card"(Page 21).OnAfterGetCurrRecord(Trigger) line 7 - Base Application by Microsoft
"Overload on Handler issue"(CodeUnit 81050).CreateCustomerCard line 2 - Overload on Handler issue by fluxxus.nl
"Overload on Handler issue"(CodeUnit 81050).AssignLookupValueToCustomerCard line 8 - Overload on Handler issue by fluxxus.nl
"Test Runner - Mgt"(CodeUnit 130454).RunTests - Test Runner by Microsoft
"Test Runner - Isol. Codeunit"(CodeUnit 130450).OnRun - Test Runner by Microsoft
"Test Suite Mgt."(CodeUnit 130456).RunTests - Test Runner by Microsoft
"Test Suite Mgt."(CodeUnit 130456).RunSelectedTests - Test Runner by Microsoft
"AL Test Tool"(Page 130451)."RunSelectedTests - OnAction" - Test Runner by Microsoft
```

**Comment by SBalslev** [comment]
Hi! Thank you for reporting this issue — catching scenarios where the compiler should produce an error but doesn't is extremely valuable feedback.

We can confirm that the compiler now raises a DuplicateHandlerMethodName diagnostic when handler functions share the same name, even with different signatures. This check has been in place since **Business Central runtime 13.0 (2019 Wave 1)** and has been refined in subsequent releases.

We're closing this as resolved. If you see any remaining issues with handler function validation on a current version, please don't hesitate to open a new issue.

Thank you for helping us improve the AL developer experience!
