### ISSUE TITLE
Protected var Label in a table causes BC crash, no compiler error

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#6604]
**1. Protected var Label in a table causes BC crash, no compiler error**
Add a protected var Label to a table, add a Page for it, publish and run the page in BC. This causes the server/web client to show the "an error occured" page.

Using a protected var Label in a Page causes the Al compiler to raise 

> error CS0176: Member 'Page81000.myTextTxt' cannot be accessed with an instance reference; qualify it with a type name instead.

Not sure what is means in this context, but at least a blocker to compile/publish. This blocker does not occur if the protected var Label is defined in a Table.

**2. To Reproduce**

1. Create a new AL app
2. Create a table in the app
    Add the following:
```
        protected var
        MyTextTxt: Label 'My Text', Locked = true;
```

3. Create a Page for the Table
4. Publish the app
5. Run the page

**3. Expected behavior**
I expect that the error is already raised in the compiler, also for tables.

**4. Actual behavior**
Able to publish, able to run with a "crash"/error page.

**5. Versions:**

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.1.453917
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

Name: Visual Studio Code
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z (2 wks ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Build: Business Central 18.0.23013.23795, 17.x, probably more

**Comment by atoader** [comment]
Can you provide a project that reproduces the issue? It makes it a lot more efficient to debug the problem.

**Comment by MODUSCarstenScholling** [comment]
Here we go...
[MicrosoftIssues.zip](https://github.com/microsoft/AL/files/6399623/MicrosoftIssues.zip)

And the funny thing:
```
This version of Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
User: 
Type: System.InvalidOperationException
Message:
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\170\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\B8\B8033A4FB6C878A879E051981E906AE7153442390559016EA7198C403CA5B67D.cs(22,21): error CS0176: Member 'Record81000.myTextTxt' cannot be accessed with an instance reference; qualify it with a type name instead
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\170\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\B8\B8033A4FB6C878A879E051981E906AE7153442390559016EA7198C403CA5B67D.cs(36,28): error CS0176: Member 'Record81000.myTextTxt' cannot be accessed with an instance reference; qualify it with a type name instead
  
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.GetClrType(RuntimePackageId runtimePackageId, ApplicationObjectId objectId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.CompileAndLoadClrObject()
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.TryGetMetaApplicationObject(ApplicationObjectId appObjectId, NCLMetaApplicationObject& metaApplicationObject, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetTableMetadata(Int32 id, Int32 appGroupId, Boolean requireCompiled)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.MergePageAndTable(MasterPage masterPage, Boolean withoutConfiguration)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMasterPage(Int32 id, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, Boolean forceElementRemovalOptionIfApplicable, String viewName)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMetadataForPageAndAddToCollection(Int32 pageId, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, PageDependencyResult metadataCollection)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMasterPageDependencies(MasterPage page, String personalizationId, Boolean applyPersonalization, ICollection`1 tablesToSkip)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMetadataForPageAndAllItsDependencies(Int32 pageId, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, ICollection`1 tablesToSkip, String viewName)
     at SyncInvokeGetMetadataForPageAndAllItsDependencies(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233079
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.GetClrType(RuntimePackageId runtimePackageId, ApplicationObjectId objectId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.CompileAndLoadClrObject()
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.TryGetMetaApplicationObject(ApplicationObjectId appObjectId, NCLMetaApplicationObject& metaApplicationObject, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetTableMetadata(Int32 id, Int32 appGroupId, Boolean requireCompiled)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.MergePageAndTable(MasterPage masterPage, Boolean withoutConfiguration)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMasterPage(Int32 id, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, Boolean forceElementRemovalOptionIfApplicable, String viewName)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMetadataForPageAndAddToCollection(Int32 pageId, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, PageDependencyResult metadataCollection)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMasterPageDependencies(MasterPage page, String personalizationId, Boolean applyPersonalization, ICollection`1 tablesToSkip)
     at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetMetadataForPageAndAllItsDependencies(Int32 pageId, DataSourceType dataSourceType, String personalizationId, Boolean applyPersonalization, ICollection`1 tablesToSkip, String viewName)
     at SyncInvokeGetMetadataForPageAndAllItsDependencies(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
```

**Comment by dannoe** [comment]
Duplicate https://github.com/microsoft/AL/issues/6331?

**Comment by MODUSCarstenScholling** [comment]
Indeed. But for me it does not happen in a page. But I'm closing this.
