### ISSUE TITLE
Processing of message 'textDocument/didChange' failed with error

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#6666]
I do not know how to reproduce this nor do I feel obliged or interested in wasting time on delving deeper into this. However, I ran into this, which messes up the formatting of my AL-source file when I try saving (autoformat).

Leaving this here just in case it causes someone to get a stroke of insight.

[Error - 14.43.26] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/didChange' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'length')'
Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Microsoft.Dynamics.Nav.CodeAnalysis.TextSpan..ctor(Int32 start, Int32 length) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextSpan.cs:line 36
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.UpdateBuffer(DidChangeTextDocumentRequest updateRequest, CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:line 111
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeTextDocumentRequestHandler.HandleAsync(DidChangeTextDocumentRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeTextDocumentRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by SBalslev** [comment]
Hi! Thank you for reporting this error. Since this was reported, the AL Language Server's document synchronization handling has been significantly improved.

We're closing this as part of a cleanup of older issues. If you still encounter 	extDocument/didChange errors on a current version of the AL Language extension, please don't hesitate to open a new issue.

Thank you for your contribution!
