### ISSUE TITLE
Copying a read-only List with GetRange() crashes the client with casting error

### ISSUE THREAD

**Issue by db-bc** [microsoft/AL#6697]
I found https://github.com/microsoft/AL/issues/6696 while just trying to get a list of `enum` `Names()` and chop off the 1st one representing the blank values. Now I'm trying to be clever and work around that by taking a `GetRange()` of the `Names()` list and omit the 1st name that way. I shouldn't have tried to be clever! I just get a _different, worse_ error/crash.

Shouldn't it be OK to take a read-only 'view' `List` of a read-only list, so long as we don't then try to mutate the 'view' copy (and see #6696 for _that_)?

If not, can this be diagnosed at compile-time, as I also request for #6696?

the code:
```al
pageextension 66666 Test extends "Customer List"
{
    trigger OnOpenPage()
    var
        Names, Range : List of [Text];
    begin
        Names := Enum::"Customer Blocked".Names();
        Range := Names.GetRange(2, Names.Count() - 1);
    end;
}
```

result:
![image](https://user-images.githubusercontent.com/63455896/124756639-9796ef00-df24-11eb-849c-121ecb30d01e.png)

the error from Event Viewer:
```none
Server instance: bc17cu1
Tenant ID: 
Environment Name: 
Environment Type: 
User: TCTL\daniel.boles
Type: System.InvalidCastException
Message: Unable to cast object of type 'System.Collections.ObjectModel.ReadOnlyCollection`1[Microsoft.Dynamics.Nav.Runtime.NavText]' to type 'System.Collections.Generic.List`1[Microsoft.Dynamics.Nav.Runtime.NavText]'.
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.TrappableOperationExecutor.ExecuteFactory[T](Func`1 factory, Func`2 mapNativeException)
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension66666.OnOpenPage_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension66666.OnOpenPage()
     at Microsoft.Dynamics.Nav.Types.LinqExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 action)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnOpenPage()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.OpenForm()
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.<>c__DisplayClass15_1.<HandleRegistrateDataAccess>b__0(NsDataAccess dataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess(ITreeObject parent, NavForm form, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess(ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess(ITreeObject parent, NavRecordState state, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.HandleRegistrateDataAccess(FormOpenResponse openResponse, List`1 registeredForms)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFormRequest form)
     at SyncInvokeOpenForm(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147467262
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.TrappableOperationExecutor.ExecuteFactory[T](Func`1 factory, Func`2 mapNativeException)
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension66666.OnOpenPage_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension66666.OnOpenPage()
     at Microsoft.Dynamics.Nav.Types.LinqExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 action)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnOpenPage()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.OpenForm()
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.<>c__DisplayClass15_1.<HandleRegistrateDataAccess>b__0(NsDataAccess dataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess(ITreeObject parent, NavForm form, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess(ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess(ITreeObject parent, NavRecordState state, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.HandleRegistrateDataAccess(FormOpenResponse openResponse, List`1 registeredForms)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFormRequest form)
     at SyncInvokeOpenForm(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
```

**Comment by nndobrev** [comment]
@db-bc Thank you for being so active lately, we really appreciate the provided feedback. This definitely needs to be investigated.

**Comment by db-bc** [comment]
@nndobrev You're very welcome. It's great to have a place where these things can be reported, so I do as much as I can. Thanks to you all over there for all the work on AL!

**Comment by NKarolak** [comment]
@nndobrev If you really love hunting bugs, what about proceeding with the oldest ones? 
Just a tiny example: https://github.com/microsoft/AL/issues/created_by/nkarolak ;-)

**Comment by SBalslev** [comment]
Thank you for the detailed repro on this one — we really appreciate the effort you put into documenting it. This issue is tagged as a runtime concern outside the scope of the AL compiler tooling, and we haven't been able to follow up on it.

We're closing it as part of a cleanup of older issues. If you can still reproduce this on the latest version of Business Central, please open a new issue and we'll be happy to take another look. Your continued feedback helps us improve the platform!
