### ISSUE TITLE
List page search crashes when entering large numbers if datetime field is present on the page

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/AL#6707]
When:
- You have a list page containing a visible field of type "Duration";
- You enter a numeric search string with a value that exceeds 2,147,483,647 (the maximum for an Int32)

Then:
- The client crashes

Event log:
![Duration_Search_Bug](https://user-images.githubusercontent.com/47315514/125634839-38ec9c46-e5b1-42b5-8ae4-1bc6344af7fa.png)

Server instance: [REDACTED]
Tenant ID: 
Environment Name: 
Environment Type: 
User: [REDACTED]
Type: System.OverflowException
Message: TimeSpan overflowed because the duration is too long.
StackTrace:
     at System.TimeSpan.Interval(Double value, Int32 scale)
     at Microsoft.Dynamics.Nav.Runtime.NavDuration.Format(FormatSettings formatSettings, Int32 standardFormatNumber)
     at Microsoft.Dynamics.Nav.Runtime.NavFormatEvaluateHelper.FormatWithParsedFormatString(NavValue value, Int32 length, String format, Int32 number, FormatSettings settings)
     at Microsoft.Dynamics.Nav.Runtime.NavFormatEvaluateHelper.FormatWithFormatNumber(NavValue value, Int32 length, Int32 number, FormatSettings settings)
     at Microsoft.Dynamics.Nav.Runtime.NavFormatEvaluateHelper.Format(NavValue value, Int32 length, Int32 number, FormatSettings formatSettings)
     at Microsoft.Dynamics.Nav.Runtime.NavValue.ToString(Boolean invariant)
     at Microsoft.Dynamics.Nav.Runtime.FilterExpressionContext.ValueToString(NavValue value, FilterExpressionStringOptions stringOptions)
     at Microsoft.Dynamics.Nav.Runtime.FilterStringVisitor.VisitUnary(UnaryFilterExpression unaryExpression, Tuple`2 input)
     at Microsoft.Dynamics.Nav.Runtime.FilterExpression.ToString(FilterExpressionStringOptions stringOptions)
     at Microsoft.Dynamics.Nav.Runtime.TableState.CreateNavFilter(NCLMetaField field, FilterExpression filter)
     at Microsoft.Dynamics.Nav.Runtime.TableState.<>c.<GetNavFilterGroups>b__74_2(KeyValuePair`2 f)
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Microsoft.Dynamics.Nav.Runtime.TableState.<>c.<GetNavFilterGroups>b__74_1(KeyValuePair`2 g)
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Microsoft.Dynamics.Nav.Runtime.TableState.GetNavTableView()
     at Microsoft.Dynamics.Nav.Service.NSDataSetState.UpdateFromRecord(NavRecordState state, NsDataAccess recDataAccess, Boolean includeDynamicCaptions)
     at Microsoft.Dynamics.Nav.Service.NSDataSetState.Create(NsDataAccess recDataAccess, Boolean includeDynamicCaptions, Boolean includeChanges)
     at Microsoft.Dynamics.Nav.Service.NSPage.<GetPageData>b__6_0(NsDataAccess recDataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NSPage.GetPage(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.Microsoft.Dynamics.Nav.Types.INavService.GetPage(PageRequestDefinition pageRequestDefinition, NavRecordState state)
     at SyncInvokeGetPage(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: mscorlib
HResult: -2146233066
StackTrace:
     at System.TimeSpan.Interval(Double value, Int32 scale)
     at Microsoft.Dynamics.Nav.Runtime.NavDuration.Format(FormatSettings formatSettings, Int32 standardFormatNumber)
     at Microsoft.Dynamics.Nav.Runtime.NavFormatEvaluateHelper.FormatWithParsedFormatString(NavValue value, Int32 length, String format, Int32 number, FormatSettings settings)
     at Microsoft.Dynamics.Nav.Runtime.NavFormatEvaluateHelper.FormatWithFormatNumber(NavValue value, Int32 length, Int32 number, FormatSettings settings)
     at Microsoft.Dynamics.Nav.Runtime.NavFormatEvaluateHelper.Format(NavValue value, Int32 length, Int32 number, FormatSettings formatSettings)
     at Microsoft.Dynamics.Nav.Runtime.NavValue.ToString(Boolean invariant)
     at Microsoft.Dynamics.Nav.Runtime.FilterExpressionContext.ValueToString(NavValue value, FilterExpressionStringOptions stringOptions)
     at Microsoft.Dynamics.Nav.Runtime.FilterStringVisitor.VisitUnary(UnaryFilterExpression unaryExpression, Tuple`2 input)
     at Microsoft.Dynamics.Nav.Runtime.FilterExpression.ToString(FilterExpressionStringOptions stringOptions)
     at Microsoft.Dynamics.Nav.Runtime.TableState.CreateNavFilter(NCLMetaField field, FilterExpression filter)
     at Microsoft.Dynamics.Nav.Runtime.TableState.<>c.<GetNavFilterGroups>b__74_2(KeyValuePair`2 f)
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Microsoft.Dynamics.Nav.Runtime.TableState.<>c.<GetNavFilterGroups>b__74_1(KeyValuePair`2 g)
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Microsoft.Dynamics.Nav.Runtime.TableState.GetNavTableView()
     at Microsoft.Dynamics.Nav.Service.NSDataSetState.UpdateFromRecord(NavRecordState state, NsDataAccess recDataAccess, Boolean includeDynamicCaptions)
     at Microsoft.Dynamics.Nav.Service.NSDataSetState.Create(NsDataAccess recDataAccess, Boolean includeDynamicCaptions, Boolean includeChanges)
     at Microsoft.Dynamics.Nav.Service.NSPage.<GetPageData>b__6_0(NsDataAccess recDataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NSPage.GetPage(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.Microsoft.Dynamics.Nav.Types.INavService.GetPage(PageRequestDefinition pageRequestDefinition, NavRecordState state)
     at SyncInvokeGetPage(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)

**Comment by kalberes** [comment]
Please open a support case if you want this to be fixed. We can't do much about it on this platform.
