### ISSUE TITLE
AL Find Event - Strange Error for BC14

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#6780]
Please include the following with each issue:

**1. Describe the bug**
When I execute the Command "AL: Find Event" within a BC 14 Project I reive the following error.

> Processing of message 'al/getEventPublishersRequest' failed with error: 'One or more errors occurred. (One or more errors occurred. (Nullable object must have a value.)) (Nullable object must have a value.)'
Details:
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Nullable object must have a value.)) (Nullable object must have a value.)
 ---> System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.CreateMethodSignature(ISymbol s, IApplicationObjectTypeSymbol appObj, String appObjName) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 75
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.<>c.<HandleAsync>b__3_3(ISymbol e) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 52
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.SortHelper`2.BuildKeysFromSource(GrowingArray`1& keys, List`1& values)
   at System.Linq.Parallel.SortHelper`2.Sort()
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.Spool(QueryTaskGroupState groupState, PartitionedStream`2 partitions, Shared`1 results, TaskScheduler taskScheduler)
   at System.Linq.Parallel.OrderPreservingMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.SelectQueryOperator`2.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.SortQueryOperatorResults`2.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 childPartitionedStream)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStreamNotIndexed[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, QuerySettings settings)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStream[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStreamNotIndexed[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, QuerySettings settings)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStream[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.SortQueryOperatorResults`2.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.HandleAsync(GetEventPublishersRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 43
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**2. To Reproduce**

1. Open the Command Palatte in VS Code
2. Execute the Command AL : Find Event in a BC 14 Project

**3. Expected behavior**
If this feature cannot be supported for BC 14, then please add a clear and understandable error notifaction.

**4. Actual behavior**
Right now there is only a uncaught error

**5. Versions:**

- AL Language: v7.4.502459
- Visual Studio Code: 
      Version: 1.60.2 (user setup)
   Date: 2021-09-22T12:00:31.514Z (1 wk ago)
   Electron: 13.1.8
   Chrome: 91.0.4472.164
   Node.js: 14.16.0
   V8: 9.1.269.39-electron.0
   OS: Windows_NT x64 10.0.19042

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by thpeder** [comment]
Hi @pri-kise,

Thanks for reporting your issue but this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by pri-kise** [comment]
@thpeder could you please ReOpen this issue, since this error is still there for a preview release.

AL Language Extension: `9.0.519128`

> [Error - 07:31:29] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/getEventPublishersRequest' failed with error: 'One or more errors occurred. (Nullable object must have a value.)'
Details:
System.AggregateException: One or more errors occurred. (Nullable object must have a value.)
 ---> System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.CreateMethodSignature(ISymbol s, IApplicationObjectTypeSymbol appObj, String appObjName) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 75
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.<>c.<HandleAsync>b__3_3(ISymbol e) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 52
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.SortHelper`2.BuildKeysFromSource(GrowingArray`1& keys, List`1& values)
   at System.Linq.Parallel.SortHelper`2.Sort()
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.Spool(QueryTaskGroupState groupState, PartitionedStream`2 partitions, Shared`1 results, TaskScheduler taskScheduler)
   at System.Linq.Parallel.OrderPreservingMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.SelectQueryOperator`2.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.SortQueryOperatorResults`2.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 childPartitionedStream)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStream[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.SelectManyQueryOperator`3.WrapPartitionedStream[TLeftKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.SortQueryOperatorResults`2.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.GetEventPublishersRequestHandler.HandleAsync(GetEventPublishersRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\GetEventPublishersRequestHandler.cs:line 43
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by thpeder** [comment]
You have a good point, the AL Extension in the market place should be backwards compatible.

**Comment by SBalslev** [comment]
Hi! Thank you for reporting this issue — we appreciate the detailed repro steps.

This repository is focused on the latest versions of the AL compiler and developer tools. The version referenced in this issue is no longer in mainstream support, and significant improvements have been made in subsequent releases.

If you can reproduce this on a current version, please don't hesitate to open a new issue and we'll be happy to investigate.

Thank you for helping us improve the AL developer experience!
