### ISSUE TITLE
Error "A request has failed..."

### ISSUE THREAD

**Issue by VladimirTkalich** [microsoft/AL#6791]
Please include the following with each issue:

**1. Describe the bug**
When mouse move on source code of ".alpackages\Microsoft_Base Application_18.5.29545.30737.app"  very often appears the message in right down corner:
"A request has failed. See the output for more information. Source: AL Language (Extension)"

Information in Output:
"[Error - 08:26:14] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/gotodefinition' failed with error: 'Index was outside the bounds of the array.'
Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.FilePathHelper.ParsePreviewFileUrl(Uri uri) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\FilePathHelper.cs:line 97
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDeclaringSymbolAsync(Uri previewUri, CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 136
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetContentAsync(Uri previewUri, LaunchConfiguration configuration, CancellationToken token, Boolean relyOnCachedValue) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 74
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.ReferenceSymbolDefinitionManager.GetDefinitionForSymbolAtPositionAsync(Uri previewUri, Position requestPosition, LaunchConfiguration configuration, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\ReferenceSymbolDefinitionManager.cs:line 100
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.AlDefinitionRequestHandler.ProcessRequestAsync(AlDefinitionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\AlDefinitionRequestHandler.cs:line 51
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80
"

**2. To Reproduce**
Move mouse pointer over source code  of ".alpackages\Microsoft_Base Application_18.5.29545.30737.app"

**3. Expected behavior**
No action until I click mouse

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language: v8.1.525271
- Visual Studio Code: 1.61.0
- Business Central: 18.5 (Platform 18.0.29486.30668 + Application 18.5.29545.0)
- List of Visual Studio Code extensions that you have installed:
Markdown All in One v3.4.0
AZ AL Dev Tools/AL Code Outline v3.0.18
waldo's CRS AL Language Extension v1.4.11
AL Toolbox v2.0.14
AL Object Designer v0.2.4
AL CodeActions v1.0.7
AL Variable Helper v2.4.0
AL Navigator v0.4.6
AL Extension Pack v1.0.15
AL Test Runner v0.6.1
AL Object ID Ninja v2.0.0
AL Toolbox v2.0.14
Bracket Pair Colorizer 2 v0.2.1
Create GUID v0.0.2
Docker v1.17.0
Git History v0.6.18
GitLens — Git supercharged v11.6.1
NAB AL Tools v1.6.0
Partial Diff v1.4.3
PowerShell v2021.10.0
REST Client v0.24.5
snippet-creator v0.0.5
TODO Highlight v1.0.4
Todo Tree v0.0.214
vscode-icons v11.6.0
XLIFF Sync v1.2.0
### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
