### ISSUE TITLE
Dictionary of [Integer, TextBuilder] causes AL to crash

### ISSUE THREAD

**Issue by vjekob** [microsoft/AL#6823]
Please include the following with each issue:

**1. Describe the bug**
When declaring a variable of type `Dictionary of [Integer, TextBuilder]` the parser doesn't show a syntax error. However, AL compiler starts crashing and it's impossible to continue developing until the variable declaration is removed.

**2. To Reproduce**

1. Create a new codeunit object
2. Declare a global variable of type `Dictionary of [Integer, TextBuilder]`, for example
```
var
  Builders: Dictionary of [Integer, TextBuilder];
```

**3. Expected behavior**
Compiler should compile without crashing. `Dictionary of [Integer, TextBuilder]` should be a valid type declaration:

**4. Actual behavior**
Compiler starts putting this info into the Output window:

```
[Error - 15:54:09] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeLens' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.VisitVariable(VariableSymbol symbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:line 132
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.VariableSymbol.Accept(SymbolVisitor visitor) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\Symbols.Generated.cs:line 1265
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplay.cs:line 113
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.Symbol.ToDisplayString(SymbolDisplayFormat format) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Symbol.cs:line 471
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.SymbolExtensions.GetSymbolInformationName(Symbol symbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\SymbolExtensions.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.SymbolExtensions.ToSymbolInformation(Symbol symbol, String fileUri, Boolean useSymbolLocation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\SymbolExtensions.cs:line 19
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.ProcessMember(String fileUri, Predicate`1 predicate, Symbol symbol, ArrayBuilder`1 builder, Boolean isCodeLens, Boolean onlySearchTopLevelObjects, Int32 depth) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:line 129
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.ProcessMember(String fileUri, Predicate`1 predicate, Symbol symbol, ArrayBuilder`1 builder, Boolean isCodeLens, Boolean onlySearchTopLevelObjects, Int32 depth) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:line 136
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.GetSymbolInformations(Document document, CancellationToken cancellationToken, Boolean onlySearchTopLevelObjects, Boolean isCodeLens, Predicate`1 predicate) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:line 108
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.GetCodeLensSymbolInformations(Document document, CancellationToken cancellationToken, Predicate`1 predicate) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:line 71
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensRequestHandler.HandleAsync(CodeLensRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensRequestHandler.cs:line 30
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80
```

**5. Versions:**

- AL Language: v8.1.525271
- Visual Studio Code: 1.62.0
- Business Central: BC19
- List of Visual Studio Code extensions that you have installed: All extensions are disabled except for AL Language. The problem still happens.

**Comment by vjekob** [comment]
The same problem happens with `List of [TextBuilder]`.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 32781 and VS Code Extension Version 9.0.546911. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
