### ISSUE TITLE
Code-analysis crash

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#6825]
[Error - 9.14.32] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeAction' failed with error: 'An unexpected error happened when processing the document 'c:/../ItemExportPST.Codeunit.al' at position 'Line: 8 - Character: 24'. Left token: '('. Target token: '('. Right token: 'PostiExportPST'. 
Exception details: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.RecommendPropertiesAsync(Document document, MemberSyntaxContext context, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"'
Details:
Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionException: An unexpected error happened when processing the document 'c:/../ItemExportPST.Codeunit.al' at position 'Line: 8 - Character: 24'. Left token: '('. Target token: '('. Right token: 'PostiExportPST'. 
Exception details: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.RecommendPropertiesAsync(Document document, MemberSyntaxContext context, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 201
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.CreateSpellCheckCodeIssueAsync(CodeFixContext context, SyntaxToken nameToken, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 120
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.CheckNodeAsync(CodeFixContext context, Document document, SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 84
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.RegisterCodeFixesAsync(CodeFixContext context) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 56
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(Document document, TextSpan span, ICodeFixProvider fixer, ImmutableArray`1 diagnostics, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 147
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.AppendFixesAsync(Document document, TextSpan span, IEnumerable`1 diagnosticsWithSameSpan, ArrayBuilder`1 result, ICodeFixProvider fixer, Func`2 hasFix, Func`2 getFixes, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 131
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.AppendFixesAsync(Document document, TextSpan span, IEnumerable`1 diagnostics, ArrayBuilder`1 result, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 96
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.GetFixesAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 74
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeActions.ALCodeActionService.GetCodeActionsAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeActions\ALCodeActionService.cs:line 60
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeActionRequestHandler.HandleAsync(ProtocolCodeActionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeActionRequestHandler.cs:line 59
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

[Error - 9.15.57] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeAction' failed with error: 'An unexpected error happened when processing the document 'c:/../ItemTabExt.TableExt.al' at position 'Line: 259 - Character: 13'. Left token: ';'. Target token: ';'. Right token: '"Brochure Content"'. 
Exception details: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.RecommendPropertiesAsync(Document document, MemberSyntaxContext context, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"'
Details:
Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionException: An unexpected error happened when processing the document 'c:/../ItemTabExt.TableExt.al' at position 'Line: 259 - Character: 13'. Left token: ';'. Target token: ';'. Right token: '"Brochure Content"'. 
Exception details: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.RecommendPropertiesAsync(Document document, MemberSyntaxContext context, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.PropertyDeclarationCompletionProvider.ProvideCompletionsAsync(CompletionContext context, AbstractSyntaxContext memberSyntaxContext) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\Providers\PropertyDeclarationCompletionProvider.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, OptionSet options, Nullable`1 defaultSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 386
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 185"
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 201
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.CreateSpellCheckCodeIssueAsync(CodeFixContext context, SyntaxToken nameToken, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 120
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.CheckNodeAsync(CodeFixContext context, Document document, SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 84
   at Microsoft.Dynamics.Nav.CodeAnalysis.SpellCheck.SpellCheckCodeFixProvider.RegisterCodeFixesAsync(CodeFixContext context) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\Providers\SpellCheck\SpellCheckCodeFixProvider.cs:line 56
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(Document document, TextSpan span, ICodeFixProvider fixer, ImmutableArray`1 diagnostics, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 147
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.AppendFixesAsync(Document document, TextSpan span, IEnumerable`1 diagnosticsWithSameSpan, ArrayBuilder`1 result, ICodeFixProvider fixer, Func`2 hasFix, Func`2 getFixes, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 131
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.AppendFixesAsync(Document document, TextSpan span, IEnumerable`1 diagnostics, ArrayBuilder`1 result, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 96
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeFixes.CodeFixService.GetFixesAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeFixes\CodeFixService.cs:line 74
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeActions.ALCodeActionService.GetCodeActionsAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeActions\ALCodeActionService.cs:line 60
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeActionRequestHandler.HandleAsync(ProtocolCodeActionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeActionRequestHandler.cs:line 59
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80

**Comment by kalberes** [comment]
Can you please provide repro steps and versions.

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
