### ISSUE TITLE
AL: Find Event crashes

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/AL#6844]
**1. Describe the bug**
AL: Find Event crashes when trying to execute the command

**2. To Reproduce**

1. Go in a codeunit
2. use F1: find event

**3. Expected behavior**
Seen events in base app

**4. Actual behavior**
Error appears:
```
[Window Title]
Visual Studio Code
[Content]
Command 'AL: Find Event' resulted in an error (An unknown error occurred. Please consult the log for more details.)
[OK]
```

VSC Output - Log (extension Host):
```
[2021-11-23 11:57:08.877] [exthost] [error] [ms-dynamics-smb.al] provider FAILED
[2021-11-23 11:57:08.877] [exthost] [error] TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Bert.Detemmerman\.vscode\extensions\ms-dynamics-smb.al-8.2.545335\node_modules\vscode-languageclient\lib\common\protocolConverter.js:151:27)
	at asHover (c:\Users\Bert.Detemmerman\.vscode\extensions\ms-dynamics-smb.al-8.2.545335\node_modules\vscode-languageclient\lib\common\protocolConverter.js:191:31)
	at async d.provideHover (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:170516)
[2021-11-23 11:58:09.400] [exthost] [warning] TextEditor is closed/disposed
```

After disabling all other extensions (and trying again):
```
[2021-11-23 12:04:12.698] [exthost] [error] Error: 
	at handleResponse (c:\Users\Bert.Detemmerman\.vscode\extensions\ms-dynamics-smb.al-8.2.545335\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\Bert.Detemmerman\.vscode\extensions\ms-dynamics-smb.al-8.2.545335\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\Bert.Detemmerman\.vscode\extensions\ms-dynamics-smb.al-8.2.545335\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21) al.insertEvent {"value":"ms-dynamics-smb.al","_lower":"ms-dynamics-smb.al"}
```

**5. Versions:**

- AL Language: 8.2.545335
- Visual Studio Code: 
Version: 1.62.3 (system setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
- Business Central:
Microsoft_Base Application_19.0.29894.32088.app
- List of Visual Studio Code extensions that you have installed:
albymor.increment-selection
andrzejzwierzchowski.al-code-outline
BartPermentier.al-toolbox
chunsen.bracket-select
ClipDynamics.al-language-tools      
coderAllan.vscode-dgmlviewer        
CoenraadS.bracket-pair-colorizer-2  
davidfeldhoff.al-codeactions        
DotJoshJohnson.xml
dynasist.al-studio
eamodio.gitlens
funkyremi.vscode-google-translate   
Gruntfuggly.todo-tree
heaths.vscode-guid
hediet.vscode-drawio
humao.rest-client
jamespearson.al-test-runner
jasonlhy.hungry-delete
martonsagi.al-object-designer
mhutchie.git-graph
ms-azure-devops.azure-pipelines
ms-azuretools.vscode-docker
ms-dynamics-smb.al
ms-mssql.data-workspace-vscode
ms-mssql.mssql
ms-mssql.sql-database-projects-vscode
ms-vscode.azure-account
ms-vscode.powershell
rasmus.al-formatter
rasmus.al-var-helper
redhat.vscode-yaml
usernamehw.errorlens
waldo.crs-al-language-extension
wayou.vscode-todo-highlight
wbrakowski.al-navigator
yzhang.markdown-all-in-one

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by dnpb** [comment]
Yup, I just get this popup:
![image](https://user-images.githubusercontent.com/63455896/143022383-f82cf6f2-f997-49d5-baf1-626b0d9b6d2e.png)

**Comment by pmatsconsulting** [comment]
The same:
![image](https://user-images.githubusercontent.com/43445162/143325817-49491f12-4e2c-4eaf-bd99-79bfbe37ba23.png)

Worked with version v8.2.545335

**Comment by AntonioCapdevila** [comment]
I have the same issue. :-(

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 33063 and VS Code Extension Version 9.0.549427. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by BertDeTemmerman** [comment]
Awesome! Thank you.

Will this be backported to a current AL Language version (8.x)?
It would be a pity to wait until next BC version in April while have this usefull feature missing ...

**Comment by JesperSchulz** [comment]
It will, yes :-)

**Comment by BertDeTemmerman** [comment]
> It will, yes :-)

Yeah! You are (all) the best! 😀
