### ISSUE TITLE
Analyzer throws Rule0242PartialRecordsDetectJitLoads exception

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL#6848]
Please include the following with each issue:

**1. Describe the bug**
A SetLoadFields() call followed by a RequestOptionsPage.Update() call causes the analyzer to throw the following exception:

![image](https://user-images.githubusercontent.com/92365904/143415044-1a4357e1-58aa-4a76-8f07-a3595aba1095.png)

**2. To Reproduce**
- Disable all VSCode extensions except AL Language
- Open the sample project in the attachments
- Make sure code analysis is enabled
- Run "AL Package".
- The exception above is thrown

``` AL
trigger OnPreDataItem()
var
    Customer: record "Customer";
begin
    Customer.SetLoadFields(Name);
    RequestOptionsPage.Update(); // This line causes the analyzer to throw an exception
end;
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
The code analyzer should not thrown an exception

**4. Actual behavior**
The code analyzer throws an exception:
![JITIssue](https://user-images.githubusercontent.com/92365904/143415706-f93d1f8d-eb48-4c45-a9e8-a86c2db7081b.gif)

**5. Versions:**

- AL Language: 
  ![image](https://user-images.githubusercontent.com/92365904/143415888-88d5e1eb-b8b3-476c-86f8-785829de7807.png)
- Visual Studio Code:
  ![image](https://user-images.githubusercontent.com/92365904/143415967-d81d8797-0b6a-40f2-a120-4dca514998ab.png)
- Business Central: N/A
- List of Visual Studio Code extensions that you have installed:
  Only AL Language is enabled:
  ![image](https://user-images.githubusercontent.com/92365904/143416101-31871735-958c-4733-80ef-d9dee73e352d.png)

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by dnpb** [comment]
It keeps coming back! See original https://github.com/microsoft/AL/issues/6558 and my new https://github.com/microsoft/AL/issues/6891

**Comment by PhDuck** [comment]
Does not reproduce on my developer build.

**Comment by dnpb** [comment]
Repro!

```al
report 50100 Test
{
    dataset
    {
        dataitem(Customer; Customer)
        {
            trigger OnPreDataItem()
            var
                Customer: record "Customer";
            begin
                Customer.SetLoadFields(Name);
                RequestOptionsPage.Update(); // This line causes the analyzer to throw an exception
            end;
        }
    }

    requestpage
    { }
}
```

***

uncommented: borked

![image](https://user-images.githubusercontent.com/63455896/149740939-6474d236-dcaf-4e7f-8fbb-194fa8f1f733.png)

```none
Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundObjectAccess' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IFieldAccess'.
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationExtensions.GetSymbol(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationExtensions.cs:line 41
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads.JitLoadDetectionVisitor.VisitInvocationExpression(IInvocationExpression operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule0242PartialRecordsDetectJitLoads.cs:line 255
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.VisitArray[T](ImmutableArray`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.VisitBlockStatement(IBlockStatement operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 49
   at Microsoft.Dynamics.Nav.CodeAnalysis.BoundBlock.Accept(OperationVisitor visitor) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\BoundTree\Statements.cs:line 84
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads.AnalyzeMethod(OperationAnalysisContext context) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule0242PartialRecordsDetectJitLoads.cs:line 128
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 764
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1100'
```

***

commented: works
![image](https://user-images.githubusercontent.com/63455896/149740873-93b43560-1756-44f4-a330-edd2a0914eb3.png)

***

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.2.552672
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by PhDuck** [comment]
It isn't reproducing in the dev branch since it was already fixed. It seems it wasn't backported to release branch, will do that now.

**Comment by dnpb** [comment]
Thanks!
