### ISSUE TITLE
FlowField lacking CalcFormula not diagnosed by compiler, silently publishes and can cause runtime crash

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6859]
**1. Describe the bug**
A FlowField without a CalcFormula cannot possibly achieve anything, yet it is not diagnosed by the compiler.
Such fields can arise due to developers forgetting to specify a formula, or meaning to write `FieldClass = FlowFilter` but instead writing `FlowField` accidentally.
In the latter case, using the accidental FlowField as a filter in another FlowField causes a client crash with no info on the problem.

**2. To Reproduce**
```al
tableextension 50100 Item extends Item
{
    fields
    {
        field(50100; "Entry Posting Date Filter"; Date)
        {
            FieldClass = FlowField; // OOPS!! should've been a FlowFilter...
        }

        field(50110; "Latest Open Entry No."; Integer)
        {
            FieldClass = FlowField;
            CalcFormula = max("Item Ledger Entry"."Entry No." where("Item No." = field("No."),
                                                                    "Posting Date" = field("Entry Posting Date Filter"),
                                                                    Open = const(true)));
        }
    }
}

pageextension 50100 "Item List" extends "Item List"
{
    layout
    {
        addafter("Vendor No.")
        {
            field("Latest Open Entry No."; Rec."Latest Open Entry No.")
            {
                ApplicationArea = All;
            }
        }
    }
}
```

**3. Expected behavior**
I expect an error or at the very least a warning if I have declared a FlowField that can't possibly work as intended, particularly because right now it can silently compile but lead to runtime crashes later.

**4. Actual behavior**
The client crashes:
![image](https://user-images.githubusercontent.com/63455896/144589584-482b81fa-c8b9-453e-a31d-d999469fda07.png)
This event is logged:
```none
This version of Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
User: 
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.FieldsAndFormulaAreSelfReferencing(NCLMetaField[] fieldsToCalc)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.CalcFieldsFromNonVirtualTables(NavSession session, Int32 companyToken, IRecordBuffer recordBuffer, FiltersAndMarks filtersAndMarks, SecurityFiltering flowFieldSecurityFiltering, NCLMetaField[] fieldsToCalc, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.CalcFields(NavSession session, Int32 companyToken, IRecordBuffer recordBuffer, FiltersAndMarks filtersAndMarks, NCLMetaField[] fieldsToCalc, Boolean onlyFieldsSourcedFromVirtualTables, SecurityFiltering flowFieldSecurityFiltering, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.GetFilterFromMetaFilterCollection(NavSession session, Int32 companyToken, IRecordBuffer currentRecord, FiltersAndMarks filtersAndMarks, SecurityFiltering securityFiltering, NCLMetaFilterCollection filters, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.GetDistinctSourceTablesFromFlowFields(NavSession session, Int32 companyToken, IRecordBuffer currentRecord, FiltersAndMarks filtersAndMarks, SecurityFiltering flowFieldSecurityFiltering, IEnumerable`1 flowFields, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.CalcFieldsFromNonVirtualTables(NavSession session, Int32 companyToken, IRecordBuffer recordBuffer, FiltersAndMarks filtersAndMarks, SecurityFiltering flowFieldSecurityFiltering, NCLMetaField[] fieldsToCalc, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.CalcFields(NavSession session, Int32 companyToken, IRecordBuffer recordBuffer, FiltersAndMarks filtersAndMarks, NCLMetaField[] fieldsToCalc, Boolean onlyFieldsSourcedFromVirtualTables, SecurityFiltering flowFieldSecurityFiltering, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProviderHelper.CalculateAndValidateFlowField(NavSession session, PositionedFindProviderRequest request, ReadOnlyRecordBuffer inputBuffer, NCLMetaField flowField, NavValue& calculatedValue)
     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProviderHelper.ValidateFiltersAndValuesForAutoCalculatedFlowFields(NavSession session, PositionedFindProviderRequest request, ReadOnlyRecordBuffer inputBuffer, Tuple`2[] flowFields, Boolean calculateDependingOnNonstandardJoinCriteriaCondition)
     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.<>c__DisplayClass37_1.<TableFindFromPosition>b__6(ReadOnlyRecordBuffer row)
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
     at Microsoft.Dynamics.Nav.Runtime.ResultSet.TryGetAtIndex(Int32 index, ReadOnlyRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryGetRecordBufferFromResultSet(Int32 fetchIndex, MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryMoveNextImpl(MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Advance(Int32 steps, Boolean moveBackwards, Boolean automaticFindFromPositionOnInvalid, Boolean& resultSetValid, Int32 setSize)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.IssueFindFromPositionRequest(Boolean reverseDirection, Boolean includeCurrent, Int32 setSize)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecordImp(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALFind(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.BusinessApplication.Page31.OnFindRecord_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Page31.OnFindRecord(NavText which)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.FindRecord(String which)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.Find(String searchMethod)
     at Microsoft.Dynamics.Nav.Service.NSPage.PositionDataAccess(NsDataAccess recDataAccess)
     at Microsoft.Dynamics.Nav.Service.NSPage.PopulateSpecificPage(NavDataSet dataSet, NsDataAccess recDataAccess, Boolean& moreDataInReadDirection, Boolean& moreDataInOppositeDirection)
     at Microsoft.Dynamics.Nav.Service.NSPage.PopulateCLRDataSet(NavDataSet dataSet, NsDataAccess recDataAccess, Boolean& moreDataInReadDirection, Boolean& moreDataInOppositeDirection)
     at Microsoft.Dynamics.Nav.Service.NSPage.<GetPageData>b__6_0(NsDataAccess recDataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NSPage.GetPage(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.Microsoft.Dynamics.Nav.Types.INavService.GetPage(PageRequestDefinition pageRequestDefinition, NavRecordState state)
     at SyncInvokeGetPage(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147467261
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.FieldsAndFormulaAreSelfReferencing(NCLMetaField[] fieldsToCalc)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.CalcFieldsFromNonVirtualTables(NavSession session, Int32 companyToken, IRecordBuffer recordBuffer, FiltersAndMarks filtersAndMarks, SecurityFiltering flowFieldSecurityFiltering, NCLMetaField[] fieldsToCalc, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.CalcFields(NavSession session, Int32 companyToken, IRecordBuffer recordBuffer, FiltersAndMarks filtersAndMarks, NCLMetaField[] fieldsToCalc, Boolean onlyFieldsSourcedFromVirtualTables, SecurityFiltering flowFieldSecurityFiltering, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.GetFilterFromMetaFilterCollection(NavSession session, Int32 companyToken, IRecordBuffer currentRecord, FiltersAndMarks filtersAndMarks, SecurityFiltering securityFiltering, NCLMetaFilterCollection filters, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.GetDistinctSourceTablesFromFlowFields(NavSession session, Int32 companyToken, IRecordBuffer currentRecord, FiltersAndMarks filtersAndMarks, SecurityFiltering flowFieldSecurityFiltering, IEnumerable`1 flowFields, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.CalcFieldsFromNonVirtualTables(NavSession session, Int32 companyToken, IRecordBuffer recordBuffer, FiltersAndMarks filtersAndMarks, SecurityFiltering flowFieldSecurityFiltering, NCLMetaField[] fieldsToCalc, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.FlowFieldsHelper.CalcFields(NavSession session, Int32 companyToken, IRecordBuffer recordBuffer, FiltersAndMarks filtersAndMarks, NCLMetaField[] fieldsToCalc, Boolean onlyFieldsSourcedFromVirtualTables, SecurityFiltering flowFieldSecurityFiltering, Int32 recursionLevel)
     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProviderHelper.CalculateAndValidateFlowField(NavSession session, PositionedFindProviderRequest request, ReadOnlyRecordBuffer inputBuffer, NCLMetaField flowField, NavValue& calculatedValue)
     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProviderHelper.ValidateFiltersAndValuesForAutoCalculatedFlowFields(NavSession session, PositionedFindProviderRequest request, ReadOnlyRecordBuffer inputBuffer, Tuple`2[] flowFields, Boolean calculateDependingOnNonstandardJoinCriteriaCondition)
     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.<>c__DisplayClass37_1.<TableFindFromPosition>b__6(ReadOnlyRecordBuffer row)
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
     at Microsoft.Dynamics.Nav.Runtime.ResultSet.TryGetAtIndex(Int32 index, ReadOnlyRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryGetRecordBufferFromResultSet(Int32 fetchIndex, MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryMoveNextImpl(MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Advance(Int32 steps, Boolean moveBackwards, Boolean automaticFindFromPositionOnInvalid, Boolean& resultSetValid, Int32 setSize)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.IssueFindFromPositionRequest(Boolean reverseDirection, Boolean includeCurrent, Int32 setSize)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.FindRecordImp(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALFind(DataError errorLevel, String searchMethod)
     at Microsoft.Dynamics.Nav.BusinessApplication.Page31.OnFindRecord_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Page31.OnFindRecord(NavText which)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.FindRecord(String which)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.Find(String searchMethod)
     at Microsoft.Dynamics.Nav.Service.NSPage.PositionDataAccess(NsDataAccess recDataAccess)
     at Microsoft.Dynamics.Nav.Service.NSPage.PopulateSpecificPage(NavDataSet dataSet, NsDataAccess recDataAccess, Boolean& moreDataInReadDirection, Boolean& moreDataInOppositeDirection)
     at Microsoft.Dynamics.Nav.Service.NSPage.PopulateCLRDataSet(NavDataSet dataSet, NsDataAccess recDataAccess, Boolean& moreDataInReadDirection, Boolean& moreDataInOppositeDirection)
     at Microsoft.Dynamics.Nav.Service.NSPage.<GetPageData>b__6_0(NsDataAccess recDataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NSPage.GetPage(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.Microsoft.Dynamics.Nav.Types.INavService.GetPage(PageRequestDefinition pageRequestDefinition, NavRecordState state)
     at SyncInvokeGetPage(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

**5. Versions:**

- AL Language:
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.2.550913
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

- Visual Studio Code: 1.62.3
- Business Central: 19.1
- List of Visual Studio Code extensions that you have installed:
![image](https://user-images.githubusercontent.com/63455896/144588874-41b92c52-c93b-4a72-b3bb-5e8ab7b276ac.png)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 36473 and VS Code Extension Version 9.0.585662. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
