### ISSUE TITLE
Accessing non-loaded field, or other table's field, without Rec prefix makes Rule0242PartialRecordsDetectJitLoads throw NullReferenceException

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6891]
**1. Describe the bug**
The title says it all!

**2. To Reproduce**
Paste this:
``` AL
tableextension 50100 Test extends "Payment Method"
{
    local procedure Test()
    begin
        Rec.SetLoadFields("Code");
        Rec.FindFirst();
        Message(Description); // error!
        // Message(Rec.Description); // OK!
    end;
}
```

Observe that without the `Rec.` prefix on `Description`, we get this:
![image](https://user-images.githubusercontent.com/63455896/149507989-80715599-6a4e-4643-a5a2-d52e1c4e7b51.png)

...which is...
```none
Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationExtensions.GetSymbol(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationExtensions.cs:line 41
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads.JitLoadDetectionVisitor.VisitFieldAccess(IFieldAccess operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule0242PartialRecordsDetectJitLoads.cs:line 241
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.VisitArray[T](ImmutableArray`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 44
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads.JitLoadDetectionVisitor.VisitInvocationExpression(IInvocationExpression operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule0242PartialRecordsDetectJitLoads.cs:line 273
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.VisitArray[T](ImmutableArray`1 list) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationWalker.Visit(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationWalker.cs:line 36
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads.AnalyzeMethod(OperationAnalysisContext context) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule0242PartialRecordsDetectJitLoads.cs:line 128
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 764
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1100'
```

If we add the `Rec.` prefix, the error is reported correctly:
![image](https://user-images.githubusercontent.com/63455896/149508043-294ca9b4-22e1-4fb3-a85d-ee30eddfa2a1.png)

**3. Expected behavior**
The error should be reported correctly with or without the `Rec.` prefix, as that is not needed on tables/extensions and is usually omitted.

**4. Actual behavior**
Omitting the `Rec.` prefix causes the AA0242 analyser to crash instead of reporting the JIT load.

**5. Versions:**
- AL Language:
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.2.552672
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```
- Visual Studio Code: 1.63.2
- Business Central: n/a
- List of Visual Studio Code extensions that you have installed:
![image](https://user-images.githubusercontent.com/63455896/149508184-2bbcf75f-c0a6-4170-ace3-21fc6af67232.png)

**Comment by dnpb** [comment]
Any idea when this can be looked at, please?

**Comment by PhDuck** [comment]
Hey @dnpb, are you still seeing the nullref with the latest version?

I cannot reproduce the nullref:
![image](https://user-images.githubusercontent.com/6630421/155225532-51d555e4-ef23-47d4-8e06-a922b43e2072.png)

This analyzer is currently not able to support implicit rec because of limitations in the analyzers.

**Comment by lv-janpieter** [comment]
We have exactly the same however a little deviation in scenario, we are using a variable to peform a SetLoadFields and FindFirst. The code after that (if condition) is totaly unrelated to the TankMeter record variable.

We are running AL language v8.3.570094

```
TankMeter.Reset();
TankMeter.SetRange("Related to", TankMeter."Related to"::Location);
TankMeter.SetRange("Location Code", "Truck No.");
TankMeter.SetRange("Meter ID", "Meter ID");
TankMeter.SetLoadFields("Meter ID");
#pragma warning disable AA0175 // we don't want record we only want error if record does not exist
TankMeter.FindFirst();
#pragma warning restore

if ("Meter ID" <> xRec."Meter ID") then begin
    Validate("Receipt No.");
end;
```

Changing the last part to this code resolves the error:

```
if (Rec."Meter ID" <> xRec."Meter ID") then begin
    Rec.Validate("Receipt No.");
end;
```

**Comment by dnpb** [comment]
> Hey @dnpb, are you still seeing the nullref with the latest version?

The version I have now in updated VS Code is

**Comment by dnpb** [comment]
Hi @PhDuck,

> Hey @dnpb, are you still seeing the nullref with the latest version?

The version I have now in updated VS Code is below, and yes, I still get the same results, i.e. the same crashing analyser for both snippets that I posted.

Should I be testing some later version, via Docker or something? What version did you check?

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.3.570094
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.
