### ISSUE TITLE
Error when case statement has the constant 0D in a condition 

### ISSUE THREAD

**Issue by jose-lloret** [microsoft/AL#6912]
**1. Describe the bug**
Discover a bug in the compiler when a case statement has the constant 0D in the condition. It was informed in [#6136 issue](https://github.com/microsoft/AL/issues/6136) and it has been closed but the bug is still there

**2. To Reproduce**
This code snippet reproduces the error when running the action in the page.

``` AL
page 50900 "IssueWithDate"
{
    actions
    {
        area(Processing)
        {
            action(MyAction)
            {
                ApplicationArea = All;
                RunObject = codeunit IssueWithDate;
            }
        }
    }
}

codeunit 50901 "IssueWithDate"
{
    trigger OnRun()
    var
        dateVar: Date;
    begin
        dateVar := 0D;
        case dateVar of
            0D:
                Message('0D');
            else
                Message('Not 0D');
        end;
    end;
}
```

**3. Expected behavior**
The application should run smoothly and it isn't when the codeunit is run.

**4. Actual behavior**
It compiles in VSCode and is sent to the server without any errors or warnings.

This is the C# generated in the server:

``` CS
case NavDate.Create(0U):
{
    StmtHit(2);
    NavDialog.ALMessage(Guid.Parse("8da61efd-0002-0003-0507-0b0d1113171d"), "0D");
}

    break;
default:
{
    StmtHit(3);
    NavDialog.ALMessage(Guid.Parse("8da61efd-0002-0003-0507-0b0d1113171d"), "Not 0D");
}

    break;
```

And this is the error in the event log when the codeunit is run:

``` txt
Esta versión de Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
User: 
Type: System.InvalidOperationException
Message:
  C# compilation has failed for the application object CodeUnit_50901.
  The failing c# file name is 02F2FB5017461E2FB3134699582DDAD7FF4E9BA1AFF93930A4712536A4C2AB5E.cs. You can find this file with the associated AL file saved in the C:\ProgramData\Microsoft\Microsoft Dynamics NAV\200\Server\MicrosoftDynamicsNavServer$BC\apps\compilationerrors folder.
  Detailed compilation error: C:\ProgramData\Microsoft\Microsoft Dynamics NAV\200\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\02\02F2FB5017461E2FB3134699582DDAD7FF4E9BA1AFF93930A4712536A4C2AB5E.cs(71,26): error CS0150: A constant value is expected
  
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.LogErrorsAndThrowException(ApplicationObjectId objectId, String csharpCodePath, String compilationResult)
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.GetClrType(RuntimePackageId runtimePackageId, ApplicationObjectId objectId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.CompileAndLoadClrObject()
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Int32 appGroupId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunitHandle.CreateTarget()
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBaseHandle`1.get_Target()
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.InvokeRun(Int32 objectId, Object[] args)
     at Microsoft.Dynamics.Nav.Service.NSCodeUnit.<>c__DisplayClass4_0.<RunCodeunit>b__0(NsDataAccess dataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NSCodeUnit.Invoke()
     at Microsoft.Dynamics.Nav.Service.NSService.InvokeApplicationMethod(ApplicationMethodRequest applicationMethodRequest, NavRecordState state)
     at SyncInvokeInvokeApplicationMethod(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233079
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.LogErrorsAndThrowException(ApplicationObjectId objectId, String csharpCodePath, String compilationResult)
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.GetClrType(RuntimePackageId runtimePackageId, ApplicationObjectId objectId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.CompileAndLoadClrObject()
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Int32 appGroupId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunitHandle.CreateTarget()
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBaseHandle`1.get_Target()
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.InvokeRun(Int32 objectId, Object[] args)
     at Microsoft.Dynamics.Nav.Service.NSCodeUnit.<>c__DisplayClass4_0.<RunCodeunit>b__0(NsDataAccess dataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NSCodeUnit.Invoke()
     at Microsoft.Dynamics.Nav.Service.NSService.InvokeApplicationMethod(ApplicationMethodRequest applicationMethodRequest, NavRecordState state)
     at SyncInvokeInvokeApplicationMethod(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
 no es compatible con la versión de Windows que está ejecutando. Compruebe la información de sistema del equipo y después póngase en contacto con el anunciante de software. 
```

The line number 71 is:

``` CS
case NavDate.Create(0U)
```

Replacing in the AL code the case with an if statement works fine.

**5. Versions:**

- AL Language: 9.0.8.42811
- Visual Studio Code: 1.63.2
- Business Central: ES Business Central 20.0 (Plataforma 20.0.34863.0 + Aplicación 20.0.35117.0)
- List of Visual Studio Code extensions that you have installed: AL Language

**Comment by kalberes** [comment]
Thanks for reporting. We have an internal high priority bug on this, since it happened a few times on cloud compilations  too.

**Comment by kalberes** [comment]
This issue will is fixed with the next major version of teh AL compiler (9.x). If not please re-open the issue.
