### ISSUE TITLE
Ambiguous function call when using Interface with procedure overload

### ISSUE THREAD

**Issue by cstuber** [microsoft/AL#6924]
**1. Describe the bug**
If you create procedure overloads based on Interface parameters, then calling one of the procedures will result in a runtime error that indicates that the c# code generated from AL cannot resolve the call. "error CS0102: The type 'Codeunit50101' already contains a definition for 'CallMyProcedure_Scope__1176490946'"

**2. To Reproduce**

1. Create a new AL project with these objects.
2. Run the "Interface Implementation Call" Action on the "Customer List".

``` AL
interface "ISome Interface"
{
    procedure MyProcedure();
}
interface "ISome Other Interface"
{
    procedure MyProcedure();
}
codeunit 50100 "My Implementation" implements "ISome Interface"
{
    procedure MyProcedure()
    var
        myInt: Integer;
    begin

    end;
}
codeunit 50101 Caller
{
    procedure CallMyProcedure(SomeImplementation: Interface "ISome Interface")
    begin
        SomeImplementation.MyProcedure();
    end;

    procedure CallMyProcedure(SomeOtherImplementation: Interface "ISome Other Interface")
    begin
        SomeOtherImplementation.MyProcedure();
    end;
}
pageextension 50100 "Customer List" extends "Customer List"
{
    actions
    {
        addlast(processing)
        {
            action("Interface Implementation Call")
            {
                ApplicationArea = All;

                trigger OnAction()
                var
                    Caller: Codeunit Caller;
                    MyImplementation: Codeunit "My Implementation";
                begin
                    Caller.CallMyProcedure(MyImplementation);
                end;
            }
        }
    }
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
The procedure with the parameter "ISome Interface" is called as the MyImplementation Codeunit implements this interface.

**4. Actual behavior**
The client crashes. The event log shows the following error.

```
 C# compilation has failed for the application object CodeUnit_50101.
  The failing c# file name is CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs. You can find this file with the associated AL file saved in the C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\compilationerrors folder.
  Detailed compilation error: C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(104,23): error CS0102: The type 'Codeunit50101' already contains a definition for 'CallMyProcedure_Scope__1176490946'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(101,10): error CS0579: Duplicate 'NavName' attribute
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(102,10): error CS0579: Duplicate 'SignatureSpan' attribute
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(103,10): error CS0579: Duplicate 'SourceSpans' attribute
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(122,22): error CS0111: Type 'Codeunit50101.CallMyProcedure_Scope__1176490946' already defines a member called '.ctor' with the same parameter types
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(127,37): error CS0111: Type 'Codeunit50101.CallMyProcedure_Scope__1176490946' already defines a member called 'OnRun' with the same parameter types
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(36,17): error CS0152: The switch statement contains multiple cases with the label value '-1176490946'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(57,72): error CS0121: The call is ambiguous between the following methods or properties: 'Codeunit50101.CallMyProcedure_Scope__1176490946.CallMyProcedure_Scope__1176490946(Codeunit50101, NavInterfaceHandle)' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.CallMyProcedure_Scope__1176490946(Codeunit50101, NavInterfaceHandle)'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(97,72): error CS0121: The call is ambiguous between the following methods or properties: 'Codeunit50101.CallMyProcedure_Scope__1176490946.CallMyProcedure_Scope__1176490946(Codeunit50101, NavInterfaceHandle)' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.CallMyProcedure_Scope__1176490946(Codeunit50101, NavInterfaceHandle)'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(73,62): error CS0229: Ambiguity between 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(78,55): error CS0229: Ambiguity between 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(113,62): error CS0229: Ambiguity between 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(118,55): error CS0229: Ambiguity between 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId'
  
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnAction(Nullable`1 actionId, String actionTriggerMethodName)
     at Microsoft.Dynamics.Nav.Service.NSField.<>c__DisplayClass20_0.<ActionField>b__0(NsDataAccess recDataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NSField.Action(NavSession session)
     at SyncInvokeActionField(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233079
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnAction(Nullable`1 actionId, String actionTriggerMethodName)
     at Microsoft.Dynamics.Nav.Service.NSField.<>c__DisplayClass20_0.<ActionField>b__0(NsDataAccess recDataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NSField.Action(NavSession session)
     at SyncInvokeActionField(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
----------------------------------
Type: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
StackTrace:
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
Source: mscorlib
HResult: -2146232828
StackTrace:
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
----------------------------------
Type: System.InvalidOperationException
Message:
  C# compilation has failed for the application object CodeUnit_50101.
  The failing c# file name is CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs. You can find this file with the associated AL file saved in the C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\compilationerrors folder.
  Detailed compilation error: C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(104,23): error CS0102: The type 'Codeunit50101' already contains a definition for 'CallMyProcedure_Scope__1176490946'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(101,10): error CS0579: Duplicate 'NavName' attribute
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(102,10): error CS0579: Duplicate 'SignatureSpan' attribute
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(103,10): error CS0579: Duplicate 'SourceSpans' attribute
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(122,22): error CS0111: Type 'Codeunit50101.CallMyProcedure_Scope__1176490946' already defines a member called '.ctor' with the same parameter types
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(127,37): error CS0111: Type 'Codeunit50101.CallMyProcedure_Scope__1176490946' already defines a member called 'OnRun' with the same parameter types
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(36,17): error CS0152: The switch statement contains multiple cases with the label value '-1176490946'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(57,72): error CS0121: The call is ambiguous between the following methods or properties: 'Codeunit50101.CallMyProcedure_Scope__1176490946.CallMyProcedure_Scope__1176490946(Codeunit50101, NavInterfaceHandle)' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.CallMyProcedure_Scope__1176490946(Codeunit50101, NavInterfaceHandle)'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(97,72): error CS0121: The call is ambiguous between the following methods or properties: 'Codeunit50101.CallMyProcedure_Scope__1176490946.CallMyProcedure_Scope__1176490946(Codeunit50101, NavInterfaceHandle)' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.CallMyProcedure_Scope__1176490946(Codeunit50101, NavInterfaceHandle)'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(73,62): error CS0229: Ambiguity between 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(78,55): error CS0229: Ambiguity between 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(113,62): error CS0229: Ambiguity between 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId'
  C:\ProgramData\Microsoft\Microsoft Dynamics NAV\190\Server\MicrosoftDynamicsNavServer$BC\apps\metadata\3\CC\CCD2119400DE0723B76409142B23E957E665D9A0816714BC261DFB0C4608F9E6.cs(118,55): error CS0229: Ambiguity between 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId' and 'Codeunit50101.CallMyProcedure_Scope__1176490946.αscopeId'
  
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.LogErrorsAndThrowException(ApplicationObjectId objectId, String csharpCodePath, String compilationResult)
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.GetClrType(RuntimePackageId runtimePackageId, ApplicationObjectId objectId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.CompileAndLoadClrObject()
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunitHandle.CreateTarget()
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBaseHandle`1.get_Target()
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension50100.Interface_Implementation_Call_a45_OnAction_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension50100.Interface_Implementation_Call_a45_OnAction()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233079
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.LogErrorsAndThrowException(ApplicationObjectId objectId, String csharpCodePath, String compilationResult)
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppClrTypeRetriever.GetClrType(RuntimePackageId runtimePackageId, ApplicationObjectId objectId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetaApplicationObject.CompileAndLoadClrObject()
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObjectInternal(ApplicationObjectId appObjectId, Boolean requireCompiled, Boolean onlySearchCache, Int32 appGroupId)
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata.GetMetaApplicationObject(ApplicationObjectId appObjectId, Int32 appGroupId, Boolean requireCompiled, Boolean onlySearchCache)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunitHandle.CreateTarget()
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBaseHandle`1.get_Target()
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension50100.Interface_Implementation_Call_a45_OnAction_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension50100.Interface_Implementation_Call_a45_OnAction()
```

**5. Versions:**

- AL Language: 8.3.570094
- Visual Studio Code: 1.63.2
- Business Central: 19.3 (Platform 19.0.34506.34941 + Application 19.3.34541.35002)

**Comment by dnpb** [comment]
seems like a (better!) equivalent of https://github.com/microsoft/AL/issues/6594

**Comment by nndobrev** [comment]
Hey @cstuber we also saw the issue recently, but your repro steps are great. We will investigate further. Thanks a lot :)
