### ISSUE TITLE
Unrelated procedure named SetLoadFields() crashes AA0242 analyser - 'Rule0242PartialRecordsDetectJitLoads' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6962]
This code:
```al
codeunit 50100 Test
{
    trigger OnRun()
    begin
        SetLoadFields(42);
    end;

    local procedure SetLoadFields(i: Integer)
    begin
    end;
}
```
gives this result:
![image](https://user-images.githubusercontent.com/63455896/156198221-95fa4cf6-5ce5-4a5d-9e8e-4309d5f61109.png)

***

This code:
```al
codeunit 50100 Test
{
    trigger OnRun()
    begin
        DoSetLoadFields(42);
    end;

    local procedure DoSetLoadFields(i: Integer)
    begin
    end;
}
```
does not:
![image](https://user-images.githubusercontent.com/63455896/156198275-e06af6df-801f-4600-8094-27d5f3d5ea32.png)

***

The analyser should not fall over unrelated procedures that just happen to be called `SetLoadFields()`.

For instance, I want to have a local procedure `SetLoadFields(RecordRef, List of [Integer])`, but to avoid a spurious warning/crash, currently I have to rename it to something else, but I shouldn't have to :-)

Thanks in advance!

***

Full error:
```none
Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.OperationExtensions.GetSymbol(IOperation operation) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\OperationExtensions.cs:line 28
   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule0242PartialRecordsDetectJitLoads.AnalyzeMethod(OperationAnalysisContext context) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeCop\Design\Rule0242PartialRecordsDetectJitLoads.cs:line 58
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 764
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1100'
```

AL extension:
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.4.586670
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by PhDuck** [comment]
Another instance of by-name clashing, let me see what I can do.
