### ISSUE TITLE
BC 14 Workspace all the sudden corrupt

### ISSUE THREAD

**Issue by tinxit** [microsoft/AL#6984]
[Error - 16:19:38] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/didChange' failed with error: 'The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.
Please restart your workspace either by reloading the window in the Visual Studio Code command palette, or by restarting Visual Studio Code with your workspace.    
Details for the failure can be found in the EditorServices.log file in the extension installation folder.
 '
Details:
System.InvalidOperationException: The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.
Please restart your workspace either by reloading the window in the Visual Studio Code command palette, or by restarting Visual Studio Code with your workspace.    
Details for the failure can be found in the EditorServices.log file in the extension installation folder.
 
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.UpdateBuffer(DidChangeTextDocumentRequest updateRequest, CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:line 104
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeTextDocumentRequestHandler.HandleAsync(DidChangeTextDocumentRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeTextDocumentRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 91
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 100

Reloading window + downloading symbols + restarting visual studio code + restarting laptop is not working

**Comment by dnpb** [comment]
How did you fix it?
