### ISSUE TITLE
Getting Error when sending get request with content.

### ISSUE THREAD

**Issue by RavinderKumarGitHub** [microsoft/AL#7084]
System.Net.ProtocolViolationException: Cannot send a content-body with this verb-type.
at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
at System.Net.Http.HttpClientHandler.StartGettingRequestStream(RequestState state)
at System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState state)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Dynamics.Nav.Runtime.NavHttpClient.<>c__DisplayClass48_0.<SendWithTelemetry>b__0(CancellationToken ct)
at Microsoft.Dynamics.Nav.Types.NavCancellationToken.RunActionWithCancellationToken[T](Func`2 func)
at Microsoft.Dynamics.Nav.Runtime.NavHttpClient.SendWithTelemetry(HttpRequestMessage requestMessage, String endpoint)
at Microsoft.Dynamics.Nav.Runtime.NavHttpClient.<>c__DisplayClass47_0.<Send>b__1()
at Microsoft.Dynamics.Nav.Types.NavThread.<>c__DisplayClass44_0.<RunExternalAction>b__0()
at Microsoft.Dynamics.Nav.Types.NavThread.RunExternalAction[T](Func`1 action)
at Microsoft.Dynamics.Nav.Runtime.TrappableHttpOperationExecutor.<>c__DisplayClass0_0.<Execute>b__0()
at Microsoft.Dynamics.Nav.Runtime.TrappableOperationExecutor.Execute(DataError errorLevel, Func`1 operation, Action`2 processNativeException)

**Comment by dnpb** [comment]
This isn't a customer support channel, as I believe would've been explained while you were filing the issue.

And when you find a correct place for it, you should post your code and data, so readers have something to speculate about...
