### ISSUE TITLE
Snapshot debugging of Service to Service (S2S)

### ISSUE THREAD

**Issue by dkorinets** [microsoft/AL#7164]
Hi there, 
I'm experiencing troubles with the snapshot debugging of Service to Service (S2S). 

"configurations": [
        {
            "name": "snapshotInitialize: Microsoft production cloud",
            "type": "al",
            "request": "snapshotInitialize",
            "environmentType": "Sandbox",
            "environmentName": "SandboxUS",
            "tenant": "c7ea3873-1111-1111-1111-1d24e71ddc53",
            "userId": "3f07d918-1111-1111-1111-e24e9a3e531c",
            "breakOnNext": "WebServiceClient",
            "executionContext": "DebugAndProfile"
        }

**Error message:** 
[2022-09-13 10:30:59.48] Targeting Dynamics 365 Business Central environment tenant ID 'c7ea3873-1111-1111-1111-1d24e71ddc53' and primary Azure AD tenant domain name ''.
[2022-09-13 10:30:59.48] Sending request to https://api.businesscentral.dynamics.com/v2.0/SandboxUS/snapshotdebugger/snapshotendpointmetadata?tenant=c7ea3873-1111-1111-1111-1d24e71ddc53
[Error - 10:31:00 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/initializeSnapshotDebuggerAttach' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'
Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 661
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 81
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.DocumentExtensions.GetPositionAsync(Document document, LinePosition linePosition, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Shared\Extensions\DocumentExtensions.cs:line 319
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.DocumentHelper.GetDeclaringApplicationObjectAsync(Document document, Position position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\DocumentHelper.cs:line 45
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.DocumentHelper.GetDeclaringApplicationObjectAndAdjustLineNumberAsync(Document document, Position position, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\DocumentHelper.cs:line 22
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SnapshotDebuggerAttachInitializeRequestHandler.CreateSourceBreakpointLocationAsync(IList`1 snapPointLocations, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SnapshotDebuggerAttachInitializeRequestHandler.cs:line 171
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SnapshotDebuggerAttachInitializeRequestHandler.ProcessRequestAsync(SnapshotDebuggerAttachInitializeRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SnapshotDebuggerAttachInitializeRequestHandler.cs:line 83
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108

**Comment by kalberes** [comment]
As a workaround be sure that you download the production symbols with your snapshot attach configuration and try again. Clean your breakpoint list and place the snappoints  again
In debugging it is quite important that the line number you set a breakpoint locally it is the same as would execute on a BC server.

**Comment by dkorinets** [comment]
Cleaning breakpoints helps.
Thanks
