### ISSUE TITLE
Processing of message 'textDocument/semanticTokens/full' failed with error: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#7176]
Please include the following with each issue:

**1. Describe the bug**

Hi, 

I get quite often these kind of errors. I have no idea how to reproduce it. I just opened our (biggest) app and had opened the app.json directly. Then I waited for the AL language to load the project and executed `AL: Publish without debugging`.
Then in the debug console I got this error numerous times.  Then I just executed the same command again and then, on the second time, the publish succeeded. Sorry for the poor reproduce issue, but maybe you can see something with the call stack.
```
[Error - 10:08:14] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/semanticTokens/full' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertySemanticModel.GetBindableParentNode(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\PropertySemanticModel.cs:line 133
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.GetBoundNodes(SyntaxNode node, SyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 173
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 85
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertySemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\PropertySemanticModel.cs:line 224
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxTreeSemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SyntaxTreeSemanticModel.cs:line 85
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 565
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\Classifiers\NameSyntaxClassifier.cs:line 56
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classifiers.NameSyntaxClassifier.ClassifyNode(SyntaxNode syntax, SemanticModel semanticModel, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\Classifiers\NameSyntaxClassifier.cs:line 31
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.AbstractClassificationService.Worker.ClassifyNode(SyntaxNode syntax) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\AbstractClassificationService.Worker.cs:line 126
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.AbstractClassificationService.Worker.ProcessNodes() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\AbstractClassificationService.Worker.cs:line 98
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.AbstractClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, List`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\AbstractClassificationService.Worker.cs:line 77
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.AbstractClassificationService.AddSemanticClassifications(SemanticModel semanticModel, TextSpan textSpan, Workspace workspace, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, List`1 result, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\AbstractClassificationService.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.Classifier.GetClassifiedSpans(SemanticModel semanticModel, TextSpan textSpan, Workspace workspace, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.Classifier.GetClassifiedSpansAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\Classifier.cs:line 29
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.SemanticTokensFullRequestHandler.HandleAsync(SemanticTokensRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\SemanticTokensFullRequestHandler.cs:line 46
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108
```

**2. To Reproduce**
Described above.

**3. Expected behavior**
I would expect that no error occurs ;)

**4. Actual behavior**
Unable to publish.

**5. Versions:**

- AL Language: v9.5.674382
- Visual Studio Code: v1.71.2
- Business Central: https://bcartifacts.azureedge.net/sandbox/20.5.45456.46935/de
- List of Visual Studio Code extensions that you have installed:
- davidfeldhoff.al-codeactions
- ms-dynamics-smb.al
- wbrakowski.al-navigator
- vjeko.vjeko-al-objid
- bartpermentier.al-toolbox
- rasmus.al-var-helper
- andrzejzwierzchowski.al-code-outline
- ms-vscode.azure-account
- ms-azuretools.vscode-azurefunctions
- ms-azure-devops.azure-pipelines
- ms-azuretools.vscode-azureresourcegroups
- stefanmaron.businesscentral-lintercop
- wmaurer.change-case
- svipas.control-snippets
- mhutchie.git-graph
- eamodio.gitlens
- joaompinto.vscode-graphviz
- efanzh.graphviz-preview
- docsmsft.docs-markdown
- yzhang.markdown-all-in-one
- nabsolutions.nab-al-tools
- ms-vscode.powershell
- esbenp.prettier-vscode
- humao.rest-client
- wware.snippet-creator
- adpyke.vscode-sql-formatter
- gruntfuggly.todo-tree
- adamhartford.vscode-base64
- vscode-icons-team.vscode-icons
- waldo.crs-al-language-extension
- rvanbekkum.xliff-sync
- dotjoshjohnson.xml

**Comment by kalberes** [comment]
Can you please enable verbose logging in VsCode "al.editorServicesLogLevel": "Verbose" and restart the language server and somehow send the EdirorServices.log (will  be big, don't forget to reset the loglevel) found in C:\Users.vscode\extensions\ms-dynamics-smb.al-\bin when the issue happens.

**Comment by DavidFeldhoff** [comment]
Hi Kalman, happy to see you here again ;)
Will do it and keep you posted when this happens again.

**Comment by DavidFeldhoff** [comment]
I just tried to activate it, but as soon as I do that, I get errors that have not been there before. After deactivating the setting, the app compiles against successfully. Should I create a separate issue for that?
![image](https://user-images.githubusercontent.com/53570297/192694281-67cadde5-f4ec-48f7-afdf-ac64df38f3bf.png)

**Comment by DavidFeldhoff** [comment]
Can you maybe send me a mail to david.feldhoff at gws.ms, so that I know your mail address? Then I'll share a link via onedrive to that mail address, so that you can download it.

**Comment by fvet** [comment]
Facing the same on packaging the standard Base Application

- AL Language vsix: v10.0.686440
- Cloned https://github.com/microsoft/BusinessCentralApps
- Opened folder **BusinessCentralApps\Layers\W1**
- Added **settings.json** (following https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-set-up-an-environment)

```
{
    "al.assemblyProbingPaths": [
        "C:/Windows/Microsoft.NET/Framework64/v4.0.30319",
        "C:/bcartifacts.cache/sandbox/21.1.47170.0/",
        "C:/WINDOWS/assembly"
    ],
    "al.enableCodeAnalysis": false,
    "al.enableCodeActions": false,
    "al.backgroundCodeAnalysis": false,
    "al.incrementalBuild": true,
    "editor.codeLens": false,
    "al.ruleSetPath": ".vscode/ruleset.json",
    "[al]": {"editor.formatOnSave": false }
}
```

- Added **ruleset.json** to get zero warnings

```
{
    "name": "Global Rules",
    "description": "Disable all rules",
    "generalAction" : "Hidden",
    "rules":
    [        
        {
            "id": "AL0432",            
            "action" : "None"            
        },
        {
            "id": "AL0729",            
            "action" : "None"            
        },
        {
            "id": "AL0603",            
            "action" : "None"            
        },
        {
            "id": "AL0685",            
            "action" : "None"            
        },
        {
            "id": "AL0687",            
            "action" : "None"            
        },
        {
            "id": "AL0659",            
            "action" : "None"            
        },
        {
            "id": "AL0267",            
            "action" : "None"            
        },
        {
            "id": "AL0269",            
            "action" : "None"            
        },
        {
            "id": "AL0615",            
            "action" : "None"            
        },
        {
            "id": "AL0273",            
            "action" : "None"            
        },
        {
            "id": "AL0547",            
            "action" : "None"            
        },
        {
            "id": "AL0684",            
            "action" : "None"            
        },
        {
            "id": "AL0655",            
            "action" : "None"            
        },
        {
            "id": "AL0551",            
            "action" : "None"            
        },
        {
            "id": "AL0667",            
            "action" : "None"            
        },
        {
            "id": "AL0602",            
            "action" : "None"            
        },
        {
            "id": "AL0719",            
            "action" : "None"            
        },
        {
            "id": "AL0254",            
            "action" : "None"            
        }
    ]
}
```

- Tried to build the Base Application
[Output.txt](https://github.com/microsoft/AL/files/9690260/Output.txt)

```
[Error - 13:53:45] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/semanticTokens/full' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertySemanticModel.GetBindableParentNode(SyntaxNode node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\PropertySemanticModel.cs:line 133
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.GetBoundNodes(SyntaxNode node, SyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 164
   at Microsoft.Dynamics.Nav.CodeAnalysis.MemberSemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\MemberSemanticModel.cs:line 85
   at Microsoft.Dynamics.Nav.CodeAnalysis.PropertySemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\PropertySemanticModel.cs:line 224
   at Microsoft.Dynamics.Nav.CodeAnalysis.SyntaxTreeSemanticModel.GetSymbolInfoWorker(SyntaxNode node, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SyntaxTreeSemanticModel.cs:line 138
   at Microsoft.Dynamics.Nav.CodeAnalysis.SemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\SemanticModel.cs:line 565
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\Classifiers\NameSyntaxClassifier.cs:line 56
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classifiers.NameSyntaxClassifier.ClassifyNode(SyntaxNode syntax, SemanticModel semanticModel, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\Classifiers\NameSyntaxClassifier.cs:line 31
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.AbstractClassificationService.Worker.ClassifyNode(SyntaxNode syntax) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\AbstractClassificationService.Worker.cs:line 126
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.AbstractClassificationService.Worker.ProcessNodes() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\AbstractClassificationService.Worker.cs:line 98
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.AbstractClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, List`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\AbstractClassificationService.Worker.cs:line 77
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.AbstractClassificationService.AddSemanticClassifications(SemanticModel semanticModel, TextSpan textSpan, Workspace workspace, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, List`1 result, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\AbstractClassificationService.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.Classifier.GetClassifiedSpans(SemanticModel semanticModel, TextSpan textSpan, Workspace workspace, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\Classifier.cs:line 57
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Classification.Classifier.GetClassifiedSpansAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Classification\Classifier.cs:line 29
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.SemanticTokensFullRequestHandler.HandleAsync(SemanticTokensRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\SemanticTokensFullRequestHandler.cs:line 46
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108
```

**Comment by kalberes** [comment]
@DavidFeldhoff , @fvet has a repro. We will try with that one. The exception is at the same place.

**Comment by thpeder** [comment]
I'm trying to reproduce the issue, but so far without any luck.
1) @fvet  Can you tell me which files you have open when it crashes
2) If someone is able to reproduce the issue with a smaller app, then I would really appreciate it.
