### ISSUE TITLE
Processing of message 'textDocument/didChange' failed with error: 'The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#7208]
Please include the following with each issue:

**1. Describe the bug**
While downloading symbols of a clean container and a pretty easy extension I got an error message, but still the downloading of symbols continues and succeeds finally.

![image](https://user-images.githubusercontent.com/53570297/195363304-cb46c03e-3a8f-44f9-8409-3b09d9971c34.png)

The error message says 
```
[Error - 14:32:25] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/didChange' failed with error: 'The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.
Please restart your workspace either by reloading the window in the Visual Studio Code command palette, or by restarting Visual Studio Code with your workspace.
Details for the failure can be found in the EditorServices.log file in the extension installation folder.

Details:
System.InvalidOperationException: The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.
Please restart your workspace either by reloading the window in the Visual Studio Code command palette, or by restarting Visual Studio Code with your workspace.
Details for the failure can be found in the EditorServices.log file in the extension installation folder.
```

In the editorservices.log at that time it says
```log
10/12/2022 05:35:47 [/56] Sending request to [redacted]/dev/metadata?tenant=default with request ID fc1ae457-1917-4b0f-b73d-5c833e9aa578 and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 05:35:48 [/52] Sending request to [redacted]/dev/packages?publisher=Microsoft&appName=Application&versionText=20.0.0.0&appId=00000000-0000-0000-0000-000000000000&tenant=default with request ID df3e8fd1-72d8-4d28-8366-626dfc691b20 and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 05:35:48 [/42] Sending request to [redacted]/dev/packages?publisher=Microsoft&appName=System&versionText=1.0.0.0&appId=8874ed3a-0643-4247-9ced-7a7002f7135d&tenant=default with request ID b055efd1-c8ac-4688-801e-8279927bcca2 and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 05:35:54 [/81] Sending request to [redacted]/dev/packages?publisher=Microsoft&appName=System Application&versionText=21.0.0.0&appId=63ca2fa4-4f03-4f2b-a480-172fef340d3f&tenant=default with request ID 832f1239-a4d6-45e3-971a-4347e95ce055 and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 05:35:54 [/81] Sending request to [redacted]/dev/packages?publisher=Microsoft&appName=Base Application&versionText=21.0.0.0&appId=437dbf0e-84ff-417a-965d-ed2bb9650972&tenant=default with request ID e8cbf01f-812e-44ce-930a-d1c1b35946ad and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 06:50:41 [/24] Sending request to [redacted]/dev/packages?publisher=Microsoft&appName=Application&versionText=20.0.0.0&appId=00000000-0000-0000-0000-000000000000&tenant=default with request ID 619af8da-0b5b-4a26-af25-f61c2675c35a and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 06:50:41 [/24] Sending request to [redacted]/dev/packages?publisher=Microsoft&appName=System&versionText=1.0.0.0&appId=8874ed3a-0643-4247-9ced-7a7002f7135d&tenant=default with request ID 14ab4536-080f-4d51-94c5-d70b0e7ca425 and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 06:50:41 [/23] Sending request to [redacted]/dev/packages?publisher=Microsoft&appName=System Application&versionText=21.0.0.0&appId=63ca2fa4-4f03-4f2b-a480-172fef340d3f&tenant=default with request ID 63ea3590-917b-4b17-b2ac-0f2a2936f46f and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 06:50:41 [/23] Sending request to [redacted]/dev/packages?publisher=Microsoft&appName=Base Application&versionText=21.0.0.0&appId=437dbf0e-84ff-417a-965d-ed2bb9650972&tenant=default with request ID a408dfc0-7fe4-4561-af0f-e1f4ecaf801d and session ID e874a5e8-333e-466d-a07b-4b8467a0dbeb
10/12/2022 06:50:45 [/24] Content  starting at line 0 ending at line 7 is an invalid text update for document c:/[redacted]/Documents/AL/ALProject114_PageCustomization2/.vscode/temp-al-proxy.al.
10/12/2022 06:50:45 [/24] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/didChange' failed with error: 'The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.
Please restart your workspace either by reloading the window in the Visual Studio Code command palette, or by restarting Visual Studio Code with your workspace.    
Details for the failure can be found in the EditorServices.log file in the extension installation folder.
 '
Details:
System.InvalidOperationException: The language server must close to prevent text buffers not being in sync between Visual Studio Code and the AL language server.
Please restart your workspace either by reloading the window in the Visual Studio Code command palette, or by restarting Visual Studio Code with your workspace.    
Details for the failure can be found in the EditorServices.log file in the extension installation folder.
 
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.BufferManager.UpdateBuffer(DidChangeTextDocumentRequest updateRequest, CancellationToken token) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\BufferManager.cs:line 104
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DidChangeTextDocumentRequestHandler.HandleAsync(DidChangeTextDocumentRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DidChangeTextDocumentRequestHandler.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108
```

**2. To Reproduce**

No idea what I did. I think it was a small pagecustomization file that was not compilable approx. like this:
```al
pagecustomization testcust customizes 
```

And then I started calling "Download symbols". But now I can't reproduce it anymore. But looking in my editorservices.log I can see that it happened the 5th time since the 5th of october (that's exactly the release date of v10.x)

**3. Expected behavior**
working without erros :)

**4. Actual behavior**
Throwing errors but still possible to work, but nevertheless it does not leave a good feeling.

**5. Versions:**

- AL Language: v10.0.687650
- Visual Studio Code: v1.72.0
- Business Central:
- List of Visual Studio Code extensions that you have installed:
- AZ AL DevTools
- AL CodeActions
- AL Navigator
- AL Object ID Ninja
- AL Variable Helper
- and some other smaller ones which shouldn't interfere

**Comment by DavidFeldhoff** [comment]
Oh yes, you're right. Will follow that one
