### ISSUE TITLE
Processing of message 'textDocument/codeAction' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#7209]
**1. Describe the bug**
Sorry if this is a poor description, but I can't remember exactly anymore what happened here, so I don't want to send you in a wrong direction with my vague thoughts what happened. But hopefully you still could see something using the callstack. This is the error showing up int he editorservices.log

```
10/11/2022 10:22:41 [/86] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeAction' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'
Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 661
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 81
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.SourceTextExtension.GetTextSpan(SourceText sourceText, Range range) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\SourceTextExtension.cs:line 16
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeActionRequestHandler.HandleAsync(ProtocolCodeActionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeActionRequestHandler.cs:line 68
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108
```

**2. To Reproduce**
can't remember anymore, sorry.

**3. Expected behavior**
Maybe you can find something critical. Don't know anymore if it was critical for us.

**4. Actual behavior**
.

**5. Versions:**

- AL Language: v10.0.687650

**Comment by nickgoddard777** [comment]
I am getting the same error, it is when I use the AL Navigator extension and try either the Add Local Variable option or Add Global Variable option. This has only started in the last week or so.  The callstack is:
`[Error - 09:35:34] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'index')'
Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 661
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 81
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.HandleAsync(CompletionRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 45
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108`

**Comment by DominicSaladin** [comment]
I got the same error messages. When I uninstall the AL Navigator the error is gone, but the Base Application and the System Application do not get downloaded, even though the output requests the app packages...
![image](https://user-images.githubusercontent.com/43037258/203953067-b5737fd2-778a-4236-82bb-41f0d23bd5fa.png)

As you can see, every package was downloaded, except of the Base and the System Application:
![image](https://user-images.githubusercontent.com/43037258/203953393-2f4421a0-adcc-461f-a97d-b811723396e6.png)

**Comment by thloke** [comment]
Closing as this is to do with AL Navigator.
