### ISSUE TITLE
Issue with fullDependencyPublish

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL#7239]
Hey AL gurus, 

While trying to publish 'full dependecy tree', I do receive the following error message:
Please let me know what additional information you need.

```
[Error - 16:27:11] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/fullDependencyPublish' failed with error: 'Collection was modified; enumeration operation may not execute.'
Details:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Utilities.ICollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 values) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Utilities\ICollectionExtensions.cs:line 23
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.VsCodeWorkspace.RefreshSymbolReferences(ProjectId projectId, IEnumerable`1 allReferences, IList`1 diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\VsCodeWorkspace.cs:line 290
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.ActiveProjectBuilder.InvalidateReferenceCacheAndCopyReferencedProjectBuildOutputToPackageCachePath(VsCodeWorkspace workspace, IEnumerable`1 outputFiles, ProjectId sourceProjectId, IResponseQueue responseQueue) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\ActiveProjectBuilder.cs:line 245
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.ActiveProjectBuilder.Build(VsCodeWorkspace workspace, Project builtProject, StreamingTextWriter outputWriter, Boolean isRad, IList`1 args, CancellationToken cancellationToken, IResponseQueue responseQueue, ITelemetryService telemetryService, Boolean forceBuild, IList`1 outputFiles, CustomTelemetryEvent telemetryEvent) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\ActiveProjectBuilder.cs:line 177
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.ActiveProjectBuilder.BuildWorkspaceAsync(CancellationToken cancellationToken, IFileSystem fileSystem, VsCodeWorkspace workspace, String projectDir, IList`1 args, Boolean buildDependencyPackage, Boolean isRad, IResponseQueue responseQueue, Boolean forceBuildOfAllDependecnies, CustomTelemetryEvent telemetryEvent, ITelemetryService telemetryService) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\ActiveProjectBuilder.cs:line 105
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.FullDependencyPublishRequestHandler.ProcessRequestAsync(FullDependencyPublishRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\FullDependencyPublishRequestHandler.cs:line 78
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108
```

Best Regards, 
Gintautas

**Comment by thloke** [comment]
Can you share what your workspace structure is like? A graph of dependencies would be the best.

**Comment by gntpet** [comment]
Here's my graph:
![image](https://user-images.githubusercontent.com/16342128/201862627-c93f6354-b8f0-4cd3-9b52-ae147aba61eb.png)

I'm publishing from SRS.it app

Output log looks like this:
```
[2022-11-15 09:01:50.17] Preparing to publish the dependency tree with these settings:
[2022-11-15 09:01:50.17] SchemaUpdateMode: Synchronize
[2022-11-15 09:01:50.17] EnvironmentType: OnPrem
...
Compilation started for project 'email-queue' 
...
Compilation started for project 'dynamic-layout'
...
Compilation started for project 'bank-acount-for-sales-docs'
...
Compilation started for project 'azure-blob-storage-setup'
...
Compilation started for project 'SRS.core'
...
Compilation ended at '09:01:58.441'
...
[Error - 09:01:58] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/fullDependencyPublish' failed with error: 'Collection was modified; enumeration operation may not execute.'
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.51188.0 and VS Code Extension Version 11.0.728141. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
