### ISSUE TITLE
Issue with compiling/packaging app - Specified argument was out of the range of valid values. (Parameter 'position')

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7241]
Please include the following with each issue:

**1. Describe the bug**
Compiling isn't working anymore in a large project.

**3. Expected behavior**
I shouldn't receive this error.

**4. Actual behavior**
Right now, I receive the following error:

> Specified argument was out of the range of valid values. (Parameter 'position')

```
Processing of message 'al/createPackage' failed with error: 'Specified argument was out of the range of valid values. (Parameter 'position')'
Details:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'position')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.IndexOf(Int32 position) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 698
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.GetLineFromPosition(Int32 position) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 733
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetLinePosition(Int32 position) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 66
   at Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTree.GetLineSpan(TextSpan span) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Syntax\SyntaxTree.cs:line 201
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceLocation.GetLineSpan() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceLocation.cs:line 66
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.DiagnosticFormatter.Format(Diagnostic diagnostic, IFormatProvider formatter) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Diagnostics\DiagnosticFormatter.cs:line 28
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.ReportErrors(IEnumerable`1 diagnostics, CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CompilationOptions options) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 245
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver, Predicate`1 filterOpt, Predicate`1 radCompilationFilter) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 741
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDriver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 551
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, ITelemetryService telemetryService, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 482
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, ITelemetryService telemetryService, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 336
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.ActiveProjectBuilder.Build(VsCodeWorkspace workspace, Project builtProject, StreamingTextWriter outputWriter, Boolean isRad, IList`1 args, CancellationToken cancellationToken, IResponseQueue responseQueue, ITelemetryService telemetryService, Boolean forceBuild, IList`1 outputFiles, CustomTelemetryEvent telemetryEvent) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\ActiveProjectBuilder.cs:line 180
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.ActiveProjectBuilder.BuildWorkspaceAsync(CancellationToken cancellationToken, IFileSystem fileSystem, VsCodeWorkspace workspace, String projectDir, IList`1 args, Boolean buildDependencyPackage, Boolean isRad, IResponseQueue responseQueue, Boolean forceBuildOfAllDependecnies, CustomTelemetryEvent telemetryEvent, ITelemetryService telemetryService) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\ActiveProjectBuilder.cs:line 105
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.HandleAsync(CreatePackageRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 38
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 108

```

I checked the log and I receive this error on various places on multiple differnt projects.
**5. Versions:**

- AL Language: 10.1.707468

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by pri-kise** [comment]
Version v9.5.674382 is working.

**Comment by thloke** [comment]
Can you provide sample code to reproduce the issue?

**Comment by pri-kise** [comment]
I have this problem in differnt "larger" projects, around 100 Objects, but I wasn't able to reproduce this error with an minimal example project, that only contains a few files.

I disabled all extensions except the AL Lanuage extension and I enabled the verbose logging, but I haven't seen there anything special, since this error occurs on different positions on the createpackage step.

**Comment by thloke** [comment]
Before compiling, do you have any diagnostics in the problems window? From the callstack, it looks like we're reporting an incorrect position for one of the diagnostics.

It's a bit of a long shot, but does your project contain any dotnet objects?

**Comment by pri-kise** [comment]
No, i don't have any diganostics in the problems window.
No, we don't use any dotnet objects, sicne we target cloud for universal code.

**Comment by thloke** [comment]
@prisma-chku - do you have sample repro code for your case?

**Comment by thloke** [comment]
Or looking at the linked issue, are you using the same linter cop?

**Comment by prisma-chku** [comment]
I was able to "solve" the problem in the meantime with the help of this [discussion](https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/243) here. It seems to have something to do with the LinterCop Extension in VSCode...

**Comment by EmilDamsbo** [comment]
Following the discussion in https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/243 it seems that this issue is not with the AL Language extension but rather with the non-Microsoft extension LinterCop.
