### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by acoollevel** [microsoft/AL#7322]
Please include the following with each issue:

**1. Describe the bug**

Installing the AL Language extension produces the following errors:

```
2023-02-13 11:33:44.736 [error] Language client is not ready yet: Error: Language client is not ready yet
    at LanguageClient.sendRequest (/Users/levi/.vscode/extensions/ms-dynamics-smb.al-10.4.747197/node_modules/vscode-languageclient/lib/common/client.js:1852:19)
    at EditorService.<anonymous> (/Users/levi/.vscode/extensions/ms-dynamics-smb.al-10.4.747197/out/src/services/editorService.js:174:45)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/levi/.vscode/extensions/ms-dynamics-smb.al-10.4.747197/out/src/services/editorService.js:8:58)
2023-02-13 11:33:45.443 [error] Cannot read properties of undefined (reading 'document'): TypeError: Cannot read properties of undefined (reading 'document')
    at DocCommentService.onTextDocumentChanged (/Users/levi/.vscode/extensions/ms-dynamics-smb.al-10.4.747197/out/src/services/docCommentService.js:21:30)
    at /Users/levi/.vscode/extensions/ms-dynamics-smb.al-10.4.747197/out/src/services/docCommentService.js:12:85
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at k.$acceptModelChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:11193)
    at l.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
    at l.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
    at l.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10044)
    at l.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:13941)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
```

**2. To Reproduce**

1. Install AL Language extension on VS Code
2. Attempt to download symbols or debug AL extension

**3. Expected behavior**

Downloading symbols should work as usual

**4. Actual behavior**

"Could not download symbols. Please see the Visual Studio Code output log for more details."

**5. Versions:**

- AL Language: 10.4
- Visual Studio Code:  1.75.1 
- Business Central: 
- List of Visual Studio Code extensions that you have installed: AL Language only, all others disabled
- Running on M2 Pro chip, MacOs 13.2, works fine on normal M2

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Can you try uninstalling the VSCode AL extension and reinstalling it again? If that still fails, can you get the EditorServices.log file?

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
