### ISSUE TITLE
Warn on FlowFilter as Column in Query Object

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/AL#7338]
I opened a similar case #7295 wich was closed today. Unfortunately I pasted the wrong Codesnipped to reproduce the error. In my earlier issue was the FlowFilter field added as "filter". It should have been "column" to reproduce the error. The compiler accepts this which results in an runtime error. Since the error was not reproduceable with my earlier issue I am not sure if the statement, that my request was wrong in this repository also applies to this. If this is the case I am sorry for the inconvenience.

**1. Describe the bug**
When you use a FlowFilter as Column in a Query the Query Object cannot be used. 

**2. To Reproduce**
Add any FlowFilter field as columen to a query object. Use the Query.

``` AL
query 99000 MyQuery
{
    QueryType = Normal;
    
    elements
    {
        dataitem(Customer;Customer)
        {
            column(No_;"No.")
            {
                
            }
            column(Date_Filter;"Date Filter")
            {
                
            }
        }
    }
}

pageextension 99000 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        t: Query MyQuery;
    begin
        Clear(t);
        t.Open();
        if t.Read() then;
        t.Close();

        Message('App published: Hello world');
    end;
}
```

**3. Expected behavior**
The compiler should at least warn on a FlowFilter field in the query column. Better would be an error.

**4. Actual behavior**
No warning or error. A runtime Error occurs at executing the query.

When using the Query you receive in BusinessCentral:
![grafik](https://user-images.githubusercontent.com/46522333/222435262-32021a1d-be8e-4912-b6b5-1ad887082bf8.png)

In the Event Log of my container it is found:
```
This version of Server instance: BC
Tenant ID: default
Environment Name: 
Environment Type: Sandbox
Session type: WebClient
Session ID: 49
User: 
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavSqlException
ErrorNumber: 207
TransactionRolledBack: False
MaxVerbosity: Off
ErrorCode: -1
ShouldCalculateALCallStack: True
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: True
DiagnosticsSuppress: False
DiagnosticsMessage: Message not shown because the NavBaseException constructor was used without privacy classification
MessageWithoutPrivateInformation: Message not shown because the NavBaseException constructor was used without privacy classification
SuppressExceptionCreatedEvent: False
FatalityScope: None
ErrorLevel: Error
ALCallStack:
  CustomerListExt(PageExtension 99000).OnOpenPage(Trigger) line 6 - ALIssue7295 by Default publisher
  
Message:
  Der folgende SQL-Fehler war nicht erwartet.
  Invalid column name 'Date Filter'.
  SQL-Anweisung:
  SELECT "Customer"."No_" AS "No_","Customer"."Date Filter" AS "Date_Filter" FROM "bekl_biog_at21_4_52563_53455".dbo."CRONUS AT$Customer$437dbf0e-84ff-417a-965d-ed2bb9650972" AS "Customer" WITH(READUNCOMMITTED)  ORDER BY "No_" ASC OPTION(FAST 50)
  StackTrace:
     at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
     at System.Environment.get_StackTrace()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ThrowNavSqlException(SqlExceptionAdapter exceptionAdapter, Boolean transactionNoLongerValid, String commandText, Boolean isLastExceptionARollbackCause, Boolean logExceptions, NavCancellationToken cancellationToken)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.MapException(SqlExceptionAdapter exceptionAdapter, String commandText, Boolean isRollbackAction, Nullable`1 timeout, NavCancellationToken cancellationToken)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__DisplayClass133_0`1.<ExecuteFunction>b__0()
     at Microsoft.Dynamics.Nav.Types.NavThread.RunExternalAction[T](Func`1 action)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteFunctionWithTrace[T](EventTask task, Func`1 function, String commandText, SqlCommand sqlCommand, Boolean isAdoCommand, NavCancellationToken cancellationToken)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.ExecuteReader(NavCancellationToken cancellationToken)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlQueryCommand.<>c__DisplayClass32_0.<QueryExecute>b__2(NavSqlCommand command)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteCommandAndCacheOnSuccess[T](NavSqlCommandCacheKey commandKey, Func`1 newCommandFunc, Func`2 executeFunc)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlQueryCommand.QueryExecute(NavSqlConnectionScope conScope, NCLMetaQueryDefinition query, NavDatabase database, Int32 companyToken, Int32 topNumberOfRowsToReturn, Int32 skipNumberOfRows, Boolean countRows, FiltersAndMarks queryFilters, TableFilterDictionary globalAndSecurityFilters, Boolean includeCurrent, MutableRecordBuffer startingPosition, SecurityFiltering securityFiltering, Boolean addExplicitJoinHints, SortingFieldList sortingFields, Nullable`1 timeout)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlQueryCommand.<Query>d__35.MoveNext()
     at Microsoft.Dynamics.Nav.Runtime.ResultSet.TryGetAtIndex(Int32 index, ReadOnlyRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryGetRecordBufferFromResultSet(Int32 fetchIndex, MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.ResultSetEnumerator.TryMoveNextImpl(MutableRecordBuffer& recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.GetNextRow()
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.ALRead(DataError errorLevel)
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension99000.OnOpenPage_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.PageExtension99000.OnOpenPage()
     at Microsoft.Dynamics.Nav.Types.LinqExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 action)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnOpenPage()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.OpenForm()
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.<>c__DisplayClass15_1.<OpenForms>b__0(NsDataAccess dataAccess)
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess(ITreeObject parent, NavForm form, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess(ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess(ITreeObject parent, NavRecordState state, Action`1 action)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.OpenForms(FormOpenResponse openResponse, List`1 registeredForms)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFormRequest form)
     at Microsoft.Dynamics.Nav.Service.NSService.Microsoft.Dynamics.Nav.Types.IClientApi.OpenForm(OpenFormRequest form)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineDispatchProxy`1.<>c.<Invoke>b__8_0(ServiceOperationContext context)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddToThreadSchedulerCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.RunInTransactionCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TransientErrorRetryCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PartnerTelemetryPermissionErrorCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PushPopCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.<>c__DisplayClass7_0.<PerformanceCounterCombinator>b__0()
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PerformanceCounterCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.InitClientTelemetryIdsCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TlsClearCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineDispatchProxy`1.Invoke(MethodInfo targetMethod, Object[] args)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
     at generatedProxy_1.OpenForm(OpenFormRequest )
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at StreamJsonRpc.TargetMethod.<InvokeAsync>d__19.MoveNext()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
HResult: -2146233088
----------------------------------
Type: Microsoft.Data.SqlClient.SqlException
ClientConnectionId: b82e66b8-3c45-46d4-817a-118889d7f36d
Class: 16
LineNumber: 1
Number: 207
Server: XXXX
State: 1
Source: Framework Microsoft SqlClient Data Provider
ErrorCode: -2146232060
Message: Invalid column name 'Date Filter'.
StackTrace:
     at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
     at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
     at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
     at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
     at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
     at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
     at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
     at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
     at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
     at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
     at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.<ExecuteReader>b__66_0()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__DisplayClass133_0`1.<ExecuteFunction>b__0()
HResult: -2146232060
StackTrace:
     at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
     at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
     at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
     at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
     at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
     at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
     at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
     at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
     at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
     at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
     at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.<ExecuteReader>b__66_0()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__DisplayClass133_0`1.<ExecuteFunction>b__0()
 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher. 
```

Since the Query selects the column directly the select does not work,

**5. Versions:**

- AL Language: v10.4.747197
- Visual Studio Code: 1.75.1
- Business Central: AT Business Central 21.4 (Plattform 21.0.52534.53435 + Anwendung 21.4.52563.53455)
- List of Visual Studio Code extensions that you have installed:

**Comment by thloke** [comment]
Thanks for the additional information. It's still out of scope for this repository unfortunately. To clarify, what makes this out of scope is that this is a runtime error - and therefore we need the runtime team to make a call on whether this should actually be legal or if we should block this at the language level.

Because it's the SQL statement that's being constructed incorrectly, this leans towards something that should be fixed in the runtime rather than blocked in AL. But again, we can't make that call here.

The previous comment on the other issue still applies.
