### ISSUE TITLE
Delete Record on Page and Error for cannot be found in related tables

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/AL#7343]
Please include the following with each issue:

**1. Describe the bug**
If you have a 3-table structure and the 3rd table has a table relation to the second table. When you delete the second table from a page after it deletes the related records in the 3rd level table, you get an error that the related record cannot be found and closes the page.  

**2. To Reproduce**
Go to the Data Exch Def Card and delete a line from the Line Definitions that has column definitions and you will get the error. If you did not receive the error then.  Add a new line definition and a column definition and delete that line and was able to get it every time.  I was having this issue in a custom table structure we were creating. 

![image](https://user-images.githubusercontent.com/32099690/223937070-e4bbdda6-64d1-403f-a15e-1d3e63fa69c6.png)

Server instance: BC
Category: Runtime
ClientSessionId: dd363281-b849-4e8b-ae44-8aa9664fe20f
ClientActivityId: e8733674-ee1e-59d7-6b85-5f4ee60fe15c
ServerSessionUniqueId: bc03dccc-bf3b-4d59-9a18-83240f897429
ServerActivityId: 2ca54431-e44a-445b-a5c7-9f587c75d59a
EventTime: 03/09/2023 06:04:10
Message (NavCSideValidateTableRelationException): This message had personal data removed. The original may still be in transient telemetry. Find it using the transientTelemetryId.
Sending exception to client. Session terminating: False
ParentException: NavCSideValidateTableRelationException
Error Code:85132272
The field Data Exch. Line Def Code of table Data Exch. Column Def contains a value (<redacted>) that cannot be found in the related table (Data Exch. Line Def).
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
   at Microsoft.Dynamics.Nav.Service.NSFormApplicationCode.<>c__DisplayClass7_0.<Invoke>b__0(NsDataAccess dataAccess)
   at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
   at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
   at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
   at Microsoft.Dynamics.Nav.Service.NSService.Microsoft.Dynamics.Nav.Types.IClientApi.InvokeApplicationMethod(ApplicationMethodRequest applicationMethodRequest, NavRecordState state)
--- End of stack trace from previous location ---
   at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineDispatchProxy`1.<>c.<Invoke>b__8_0(ServiceOperationContext context)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddToThreadSchedulerCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.RunInTransactionCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TransientErrorRetryCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean useCoreWcfFaultException)
InnerException:
ParentException: TargetInvocationException
ExceptionStackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
InnerException:
RootException: NavCSideValidateTableRelationException
Error Code:85132272
The field Data Exch. Line Def Code of table Data Exch. Column Def contains a value (<redacted>) that cannot be found in the related table (Data Exch. Line Def).
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.ValidateNonFlowField(NCLMetaField field, Boolean isUserInput)
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.ValidateField(FieldTriggerHandler`1 fieldEvent, NCLMetaField metaField, Boolean isUserInput, List`1 beforeHandlers, List`1 afterHandlers)
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.Validate(NCLMetaField metaField, NavValue newValue, NavRecord callerRecord, Boolean isUserInput)
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.ValidateFields(IEnumerable`1 fieldNumbers, NavRecord callerRecord)
   at Microsoft.Dynamics.Nav.Runtime.NavForm.NewRecord(Boolean belowXRec, Int32[] includeNonPrimaryKeyFieldsForFilterGroups)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Service.ServiceExceptionHandling.MapServiceOperationException(Exception e, NavSession session, Boolean useCoreWcfFaultException)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean useCoreWcfFaultException)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PartnerTelemetryPermissionErrorCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PushPopCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean useCoreWcfFaultException)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.<>c__DisplayClass7_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Runtime.NavPerformanceCounterSetter.UpdatePerformanceCountersWithAverageServiceOperationAction(Action action, NavSession session)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PerformanceCounterCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.InitClientTelemetryIdsCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TlsClearCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineDispatchProxy`1.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.InvokeApplicationMethod(ApplicationMethodRequest , NavRecordState )
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at StreamJsonRpc.TargetMethod.InvokeAsync(CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.QueueUserWorkItemCallback`1.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Should be able to delete the lines without issue.  

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
