### ISSUE TITLE
BC23 Next Major Pipeline Fails with error message (Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by minaskats** [microsoft/AL#7452]
Please include the following with each issue:

**1. Describe the bug**
BC23 Next Major Pipeline Fails with error message (Object reference not set to an instance of an object.).

2023-07-14T08:07:19.5390895Z ##[error]Internal error: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
2023-07-14T08:07:19.5618193Z  ---> System.NullReferenceException: Object reference not set to an instance of an object.
2023-07-14T08:07:19.5618774Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.<>c__DisplayClass265_0.<BindImplementationValues>b__0(InterfaceTypeSymbol i) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 320
2023-07-14T08:07:19.5619427Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindImplementationValues(CommaSeparatedIdentifierEqualsIdentifierListPropertyValueSyntax propertyValue, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 320
2023-07-14T08:07:19.5620178Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindCommaSeparatedIdentifierEqualsIdentifierListPropertyValue(CommaSeparatedIdentifierEqualsIdentifierListPropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 294
2023-07-14T08:07:19.5620904Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetBoundPropertyValue(PropertySyntax syntax, DiagnosticBag diagnostics, PropertyValueSyntax propertyValue, PropertyTypeInfo info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 163
2023-07-14T08:07:19.5624133Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindProperty(PropertySyntax syntax, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 67
2023-07-14T08:07:19.5624745Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.LazyGetProperty() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 169
2023-07-14T08:07:19.5625504Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.get_Property() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 105
2023-07-14T08:07:19.5626050Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceEnumValueSymbol.GetInterfaceImplementationsCore() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceEnumValueSymbol.cs:line 146
2023-07-14T08:07:19.5626585Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EnumValueSymbol.GetInterfaceImplementations() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\EnumValueSymbol.cs:line 24
2023-07-14T08:07:19.5627205Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.EnumTypeObjectMembers.ValidateInterfaceImplementation(EnumValueSymbol enumValue, IList`1 interfacesWithoutDefaltImplementation, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\EnumTypeObjectMembers.cs:line 102
2023-07-14T08:07:19.5628652Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceEnumExtensionTypeSymbol.ForceCompleteEnumValues(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceEnumExtensionTypeSymbol.cs:line 162
2023-07-14T08:07:19.5632786Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceEnumExtensionTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceEnumExtensionTypeSymbol.cs:line 78
2023-07-14T08:07:19.5633535Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:line 224
2023-07-14T08:07:19.5634168Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.<>c__DisplayClass27_1.<ForceComplete>b__0(Int32 i) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:line 104
2023-07-14T08:07:19.5634746Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 178
2023-07-14T08:07:19.5635255Z    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
2023-07-14T08:07:19.5635751Z --- End of stack trace from previous location ---
2023-07-14T08:07:19.5636087Z    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
2023-07-14T08:07:19.5639543Z    at System.Threading.Tasks.TaskReplicator.Replica.Execute()
2023-07-14T08:07:19.5639909Z    --- End of inner exception stack trace ---
2023-07-14T08:07:19.5640208Z    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
2023-07-14T08:07:19.5640649Z    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2023-07-14T08:07:19.5641083Z --- End of stack trace from previous location ---
2023-07-14T08:07:19.5641415Z    at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
2023-07-14T08:07:19.5641888Z    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2023-07-14T08:07:19.5642428Z    at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
2023-07-14T08:07:19.5645617Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:line 101
2023-07-14T08:07:19.5646325Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 1159
2023-07-14T08:07:19.5647160Z    at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 737

AL Compiler version 11.0.12.41358

**2. To Reproduce**
Download the symbols of ver 23 and change the AL compiler to the version v11.0.827766. 
The same error appears in the VS Code.

**Comment by BazookaMusic** [comment]
This should be fixed in the latest version
