### ISSUE TITLE
VSCode- /Complier exception in report if DataItemLinkReference references a table instead of the dataitem variable

### ISSUE THREAD

**Issue by hhfiddelke** [microsoft/AL#7456]
Please include the following with each issue:

**1. Describe the bug**
Including the following report in a project with AL Language Extension v11.0.827766, VScode 1.80 causes the following (or other) exception if you try to store to store app.json or if you try tor run the compiler 

**2. To Reproduce**
Include the report in a project, run the compiler with F5.  I get an exception:
``` AL
Report 89012 "SMC Create In Store EAN"
{
    ProcessingOnly = true;

    dataset
    {
        dataitem(SMCItem; Item)
        {
            RequestFilterFields = "No.", "Item Category Code";
            dataitem(SMCItemVariant; "Item Variant")
            {
                DataItemLink = "Item No." = field("No.");
                DataItemTableView = sorting("Item No.", Code);
                dataitem(SMCItemUnitOfMeasure1; "Item Unit of Measure")
                {
                    DataItemLink = "Item No." = field("No.");
                    DataItemLinkReference = Item;
                    DataItemTableView = sorting("Item No.", Code);
                }
            }
        }
    }
}
```

**3. Expected behavior**
The only thing i know is that there should be no exception. 
The cause for the exception is the "DataItemLinkReference = Item;" in the SMCItemUnitOfMeasure1- dataitem. if you change it to "DataItemLinkReference = SMCItem;" all is working fine.

**4. Actual behavior**
This is one exception i get, when try to compile a project with this report. 
Sometimes saving app.json creates also exceptions, or starting VSCode with that project causes also an exception but always an incomplete incomplete Problems list.
```Error - 1:57:04 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.

Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.ObjectChangeManager.Update(IEnumerable`1 objectChangeElements, ObjectChangeState state) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\ObjectChange\ObjectChangeManager.cs:line 155
   at Microsoft.Dynamics.Nav.CodeAnalysis.ObjectChangeManager.Load(ObjectChangeModelDefinition objectChangeModelDefinition) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\ObjectChange\ObjectChangeManager.cs:line 106
   at Microsoft.Dynamics.Nav.CodeAnalysis.ObjectChangeManager.Load(String path, IFileSystem fileSystem) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\ObjectChange\ObjectChangeManager.cs:line 113
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.ProjectState.<>c__DisplayClass6_0.<.ctor>b__6() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Workspace\Solution\ProjectState.cs:line 97
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.ObjectChangeDocumentManager.HasProjectRadChanges(ProjectId id) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\ObjectChangeDocumentManager.cs:line 227
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.ActiveProjectBuilder.Build(VsCodeWorkspace workspace, Project builtProject, StreamingTextWriter outputWriter, Boolean isRad, IList`1 args, CancellationToken cancellationToken, IResponseQueue responseQueue, ITelemetryService telemetryService, Boolean forceBuild, IList`1 outputFiles, CustomTelemetryEvent telemetryEvent) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\ActiveProjectBuilder.cs:line 147
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.ActiveProjectBuilder.BuildWorkspaceAsync(CancellationToken cancellationToken, IFileSystem fileSystem, VsCodeWorkspace workspace, String projectDir, IList`1 args, Boolean buildDependencyPackage, Boolean isRad, IResponseQueue responseQueue, Boolean forceBuildOfAllDependecnies, CustomTelemetryEvent telemetryEvent, ITelemetryService telemetryService) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\ActiveProjectBuilder.cs:line 105
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.HandleAsync(CreatePackageRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 38
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 103
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 106
```

**5. Versions:**

- AL Language: v11.0.827766
- Visual Studio Code: 1.80 (current)
- Business Central:  21.0.46384

**Comment by hhfiddelke** [comment]
Same with compiler test with BC22, the report is the only part of the project
```
Microsoft (R) AL Compiler version 11.0.12.41358
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'ExceptionTest' containing '1' files at '15:54:30.572'.

error AL0999: Internal error: System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceGlobalVariableSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReportDataItemSymbol'.)
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceGlobalVariableSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReportDataItemSymbol'.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetReferencedReportDataItemSymbol(IdentifierNameSyntax dataItemNameSyntax, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1218
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindReportDataItemForLinkReference(IdentifierNamePropertyValueSyntax propertyValue, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1316
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindMemberReferencePropertyValue(IdentifierNamePropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1161
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetBoundPropertyValue(PropertySyntax syntax, DiagnosticBag diagnostics, PropertyValueSyntax propertyValue, PropertyTypeInfo info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 186
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindProperty(PropertySyntax syntax, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 111
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.LazyGetProperty() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 180
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.get_Property() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 106
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolExtensions.GetBoundPropertyValue[T](ContainerSymbol symbol, PropertyKind kind) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\SymbolExtensions.cs:line 825
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.MemberSymbolExtensions.GetDataItemLinkReferencedDataItem(ReportDataItemSymbol symbol) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\KindsAndExtensions\MemberSymbolExtensions.cs:line 109
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetRelatedTableForReportDataItemLink() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 2263
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindReportDataItemLinkPropertyValue(ReportDataItemLinkPropertyValueSyntax propertyValue, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 773
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetBoundPropertyValue(PropertySyntax syntax, DiagnosticBag diagnostics, PropertyValueSyntax propertyValue, PropertyTypeInfo info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 199
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindProperty(PropertySyntax syntax, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 111
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.LazyGetProperty() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 180
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 125
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceReportDataItemSymbol.ForceCompleteProperties(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceReportDataItemSymbol.cs:line 350
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceReportDataItemSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceReportDataItemSymbol.cs:line 222
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceReportDataItemSymbol.ForceCompleteMembers(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceReportDataItemSymbol.cs:line 283
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceReportDataItemSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceReportDataItemSymbol.cs:line 237
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceReportDataItemSymbol.ForceCompleteMembers(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceReportDataItemSymbol.cs:line 283
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceReportDataItemSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceReportDataItemSymbol.cs:line 237
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceMembersCompleteAndCheckUniqueness(SourceLocation locationOpt, DiagnosticBag diagnostics, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:line 175
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceCompleteMembers(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:line 1151
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:line 1119
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceReportTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceReportTypeSymbol.cs:line 60
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:line 224
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.<>c__DisplayClass27_1.<ForceComplete>b__0(Int32 i) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:line 104
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:line 101
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 1156
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 737

```

**Comment by BazookaMusic** [comment]
The second trace looks like an error in how we bind the DataItemLink property. Not sure why we would try to bind a global variable there. The first is from RAD

**Comment by hhfiddelke** [comment]
You get the same error if you place any non existing variable into the "DataItemLinkReference". 
This was a misinterpretation of mine in my first test.
