### ISSUE TITLE
Adding protected enum field to our table crashes VS Code AL Extension

### ISSUE THREAD

**Issue by ECJaneck** [microsoft/AL#7482]
**1. Describe the bug**
We created a table and want to add a field with Type enum. The enum in question is a run of the mill extensible enum without any protection level. When that field gets added everything works but as soon as the protection level of said field is changed to protected we get the following error:

Internal error: System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.TypeSymbol'.)
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.TypeSymbol'.
   at Microsoft.Dynamics.Nav.CodeAnalysis.AccessCheck.IsFieldAccessible(FieldSymbol field, Symbol within, TypeSymbol throughTypeOpt, LookupOptions options, Compilation compilation) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\AccessCheck.cs:line 247
   at Microsoft.Dynamics.Nav.CodeAnalysis.BuckStopsHereBinder.IsAccessibleHelper(Symbol symbol, TypeSymbol accessThroughType, LookupOptions options, Boolean& failedThroughTypeCheck, HashSet`1& useSiteDiagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\BuckStopsHereBinder.cs:line 79
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.CheckViability(Symbol symbol, LookupOptions options, TypeSymbol accessThroughType, Boolean diagnose, HashSet`1& useSiteDiagnostics, BoundExpression receiver) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder.cs:line 1050
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.LookupMembersWithoutInheritance(LookupResult result, TypeSymbol type, String name, LookupOptions options, Binder originalBinder, TypeSymbol accessThroughType, Boolean diagnose, HashSet`1& useSiteDiagnostics, BoundExpression receiver) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Lookup.cs:line 395
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.LookupMembersInClass(LookupResult result, TypeSymbol type, String name, BoundExpression receiver, LookupOptions options, Binder originalBinder, Boolean diagnose, HashSet`1& useSiteDiagnostics, ApplicationObjectExtensionTypeSymbol excludedExtension) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Lookup.cs:line 281
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.TryGetFieldByNameOrId(TableTypeSymbol relatedTable, Int32 fieldId, String unquotedRelatedFieldName, FieldSymbol& fieldSymbol) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 1809
   at Microsoft.Dynamics.Nav.CodeAnalysis.TableExpressionContext.TryGetSymbolByNameOrId(Boolean bindOnSource, Int32 symbolId, String unquotedSymbolName, ISymbolWithType& symbol) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\TableExpressionContext.cs:line 73
   at Microsoft.Dynamics.Nav.CodeAnalysis.BoundPropertyExpressionFactory`1.CreateLhsForCondition(IdentifierNameSyntax leftHandSide, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\BoundPropertyExpressionFactory.cs:line 144
   at Microsoft.Dynamics.Nav.CodeAnalysis.BoundPropertyExpressionFactory`1.CreateBoundPropertyValueExpressionFromRhs(SyntaxNode rhs, DiagnosticBag diagnostics, String lhsIdentifierName) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\BoundPropertyExpressionFactory.cs:line 239
   at Microsoft.Dynamics.Nav.CodeAnalysis.BoundPropertyExpressionFactory`1.CreateRhs(SyntaxNode rightHandSide, String leftHandSideName, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\BoundPropertyExpressionFactory.cs:line 89
   at Microsoft.Dynamics.Nav.CodeAnalysis.BoundPropertyExpressionFactory`1.CreateExpression(IdentifierNameSyntax leftHandside, SyntaxNode rightHandside, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\BoundPropertyExpressionFactory.cs:line 73
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindPropertyExpressions(SyntaxNode ownerSyntax, PropertyTypeInfo info, SeparatedSyntaxList`1 propertyExpressions, ExpressionContext expressionContext, CompilationOptions options, DiagnosticBag diagnostics, Boolean& hasErrors) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 2701
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindTableFilterStatement(TableFilterPropertyValueSyntax propertyValue, PropertyTypeInfo info, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 2123
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.GetBoundPropertyValue(PropertySyntax syntax, DiagnosticBag diagnostics, PropertyValueSyntax propertyValue, PropertyTypeInfo info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 182
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindProperty(PropertySyntax syntax, DiagnosticBag diagnostics) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Properties.cs:line 111
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.LazyGetProperty() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 180
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePropertySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePropertySymbol.cs:line 125
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceControlSymbol.ForceCompleteProperties(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceControlSymbol.cs:line 226
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceControlSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceControlSymbol.cs:line 172
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceControlSymbol.ForceCompleteMembers(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceControlSymbol.cs:line 246
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceControlSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceControlSymbol.cs:line 182
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceMembersCompleteAndCheckUniqueness(SourceLocation locationOpt, DiagnosticBag diagnostics, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:line 175
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceCompleteMembers(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:line 1183
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectMembers`1.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken, Predicate`1 excludeFromNameUniqueness) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Members\ObjectMembers.cs:line 1103
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourcePageTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourcePageTypeSymbol.cs:line 52
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceNamespaceSymbol.<>c__DisplayClass47_1.<ForceComplete>b__0(Int32 i) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceNamespaceSymbol.cs:line 806
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceNamespaceSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceNamespaceSymbol.cs:line 806
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceModuleSymbol.cs:line 100
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 1260
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 784

**2. To Reproduce**
We sadly can't reproduce this error in a small sample extension. For further details see the screenshot under 4. Since this is happening in our product code we can't just openly publish the source code to GitHub. We also raised a ticket TrackingID#2308160010009365 and were told to open an issue here, since a demo app isn't mandatory here. I am available for a Teams call to showcase this error in action. 

**3. Expected behavior**
No error should be thrown and we should be able to build the extension.

**4. Actual behavior**
Without protection level:
![image](https://github.com/microsoft/AL/assets/142799678/60840ed2-193a-4347-b4fb-a1bc7f633407)
As soon as the field gets set to protected:
![image](https://github.com/microsoft/AL/assets/142799678/75c8ccba-743a-4b01-abc5-770b8cbc71c1)
Here the Enum in question:
![image](https://github.com/microsoft/AL/assets/142799678/41664a12-c564-4a1e-a44e-143fda1f534f)

**5. Versions:**

- AL Language: v12.0.847725 (tried both release and pre-release)
- Visual Studio Code: 1.81
- Business Central: 22.4
- List of Visual Studio Code extensions that you have installed: None except the AL extension.

**Comment by BazookaMusic** [comment]
This will be released with the next 23 VSIX and with the next pre-release, whichever comes first
