### ISSUE TITLE
ModalPageHandler "System.IO.FileNotFoundException" error in Sandbox environments

### ISSUE THREAD

**Issue by tyurm** [microsoft/AL#7501]
Hello,

I've found that test procedures with ModalPageHandler throw an error in Sandbox env, but it works fine in docker container. I've run this procedure both from "AL Test Tool" and BCPT Suites. - same result.

Tested in next env:
Sandbox CH 22.4.59114.59220 - does not work
Sandbox CH 22.5.59966.60134 - does not work
Sandbox CH 23.0.12034.12167 (Preview) - does not work

Docker CH 22.3.58346.59599 - works fine
Docker CH 22.5.59966.60300 - works fine

Error message:
```
Error Message: Unexpected CLR exception thrown.: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Dynamics.Nav.Client.Tracing, Version=23.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Dynamics.Nav.Client.Tracing, Version=23.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Dynamics.Nav.Client.Tracing, Version=23.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
at Microsoft.Dynamics.Nav.Client.ServiceClientCallback.StartActivity(String activityName, String traceId, String spanId)
at Microsoft.Dynamics.Nav.Client.ServiceClientCallback.FormRunModal(FormRunModalRequest formRequest) in s:/repo/src/Platform/Client/Shared/Prod.Client.UI/ServiceClientCallback.cs:line 684
at Microsoft.Dynamics.Nav.Runtime.NavTestExecution.TestHandleModalForm(NavForm form, FormResult& action, NavFormRuntimeParameters parameters) in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavTestExecution.cs:line 954
at Microsoft.Dynamics.Nav.Runtime.NavForm.RunModal(NavRecord record, Int32 fieldNo) in s:/repo/src/Platform/Server/Prod.Ncl/AL/ALForm.cs:line 367
at Microsoft.Dynamics.Nav.Runtime.NavFormHandle.RunModal(NavRecord record, Int32 fieldNo) in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavFormHandle.cs:line 195
at Microsoft.Dynamics.Nav.Runtime.NavFormHandle.RunModal() in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavFormHandle.cs:line 172
at Microsoft.Dynamics.Nav.BusinessApplication.Page22.DimensionsMultiple_a45_OnAction_Scope.OnRun()
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run() in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavMethodScope.cs:line 1004
at Microsoft.Dynamics.Nav.BusinessApplication.Page22.DimensionsMultiple_a45_OnAction()
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound) in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavApplicationMethod.cs:line 111
at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound) in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavApplicationMethod.cs:line 111
at Microsoft.Dynamics.Nav.Runtime.NavForm.CallTrigger(TriggerSource source, Int32 id, String triggerMethodName, Object[] args) in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavForm.cs:line 3860
at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnAction(Nullable`1 actionId, String actionTriggerMethodName) in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavForm.cs:line 788
at Microsoft.Dynamics.Nav.Service.NSField.<>c__DisplayClass21_0.<ActionField>b__0(NsDataAccess recDataAccess) in s:/repo/src/Platform/Server/Prod.Service/NSField.cs:line 455
at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func) in s:/repo/src/Platform/Server/Prod.Service/NsDataAccess.cs:line 881
at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func) in s:/repo/src/Platform/Server/Prod.Service/NsDataAccess.cs:line 275
at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func) in s:/repo/src/Platform/Server/Prod.Service/NsDataAccess.cs:line 233
at Microsoft.Dynamics.Nav.Service.NSField.ActionField(NavSession con) in s:/repo/src/Platform/Server/Prod.Service/NSField.cs:line 418
at Microsoft.Dynamics.Nav.Service.NSField.Action(NavSession session) in s:/repo/src/Platform/Server/Prod.Service/NSField.cs:line 410
at Microsoft.Dynamics.Nav.Service.NSService.ActionField(FieldRequest fieldRequest, NavRecordState dataSetState) in s:/repo/src/Platform/Server/Prod.Service/NSService.cs:line 600
at INavServiceWrapper.ActionField(FieldRequest , NavRecordState )
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceWrapper.ActionField(FieldRequest fieldRequest, NavRecordState dataSetState) in s:/repo/src/Platform/ClientServerShared/Prod.Types/AsyncNavServiceWrapper.cs:line 233
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceWrapper.<>c__DisplayClass110_0.<BeginActionField>b__0() in s:/repo/src/Platform/ClientServerShared/Prod.Types/AsyncNavServiceWrapper.cs:line 1204
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceWrapper.Invoke(Func`1 action, AsyncCallback callback, Object asyncState, Object extraState) in s:/repo/src/Platform/ClientServerShared/Prod.Types/AsyncNavServiceWrapper.cs:line 2704
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceWrapper.BeginActionField(FieldRequest fieldRequest, NavRecordState dataSetState, AsyncCallback callback, Object asyncState) in s:/repo/src/Platform/ClientServerShared/Prod.Types/AsyncNavServiceWrapper.cs:line 1204
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceClientApi.<>c__DisplayClass14_0.<ActionField>b__0(IAsyncNavService server) in s:/repo/src/Platform/ClientServerShared/Prod.Types/Api/Client/AsyncNavServiceClientApi.cs:line 129
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceClientApi.CallServer[T](BeginCallServerMethod beginCallServerMethod, EndCallServerMethod`1 endCallServerMethod) in s:/repo/src/Platform/ClientServerShared/Prod.Types/Api/Client/AsyncNavServiceClientApi.cs:line 239
at Microsoft.Dynamics.Nav.Types.AsyncNavServiceClientApi.ActionField(FieldRequest fieldRequest, NavRecordState dataSetState) in s:/repo/src/Platform/ClientServerShared/Prod.Types/Api/Client/AsyncNavServiceClientApi.cs:line 127
at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.<>c__DisplayClass30_0.<ActionField>b__0(IClientApi api) in s:/repo/src/Platform/ClientServerShared/Prod.Types/ServiceConnection/ServiceConnectionBase.cs:line 621
at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.<>c__DisplayClass49_0`1.<CallServer>b__0() in s:/repo/src/Platform/ClientServerShared/Prod.Types/ServiceConnection/ServiceConnectionBase.cs:line 988
at Microsoft.Dynamics.Nav.Runtime.TestServiceConnection.CallServer[T](Func`1 callServer, Nullable`1 options) in s:/repo/src/Platform/Server/Prod.Ncl/Testability/TestServiceConnection.cs:line 634
at Microsoft.Dynamics.Nav.Client.ServerInvocationHandler.CallServerSync[T](Func`1 callServer, Nullable`1 options) in s:/repo/src/Platform/Client/Shared/Prod.Client.ServiceConnection/ServerInvocationHandler.cs:line 86
at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.CallServer[T](Func`2 callServer, Nullable`1 options) in s:/repo/src/Platform/ClientServerShared/Prod.Types/ServiceConnection/ServiceConnectionBase.cs:line 988
at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.ActionField(NavRecordState& state, NavDataSet recDataSet, Int32 controlId, Int32 controlEventId) in s:/repo/src/Platform/ClientServerShared/Prod.Types/ServiceConnection/ServiceConnectionBase.cs:line 621
at Microsoft.Dynamics.Nav.Runtime.TestServiceConnection.Microsoft.Dynamics.Nav.Client.IService.ActionField(NavRecordState& state, NavDataSet recDataSet, Int32 controlId, Int32 controlEventId)
at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.ActionMethod(Int32 controlId, Int32 controlEventId) in s:/repo/src/Platform/Client/Shared/Prod.Client.UI/Databinder/NSTDataAccess.cs:line 780
at Microsoft.Dynamics.Nav.Client.Actions.InvokePageTriggerAction.InvokeTrigger(LogicalControl logicalControl, UISession uiSession) in s:/repo/src/Platform/Client/Shared/Prod.Client.UI/Actions/FormActions/InvokePageTriggerAction.cs:line 119
at Microsoft.Dynamics.Nav.Client.Actions.InvokePageTriggerAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:/repo/src/Platform/Client/Shared/Prod.Client.UI/Actions/FormActions/InvokePageTriggerAction.cs:line 80
at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:/repo/src/Platform/Client/Shared/Prod.ClientFwk/Actions/LogicalAction.cs:line 585
at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession) in s:/repo/src/Platform/Client/Shared/Prod.ClientFwk/Actions/LogicalAction.cs:line 565
at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(LogicalControl logicalControl, IDictionary state, UISession uiSession) in s:/repo/src/Platform/Client/Shared/Prod.ClientFwk/Actions/LogicalAction.cs:line 484
at Microsoft.Dynamics.Framework.UI.LogicalAction.Invoke(LogicalControl logicalControl, IDictionary state) in s:/repo/src/Platform/Client/Shared/Prod.ClientFwk/Actions/LogicalAction.cs:line 411
at Microsoft.Dynamics.Framework.UI.ActionControl.Invoke(IDictionary state) in s:/repo/src/Platform/Client/Shared/Prod.ClientFwk/Forms/ActionControl.cs:line 413
at Microsoft.Dynamics.Nav.Client.TestPageClient.TestActionProxy.Invoke() in s:/repo/src/Platform/Client/TestPageClient/TestActionProxy.cs:line 53
at Microsoft.Dynamics.Nav.Runtime.NavTestAction.ALInvoke() in s:/repo/src/Platform/Server/Prod.Ncl/AL/ALTestAction.cs:line 18
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit50106.OpenDimensionsMultipleFromCustomerList_Scope__2078597899.OnRun()
at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run() in s:/repo/src/Platform/Server/Prod.Ncl/Runtime/NavMethodScope.cs:line 1004
at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit50106.OpenDimensionsMultipleFromCustomerList() - Error Call Stack:

"Customer List"(Page 22)."DimensionsMultiple - OnAction"(Trigger) line 7 - Base Application by Microsoft
"BCPT Open Customer List"(CodeUnit 50106).OpenDimensionsMultipleFromCustomerList line 5 - ALBug by Default publisher
"Test Runner - Mgt"(CodeUnit 130454).RunTests line 21 - Test Runner by Microsoft
"Test Runner - Isol. Codeunit"(CodeUnit 130450).OnRun(Trigger) line 4 - Test Runner by Microsoft
"Test Suite Mgt."(CodeUnit 130456).RunTests line 2 - Test Runner by Microsoft
"Test Suite Mgt."(CodeUnit 130456).RunTestSuiteSelection line 23 - Test Runner by Microsoft
"AL Test Tool"(Page 130451)."RunTests - OnAction"(Trigger) line 6 - Test Runner by Microsoft
```

Test Codeunit to reproduce:
```
codeunit 50106 "BCPT Open Customer List"
{
    Subtype = Test;

    trigger OnRun();
    begin
    end;

    [Test]
    [HandlerFunctions('DefaultDimMultiplePageHandler')]
    procedure OpenDimensionsMultipleFromCustomerList()
    var
        CustomerList: testpage "Customer List";
    begin
        CustomerList.OpenView();
        CustomerList.DimensionsMultiple.Invoke();
    end;

    [ModalPageHandler]
    procedure DefaultDimMultiplePageHandler(var DefaultDimMultiple: TestPage "Default Dimensions-Multiple")
    begin
    end;
}
```

**Comment by VMotin** [comment]
Hi, I'm having the same issue,
It was working well on sandbox until about a month ago and then i started having this problem on almost every test.

Hope to get a solution !

**Comment by BazookaMusic** [comment]
This repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. This issue is related to the runtime behavior of the product. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

  *   Open a support request to CSS through the PartnerSource portal
  *   Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
