### ISSUE TITLE
Using ExternalBusinessEvent in the same codeunit causes unrelated IntegrationEvent's to fail when publishing of a dependent app that subscribes to the InternalEvent to fail with "UnprocessableEntity. Reason: Value cannot be null. (Parameter 'key')"

### ISSUE THREAD

**Issue by coffeecup007** [microsoft/AL#7518]
Please include the following with each issue:

**1. Describe the bug**
We've tried Microsoft support (case 2309260040008562) and have not yet received any answer, let alone a useful answer, so we're attempting here.

When an extension has an 'ExternalBusinessEvent' and also an 'IntegrationEvent' in the same codeunit, then a subscriber in a second extension to the IntegrationEvent will fail with a null reference exception.

When deploying via vscode the error is:
```
UnprocessableEntity. Reason: Value cannot be null. (Parameter 'key')
```

When deploying via powershell you'll get:
```
RootException: ArgumentNullException
  Value cannot be null. (Parameter 'key')
  ExceptionStackTrace:
     at System.ThrowHelper.ThrowArgumentNullException(String name)
     at System.ThrowHelper.ThrowKeyNullException()
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventPublisherReflectionWrapper.GetMethodInfoByScopeType(Type scopeType)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscription..ctor(INavEventSubscriber subscriber, NavEventSubscriberMethodInfo subscriberMethodInfo, NavAppGroup subscriberNavAppGroup, NavEventSubscriptionModifiers subscriptionModifiers, Int32 memberId)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscriptionFactory.CreateEventSubscriptionsFromSubscriber(INavEventSubscriber subscriber, NavAppGroup appGroup, NavEventSubscriptionModifiers subscriptionModifiers)
```

**2. To Reproduce**

Here is how to reproduce it in the simplest possible way:
Create extension ‘A’
In extension ‘A’ have a codeunit with one ExternalBusinessEvent and one IntegrationEvent
It will compile and publish successfully.

``` AL
codeunit 50100 "DemoOfProblem"
{
    [ExternalBusinessEvent('AnyName', 'AnyDisplayName', 'AnyDescription', EventCategory::ExampleA)]
    procedure A()
    begin
    end;

    [IntegrationEvent(false, false)]
    procedure B()
    begin
    end;
}
```

Create extension ‘B’ with a dependency to the first extension.
In extension ‘B’ create a subscription to ‘B’.

``` AL
codeunit 50101 DemoOfProblemSubscriber
{
    [EventSubscriber(ObjectType::Codeunit, Codeunit::DemoOfProblem, 'B', '', true, true)]
    local procedure C()
    begin
    end;
}
```

Attempt to deploy the second extension with vscode and you will be faced with:
failed with code UnprocessableEntity. Reason: Value cannot be null. (Parameter 'key')

If you publish the second extension with the powershell cmdlet then you'll get  
```
ArgumentNullException
  Value cannot be null. (Parameter 'key')
  ExceptionStackTrace:
     at System.ThrowHelper.ThrowArgumentNullException(String name)
     at System.ThrowHelper.ThrowKeyNullException()
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventPublisherReflectionWrapper.GetMethodInfoByScopeType(Type scopeType)
     at Microsoft.Dynamics.Nav.EventSubscription.NavEventSubscription..ctor(INavEventSubscriber subscriber, NavEventSubscriberMethodInfo subscriberMethodInfo, NavAppGroup subscriberNavAppGroup, NavEventSubscriptionModifiers subscriptionModifiers, Int32 memberId)

```

If you comment out the ExternalBusinessEvent in the first extension the problem goes away.
If you don't subscribe to the event, then the problem goes away.
Obviously both aren't acceptable, as there is a need to have both an ExternalBusinessEvent and an IntegrationEvent

**3. Expected behavior**
Having an [ExternalBusinessEvent] on an unrelated event should not cause a completely unrelated [IntegrationEvent] to fail to have a subscription.

**4. Actual behavior**
Upon publishing a subscriber that subscribes to any IntegrationEvent that's in the same codeunit as an ExternalBusinessEvent fails, which is not desired.

**5. Versions:**

- AL Language: runtime 11.0/BC22 with ms-dynamics-smb.al-13.0.864697
- Visual Studio Code: 1.82.2
- Business Central: 22.5
- List of Visual Studio Code extensions that you have installed: none.

**Comment by dannoe** [comment]
For reference: https://www.yammer.com/dynamicsnavdev/threads/2465428445929472

**Comment by EmilDamsbo** [comment]
@PooyaKharamesh Could you have a look at this one?

**Comment by PooyaKharamesh** [comment]
This issue is fixed and backported to the affected releases. The fix will be available within a few days.

**Comment by coffeecup007** [comment]
Can we please have an update on the components that were involved and what versions of said components we need to update to so that we can see the fix?  Thanks.
