### ISSUE TITLE
Currpage.close in fields OnValidate crash client after lookuppage selection

### ISSUE THREAD

**Issue by thellMa** [microsoft/AL#7615]
Please include the following with each issue:

**1. Describe the bug**
After a User picks a row from an Lookup page the page breaks if it have an Currpage.Close() statement in its OnValidate Trigger.
It works fine if only the dropdown list is used instead.

**2. To Reproduce**

Recording of issue.
https://www.youtube.com/watch?v=ecBfPL6iJKQ

In short, when user is selecting a row on an Lookup list client crashes if an CurrPage.Close is executed afterwards in fields. OnValidate Trigger.

See attached source example.
[CurrpageCloseBreak.zip](https://github.com/microsoft/AL/files/13597529/CurrpageCloseBreak.zip)

**3. Expected behavior**
Current Page closes.
(This is behaviour is used to reload current page to change columns visibilities, works fine with DropDown selection.)

**4. Actual behavior**
Web Client crashes.

**5. Versions:**

- AL Language: 12.3.900902
- Visual Studio Code:  1.84.2
- Business Central:  FI Business Central 23.1 (Platform 23.0.14464.0 + Application 23.1.13431.13546)
- List of Visual Studio Code extensions that you have installed:
365businessdevelopment.bdev-al-xml-doc
aar.xlf-editor
AlexCrome.parallel-folders
andrzejzwierzchowski.al-code-outline
atlassian.atlascode
AvaloniaTeam.vscode-avalonia
BartPermentier.al-toolbox
chunsen.bracket-select
davidfeldhoff.al-codeactions
donjayamanne.githistory
eamodio.gitlens
fernandoescolar.vscode-solution-explorer
GitHub.copilot
GitHub.copilot-chat
Gruntfuggly.todo-tree
heaths.vscode-guid
humao.rest-client
jamespearson.al-test-runner
kdcro101.favorites
letmaik.git-tree-compare
martonsagi.al-object-designer
mhutchie.git-graph
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-dynamics-smb.al
ms-vscode.powershell
nabsolutions.nab-al-tools
nwallace.createGUID
pspester.pester-test
rasmus.al-var-helper
redhat.vscode-yaml
rslfrkndmrky.rsl-vsc-focused-folder
rvanbekkum.xliff-sync
ryu1kn.partial-diff
stefanmaron.businesscentral-lintercop
streetsidesoftware.code-spell-checker
tomblind.scm-buttons-vscode
tylerleonhardt.msft-todo-unofficial
vjeko.vjeko-al-objid
vscode-icons-team.vscode-icons
waldo.al-extension-pack
waldo.crs-al-language-extension
wayou.vscode-todo-highlight
wbrakowski.al-navigator

### Final Checklist

Please remember to do the following:

* [ x ] Search the issue repository to ensure you are reporting a new issue

* [ x ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ x ] Simplify your code around the issue to better isolate the problem

**Comment by thellMa** [comment]
Here is the callstack from my docker container.

```
PS C:\Run> Get-EventLog -LogName Application -Newest 10 | Select-Object -ExpandProperty message
Category: Microsoft.Dynamics.Framework.UI.WebBase.ClientExceptionStateProcessingStrategy
EventId: 0
ConnectionId: 0HMVMEHD2BA46
RequestId: 0HMVMEHD2BA46:00000012
RequestPath: /BC/csh
TransportConnectionId: NQ-jQ5nfIQLSad0Jc9eUzw
MemberName: TryToSendToTelemetry
FilePath: s:\repo\src\Platform\Client\Web\Prod.Client.WebBase\Exception\ClientExceptionStateProcessingStrategy.cs
LineNumber: 88
ExceptionType: System.NullReferenceException



Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Framework.UI.LookupProvider.LogicalForm_FormClosed(Object sender, FormClosedEventArgs e) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Communication\LookupProvider.cs:line 59
   at Microsoft.Dynamics.Framework.UI.LogicalFormCloseMainHandler.DoMarkClosed(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormCloseMainHandler.cs:line 90
   at Microsoft.Dynamics.Framework.UI.LogicalFormCloseController.MarkClosedFormsThisAndChildForms(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormCloseController.cs:line 148
   at Microsoft.Dynamics.Framework.UI.LogicalForm.PerformClose(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormClosePart.cs:line 112
   at Microsoft.Dynamics.Framework.UI.CloseAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\FormAction.cs:line 196
   at Microsoft.Dynamics.Nav.Client.Actions.ExitActionBase.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\ExitActionBase.cs:line 46
   at Microsoft.Dynamics.Nav.Client.Actions.ExitAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\ExitAction.cs:line 219
   at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 585
   at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(LogicalControl logicalControl, IDictionary state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 497
   at Microsoft.Dynamics.Framework.UI.ActionControl.Invoke(IDictionary state) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\ActionControl.cs:line 435
   at Microsoft.Dynamics.Framework.UI.InvokeActionInteraction.InvokeCore(InvokeActionInteractionInput invokeActionInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteractions\InvokeActionInteraction.cs:line 136
   at Microsoft.Dynamics.Framework.UI.InteractionInvoker.InvokeCore[T](String interactionName, Func`2 invokeMethod, T input) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 59
   at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 46
   at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_2.<InvokeInteractions>b__4() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 157

Error accessing Website BC
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Microsoft.Dynamics.Framework.UI
HResult: -2147467261
StackTrace:
     at Microsoft.Dynamics.Framework.UI.LookupProvider.LogicalForm_FormClosed(Object sender, FormClosedEventArgs e) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Communication\LookupProvider.cs:line 59
     at Microsoft.Dynamics.Framework.UI.LogicalFormCloseMainHandler.DoMarkClosed(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormCloseMainHandler.cs:line 90
     at Microsoft.Dynamics.Framework.UI.LogicalFormCloseController.MarkClosedFormsThisAndChildForms(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormCloseController.cs:line 148
     at Microsoft.Dynamics.Framework.UI.LogicalForm.PerformClose(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormClosePart.cs:line 112
     at Microsoft.Dynamics.Framework.UI.CloseAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\FormAction.cs:line 196
     at Microsoft.Dynamics.Nav.Client.Actions.ExitActionBase.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\ExitActionBase.cs:line 46
     at Microsoft.Dynamics.Nav.Client.Actions.ExitAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\ExitAction.cs:line 219     at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 585
     at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(LogicalControl logicalControl, IDictionary state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 497
     at Microsoft.Dynamics.Framework.UI.ActionControl.Invoke(IDictionary state) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\ActionControl.cs:line 435
     at Microsoft.Dynamics.Framework.UI.InvokeActionInteraction.InvokeCore(InvokeActionInteractionInput invokeActionInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteractions\InvokeActionInteraction.cs:line 136
     at Microsoft.Dynamics.Framework.UI.InteractionInvoker.InvokeCore[T](String interactionName, Func`2 invokeMethod, T input) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 59
     at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 46
     at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_2.<InvokeInteractions>b__4() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 157
StackTrace:
     at Microsoft.Dynamics.Framework.UI.LookupProvider.LogicalForm_FormClosed(Object sender, FormClosedEventArgs e) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Communication\LookupProvider.cs:line 59
     at Microsoft.Dynamics.Framework.UI.LogicalFormCloseMainHandler.DoMarkClosed(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormCloseMainHandler.cs:line 90
     at Microsoft.Dynamics.Framework.UI.LogicalFormCloseController.MarkClosedFormsThisAndChildForms(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormCloseController.cs:line 148
     at Microsoft.Dynamics.Framework.UI.LogicalForm.PerformClose(FormClose formClose) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalFormClosePart.cs:line 112
     at Microsoft.Dynamics.Framework.UI.CloseAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\FormAction.cs:line 196
     at Microsoft.Dynamics.Nav.Client.Actions.ExitActionBase.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\ExitActionBase.cs:line 46
     at Microsoft.Dynamics.Nav.Client.Actions.ExitAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\ExitAction.cs:line 219     at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 585
     at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(LogicalControl logicalControl, IDictionary state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 497
     at Microsoft.Dynamics.Framework.UI.ActionControl.Invoke(IDictionary state) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\ActionControl.cs:line 435
     at Microsoft.Dynamics.Framework.UI.InvokeActionInteraction.InvokeCore(InvokeActionInteractionInput invokeActionInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteractions\InvokeActionInteraction.cs:line 136
     at Microsoft.Dynamics.Framework.UI.InteractionInvoker.InvokeCore[T](String interactionName, Func`2 invokeMethod, T input) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 59
     at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 46
     at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_2.<InvokeInteractions>b__4() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 157

```
