### ISSUE TITLE
DotNet exceptions with CodeAnalysis - 'codeLens/resolve' failed with error

### ISSUE THREAD

**Issue by sschuh** [microsoft/AL#7643]
**1. Describe the bug**
An error occurs when i switch to a specific al file.

```
[Error - 4:53:13 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'codeLens/resolve' failed with error: 'One or more errors occurred. (One or more errors occurred. (Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceRequestPageExtensionTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ApplicationObjectExtensionTypeSymbol'.))'
Details:
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceRequestPageExtensionTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ApplicationObjectExtensionTypeSymbol'.))
 ---> System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceRequestPageExtensionTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ApplicationObjectExtensionTypeSymbol'.)
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SourceRequestPageExtensionTypeSymbol' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ApplicationObjectExtensionTypeSymbol'.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.TriggerReferenceHelpers.GetAdjustedContainingSymbol(ISymbol symbol) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\TriggerReferenceHelpers.cs:line 149
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.SymbolFinder.IsTriggerReferenceForTrigger(ISymbol triggerMethod, ISymbol otherTrigger) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\SymbolFinder.cs:line 196
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.<>c__DisplayClass12_0.<GetStandardSymbolsNodeMatchFunction>b__0(SyntaxNode node, SemanticModel model)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.FindReferencesInTokensAsync(Document document, IEnumerable`1 tokens, Func`2 tokensMatch, Func`3 symbolsMatch, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 164
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder.FindReferencesInDocumentUsingIdentifierAsync(String identifier, Document document, Func`2 tokensMatch, Func`3 symbolsMatch, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 116
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.AbstractReferenceFinder`1.Concat[T](Task`1[] tasks) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\Finders\AbstractReferenceFinder.cs:line 241
   at System.Threading.Tasks.TaskFactory`1.<>c__56`1.<ContinueWhenAllImpl>b__56_0(Task`1 starter, Object continuationFunction)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessDocumentAsync(Document document, SymbolAndProjectId symbolAndProjectId, IReferenceFinder finder) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 59
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessDocumentAsync(Document document, SymbolAndProjectId symbolAndProjectId, IReferenceFinder finder) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 68
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessDocumentQueueAsync(Document document, ValueSet documentQueue) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 40
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessDocumentQueueAsync(Document document, ValueSet documentQueue) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_DocumentProcessing.cs:line 47
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessProjectAsync(Project project, MultiDictionary`2 documentMap) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 96
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessProjectAsync(Project project, Dictionary`2 projectToDocumentMap) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 73
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessProjectAsync(ProjectId projectId, Dictionary`2 projectToDocumentMap, HashSet`1 visitedProjects) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 56
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessProjectsAsync(IEnumerable`1 connectedProjectSet, Dictionary`2 projectToDocumentMap) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine_ProjectProcessing.cs:line 36
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.ProcessAsync(Dictionary`2 projectToDocumentMap) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 106
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.FindReferencesAsync(SymbolAndProjectId symbolAndProjectId) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 64
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesSearchEngine.FindReferencesAsync(SymbolAndProjectId symbolAndProjectId) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesSearchEngine.cs:line 69
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.SymbolFinder.FindReferencesAsync(SymbolAndProjectId symbolAndProjectId, Solution solution, IStreamingFindReferencesProgress progress, IImmutableSet`1 documents, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\SymbolFinder_References.cs:line 57
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindSymbols.SymbolFinder.FindReferencesAsync(ISymbol symbol, Solution solution, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindSymbols\SymbolFinder_References.cs:line 28
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesService.FindReferencedSymbolsInternalAsync(Document document, Int32 position, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesService.cs:line 46
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Utilities\TaskExtensions.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.FindReferences.FindReferencesService.FindReferencedSymbolsAsync(Document document, Int32 position, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\FindReferences\FindReferencesService.cs:line 25
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensResolveRequestHandler.CreateReferencesCodeLens(CodeLensResolveRequest request, CodeLens response, Document document, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensResolveRequestHandler.cs:line 94
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensResolveRequestHandler.HandleAsync(CodeLensResolveRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensResolveRequestHandler.cs:line 80
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 84
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 84
```

**2. To Reproduce**

Here is my used object.

Maybe this is reproducable with object page 295 "Req. Wksh. Names".

```
page 5157294 "KVSTRDDemandPlanningWkshNames"
{
    ApplicationArea = KVSTRDBasic;
    Caption = 'Demand Planning Wksh. Names';
    DataCaptionExpression = DataCaption();
    PageType = List;
    SourceTable = "KVSTRDDemandPlanningWkshName";
    UsageCategory = None;

    layout
    {
        area(content)
        {
            repeater(Control1)
            {
                ShowCaption = false;
                field(Name; Rec.Name)
                {
                    ToolTip = ' ', Locked = true;
                }
                field(Description; Rec.Description)
                {
                    ToolTip = ' ', Locked = true;
                }
            }
        }
        area(factboxes)
        {
            systempart(LinksPart; Links)
            {
                Visible = false;
            }
            systempart(NotesPart; Notes)
            {
                Visible = false;
            }
        }
    }
    actions
    {
        area(processing)
        {
            action(EditWorksheet)
            {
                Caption = 'Edit Worksheet';
                Image = OpenWorksheet;
                ShortCutKey = 'Return';
                ToolTip = ' ', Locked = true;

                trigger OnAction()
                var
                    DemandPlanningJournalMgt: Codeunit KVSTRDDemandPlanningJournalMgt;
                begin
                    DemandPlanningJournalMgt.TemplateSelectionFromBatch(Rec);
                end;
            }
        }
        area(Promoted)
        {
            group(Category_Process)
            {
                Caption = 'Process';
                actionref("EditWorksheet_Promoted"; "EditWorksheet")
                {
                }
            }
        }
    }

    trigger OnInit()
    begin
        Rec.SetRange("Worksheet Template Name");
    end;

    trigger OnOpenPage()
    var
        DemandPlanningJournalMgt: Codeunit KVSTRDDemandPlanningJournalMgt;
        DemandPlanningMgt: Codeunit KVSTRDDemandPlanningMgt;
    begin
        DemandPlanningMgt.TestDemandPlanningWorksheetIsActive();
        DemandPlanningJournalMgt.OpenJnlBatch(Rec);
    end;

    local procedure DataCaption(): Text[250]
    var
        DemandPlanningWkshTempl: Record "KVSTRDDemandPlanningWkshTempl";
    begin
        if not CurrPage.LookupMode then
            if Rec.GetFilter("Worksheet Template Name") <> '' then
                if Rec.GetRangeMin("Worksheet Template Name") = Rec.GetRangeMax("Worksheet Template Name") then
                    if DemandPlanningWkshTempl.Get(Rec.GetRangeMin("Worksheet Template Name")) then
                        exit(DemandPlanningWkshTempl.Name + ' ' + DemandPlanningWkshTempl.Description);
    end;
}
```

**3. Expected behavior**
No error.

**4. Actual behavior**
Error.

**5. Versions:**

- AL Language: 
v13.0.921843

- Visual Studio Code: 
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Business Central: 
23.3

- List of Visual Studio Code extensions that you have installed:
<img width="302" alt="image" src="https://github.com/microsoft/AL/assets/34685182/0bb265fb-0c59-463b-ae78-e603ceb79c25">

**Comment by BazookaMusic** [comment]
This is equivalent to an NRE, should be fixed

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.16183.0 and VS Code Extension Version 13.0.940478. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
