### ISSUE TITLE
Altgen proxy table command error (AL Table Proxy Generator Error)

### ISSUE THREAD

**Issue by Shathika94** [microsoft/AL#7657]
**1. Describe the bug**
I'm trying to sychronize dataverse with Business Central onprem and I have synced User, Account, Business Unit, Work Order Substatus tables from dataverse to Business central using AL Table Proxy Generator which is available with the AL Language extension. However msdyn_functionallocation table is not syncing and giving an error as _**System.NullReferenceException: Object reference not set to an instance of an object.**_

Below are the queries that I used to perform the syncing.
**.\altpgen -project:"C:\Users\abc1\Documents\AL\***" -packagecachepath:"C:\Users\abc1\Documents\AL\***\.alpackages" -serviceuri:"[https://***.crm3.dynamics.com/"](https://***.crm3.dynamics.com/%22) -entities:msdyn_functionallocation -tabletype:CDS**

below is the complete error message I'm receiving.

How to resolve this?

PS C:\Users\adnm1\.vscode\extensions\ms-dynamics-smb.al-12.5.914975\bin> .\altpgen -project:"C:\Users\abc1\Documents\AL\***" -packagecachepath:"C:\Users\abc1\Documents\AL\***\.alpackages" -serviceuri:"[https://***.crm3.dynamics.com/"](https://***.crm3.dynamics.com/%22) -entities:msdyn_functionallocation -tabletype:CDS
Microsoft (R) AL Table Proxy Generator version 12.5.13.63033
Copyright (C) Microsoft Corporation. All rights reserved

 

Authenticating Dataverse using ServiceUri=https://***.crm3.dynamics.com/
Authenticated.
Retrieving entity metadata.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Immutable.ImmutableArray`1.get_Length()
   at Microsoft.Dynamics.Nav.TableProxyGenerator.BuilderBase.CalcDataType(XrmEntityAttribute attr) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\BuilderBase.cs:line 456
   at Microsoft.Dynamics.Nav.TableProxyGenerator.BuilderBase.AddNormalField(XrmEntityAttribute attr) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\BuilderBase.cs:line 84
   at Microsoft.Dynamics.Nav.TableProxyGenerator.BuilderBase.BuildFields() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\BuilderBase.cs:line 56
   at Microsoft.Dynamics.Nav.TableProxyGenerator.BuildContext.BuildFields() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\BuildContext.cs:line 140
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorTool.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\TableProxyGeneratorTool.cs:line 62
   at Microsoft.Dynamics.Nav.CodeAnalysis.CompilationDependentTool.Run(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\CompilationDependentTool.cs:line 125
   at Microsoft.Dynamics.Nav.CodeAnalysis.CompilationDependentTool.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\CompilationDependentTool.cs:line 77
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorCommandLineTool.Run(String clientDirectory, String baseDirectory, String[] args) in D:\a\_work\1\s\source\Prod\altpgen\TableProxyGeneratorCommandLineTool.cs:line 29

**Comment by Shathika94** [comment]
Yes I have three more Picklist type fields. Yes this is the only entity I'm getting the error. Previously I successfully did on Business Unit, Customer Asset, Work Order, User and Work Order Substatus.

Any Help?

**Comment by onbuyuka** [comment]
It is clearly caused by one of the three picklists, what is the output of below query? You can call this in a browser tab.

`GET [Organization URI]/api/data/v9.2/EntityDefinitions(LogicalName='msdyn_functionallocation')/Attributes/Microsoft.Dynamics.CRM.PicklistAttributeMetadata?$select=LogicalName&$expand=OptionSet,GlobalOptionSet`

If this is blocking you, repeating that you can always create proxy tables manually, you can take the one created above and add more fields if needed.

**Comment by BazookaMusic** [comment]
The initial stack trace points to a null ref exception due to trying to get the length of an uninitialized immutable array. I'm marking it for triage as this is a bug

**Comment by Shathika94** [comment]
onbuyuka can you please share the Work Order table as well. I want to see the functionlocation field to add it manually.

**Comment by onbuyuka** [comment]
@Shathika94 I meant if this issue is blocking you or not. As I said it is caused by one of those picklists hence why I wanted to see the definitions of them. I can try to reproduce the issue that way. Could you please share the output of the query above?
