### ISSUE TITLE
ToolTipsToTableFieldCodeFixProvider.GetControlAndField crashes

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#7767]
[Error - 1:23:39 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeAction' failed with error: 'Object reference not set to an instance of an object.'
Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.CodeRefactoring.Providers.ToolTipsToTableFieldCodeFixProvider.GetControlAndField(SemanticModel semanticModel, SyntaxNode controlSyntax) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeRefactoring\Providers\ToolTipsToTableFieldCodeFixProvider.cs:line 281
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.CodeRefactoring.Providers.ToolTipsToTableFieldCodeFixProvider.ComputeRefactoringsAsync(CodeRefactoringContext context) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeRefactoring\Providers\ToolTipsToTableFieldCodeFixProvider.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeRefactoring.CodeRefactoringService.GetRefactoringFromProviderAsync(Document document, TextSpan textSpan, CodeRefactoringProvider provider, CancellationToken cancellationToken) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeRefactoring\CodeRefactoringService.cs:line 70
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeRefactoring.CodeRefactoringService.GetRefactoringsAsync(Document document, TextSpan state, CancellationToken cancellationToken) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeRefactoring\CodeRefactoringService.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.CodeActions.ALCodeActionService.GetCodeActionsAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\CodeActions\ALCodeActionService.cs:line 50
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeActionRequestHandler.HandleAsync(ProtocolCodeActionRequest request, Int32 requestId, CancellationToken cancellationToken) in X:\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeActionRequestHandler.cs:line 64
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in X:\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 84
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in X:\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 84

**Comment by krupybalu** [comment]
I am closing this issue because it appears that it has been resolved. The fix will be available with the next VSIX pre-release.
