### ISSUE TITLE
Attaching to the next WebServiceClient fails with "Invalid debug adapter"

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#7770]
**1. Describe the bug**
I try to attach to the next WebServiceClient. If I trigger the webservice call, the debugger just stops and there is a log entry in the "extension host" window in vscode.

**2. To Reproduce**
Have a workspace file with the following launch/configurations settings:
```json
{
  "name": "Attach: sandbox-test (WebService)",
  "type": "al",
  "request": "attach",
  "tenant": "<tenant-id>",
  "environmentType": "Sandbox",
  "environmentName": "sandbox-test",
  "breakOnError": "All",
  "breakOnRecordWrite": "None",
  "breakOnNext": "WebServiceClient",
  "userId": "USER ID"	
}
```

Run: "AL: Debug without publishing"

**3. Expected behavior**
Debugging should work

**4. Actual behavior**
The following log entry occurs in vscode, as soon as the webservice call is triggered.
```
2024-06-13 17:20:20.593 [error] Error: Invalid debug adapter
    at l.p (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1769:95)
    at l.$acceptDAExit (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1769:35)
    at y.S (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:14598)
    at y.Q (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:14364)
    at y.M (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:13397)
    at y.L (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:12453)
    at u.value (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:10928)
    at h.y (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at h.fire (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:876)
    at r.fire (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:615:14848)
    at U.onmessage (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1673:8154)
```
**5. Versions:**

- AL Language: Version: 13.0.1027618
- Visual Studio Code: 1.90.0
- Business Central: Version: DE Business Central 24.1, (Platform 24.0.20440.0 + Application 24.1.18927.19282)
- List of Visual Studio Code extensions that you have installed: Tested with only AL extension enabled.

Internal work item: [AB#538498](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538498)

**Comment by kalberes** [comment]
I have no repro on this? On the other hand it looks like a vscode issue? Have you tried with the experimental vscode? Whether that also reproes?
I have seen traces of similar issues on teh vscode branch:
https://github.com/microsoft/vscode/issues/196948
