### ISSUE TITLE
Suggesion: Pre-Compiler Exception with a hint of the related file(s)

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#779]
When I get the following Exception from the Pre-Compiler in VsCode, it would be nice if I get a hint which file(s) is/are related. Otherwise it is difficult for me to create a simple reproducible example.
```
[Error - 8:35:38 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'codeLens/resolve' failed with error: 'Specified argument was out of the range of valid values.
Parameter name: index'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\SourceText.cs:line 684
   at Microsoft.Dynamics.Nav.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Text\TextLineCollection.cs:line 75
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensResolveRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensResolveRequestHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__5.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 50
```

**Comment by DominikDitoIvosevic** [comment]
This bug is related to how Visual Studio Code handles codelens events. For some reason vscode requests codelens for already deleted code. I suppose this was happening to you when you tried deleting a few lines of code while having codelens enabled for AL.

I have added versioning for codelens requests so this should be fixed in a future update. In case you are still getting this bug afterwards please tell me what kind of action were you doing (deleting code/editing code/compiling) so that I may investigate but I believe the bug has been fixed now.
