### ISSUE TITLE
AL Table Proxy Generator - System.NullReferenceException

### ISSUE THREAD

**Issue by adcprowi** [microsoft/AL#7894]
**1. Describe the bug**
I'm trying to synchronize Dataverse tables with a Business Central Online environment by using the altpgen.exe tool.
The commands that are generating the error were working fine in the past with the same setup.
I've tried this on multiple custom tables and for an extension on the contacts table. The issue occurs in both cases.

1. Example command for custom tables
` .\altpgen -project:"C:\MyProjectPath" -packagecachepath:"C:\MyProjectPath\.alpackages" -serviceuri:"https://xxx.crm4.dynamics.com/" -clientid:myClientId -redirecturi:"http://localhost" -entities:cr9fa_repairheader -baseid:50012 -tabletype:CDS`

2. Example command for table extension
`.\altpgen -project:"C:\MyProjectPath" -packagecachepath:"C:\MyProjectPath\.alpackages" -serviceuri:"https://xxx.crm4.dynamics.com/" -clientid:myClientId -redirecturi:"http://localhost" -entities:contact -tabletype:CDS`

3. Output
```
Microsoft (R) AL Table Proxy Generator version 15.0.17.63735
Copyright (C) Microsoft Corporation. All rights reserved

Authenticating Dataverse using ServiceUri=https://xxx.crm4.dynamics.com/
Authenticated.
Retrieving entity metadata.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.TableProxyGenerator.BuildContext.<>c__DisplayClass25_0.<.ctor>b__3(SourceTableExtensionTypeSymbol ao) in X:\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\BuildContext.cs:line 107
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.Dynamics.Nav.CodeAnalysis.ImmutableArrayExtensions.ToImmutableArrayOrEmpty[T](IEnumerable`1 items) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Collections\ImmutableArrayExtensions.cs:line 41
   at Microsoft.Dynamics.Nav.TableProxyGenerator.BuildContext..ctor(Compilation compilation, XrmMetadataService service, ImmutableArray`1 entityNames, Nullable`1 tableType, String prefix, Int32 baseId, Boolean test) in X:\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\BuildContext.cs:line 105
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorTool.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in X:\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\TableProxyGeneratorTool.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.CompilationDependentTool.Run(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in X:\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\CompilationDependentTool.cs:line 125
   at Microsoft.Dynamics.Nav.CodeAnalysis.CompilationDependentTool.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in X:\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\CompilationDependentTool.cs:line 77
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorCommandLineTool.Run(String clientDirectory, String baseDirectory, String[] args) in X:\Prod\altpgen\TableProxyGeneratorCommandLineTool.cs:line 29
```

This seems related to a previously reported issue: https://github.com/microsoft/AL/issues/7657

**Comment by onbuyuka** [comment]
From the stack trace it looks like this is occurs when loading reference symbols. What packages do you have in .alpackages folders and what objects do you have in app MyProjectPath?

I was not able to reproduce, could you please try with empty .alpackages folder just to test?

**Comment by adcprowi** [comment]
I noticed the .alpackages file was copied/created in the folder above the actual project files.
I was accidentally referencing this folder and didn't notice as this was still working a few weeks ago.
Referencing the up-to date .alpackages fixed the issue.
