### ISSUE TITLE
AL Table Proxy Generator 14.1.18 Authentication Failure - Microsoft.Dynamics.Nav.Xrm.Common.XrmException

### ISSUE THREAD

**Issue by jjjon3** [microsoft/AL#7895]
Hello,

I am trying to integrate my custom tables in Business Central with the Dataverse. After following this [guide](https://yzhums.com/49871/) step by step,  I keep getting below error and I couldn't find any other solutions after looking up the errror.

PowerShell error:
Microsoft (R) AL Table Proxy Generator version 14.1.18.1238
Copyright (C) Microsoft Corporation. All rights reserved

Authenticating Dataverse using ServiceUri=https://org[serviceURI].crm3.dynamics.com/
Authentication failure. Reason: One or more errors occurred. (Only loopback redirect uri is supported, but msal[redirectUri]://auth/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details)
error CDS0001: Error connecting to Dataverse. 
Microsoft.Dynamics.Nav.Xrm.Common.XrmException: Failed to connect to Dataverse
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateServiceConnection(Object externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId,
 SecureString password, String domain, String Geo, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, String clientId, Uri redirectUri, PromptBehavior promptBehavior, OrganizationWebProxyClientAsync externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned, Boolean useDefaultCreds, Version incomingOrgVersion, ILogger externalLogger, String tokenCacheStorePath)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient..ctor(Uri instanceUrl, Func`2 tokenProviderFunction, Boolean useUniqueInstance, ILogger logger)
   at Microsoft.Dynamics.Nav.Xrm.XrmService.<>c__DisplayClass11_0.<Connect>b__0() in X:\Prod\Microsoft.Dynamics.Nav.Xrm\XrmService.cs:line 84
   at Microsoft.Dynamics.Nav.Xrm.Common.XrmHelper.ExecuteXrm(Action action) in X:\Prod\Microsoft.Dynamics.Nav.Xrm\XrmHelper.cs:line 49

**Comment by jjjon3** [comment]
Someone from the MS Community Forum sent me [this](https://github.com/microsoft/AL/issues/7869) for the solution.
