### ISSUE TITLE
Query.SaveAsJson is crashing on "Null" DateTime

### ISSUE THREAD

**Issue by martinm1000** [microsoft/AL#7913]
I hope this is a good place for this bug report.

I'm trying the newly added feature of saving a Query to JSON, only to get the 'Something went wrong' crash.

I'm not on cloud, but in the lastest Docker image for 25.1, and using the runtime 14.

The following code compiles but crash on execution:

```pascal
procedure GetQueryResultsAsJson(QueryId: Integer) Result: Text
var
    OS: OutStream;
    IS: InStream;
    TempBlob: Codeunit "Temp Blob";
    JSON: Text;
begin

    OS := TempBlob.CreateOutStream(TextEncoding::UTF8); // ??

    // SaveAsCsv works, SaveAsJson = Something went wrong

    if (Query.SaveAsJson(QueryId, OS)) then begin
        IS := TempBlob.CreateInStream();
        IS.Read(JSON);
    end else begin
        Error(GetLastErrorText());
    end;

    exit(JSON);
end;
```

Note that I can replace `SaveAsJson` by `SaveAsCSV` and I get results:

|ProjectCode|TaskCode|TaskType   |ParentCode|Indentation|Description|Start                |End|Closed|DepartmentCode|CategoryGroupCode|CategoryCode|DefaultInvLaborUOM|Totaling|SystemId                            |SystemModifiedAt     |
|-----------|--------|-----------|----------|-----------|-----------|---------------------|---|------|--------------|-----------------|------------|------------------|--------|------------------------------------|---------------------|
|J00010     |1000    |Begin-Total|          |0          |Project X1 |0                    |0  |False |C01-01        |CONSULTING       |            |HOUR              |        |3e87e0ad-70a7-ef11-b7e3-e35e4a46447d|11/20/2024 3:04:04 PM|
|J00010     |1100    |Begin-Total|1000      |1          |Phase 1    |0                    |0  |False |C01-01        |CONSULTING       |            |HOUR              |        |3f87e0ad-70a7-ef11-b7e3-e35e4a46447d|11/20/2024 3:04:04 PM|
|J00010     |1110    |Posting    |1100      |2          |Task 1     |1/31/2025 12:00:00 AM|0  |False |C01-01        |CONSULTING       |            |HOUR              |        |4087e0ad-70a7-ef11-b7e3-e35e4a46447d|11/20/2024 3:04:04 PM|

Extracting the events from inside docker with `Get-BcContainerEventLog -containerName sandbox1`, I can see this :

```
This version of Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
User: 
Type: System.InvalidCastException
Message: Unable to cast object of type 'System.DBNull' to type 'System.DateTime'.
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147467262
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.SaveAsJsonRenderer.SetNavDateOrNavTimeValue(Int32 columnIndex, Object value)
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.ParseResultSetEnumeratorAsync()
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.<>c__DisplayClass169_0.<<RunQueryInternalAsync>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Runtime.ApplicationObjectRootScope.AddApplicationObjectRootScopeAsync[T](NavApplicationObjectBase applicationObject, Func`1 action)
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.SaveToStreamAsync(NavQuery query, OutputType filetype, DataError errorLevel, NavOutStream outStream, String delimiter, Boolean fixedFormat, Int32[] positions)
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.SaveToStreamAsync(NavSession session, OutputType filetype, DataError errorLevel, Int32 queryId, NavOutStream outStream, String delimiter, Boolean fixedFormat, Int32[] positions)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit51900.GetQueryResultsAsJson_Scope__1201053547.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.BusinessApplication.Page51900.OnOpenPage_Scope.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnOpenPageAsync()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.OpenFormAsync()
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.<>c__DisplayClass15_1.<<OpenFormsAsync>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccessAsync(ITreeObject parent, NavForm form, Func`2 action)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccessAsync(ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Func`2 action)
     at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.OpenFormsAsync(FormOpenResponse openResponse, List`1 registeredForms)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.OpenAsync(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.OpenFormAsync(OpenFormRequest form)
     at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineHelper.CallWithHandlingTargetInvocationException[T](Func`1 asyncFunc)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.StartSamplingProfilingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddSessionToThreadSchedulerCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.RunInTransactionCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TransientErrorRetryCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation, Boolean useCoreWcfFaultException)
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.SaveAsJsonRenderer.SetNavDateOrNavTimeValue(Int32 columnIndex, Object value)
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.ParseResultSetEnumeratorAsync()
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.<>c__DisplayClass169_0.<<RunQueryInternalAsync>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Runtime.ApplicationObjectRootScope.AddApplicationObjectRootScopeAsync[T](NavApplicationObjectBase applicationObject, Func`1 action)
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.SaveToStreamAsync(NavQuery query, OutputType filetype, DataError errorLevel, NavOutStream outStream, String delimiter, Boolean fixedFormat, Int32[] positions)
     at Microsoft.Dynamics.Nav.Runtime.NavQuery.SaveToStreamAsync(NavSession session, OutputType filetype, DataError errorLevel, Int32 queryId, NavOutStream outStream, String delimiter, Boolean fixedFormat, Int32[] positions)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit51900.GetQueryResultsAsJson_Scope__1201053547.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.BusinessApplication.Page51900.OnOpenPage_Scope.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnOpenPageAsync()
     at Microsoft.Dynamics.Nav.Runtime.NavForm.OpenFormAsync()
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.<>c__DisplayClass15_1.<<OpenFormsAsync>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccessAsync(ITreeObject parent, NavForm form, Func`2 action)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccessAsync(ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Func`2 action)
     at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.OpenFormsAsync(FormOpenResponse openResponse, List`1 registeredForms)
     at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.OpenAsync(NavSession session)
     at Microsoft.Dynamics.Nav.Service.NSService.OpenFormAsync(OpenFormRequest form)
     at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineHelper.CallWithHandlingTargetInvocationException[T](Func`1 asyncFunc)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.StartSamplingProfilingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddSessionToThreadSchedulerCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.RunInTransactionCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TransientErrorRetryCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation, Boolean useCoreWcfFaultException)
 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

So it looks like the underlying .Net code under AL doesn't like the dates that we have at "NULL". Those are of `AL` type `Date` and
are seen as `1753-01-01 00:00:00.000` in the Database and `0001-01-01` outside the DB...

Next, I'll try to get a query that only will return rows with non-null dates...

**Comment by martinm1000** [comment]
If I update the table in the DB with dates (ie.: update [x] = ''2025-01-31 00:00:00.000' where X = '1753-01-01 00:00:00.000', it works.
If I remove the 2 `Date` fields from the query, it works.

So there's an issue with '1753-01-01'

**Comment by BazookaMusic** [comment]
This repository is only dedicated to bug reports for AL compiler and developer tools. Runtime issues should follow the support process indicated below. 

# How to get help
- Review our resources for [help and support](https://learn.microsoft.com/en-us/dynamics365/business-central/product-help-and-support)
- If you are a Microsoft Partner, follow the [documentation](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/manage-technical-support#escalating-support-issues-to-microsoft) here to escalate a customer issue
- If you are a Business Central customer, read about [reporting a problem](https://learn.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem)
- Open a bug in [Collaborate](https://aka.ms/collaborate)
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

## General Questions
You can use [Viva Engage](https://www.yammer.com/dynamicsnavdev) for asking questions and providing feedback around the runtime behavior of the product.

**Comment by BazookaMusic** [comment]
This does look like a bug but this repository is only for the compiler. Try one of the options above to get a bug created for the appropriate team.
