### ISSUE TITLE
Application Crashes when access record "Report Data Items"

### ISSUE THREAD

**Issue by sankarvinop** [microsoft/AL#7936]
On Perm-BC250 - Version: W1 25.1 (Platform 25.0.25866.0 + Application 25.1.25873.25900)

When we try to access and filter Related Table Id field system is getting crashed

 http://localhost:8080/BC250/?table=2000000203, system is getting crashed 

Error from Event Viewer

Category: Microsoft.Dynamics.Framework.UI.WebBase.ClientExceptionStateProcessingStrategy
EventId: 0
ConnectionId: 0HN8UETELUN1I
RequestId: 0HN8UETELUN1I:0000000E
RequestPath: /BC250/csh
TransportConnectionId: PPiOAqmnxAO1huiEqax3gQ
MemberName: TryToSendToTelemetry
FilePath: s:\repo\src\Platform\Client\Web\Prod.Client.WebBase\Exception\ClientExceptionStateProcessingStrategy.cs
LineNumber: 88
ExceptionType: Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException

 

Exception: 
Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException: The server "BC250" was unable to process the request. The application will close.
 ---> Microsoft.Dynamics.Nav.Types.Exceptions.NavServerSessionException: The server "BC250" was unable to process the request. The application will close.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.Runtime.ReportDataItemsDataProvider.GetReportDataItems(NavInteger reportId, Range range, SortOrder sortOrder, FilterFieldDictionary nonPrimaryKeyFilters)+MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at Microsoft.Dynamics.Nav.Runtime.ResultSet.TryGetAtIndexWithoutBufferAsync(Int32 index)
   at Microsoft.Dynamics.Nav.Runtime.ResultSet.TryGetAtIndexAsync(Int32 index)
   at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
--- End of stack trace from previous location ---
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.AdvanceAsync(Int32 steps, Boolean moveBackwards, Boolean automaticFindFromPositionOnInvalid, Int32 setSize)
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.AdvanceAsync(Int32 steps, Boolean moveBackwards, Boolean automaticFindFromPositionOnInvalid, Int32 setSize)
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.NextRecordAsync(Int32 steps, Int32 setSize)

   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.Dynamics.Nav.BusinessApplication.Page50048.DeployLatestExtension_a45_OnAction_Scope.OnRunAsync()
   at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
--- End of stack trace from previous location ---
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethodAsync(NavApplicationObjectBase applicationObject, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
   at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnActionAsync(Nullable`1 actionId, String actionTriggerMethodName, Object[] args)
   at Microsoft.Dynamics.Nav.Service.NSField.<>c__DisplayClass21_0.<<ActionFieldAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccessAsync[T](ITreeObject parent, NavForm form, Func`2 func)
   at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccessAsync[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Func`2 func)
   at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineHelper.CallWithHandlingTargetInvocationException[T](Func`1 asyncFunc)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.StartSamplingProfilingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddSessionToThreadSchedulerCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.RunInTransactionCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TransientErrorRetryCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation, Boolean useCoreWcfFaultException)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.CallServer[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionStateManager.cs:line 54
   at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServer[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ServiceConnection.cs:line 0
   at Microsoft.Dynamics.Nav.Client.ServerInvocationHandler.CallServerSync[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ServerInvocationHandler.cs:line 99
   at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.ActionField(NavRecordState& state, NavDataSet recDataSet, Int32 controlId, Int32 controlEventId, Object[] args) in s:\repo\src\Platform\ClientServerShared\Prod.Types\ServiceConnection\ServiceConnectionBase.cs:line 623
   at Microsoft.Dynamics.Nav.Client.ServiceConnection.Microsoft.Dynamics.Nav.Client.IService.ActionField(NavRecordState& state, NavDataSet recDataSet, Int32 controlId, Int32 controlEventId, Object[] args)
   at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.ActionMethod(Int32 controlId, Int32 controlEventId, Object[] args) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Databinder\NSTDataAccess.cs:line 786
   at Microsoft.Dynamics.Nav.Client.Actions.InvokePageTriggerAction.InvokeTrigger(LogicalControl logicalControl, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\InvokePageTriggerAction.cs:line 115
   at Microsoft.Dynamics.Nav.Client.Actions.InvokePageTriggerAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\InvokePageTriggerAction.cs:line 76
   at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 562
   at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(LogicalControl logicalControl, IDictionary state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 469
   at Microsoft.Dynamics.Framework.UI.ActionControl.Invoke(IDictionary state) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\ActionControl.cs:line 417
   at Microsoft.Dynamics.Framework.UI.InvokeActionInteraction.InvokeCore(InvokeActionInteractionInput invokeActionInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteractions\InvokeActionInteraction.cs:line 86
   at Microsoft.Dynamics.Framework.UI.InteractionInvoker.InvokeCore[T](String interactionName, Func`2 invokeMethod, T input) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 48
   at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 43
   at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_2.<InvokeInteractions>b__4() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 145

**Comment by BazookaMusic** [comment]
🔻🔻🔻This repository is only dedicated to bug reports for AL compiler and developer tools. Runtime issues should follow the support process indicated below. 🔻🔻🔻

# How to get help
- Review our resources for [help and support](https://learn.microsoft.com/en-us/dynamics365/business-central/product-help-and-support)
- If you are a Microsoft Partner, follow the [documentation](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/manage-technical-support#escalating-support-issues-to-microsoft) here to escalate a customer issue
- If you are a Business Central customer, read about [reporting a problem](https://learn.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem)
- Open a bug in [Collaborate](https://aka.ms/collaborate)
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

## General Questions
You can use [Viva Engage](https://www.yammer.com/dynamicsnavdev) for asking questions and providing feedback around the runtime behavior of the product.
