### ISSUE TITLE
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#833]
So...I finally finished refactoring one of our larger apps and got rid of all the AL compile errors. Then I got this. Obviously this is keeping us from proceeding. It's build 18825.

[Error - 7:24:03 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.CodeGenFacts.GetRuntimeTypeSyntax(Symbol symbol) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\CodeGenFacts.cs:line 460
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitCaseStatementAsIfThenElse(ArrayBuilder`1 statementList, BoundCaseStatement stmt) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 659
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitCaseStatement(ArrayBuilder`1 statementList, BoundCaseStatement stmt) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 622
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 252
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitBlock(BoundBlock block) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 121
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 233
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitStatement(BoundStatement stmt) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 143
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitIfStatement(BoundIfStatement stmt) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 282
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitSingleStatement(ArrayBuilder`1 statementList, BoundStatement stmt) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 237
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitBlock(BoundBlock block) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator_Statements.cs:line 121
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitScopeRunMethod() in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator.cs:line 599
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.EmitScopeClass() in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator.cs:line 230
   at Microsoft.Dynamics.Nav.CodeAnalysis.Emit.MethodCodeGenerator.Generate() in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Emitter\CodeGen\MethodCodeGenerator.cs:line 94
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethod(MethodSymbol methodSymbol) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 436
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMembers(ContainerSymbol containingType) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 309
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 233
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 216
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 150
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 808
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 785
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 531
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 312
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\39\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by dennisfrostlander** [comment]
This is a bug in compiling an AL `case of` statement, which is somewhat non-standard or complex. 
This statement is inside an an `if` block in a procedure or a trigger.
Would it be possible for you for find this statement simply by commenting out suspicious `case of` blocks and building afterwards?

**Comment by jcooper01** [comment]
There are 382 case statements in the app. Almost all are inside an if block. Any way to narrow it down more?

**Comment by dennisfrostlander** [comment]
Hard to say at the moment. I'd look for something non-standard in the case of expression - complex expressions `case a + b + c of`, method calls `case myCodeUnit.CallSomething()`, accessing XmlNodes, report data items, etc...

**Comment by jcooper01** [comment]
I went through all case statements in our app...here's what was causing the issue:

CASE (Tran."Transaction Amount" - ROUND(Tran."Transaction Amount", 1, '<')) * 100 OF

**Comment by dennisfrostlander** [comment]
We are working on a fix. Thanks a lot for the investigation!

**Comment by Jan-Skrubbeltrang** [comment]
Still an issue in the AL compiler: Got Same type of error of December build of compiler

Commented out all Case statements to no awail.... 

[Error - 08:47:13] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Objektreferencen er ikke indstillet til en forekomst af et objekt.'
StackTrace:
   ved Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ResolveApplicationObjectReference(ModuleSymbol module, SymbolKind kind, Subtype subType) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:linje 654
   ved Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ResolveElementType(ModuleSymbol module, Symbol owner, String typeString, Subtype subType, String optionMembers) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:linje 744
   ved Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReference.SerializableSymbolModelConverter.ResolveType(ModuleSymbol module, Symbol owner, String typeString, Subtype subType, String arrayDimensions, String optionMembers) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolReference\SerializableSymbolModelConverter.cs:linje 75
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReferenceGlobalVariableSymbol..ctor(ContainerSymbol containingSymbol, VariableDefinition variable) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceGlobalVariableSymbol.cs:linje 21
   ved Microsoft.Dynamics.Nav.CodeAnalysis.ReferenceTableExtensionTypeSymbol.<LazyGetMembers>b__32_0(VariableDefinition m) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceTableExtensionTypeSymbol.cs:linje 142
   ved System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   ved System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   ved System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   ved System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   ved Microsoft.Dynamics.Nav.CodeAnalysis.ReferenceTableExtensionTypeSymbol.LazyGetMembers() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceTableExtensionTypeSymbol.cs:linje 142
   ved Microsoft.Dynamics.Nav.CodeAnalysis.ReferenceTableExtensionTypeSymbol.GetMembers() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceTableExtensionTypeSymbol.cs:linje 103
   ved Microsoft.Dynamics.Nav.CodeAnalysis.ReferenceTableExtensionTypeSymbol.GetCodeMembers() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Reference\ReferenceTableExtensionTypeSymbol.cs:linje 128
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ObjectTypeSymbol.GetCodeMembers(String name) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\ObjectTypeSymbol.cs:linje 129
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.LookupMembersFromExtensions(LookupResult result, TypeSymbol type, String name, LookupOptions options, Binder originalBinder, TypeSymbol accessThroughType, Boolean diagnose, HashSet`1& useSiteDiagnostics, BoundExpression receiver) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Lookup.cs:linje 354
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.LookupMembersInClass(LookupResult result, TypeSymbol type, String name, BoundExpression receiver, LookupOptions options, Binder originalBinder, Boolean diagnose, HashSet`1& useSiteDiagnostics) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Lookup.cs:linje 222
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.LookupMembersInType(LookupResult result, TypeSymbol type, String name, BoundExpression receiver, LookupOptions options, Binder originalBinder, Boolean diagnose, HashSet`1& useSiteDiagnostics) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Lookup.cs:linje 143
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.LookupMembersInternal(LookupResult result, ContainerSymbol container, String name, LookupOptions options, Binder originalBinder, Boolean diagnose, HashSet`1& useSiteDiagnostics, BoundExpression receiver) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Lookup.cs:linje 95
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.LookupMembersWithFallback(LookupResult result, ContainerSymbol namespaceOrType, String name, HashSet`1& useSiteDiagnostics, LookupOptions options) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder.cs:linje 509
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInstanceMemberAccess(SyntaxNode node, SyntaxNode right, BoundExpression boundLeft, String rightName, Boolean invoked, Boolean isStatement, DiagnosticBag diagnostics) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:linje 1470
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindMemberAccessWithBoundLeft(ExpressionSyntax node, BoundExpression boundLeft, NameSyntax right, Boolean invoked, Boolean isStatement, DiagnosticBag diagnostics) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:linje 1423
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindMemberAccess(MemberAccessExpressionSyntax node, Boolean invoked, Boolean isStatement, DiagnosticBag diagnostics) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:linje 1370
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindExpressionStatement(SyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:linje 517
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:linje 83
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatements(SyntaxList`1 syntaxStatements, DiagnosticBag diagnostics, Binder binder) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:linje 53
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:linje 33
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.BindMethodBody(MethodSymbol method, DiagnosticBag diagnostics) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 463
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethod(MethodSymbol methodSymbol) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 385
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMembers(ContainerSymbol containingType) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 309
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 233
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 216
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:linje 150
   ved System.Threading.Tasks.Task.Execute()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 161
   ved Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:linje 145
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:linje 810
   ved Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:linje 787
   ved Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:linje 531
   ved Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:linje 413
   ved Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:linje 312
   ved Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:linje 32
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() i C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:linje 59

**Comment by DominikDitoIvosevic** [comment]
@Jan-Skrubbeltrang Null Reference Exceptions are a generic group of bugs. Your issue is different from this one. Could you please open a new bug?

Are you maybe trying to reference an extension which has a global variable of type label? This is a known bug and has been fixed
