### ISSUE TITLE
Label Locked failure 'String was not recognized as a valid Boolean.'

### ISSUE THREAD

**Issue by epernst** [Microsoft/AL#892]
Using AL 0.10.13928 the system fails with "Processing of message 'textDocument/completion' failed with error: 'String was not recognized as a valid Boolean.'".

Its easy reproducible:
![ccd0a735-1753-48f6-9b00-ab5f3847b57b](https://user-images.githubusercontent.com/5236163/32412970-ce9f0512-c206-11e7-95a0-5e45addf97ff.GIF)

I know Locked need a true or false, but it shouldn't fail like this.

/Erik

Full Error

`[Error - 8:44:02 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/completion' failed with error: 'String was not recognized as a valid Boolean.'
StackTrace:
   at System.Boolean.Parse(String value)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindLabel(LabelSyntax syntax, DiagnosticBag diagnostics) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:line 1909
   at Microsoft.Dynamics.Nav.CodeAnalysis.SourceLabelTypeSymbol..ctor(Symbol containingSymbol, LabelDataTypeSyntax syntax, ImmutableArray`1 locations, DiagnosticBag diagnostics) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceLabelTypeSymbol.cs:line 69
   at Microsoft.Dynamics.Nav.CodeAnalysis.SourceLabelTypeSymbol.Create(Symbol owner, LabelDataTypeSyntax syntax, DiagnosticBag diagnostics) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceLabelTypeSymbol.cs:line 57
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindType(Symbol ownerSymbol, DataTypeSyntax syntax, DiagnosticBag diagnostics) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Symbols.cs:line 60
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindVariableOrParameterType(Symbol ownerSymbol, TypeReferenceBaseSyntax syntax, DiagnosticBag diagnostics) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Symbols.cs:line 353
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindVariableType(Symbol ownerSymbol, TypeReferenceBaseSyntax syntax, DiagnosticBag diagnostics) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Symbols.cs:line 302
   at Microsoft.Dynamics.Nav.CodeAnalysis.SourceVariableSymbol.LazyGetType() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceVariableSymbol.cs:line 119
   at Microsoft.Dynamics.Nav.CodeAnalysis.SourceVariableSymbol.get_Type() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Source\SourceVariableSymbol.cs:line 76
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.VisitVariable(VariableSymbol symbol) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:line 172
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplay.cs:line 131
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbol.ToDisplayParts(SymbolDisplayFormat format) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Symbol.cs:line 483
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.SymbolCompletionItem.Create(String displayText, TextSpan span, IReadOnlyList`1 symbols, Int32 contextPosition, Int32 descriptionPosition, String sortText, String insertionText, Nullable`1 glyph, String filterText, Boolean preselect, SupportedPlatformData supportedPlatforms, Boolean isArgumentName, ImmutableDictionary`2 properties, ImmutableArray`1 tags, CompletionItemRules rules) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\SymbolCompletionItem.cs:line 63
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.CreateItem(String displayText, String insertionText, Int32 position, List`1 symbols, AbstractSyntaxContext context, TextSpan span, Boolean preselect, SupportedPlatformData supportedPlatformData) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 111
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.CreateItem(String displayText, String insertionText, Int32 position, List`1 symbols, AbstractSyntaxContext context, TextSpan span, Dictionary`2 invalidProjectMap, List`1 totalProjects, Boolean preselect) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 106
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<>c__DisplayClass5_0.<CreateItems>b__3(IGrouping`2 g) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 47
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.CreateItems(Int32 position, IEnumerable`1 symbols, TextSpan span, AbstractSyntaxContext context, Dictionary`2 invalidProjectMap, List`1 totalProjects, Boolean preselect) in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 44
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__14.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.AbstractSymbolCompletionProvider.<ProvideCompletionsAsync>d__13.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\AbstractSymbolCompletionProvider.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetContextAsync>d__24.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 368
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__17.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis.Workspaces\Completion\CompletionServiceWithProviders.cs:line 186
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CompletionRequestHandler.<HandleAsync>d__4.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CompletionRequestHandler.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__5.MoveNext() in C:\Agent\_work\38\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 50

`

**Comment by DominikDitoIvosevic** [comment]
You are correct that this should be more graceful. I will fix it

**Comment by DominikDitoIvosevic** [comment]
Hi. I have tried reproing this issue on our latest build and I cannot. Since I cannot repro I think it was fixed with my bug fix which addressed a wide set of crashes for codelens.

Here is my attempt at repro. Please wait for the update and it should be fixed.

![image](https://user-images.githubusercontent.com/6378638/32483612-1796713c-c39d-11e7-9ec6-7a6964c626e2.png)

**Comment by epernst** [comment]
Will check when the new build is public, which is when? ;)

Yes, it was a GIF, looks fine here on Firefox. I just dropped the file into the editor.
