### ISSUE TITLE
Problems with the dictionary, both with IntelliSense and missing functions.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#908]
The newly introduced dictionary unfortunately still causes some problems. The IntelliSense doesn't work at all with me. There is always an error message that I can see in the Visual Studio Code problem window. The message looks like this:

```
[Error - 07:43:20] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'textDocument/codeLens' failed with error: 'the index was out of range'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.AddParametersIfRequired(MethodSymbol symbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:Line 407.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplayVisitor.VisitMethod(MethodSymbol symbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplayVisitor.cs:Line 399.
   at Microsoft.Dynamics.Nav.CodeAnalysis.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\SymbolDisplay\SymbolDisplay.cs:Line 131.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbol.ToDisplayString(SymbolDisplayFormat format) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\Symbol.cs:Line 503.
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<>c__DisplayClass0_0.<GetSymbolInformations>b__2(ISymbol s) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:Line 36.
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Utility.DocumentExtensions.<GetSymbolInformations>d__0.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Utility\DocumentExtensions.cs:Line 33.
--- End of batch monitoring from the previous location where the exception was raised ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.CodeLensRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\CodeLensRequestHandler.cs:Line 31.
--- End of batch monitoring from the previous location where the exception was raised ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:Line 59.
```

Furthermore, the descriptions have not yet made it quite clear to me. How can I iterate through all existing keys and values within this dictionary? I can check for a certain key, but apparently I can't get an overview of all available keys. Furthermore,"ElementAt" seems to be missing as a function.

**Comment by atoader** [comment]
Hi!
What version of the extension are you using? Do you have code to repro the issue?
To iterate through all the keys and values:
```
var
  d : dictionary of [text, integer];
  key : text;
  value : integer;
begin
  foreach key in d.Keys do
    Message(format(d.Get(key)))
end;
```
Which ElementAt method are you referring to? Is it this one: https://msdn.microsoft.com/en-us/library/bb299233(v=vs.110).aspx ?
