### ISSUE TITLE
Go To Definition error

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#925]
AL code:
tableextension 50000 "Item Extension" extends Item
{
    fields
    {
        field(50000;"Show Item";Boolean)
        {
            
        }
    }
    
}
If I try "Go To Definition" on Item the error below is thrown. The same error is thrown if trying to look at the page (i.e. Sales Order, but for Role Centers seem to work without error). 

[Error - 5:52:57 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/previewDocument' failed with error: 'Sequence contains no elements'
StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertTextConst(TypeSymbol type) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 363
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.GetDataTypeSyntax(TypeSymbol type) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 352
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertTypeReference(TypeSymbol type) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 329
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertVariables(IEnumerable`1 variables) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 95
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.ConvertMembers(ImmutableArray`1 members) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 65
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntaxTable.ConvertTable(TableTypeSymbol table) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax_Table.cs:line 47
   at Microsoft.Dynamics.Nav.CodeAnalysis.PreviewReference.ReferenceSymbolToSyntax.Convert(ISymbol symbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\PreviewReference\ReferenceSymbolToSyntax.cs:line 39
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPreviewDocumentRequestHandler.SymbolToPreviewText(ISymbol symbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPreviewDocumentRequestHandler.cs:line 64
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPreviewDocumentRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPreviewDocumentRequestHandler.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by kalberes** [comment]
Hi, 
You have probably downloaded your symbols by first generating them from C/SIDE.
We have a "few" issues with the symbol reference generation from C/SIDE that will be fixed by the Nav 2018 release and the December update.
Until then the best is - unless you want just to try it out - to use symbols the old way, by disabling the EnableSymbolLoadingAtServerStartup flag and not generating symbols from C/SIDE.

**Comment by DanielGoehler** [comment]
I have the same issue on the November Update VM with **Go to Definition** on every _tableextension_ I tried. 

What is the best way to disable **EnableSymbolLoadingAtServerStartup** since Dynamics NAV Administration is not installed on the machine anymore and the service tier run inside a docker container?
