### ISSUE TITLE
Package creation exception

### ISSUE THREAD

**Issue by ABaludin** [Microsoft/AL#977]
Steps:
1. Create codeunit in c/al development environment
2. create function with relation to 1297 codeunit Http management (yes, i know that .NET is not supported):
CLEAR(IStream);
HttpMgt.Initialize(Url);
HttpMgt.CreateInstream(IStream);
HttpMgt.GetResponseStream(IStream);
3. Set properties:
 local = no 
 functionVisibility = external
4. Insert calling of this function to AL
5. Press F5 and it throw next exception:

Microsoft (R) AL Compiler version 0.11.14434
Copyright (C) Microsoft Corporation. All rights reserved

[Error - 11:53:46 AM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/createPackage' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.RecordTypeSymbol.Equals(TypeSymbol t2, Boolean ignoreTemporary) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\BuiltIn\RecordTypeSymbol.cs:line 37
   at Microsoft.Dynamics.Nav.CodeAnalysis.Conversions.HasIdentityConversion(TypeSymbol source, TypeSymbol destination) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\Conversions\Conversions.cs:line 429
   at Microsoft.Dynamics.Nav.CodeAnalysis.Conversions.ClassifyImplicitConversionFromExpression(BoundExpression sourceExpression, TypeSymbol source, TypeSymbol destination, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\Conversions\Conversions.cs:line 110
   at Microsoft.Dynamics.Nav.CodeAnalysis.Conversions.ClassifyImplicitConversionFromExpression(BoundExpression sourceExpression, TypeSymbol destination, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\Conversions\Conversions.cs:line 77
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.CheckArgumentForConversionApplicability(BoundExpression argument, ParameterSymbol parameter, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 565
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.IsApplicable(EffectiveParameters parameters, AnalyzedArguments arguments, BoundExpression receiverOpt, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 373
   at Microsoft.Dynamics.Nav.CodeAnalysis.OverloadResolution.IsApplicable[TMember](TMember member, AnalyzedArguments arguments, EffectiveParameters effectiveParameters, BoundExpression receiverOpt, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 332
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.ResolveDefaultMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:line 2066
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.ResolveMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, HashSet`1& useSiteDiagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Expressions.cs:line 2035
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindMethodGroupInvocation(SyntaxNode syntax, SyntaxNode expression, String methodName, BoundMethodGroup methodGroup, Boolean isStatement, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 140
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode expression, String methodName, BoundExpression boundExpression, Boolean isStatement, Boolean asProperty, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 98
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics, Boolean isStatement) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Invocation.cs:line 31
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindExpressionStatement(SyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 508
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 83
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindStatements(SyntaxList`1 syntaxStatements, DiagnosticBag diagnostics, Binder binder) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 53
   at Microsoft.Dynamics.Nav.CodeAnalysis.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Binder\Binder_Statements.cs:line 33
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.BindMethodBody(MethodSymbol method, DiagnosticBag diagnostics) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 463
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethod(MethodSymbol methodSymbol) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 385
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMembers(ContainerSymbol containingType) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 309
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMembers(ContainerSymbol containingType) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 340
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMembers(ContainerSymbol containingType) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 345
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 233
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass17_0.<CompileObjectAsTask>b__0() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 216
   at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\UICultureUtilities.cs:line 150
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.WaitForWorkers() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 145
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 808
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 785
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogger errorLogger, AnalyzerDriver analyzerDriver) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 531
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 413
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 312
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.CreatePackageRequestHandler.<HandleAsync>d__3.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\CreatePackageRequestHandler.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\40\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by DominikDitoIvosevic** [comment]
Hi @ABaludin ! What do you mean with 
"Insert calling of this function to AL"?
Do you generate new symbols from cside?
The issue happens when packaging the extension so it doesn't have to do directly with any changes you do in CSIDE.
It's probably some extension code you wrote causing this.

Could you please try extracting the code which is causing the crash?
Could you tell me if the crash happens if you remove all your dependencies **except** System, Application and Test?

**Comment by ABaludin** [comment]
Hi @DominikDitoIvosevic 
In CSIDE:

Codeunit Mycodeunit

[External] Myfunction(RequestLine)
var HttpManagement : codeunit 1297
Begin
  HttpManagement.initalise(RequestLine);
  HttpManagement.sendrequest;
End;

In AL:

Procedure MyProcedure()
var 
  RequestLine : text;
  Mycodeunit: codeunit Mycodeunit;
begin
  RequestLine := 'some url';
  Mycodeunit.Myfunction(RequestLine);
end;


Yes, i generate new symbols.
Yes, The issue happens when packaging the extension
Yes, the exception doesn't appear if i remove "Mycodeunit.Myfunction(RequestLine);" from AL.

As i see now, vscode shows a problem when I insert this call:
Internal error: 'Object reference not set to an instance of an object.', Stack trace=unknown

So if I try to package my extension - it throws that big exception.

**Comment by DominikDitoIvosevic** [comment]
hi @ABaludin . Are you still experiencing these issues? I have tried reproing your example myself and I have no issues running the code.

**Comment by ABaludin** [comment]
@DominikDitoIvosevic this error occurs only if i'm trying to publish incorrect package with functions which includes links on dotnet variables. So, it's not a problem for me at all - I've just tested what happens if i try to do it.

**Comment by DominikDitoIvosevic** [comment]
I suppose this issue is resolved then. If you have more requests please open a new issue
